import { Link } from "react-router-dom";
import { PublicShell } from "@/components/layout/PublicShell";
import { T } from "@/styles/tokens";
import { img, type ImageKey } from "@/content/imageRegistry";
const mono:React.CSSProperties={fontFamily:T.mono,fontSize:10.5,letterSpacing:".15em",textTransform:"uppercase"};const display:React.CSSProperties={fontFamily:T.display,fontWeight:500,letterSpacing:"-.05em"};
const STORIES=[
 {tag:"IDEA",title:"Everything you love is connected.",dek:"Treat the living planet as infrastructure for human life — not scenery around it.",image:"heroEarth" as ImageKey,to:"/about/story"},
 {tag:"METHODS",title:"A point on a map is not a range.",dek:"Useful planetary interfaces keep observation, interpretation and conclusion visibly separate.",image:"amazoniaHero" as ImageKey,to:"/atlas"},
 {tag:"SPECIES",title:"Meet life before the problem.",dek:"Begin with the living subject, then reveal place, relationships, pressure and response.",image:"oce4nDomainHero" as ImageKey,to:"/species"},
 {tag:"S4PIENS",title:"Put the human back inside the system.",dek:"Food, water, energy and materials run through living systems in both directions.",image:"s4piensDomainHero" as ImageKey,to:"/s4piens"},
] as const;
export function Magazine(){return <PublicShell><main style={{background:"#fff",color:T.ink}}><header style={{maxWidth:1400,margin:"0 auto",padding:"clamp(120px,15vw,210px) clamp(20px,5vw,72px) clamp(42px,6vw,80px)"}}><div style={{...mono,color:T.blue}}>4CULTURE_ · EDITORIAL</div><h1 style={{...display,margin:"18px 0 0",fontSize:"clamp(70px,13vw,190px)",lineHeight:.74}}>M4GAZINE_</h1><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(280px,.55fr)",gap:"clamp(28px,7vw,110px)",alignItems:"end",marginTop:44}} className="mag-intro"><h2 style={{...display,margin:0,fontSize:"clamp(38px,5vw,72px)",lineHeight:.92,maxWidth:"12ch"}}>Ideas for a living planet.</h2><p style={{margin:0,color:T.dim,fontSize:"clamp(16px,1.45vw,20px)",lineHeight:1.65}}>Data can show a relationship. Story can make a person stay with it. M4GAZINE is the editorial layer connecting evidence, systems, species, culture and action.</p></div></header><section style={{borderTop:`1px solid ${T.lineStrong}`}}><div className="mag-grid" style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:1,background:T.lineStrong}}>{STORIES.map((story)=>{const media=img(story.image);return <Link key={story.title} to={story.to} style={{display:"grid",gridTemplateRows:"minmax(280px,36vw) auto",background:"#fff",color:T.ink,textDecoration:"none"}} className="mag-card"><div style={{overflow:"hidden",background:"#050505"}}><img src={media.src} alt={media.alt} loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:media.objectPosition??"50% 50%",transition:"transform .8s ease"}}/></div><div style={{padding:"clamp(24px,4vw,48px)"}}><div style={{...mono,color:T.blue}}>{story.tag}</div><h2 style={{...display,margin:"15px 0 0",fontSize:"clamp(30px,4vw,58px)",lineHeight:.94}}>{story.title}</h2><p style={{margin:"18px 0 0",maxWidth:620,color:T.dim,fontSize:"clamp(15px,1.25vw,18px)",lineHeight:1.58}}>{story.dek}</p><div style={{...mono,marginTop:26}}>ENTER →</div></div></Link>})}</div></section><section style={{background:"#050505",color:"#fff"}}><div style={{maxWidth:1320,margin:"0 auto",padding:"clamp(78px,10vw,150px) clamp(20px,5vw,72px)"}}><div style={{...mono,color:T.blue}}>WHY EDITORIAL EXISTS</div><p style={{...display,margin:"22px 0 0",fontSize:"clamp(38px,6.5vw,96px)",lineHeight:.92,maxWidth:"15ch"}}>Understanding is not complete until people can carry it with them.</p><Link to="/domains/4culture" style={{...mono,display:"inline-flex",marginTop:34,color:"#fff",textDecoration:"none",borderBottom:"1px solid #fff",paddingBottom:5}}>ENTER 4CULTURE →</Link></div></section><style>{`.mag-card:hover img,.mag-card:focus-visible img{transform:scale(1.025)}.mag-card:focus-visible{outline:3px solid ${T.blue};outline-offset:-3px}@media(max-width:800px){.mag-grid,.mag-intro{grid-template-columns:1fr!important}}@media(prefers-reduced-motion:reduce){.mag-card img{transition:none!important}}`}</style></main></PublicShell>}
