const UPDATED = '9 September 2026';

const styles = `
:root{--blue:#2E2EFF;--ink:#0A0A0A;--paper:#fff;--muted:#666;--line:#e9e9e9}
*{box-sizing:border-box}html{background:var(--paper);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{margin:0}a{color:inherit}.shell{max-width:1120px;margin:0 auto;padding:0 28px}.top{position:sticky;top:0;background:rgba(255,255,255,.94);backdrop-filter:blur(12px);border-bottom:1px solid var(--line);z-index:10}.nav{height:72px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{font-weight:760;letter-spacing:-.04em;font-size:21px;text-decoration:none}.brand span{color:var(--blue)}.navlinks{display:flex;gap:22px;font-size:14px}.navlinks a{text-decoration:none;color:#444}.navlinks a:hover{color:var(--blue)}.hero{padding:82px 0 48px;border-bottom:1px solid var(--line)}.eyebrow{font:600 12px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em;text-transform:uppercase;color:var(--blue)}h1{font-size:clamp(52px,9vw,104px);letter-spacing:-.065em;line-height:.88;margin:18px 0 28px;max-width:900px}.lead{max-width:760px;font-size:20px;line-height:1.55;color:#383838}.meta{margin-top:28px;font:500 12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:#777;text-transform:uppercase;letter-spacing:.07em}.content{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:80px;padding:64px 0 100px}.article{max-width:760px}.article section{padding:0 0 44px;margin:0 0 44px;border-bottom:1px solid var(--line)}.article section:last-child{border-bottom:0}.article h2{font-size:28px;line-height:1.1;letter-spacing:-.04em;margin:0 0 18px}.article h3{font-size:18px;margin:28px 0 10px}.article p,.article li{font-size:16px;line-height:1.7;color:#303030}.article ul{padding-left:22px}.toc{position:sticky;top:104px;align-self:start;border-left:1px solid var(--line);padding-left:22px}.toc strong{display:block;font:600 11px/1.3 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.09em;text-transform:uppercase;margin-bottom:14px}.toc a{display:block;text-decoration:none;color:#666;font-size:13px;line-height:1.35;padding:6px 0}.toc a:hover{color:var(--blue)}.note{background:#f6f6ff;border-left:3px solid var(--blue);padding:18px 20px;margin:24px 0}.footer{border-top:1px solid var(--line);padding:32px 0 54px;color:#666;font-size:13px}.footergrid{display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:7px 11px;text-decoration:none}.pill:hover{border-color:var(--blue);color:var(--blue)}
@media(max-width:760px){.shell{padding:0 20px}.nav{height:64px}.navlinks{gap:14px;font-size:13px}.hero{padding:56px 0 36px}h1{font-size:54px}.lead{font-size:18px}.content{grid-template-columns:1fr;gap:0;padding-top:42px}.toc{display:none}.article section{padding-bottom:34px;margin-bottom:34px}.article h2{font-size:24px}}
`;

function frame(title, eyebrow, lead, toc, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${title} — 4PLANET</title><meta name="description" content="${lead.replace(/"/g,'&quot;')}"><style>${styles}</style></head><body>
  <header class="top"><div class="shell nav"><a class="brand" href="https://4planet.org">4PLANET<span>_</span></a><nav class="navlinks" aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="https://4planet.org">Home</a></nav></div></header>
  <main><section class="hero"><div class="shell"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="lead">${lead}</p><div class="meta">Last updated ${UPDATED} · Norway</div></div></section>
  <div class="shell content"><article class="article">${body}</article><aside class="toc"><strong>On this page</strong>${toc}</aside></div></main>
  <footer class="footer"><div class="shell footergrid"><div>4PLANET · For a Living Planet.</div><div><a class="pill" href="mailto:odin@4planet.org">odin@4planet.org</a></div></div></footer>
  </body></html>`;
}

const privacyBody = `
<section id="scope"><h2>1. Scope and controller</h2><p>This Privacy Policy explains how 4PLANET processes personal data when you use 4planet.org and connected 4PLANET services that use the shared 4PLANET identity system, including 4SAPIEN at 4sapien.com.</p><p>Until a dedicated 4PLANET operating entity is established, the service is operated by <strong>SKOG COMMUNICATIONS AS</strong>, organisation number <strong>923 003 789</strong>, Norway. For privacy requests, contact <a href="mailto:odin@4planet.org">odin@4planet.org</a>.</p><div class="note"><strong>Our principle:</strong> collect less, use data for a defined purpose, protect access, and do not collect personal data merely because it may become useful later.</div></section>
<section id="data"><h2>2. Data we may process</h2><h3>Account and identity data</h3><p>If you create an account, we may process your email address, account identifier, authentication events and, if you choose Google sign-in, basic profile information made available by Google such as your name, email address and profile image.</p><h3>4SAPIEN profile and service data</h3><p>Where you choose to use 4SAPIEN features, we may process information you provide such as household settings, dietary preferences, items you avoid, preferred store, weekly budget, personal priorities, shopping lists, meal plans, shopping trips and receipt images or totals.</p><h3>Technical and security data</h3><p>Our infrastructure providers may process technical information necessary to deliver and protect the service, such as IP address, browser and device information, timestamps, request metadata and security logs.</p><h3>Location data</h3><p>Some 4PLANET features may use location to provide place-based functionality. Precise location is transient by default. We do not intend to store a person's precise location unless the functionality requires it and the user knowingly enables that use.</p><h3>Local device data</h3><p>Some features are local-first and may use browser storage on your device for preferences, session state or continuity. Clearing browser data may remove locally stored information.</p></section>
<section id="purpose"><h2>3. Why we process data</h2><p>We process personal data only where there is a defined purpose, including to:</p><ul><li>create, authenticate and secure your account;</li><li>provide requested 4PLANET and 4SAPIEN functionality;</li><li>save and synchronise information you choose to store;</li><li>protect users, prevent abuse and maintain service reliability;</li><li>respond to support, privacy and account requests;</li><li>improve functionality using appropriately minimised or aggregated information; and</li><li>meet legal obligations where applicable.</li></ul><p>Depending on the context, the legal basis may be performance of a contract or steps you request before entering one, our legitimate interests in operating and securing the service, your consent for optional processing where required, or compliance with a legal obligation.</p></section>
<section id="providers"><h2>4. Service providers and external services</h2><p>We use specialised providers to operate 4PLANET. These currently include:</p><ul><li><strong>Supabase</strong> for authentication, database and private file storage;</li><li><strong>Cloudflare</strong> for hosting, delivery and security;</li><li><strong>Google</strong> if you choose Sign in with Google; and</li><li>external product or ecological data sources where a feature requires a lookup.</li></ul><p>For example, a product lookup may send a barcode or search term to an external product-data source. We aim not to send your account identity to a data provider unless it is required for the functionality and disclosed appropriately.</p><p>Providers may process data in countries outside Norway or the EEA. Where applicable, we rely on the provider's lawful transfer mechanisms and contractual safeguards.</p></section>
<section id="sharing"><h2>5. Sharing and sale of personal data</h2><p>We do not sell personal data. We may share personal data with service providers acting on our behalf, when you direct us to do so, when necessary to provide a requested feature, or when required by law. We require access to be limited to what is reasonably necessary for the relevant purpose.</p></section>
<section id="retention"><h2>6. Retention</h2><p>We retain personal data only for as long as reasonably necessary for the purpose for which it was collected, to provide an active account or requested service, to protect the system, or to meet legal obligations. Retention can differ by data type. We avoid inventing longer retention periods merely for possible future use.</p><p>If you ask us to delete your account or personal data, we will act on the request subject to technical, security and legal requirements. Some limited records may need to be retained where law or legitimate security requirements require it.</p></section>
<section id="security"><h2>7. Security</h2><p>We use access controls, authentication, private storage, row-level access policies and secret-handling practices designed to protect personal data. No online service can guarantee absolute security, but we design the system to minimise unnecessary exposure and restrict user-owned data to the relevant authenticated user.</p></section>
<section id="rights"><h2>8. Your rights</h2><p>If European or Norwegian data-protection law applies, you may have rights including access, correction, deletion, restriction, data portability, objection to certain processing and withdrawal of consent where processing is based on consent.</p><p>To exercise a right, contact <a href="mailto:odin@4planet.org">odin@4planet.org</a>. We may need to verify your identity before acting on a request. You also have the right to complain to the Norwegian Data Protection Authority (Datatilsynet) or another competent supervisory authority.</p></section>
<section id="cookies"><h2>9. Cookies and browser storage</h2><p>4PLANET may use cookies or browser storage that are necessary for authentication, security, preferences and core service functionality. If we introduce non-essential tracking or advertising technologies that require consent, we will provide the appropriate notice and controls before using them where required.</p><p>We do not use personal data to build advertising profiles for third-party advertisers.</p></section>
<section id="children"><h2>10. Children</h2><p>Account-based services are not designed for children under 13 to create accounts independently. If we develop services specifically for children or schools, we will apply additional age-appropriate protections and consent requirements.</p></section>
<section id="changes"><h2>11. Changes to this policy</h2><p>4PLANET is developing quickly. We may update this policy as products, providers or legal requirements change. We will publish the current version here and update the date at the top. Material changes may be communicated through the relevant service where appropriate.</p></section>
<section id="contact"><h2>12. Contact</h2><p>Privacy questions, access requests or deletion requests can be sent to <a href="mailto:odin@4planet.org">odin@4planet.org</a>.</p><p><strong>SKOG COMMUNICATIONS AS</strong><br>Organisation no. 923 003 789<br>Norway</p></section>`;

const privacyToc = `<a href="#scope">Scope & controller</a><a href="#data">Data we process</a><a href="#purpose">Purposes</a><a href="#providers">Providers</a><a href="#sharing">Sharing</a><a href="#retention">Retention</a><a href="#security">Security</a><a href="#rights">Your rights</a><a href="#cookies">Cookies</a><a href="#children">Children</a><a href="#changes">Changes</a><a href="#contact">Contact</a>`;

const termsBody = `
<section id="agreement"><h2>1. Agreement</h2><p>These Terms of Service govern your use of 4planet.org and connected 4PLANET products and services that link to these terms, including account-based features provided through the shared 4PLANET identity system.</p><p>By using the service, you agree to these terms. If you do not agree, do not create an account or use account-based functionality.</p><p>Until a dedicated 4PLANET operating entity is established, the service is operated by <strong>SKOG COMMUNICATIONS AS</strong>, organisation number <strong>923 003 789</strong>, Norway.</p></section>
<section id="service"><h2>2. The service</h2><p>4PLANET is a developing platform for ecological intelligence, understanding, participation and related personal tools. Products may include experimental, beta or early-stage functionality. Coverage, data sources and features can change as the system develops.</p><div class="note"><strong>Truth by design:</strong> limited real coverage is preferable to false completeness. Where information is unknown, provisional or source-dependent, the service may state that explicitly rather than manufacture certainty.</div></section>
<section id="accounts"><h2>3. Accounts and security</h2><p>You are responsible for maintaining control of the credentials and devices used to access your account. You must provide accurate information where the service requires it and must not impersonate another person or create accounts for abusive or unlawful purposes.</p><p>If you believe your account has been compromised, contact <a href="mailto:odin@4planet.org">odin@4planet.org</a>.</p></section>
<section id="use"><h2>4. Acceptable use</h2><p>You may not use 4PLANET to:</p><ul><li>break applicable law or infringe another person's rights;</li><li>attempt to bypass authentication, access controls or security measures;</li><li>interfere with or overload the service;</li><li>scrape, extract or redistribute protected content in violation of source licences or terms;</li><li>submit malware, abusive automation or harmful code;</li><li>misrepresent 4PLANET data, proof or source material as something it is not; or</li><li>use sensitive ecological information to create a credible risk of harm to species, habitats or protected locations.</li></ul><p>We may restrict or suspend access where reasonably necessary to protect users, the service, data providers, ecological safety or legal compliance.</p></section>
<section id="information"><h2>5. Information, data and decisions</h2><p>4PLANET combines information from multiple sources. Source coverage, licences, update cycles and confidence may vary. The service is designed to distinguish source information, interpretation, action and proof, but errors or gaps may still occur.</p><p>Unless we expressly state otherwise, 4PLANET content is provided for information and product functionality, not as legal, medical, financial, investment or other regulated professional advice. Important decisions should be checked against appropriate primary sources or qualified professionals.</p></section>
<section id="personal"><h2>6. Personal tools, including 4SAPIEN</h2><p>Personal features may help organise preferences, food choices, shopping, budgets or related information. They are decision-support tools, not a guarantee of health outcomes, prices, savings, availability or environmental impact.</p><p>Allergen, nutrition, ingredient and product information can be incomplete or changed by manufacturers. If a decision is safety-critical, check the product label and relevant professional guidance rather than relying solely on the service.</p></section>
<section id="thirdparty"><h2>7. Third-party services and sources</h2><p>Some functionality depends on third-party infrastructure, identity providers, APIs, websites or datasets. Their own terms and privacy practices may apply. 4PLANET does not control third-party availability and may change or remove an integration if access, licensing, reliability or safety conditions change.</p></section>
<section id="ip"><h2>8. Intellectual property</h2><p>4PLANET branding, original interface design, original text, software and other original material are protected by applicable intellectual-property law. Third-party datasets, imagery, trademarks and source material remain subject to their respective ownership, licences and attribution requirements.</p><p>These terms do not grant you ownership of 4PLANET intellectual property or third-party content. Normal personal use of the public service is permitted; commercial republication, extraction or redistribution may require separate permission.</p></section>
<section id="usercontent"><h2>9. Information you provide</h2><p>You retain rights you have in information you provide. You give us the limited rights necessary to host, process, transmit and display that information solely to operate, secure and improve the service in accordance with our Privacy Policy.</p><p>Do not upload material you do not have the right to provide, or highly sensitive information that the relevant feature does not require.</p></section>
<section id="availability"><h2>10. Availability and changes</h2><p>We may add, modify, pause or discontinue features as 4PLANET develops. We aim to preserve user trust and avoid unnecessary disruption, but continuous availability is not guaranteed. Beta and early-stage features may change more frequently.</p></section>
<section id="liability"><h2>11. Responsibility and liability</h2><p>To the extent permitted by applicable law, the service is provided without a guarantee that it will always be uninterrupted, error-free or complete. Nothing in these terms excludes or limits rights or liability that cannot lawfully be excluded, including mandatory consumer rights.</p><p>You remain responsible for decisions you make using information from the service. Where 4PLANET links to an external source or service, responsibility for that external service remains with its provider.</p></section>
<section id="termination"><h2>12. Suspension, termination and deletion</h2><p>You may stop using the service at any time. You may request deletion of your account or personal data by contacting <a href="mailto:odin@4planet.org">odin@4planet.org</a>. We may suspend or terminate access for material breach of these terms, security threats, abuse or legal requirements.</p></section>
<section id="law"><h2>13. Governing law</h2><p>These terms are governed by Norwegian law, subject to any mandatory consumer protections that apply in your country of residence. Disputes should first be raised with us at <a href="mailto:odin@4planet.org">odin@4planet.org</a> so we can attempt to resolve them directly.</p></section>
<section id="changes"><h2>14. Changes to these terms</h2><p>We may update these terms as the service develops. The current version will be published at this URL with an updated date. If a change materially affects an account-based service, we may provide additional notice where appropriate.</p></section>
<section id="contact"><h2>15. Contact</h2><p><a href="mailto:odin@4planet.org">odin@4planet.org</a></p><p><strong>SKOG COMMUNICATIONS AS</strong><br>Organisation no. 923 003 789<br>Norway</p></section>`;

const termsToc = `<a href="#agreement">Agreement</a><a href="#service">The service</a><a href="#accounts">Accounts</a><a href="#use">Acceptable use</a><a href="#information">Information</a><a href="#personal">4SAPIEN</a><a href="#thirdparty">Third parties</a><a href="#ip">IP</a><a href="#usercontent">Your information</a><a href="#availability">Availability</a><a href="#liability">Liability</a><a href="#termination">Termination</a><a href="#law">Law</a><a href="#changes">Changes</a><a href="#contact">Contact</a>`;

function headers() {
  return {
    'content-type': 'text/html; charset=utf-8',
    'cache-control': 'public, max-age=300, s-maxage=300',
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'strict-origin-when-cross-origin',
    'permissions-policy': 'camera=(), microphone=(), geolocation=()',
    'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; font-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self' mailto:"
  };
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, '') || '/';
    if (path === '/privacy') {
      return new Response(frame('Privacy Policy','4PLANET · Legal','How 4PLANET handles personal data across our shared identity system and connected products.',privacyToc,privacyBody), {status:200, headers:headers()});
    }
    if (path === '/terms') {
      return new Response(frame('Terms of Service','4PLANET · Legal','The rules for using 4PLANET and connected account-based services.',termsToc,termsBody), {status:200, headers:headers()});
    }
    return Response.redirect('https://4planet.org', 302);
  }
};
