import { test, expect } from '@playwright/test';
test('4BRAIN fictional first/second visit and correction remain visibly truthful',async({page})=>{
await page.goto('/');
await expect(page.getByRole('heading',{name:/Your intelligence/i})).toBeVisible();
await expect(page.getByText(/No sign-in or AI connection/)).toBeVisible();
await page.getByRole('link',{name:/See fictional demo/}).click();
await page.getByLabel('Alex’s goal').selectOption('learn');
await page.getByLabel('One constraint').selectOption('focus');
await page.getByRole('button',{name:'Review proposed memory'}).click();
await expect(page.getByText('Learn a new skill').last()).toBeVisible();
await expect(page.getByText('PENDING APPROVAL')).toBeVisible();
await page.getByRole('button',{name:'Approve this sample memory'}).click();
await expect(page.getByText('Start with what matters')).toBeVisible();
await expect(page.getByText(/Learn a new skill/i).last()).toBeVisible();
await page.getByRole('button',{name:'Simulate a later visit'}).click();
await expect(page.getByText(/simulated next visit/i).first()).toBeVisible();
await expect(page.getByText(/Continue with learn a new skill/i)).toBeVisible();
await page.getByRole('button',{name:'Correct or remove memory'}).click();
await page.getByRole('button',{name:'Remove memory'}).click();
await expect(page.getByText(/No approved context available/)).toBeVisible();
await page.getByRole('button',{name:'Simulate a later visit'}).click();
await expect(page.getByText(/No active memory/)).toBeVisible();
await expect(page.locator('body')).not.toContainText('ODIN BRAIN —');
const dim=await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1);
expect(dim).toBe(true);
});
test('device-local user Context Pack persists after refresh, corrects, exports and deletes',async({page})=>{
 await page.goto('/');
 await page.getByRole('link',{name:/Make your first Context Pack/}).click();
 await page.getByRole('button',{name:/Approve and save on this device/}).click();
 await expect(page.getByText(/Add a goal, a constraint/)).toBeVisible();
 await page.getByLabel('01 / Your goal').fill('Plan a community garden');
 await page.getByLabel('02 / One important constraint').fill('One afternoon per week');
 await page.getByLabel('03 / The next task you want help with').fill('Choose a simple first task');
 await page.getByRole('button',{name:/Approve and save on this device/}).click();
 await expect(page.getByText(/Review and tick/)).toBeVisible();
 await page.getByLabel(/I have reviewed these words/).check();
 await page.getByRole('button',{name:/Approve and save on this device/}).click();
 await expect(page.locator('#studio-status').getByText('SAVED ON THIS DEVICE')).toBeVisible();
 await expect(page.getByText('Plan a community garden').first()).toBeVisible();
 await page.reload();
 await expect(page.locator('#studio-status').getByText('SAVED ON THIS DEVICE')).toBeVisible();
 await expect(page.getByText('One afternoon per week').first()).toBeVisible();
 await page.getByRole('button',{name:/Review or correct/}).click();
 await page.getByLabel('02 / One important constraint').fill('Two afternoons per month');
 await page.getByLabel(/I have reviewed these words/).check();
 await page.getByRole('button',{name:/Approve updated note/}).click();
 await expect(page.getByText('Two afternoons per month').first()).toBeVisible();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Export JSON'}).click();
 const d=await downloadPromise;expect(d.suggestedFilename()).toBe('4brain-my-local-context.json');
 await page.getByRole('button',{name:/Delete from this browser/}).click();
 await expect(page.locator('#studio-status').getByText('NOT SAVED')).toBeVisible();
 await page.reload();
 await expect(page.locator('#studio-status').getByText('NOT SAVED')).toBeVisible();
 await expect(page.getByText('Plan a community garden')).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
