import { useState } from "react";
import { Link } from "react-router-dom";
import { PublicShell } from "@/components/layout/PublicShell";
import { SpeciesAtlasWindow } from "@/components/species/SpeciesAtlasWindow";
import { speciesBySlug } from "@/data/species";
import { hasShowableImage, speciesMedia } from "@/data/speciesMedia";
import { T } from "@/styles/tokens";

const mono:React.CSSProperties={fontFamily:T.mono,fontSize:10,letterSpacing:".13em",textTransform:"uppercase"};
const display:React.CSSProperties={fontFamily:T.display,fontWeight:500,letterSpacing:"-.055em"};
const max:React.CSSProperties={maxWidth:1320,margin:"0 auto",paddingLeft:"clamp(20px,5vw,72px)",paddingRight:"clamp(20px,5vw,72px)"};
const ACCENT="#3AE86F";
const VIDEO={src:"https://upload.wikimedia.org/wikipedia/commons/3/3b/Pantanal_Jaguar_%28Panthera_onca%29.webm",source:"https://commons.wikimedia.org/wiki/File:Pantanal_Jaguar_(Panthera_onca).webm",creator:'Gregory "Slobirdr" Smith',licence:"CC BY-SA 2.0"};
const PRESSURES=[
 ["HABITAT LOSS + FRAGMENTATION","Range-wide conservation pressure. Local intensity, corridor function and population effect require place-specific evidence."],
 ["CONFLICT + RETALIATORY KILLING","A documented conservation pressure class. No conflict or killing is inferred at a particular occurrence point."],
 ["PREY DEPLETION","Hunting pressure on wild prey can matter across jaguar range, but local food limitation is not inferred here."],
] as const;
const PREY=["CAPYBARA","PECCARIES","CAIMANS","DEER"] as const;

export default function JaguarGold(){
 const profile=speciesBySlug("jaguar"); const media=speciesMedia("jaguar"); const [motion,setMotion]=useState(false);
 if(!profile)return null; const hero=hasShowableImage("jaguar")?media?.localPath:"";
 return <PublicShell><article style={{background:"#fff",color:T.ink}}>
  <header style={{position:"relative",minHeight:"100svh",background:"#020603",color:"#fff",overflow:"hidden"}}>
   {hero&&<img src={hero} alt="Jaguar in a natural landscape" fetchPriority="high" style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",objectPosition:"50% 50%",opacity:.86}}/>}
   <div aria-hidden style={{position:"absolute",inset:0,background:"linear-gradient(90deg,rgba(0,0,0,.8),rgba(0,0,0,.26) 60%,rgba(0,0,0,.08)),linear-gradient(0deg,rgba(0,0,0,.8),transparent 58%)"}}/>
   <div style={{...max,position:"relative",zIndex:1,minHeight:"100svh",display:"flex",flexDirection:"column",justifyContent:"flex-end",paddingTop:120,paddingBottom:"clamp(54px,8vw,100px)"}}>
    <div style={{...mono,color:ACCENT}}>4PLANET SPECIES_ · E4RTH_</div>
    <h1 style={{...display,margin:"20px 0 0",fontSize:"clamp(82px,15vw,196px)",lineHeight:.75}}>JAGUAR</h1>
    <div style={{fontFamily:T.display,fontStyle:"italic",fontSize:"clamp(20px,3vw,34px)",marginTop:20,opacity:.85}}>{profile.scientificName}</div>
    <p style={{margin:"28px 0 0",maxWidth:760,fontSize:"clamp(18px,2.2vw,25px)",lineHeight:1.52,color:"rgba(255,255,255,.9)"}}>Follow one living animal outward — into place, prey, rainforest relationships, pressure and response.</p>
    <div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:30}}><a href="#atlas-window" style={{...mono,color:"#041008",background:ACCENT,textDecoration:"none",padding:"13px 16px"}}>WHERE HAS IT BEEN RECORDED? ↓</a><Link to="/ecosystems/amazon-rainforest" style={{...mono,color:"#fff",border:"1px solid rgba(255,255,255,.58)",textDecoration:"none",padding:"12px 16px"}}>ENTER AMAZONIA →</Link></div>
    {media?.attribution&&<div style={{...mono,fontSize:8.5,marginTop:20,color:"rgba(255,255,255,.52)",maxWidth:760}}>IMAGE · {media.attribution} · {media.licence}</div>}
   </div>
  </header>

  <section style={{background:"#050805",color:"#fff"}}><div className="jaguar-intro" style={{...max,paddingTop:"clamp(70px,9vw,126px)",paddingBottom:"clamp(70px,9vw,126px)",display:"grid",gridTemplateColumns:"minmax(0,1.2fr) minmax(260px,.65fr)",gap:"clamp(38px,8vw,110px)"}}><div><div style={{...mono,color:ACCENT}}>01_ MEET THE SPECIES</div><h2 style={{...display,margin:"16px 0 0",fontSize:"clamp(42px,7vw,96px)",lineHeight:.9}}>A predator built for connected landscapes.</h2><p style={{margin:"26px 0 0",maxWidth:760,color:"rgba(255,255,255,.72)",fontSize:"clamp(16px,1.6vw,20px)",lineHeight:1.66}}>{profile.intro||profile.context}</p></div><div style={{borderTop:"1px solid rgba(255,255,255,.26)",paddingTop:20}}><div style={{...mono,color:"rgba(255,255,255,.48)"}}>IDENTITY</div><p style={{fontSize:22,lineHeight:1.4}}>{profile.commonName}<br/><em>{profile.scientificName}</em></p><div style={{...mono,color:"rgba(255,255,255,.48)",marginTop:22}}>SOURCE IDENTITY</div><p style={{fontSize:14,lineHeight:1.6,color:"rgba(255,255,255,.7)"}}>GBIF taxon {profile.gbifKey}. Identity does not establish local presence, abundance or population state.</p></div></div></section>

  <div id="atlas-window"><SpeciesAtlasWindow gbifKey={profile.gbifKey} commonName={profile.commonName} scientificName={profile.scientificName} entityId={profile.id} journey={profile.journey} ecosystems={[{label:"AMAZON RAINFOREST",href:"/ecosystems/amazon-rainforest",relationship:"CURATED REGIONAL LIVING-SYSTEM CONTEXT",boundary:"A bounded 4PLANET learning bridge. It is not inferred from GBIF occurrence points and does not assert ecosystem membership for a particular observation, animal or population."}]}/></div>

  <section style={{background:"#edf3e9"}}><div style={{...max,paddingTop:"clamp(74px,10vw,140px)",paddingBottom:"clamp(74px,10vw,140px)"}}><div style={{...mono,color:"#176b35"}}>03_ ENTER THE LIVING SYSTEM</div><h2 style={{...display,margin:"16px 0 0",fontSize:"clamp(44px,7vw,100px)",lineHeight:.89,maxWidth:"12ch"}}>The jaguar does not exist alone.</h2><p style={{margin:"26px 0 0",maxWidth:760,fontSize:"clamp(16px,1.6vw,20px)",lineHeight:1.65,color:"rgba(8,8,8,.7)"}}>Place, prey, water, forest structure, movement and human decisions form the system around the animal. Amazonia is one regional learning entry, not the jaguar's entire range.</p><Link to="/ecosystems/amazon-rainforest" style={{display:"block",marginTop:44,background:"#071009",color:"#fff",textDecoration:"none",padding:"clamp(30px,6vw,66px)"}}><div style={{...mono,color:ACCENT}}>ECOSYSTEM_ · E4RTH_</div><strong style={{...display,display:"block",fontSize:"clamp(48px,8vw,116px)",lineHeight:.83,marginTop:22}}>AMAZON<br/>RAINFOREST</strong><p style={{maxWidth:650,color:"rgba(255,255,255,.7)",lineHeight:1.65,marginTop:26}}>Follow water, forest, species, people, pressure, evidence and response as one connected regional story.</p><div style={{...mono,color:ACCENT,marginTop:28}}>ENTER ECOSYSTEM →</div></Link></div></section>

  <section style={{background:"#fff"}}><div style={{...max,paddingTop:"clamp(72px,9vw,126px)",paddingBottom:"clamp(72px,9vw,126px)"}}><div style={{...mono,color:"#176b35"}}>04_ FOLLOW A RELATIONSHIP</div><h2 style={{...display,margin:"16px 0 0",fontSize:"clamp(42px,6vw,88px)",lineHeight:.9,maxWidth:"12ch"}}>Predator becomes relationship.</h2><p style={{margin:"24px 0 0",maxWidth:720,color:T.dim,fontSize:"clamp(16px,1.5vw,19px)",lineHeight:1.64}}>These are documented prey groups, not a universal diet formula. Relative importance changes by place and prey availability.</p><div className="jaguar-prey" style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:1,background:T.lineStrong,marginTop:42}}>{PREY.map((prey)=><div key={prey} style={{minHeight:180,padding:22,background:"#fff",display:"flex",flexDirection:"column",justifyContent:"space-between"}}><span style={{...mono,color:T.dim}}>DOCUMENTED PREY EXAMPLE</span><strong style={{fontFamily:T.display,fontSize:"clamp(20px,2vw,28px)"}}>{prey}</strong></div>)}</div></div></section>

  <section style={{background:"#050505",color:"#fff"}}><div style={{...max,paddingTop:"clamp(72px,9vw,126px)",paddingBottom:"clamp(72px,9vw,126px)"}}><div className="jaguar-motion-head" style={{display:"grid",gridTemplateColumns:"1fr auto",gap:24,alignItems:"end"}}><div><div style={{...mono,color:ACCENT}}>05_ MOTION STUDY · RIGHTS-CLEARED SOURCE</div><h2 style={{...display,margin:"16px 0 0",fontSize:"clamp(42px,6vw,88px)",lineHeight:.9,maxWidth:"12ch"}}>Watch the animal move.</h2></div><button onClick={()=>setMotion((v)=>!v)} type="button" aria-pressed={motion} style={{...mono,padding:"12px 14px",background:motion?ACCENT:"transparent",color:motion?"#050505":"#fff",border:`1px solid ${ACCENT}`,cursor:"pointer"}}>{motion?"STOP MOTION":"PLAY MOTION"}</button></div>{motion&&<div style={{marginTop:38}}><video controls autoPlay muted playsInline preload="metadata" style={{width:"100%",maxHeight:"72svh",objectFit:"cover",background:"#000"}}><source src={VIDEO.src} type="video/webm"/></video><p style={{...mono,color:"rgba(255,255,255,.5)",lineHeight:1.6}}>VIDEO · {VIDEO.creator} · {VIDEO.licence} · <a href={VIDEO.source} target="_blank" rel="noreferrer" style={{color:ACCENT}}>SOURCE ↗</a></p></div>}</div></section>

  <section style={{background:"#fff"}}><div style={{...max,paddingTop:"clamp(72px,9vw,126px)",paddingBottom:"clamp(72px,9vw,126px)"}}><div style={{...mono,color:"#176b35"}}>06_ PRESSURE · RANGE-WIDE CLASSES</div><h2 style={{...display,margin:"16px 0 0",fontSize:"clamp(42px,6vw,88px)",lineHeight:.9,maxWidth:"12ch"}}>Pressure is not one red warning label.</h2><div style={{marginTop:42,borderTop:`1px solid ${T.lineStrong}`}}>{PRESSURES.map(([title,boundary],i)=><div key={title} className="pressure-row" style={{display:"grid",gridTemplateColumns:"70px minmax(200px,.55fr) minmax(0,1fr)",gap:"clamp(18px,4vw,64px)",padding:"clamp(26px,4vw,48px) 0",borderBottom:`1px solid ${T.line}`}}><span style={{...mono,color:"#176b35"}}>0{i+1}</span><strong style={{fontFamily:T.display,fontSize:"clamp(22px,2.5vw,34px)",fontWeight:500}}>{title}</strong><p style={{margin:0,color:T.dim,lineHeight:1.62}}>{boundary}</p></div>)}</div><a href="https://www.panthera.org/cat/jaguar" target="_blank" rel="noreferrer" style={{...mono,display:"inline-flex",marginTop:30,color:T.ink,textDecoration:"none",borderBottom:"1px solid currentColor",paddingBottom:5}}>SOURCE · PANTHERA JAGUAR ↗</a></div></section>

  <section style={{background:ACCENT,color:"#041008"}}><div style={{...max,paddingTop:"clamp(78px,10vw,150px)",paddingBottom:"clamp(78px,10vw,150px)"}}><div style={{...mono}}>SPECIES → ECOSYSTEM → PRESSURE → RESPONSE</div><h2 style={{...display,margin:"20px 0 0",fontSize:"clamp(44px,7vw,104px)",lineHeight:.89,maxWidth:"13ch"}}>One animal is enough to enter the whole living system.</h2><div style={{display:"flex",gap:18,flexWrap:"wrap",marginTop:36}}><Link to="/ecosystems/amazon-rainforest" style={{...mono,color:"#041008",textDecoration:"none",borderBottom:"1px solid currentColor",paddingBottom:5}}>ENTER AMAZONIA →</Link><Link to="/living-systems" style={{...mono,color:"#041008",textDecoration:"none",borderBottom:"1px solid currentColor",paddingBottom:5}}>LIVING SYSTEMS →</Link><Link to="/missions/am4zonia" style={{...mono,color:"#041008",textDecoration:"none",borderBottom:"1px solid currentColor",paddingBottom:5}}>AM4ZONIA_ →</Link></div></div></section>
  <style>{`@media(max-width:850px){.jaguar-intro,.jaguar-motion-head{grid-template-columns:1fr!important}.jaguar-prey{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:620px){.jaguar-prey{grid-template-columns:1fr!important}.pressure-row{grid-template-columns:42px 1fr!important}.pressure-row p{grid-column:2}}@media(prefers-reduced-motion:reduce){video{scroll-behavior:auto}}`}</style>
 </article></PublicShell>
}
