export const DECISION_PROOF_VERSION = "s4piens-decision-proof-0.1.0";
export const DECISION_EVIDENCE_STATES = Object.freeze(["OBSERVED", "MODELLED", "CACHED", "UNKNOWN", "UNAVAILABLE"]);
export const DECISION_AXIS_IDS = Object.freeze(["YOU", "WALLET", "PLANET"]);
const states = new Set(DECISION_EVIDENCE_STATES); const axisIds = new Set(DECISION_AXIS_IDS); const text = (value) => typeof value === "string" ? value.trim() : "";
function axis(value) { const id = text(value?.id).toUpperCase(); const evidenceState = text(value?.evidenceState).toUpperCase(); if (!axisIds.has(id)) throw new TypeError(`Invalid Decision Proof axis: ${id || "missing"}`); if (!states.has(evidenceState)) throw new TypeError(`Invalid evidence state: ${evidenceState || "missing"}`); return Object.freeze({ id, evidenceState, confidence: text(value?.confidence).toUpperCase() || "UNKNOWN", summary: text(value?.summary), limitation: text(value?.limitation) }); }
export function buildDecisionProof(input = {}) {
  const axes = Array.isArray(input.axes) ? input.axes.map(axis) : []; const missingAxes = DECISION_AXIS_IDS.filter((id) => !axes.some((item) => item.id === id));
  const options = Array.isArray(input.options) ? input.options.map((option) => ({ id: text(option?.id), label: text(option?.label) })).filter((option) => option.id && option.label) : [];
  const sources = Array.isArray(input.sources) ? input.sources.map((source) => ({ id: text(source?.id) || "unknown", sourceClass: text(source?.sourceClass) || "UNKNOWN", independenceKey: text(source?.independenceKey) || text(source?.id) || "unknown", publicSafe: source?.publicSafe !== false, paidRankingInfluence: source?.paidRankingInfluence === true })) : [];
  const sponsorIndependent = sources.every((source) => !source.paidRankingInfluence); const quorumStatus = input.quorum?.status === "QUORUM" ? "QUORUM" : "NO_QUORUM"; const eligible = sponsorIndependent && quorumStatus === "QUORUM" && options.length >= 2 && missingAxes.length === 0;
  const gate = !sponsorIndependent ? "WITHHELD_SPONSOR_CONFLICT" : missingAxes.length ? "WITHHELD_AXIS_GAP" : options.length < 2 ? "WITHHELD_OPTION_GAP" : quorumStatus !== "QUORUM" ? "WITHHELD_NO_QUORUM" : "EVIDENCE_QUORUM";
  return Object.freeze({ version: DECISION_PROOF_VERSION, proofId: text(input.proofId) || `decision:${text(input.domain).toLowerCase() || "general"}:${text(input.subjectId) || "unbound"}`, createdAt: text(input.createdAt) || new Date().toISOString(), domain: text(input.domain).toUpperCase() || "GENERAL", subjectId: text(input.subjectId) || null, question: text(input.question), options, criteria: Array.isArray(input.criteria) ? input.criteria.map(text).filter(Boolean) : [], axes, missingAxes, evidence: { quorumStatus, sources, sponsorIndependent }, recommendation: { status: eligible ? "ELIGIBLE" : "WITHHELD", gate, value: eligible ? (input.recommendation ?? null) : null }, unknowns: Array.isArray(input.unknowns) ? input.unknowns.map(text).filter(Boolean) : [], hardStops: Array.isArray(input.hardStops) ? input.hardStops.map(text).filter(Boolean) : [], truthBoundary: "YOU, WALLET and PLANET remain separate. Missing evidence cannot improve an option. Paid ranking influence blocks recommendation eligibility. No universal or moral score is generated." });
}
