import type { MagazineFeature } from "@/content/magazineFeatureTypes";
import { L, P, Q, S } from "@/content/magazineFeatureTypes";

export const MAGAZINE_REPORTED_FEATURES: Record<string, MagazineFeature> = {
  "ocean-watch-1-8-million-kilometres": {
    hero: "oce4nDomainHero",
    secondaryMission: "wh4les",
    secondaryKicker: "THE METHOD / LOOKING, REPEATED",
    secondaryCaption: "A long monitoring record is built from ordinary acts repeated carefully: route, effort, observation, record.",
    secondaryNote: "4PLANET context image. It does not depict a specific ORCA survey or live cetacean location.",
    blocks: [
      L("The most important thing on a whale survey can be the hour in which nothing happens. No fin cuts the surface. No blow appears on the horizon. The sea keeps moving and the observers keep looking. That empty hour is not a failure. If the method is recorded properly, it becomes part of the evidence."),
      P("That idea sits underneath one of the more remarkable citizen-science records in European marine conservation. ORCA says its dedicated effort-based monitoring programme began in 2006 and, by the end of 2025, had accumulated 4,731 dedicated surveys, 1,848,758 kilometres of searching and more than 60,000 hours of active observation. Across those surveys, the organisation reports 363,193 individual cetaceans from 54 species."),
      P("The numbers are large enough to sound abstract. The useful way to read them is smaller: bridge watch after bridge watch, crossing after crossing, volunteers trained to look in a standardised way and to keep recording the conditions around what they see. A sighting on its own is a moment. A sighting attached to effort becomes part of a time series."),
      S("Why the blank sea matters"),
      P("Wildlife data can become misleading the moment effort disappears. Ten dolphins seen during ten minutes of looking are not the same observation as ten dolphins seen during ten hours. A route with no sightings is not an empty dataset if observers were present, conditions were recorded and the search was carried out consistently. Knowing where people looked, for how long and under what conditions gives the sightings around it meaning."),
      Q("A wildlife sighting is a moment. Repeated, standardised observation can become infrastructure."),
      P("This is why ORCA’s record is more interesting than a giant whale counter. The real object is the relationship between route, time, search effort and observation. That relationship lets researchers ask better questions about where cetaceans are encountered, how patterns change and where further work may be needed. It also prevents one of the most common errors in public nature data: turning a dot on a map into a claim it cannot support."),
      S("Citizen science with a hard edge"),
      P("Citizen science is sometimes described as though participation itself were the scientific achievement. It is not. The hard part is designing participation so that thousands of human decisions do not dissolve into incomparable anecdotes. Training, common protocols, quality control and persistence are what turn enthusiasm into useful evidence."),
      P("ORCA’s model uses vessels that are already moving through the ocean as observation platforms. That is powerful because repeated commercial routes can create recurring windows onto the same waters. It is also bounded. A ferry corridor is a corridor, not the whole ocean. What is detected depends on where the vessel travels, when surveys happen, sea state, visibility, observer effort and the animals themselves."),
      S("The lesson for environmental intelligence"),
      P("The broader lesson reaches beyond cetaceans. Environmental monitoring often fails in public interfaces because observation and interpretation are collapsed into one thing. A map shows a point, and the point quietly becomes a population. A blank area looks like absence. A dramatic encounter becomes a trend. Good systems resist that temptation."),
      P("For 4PLANET, the chain worth preserving is simple enough to say in one breath and difficult enough to build properly: route → effort → observation → evidence → interpretation → decision. The value is not in making the ocean look fully known. It is in making the limits of what we know visible enough that the next decision can be better."),
      S("What to remember"),
      P("When you see a wildlife map, ask what happened before the dot appeared. Who was looking? For how long? Along which route? Using which method? And what would a day with no sightings look like in the same system? Those questions are not footnotes. They are the difference between a compelling picture and a usable record of a living ocean."),
    ],
  },

  "five-am-bay-of-biscay": {
    hero: "participationField2",
    secondary: "pl4sticHero",
    secondaryKicker: "BAY OF BISCAY / A WORKING TRANSECT",
    secondaryCaption: "At sea, a line on a map becomes hours of attention, changing conditions and a sequence of recorded encounters.",
    secondaryNote: "4PLANET ocean context image. It is not the Salamanca, the ORCA team or a documented animal from this survey.",
    blocks: [
      L("At 5 a.m., north of the Channel Islands, the bridge of the Salamanca became a field station. The ferry was already doing what ferries do — moving people and freight between Portsmouth and Santander. For a small team of trained observers, the same journey became something else: a disciplined line through the sea."),
      P("ORCA’s account of the 22 June 2026 survey is wonderfully ordinary at first. The team reached the bridge early. Common dolphins appeared through the day. Ocean sunfish were recorded. Hours passed. Then, near the Bay of Biscay’s abyssal plain, the rhythm changed: roughly 60 common dolphins approached the ship from multiple directions just before the observers finished for the evening."),
      P("This is the kind of moment wildlife storytelling naturally gravitates towards. Sixty dolphins is cinematic. The less glamorous part is what gives the encounter scientific value: the hours before it, the route underneath it, the fact that the observers were there whether the sea was spectacular or quiet."),
      S("A route becomes a place"),
      P("The Bay of Biscay is often pictured as a blue gap between Britain, France and Spain. From a survey bridge it becomes a sequence of positions, conditions and habitats. Continental shelf gives way to deeper water. Weather and visibility change. Animals appear and disappear. The ship keeps moving, which means every observation is tied to a moving sampling effort rather than a fixed point."),
      P("On the return leg from Santander, the team recorded two Cuvier’s beaked whales not long after departure. Then came several hours with no further sightings before common dolphins and the distant blow of a large whale were recorded later in the day. A nearby ORCA survey team on another ferry had recently encountered pilot whales, Cuvier’s beaked whales and northern bottlenose whales."),
      Q("The character in this story is not only the whale or dolphin. It is the method that keeps looking when the sea stops performing."),
      S("The temptation to tell too much"),
      P("A ferry survey produces a seductive kind of geography. Plot the route, add icons for each encounter and it can start to look like a migration map. It is not. The route shows where the ship travelled. The sightings show where animals were recorded during that effort. Neither tells us, by itself, where those animals came from, where they were going or how many were in the wider population."),
      P("That restraint matters because the better environmental visualisation becomes, the easier it is to imply certainty. A line can look like a track. A cluster can look like a hotspot. An empty stretch can look biologically empty. The honest version keeps the semantic boundaries attached: survey corridor, observation, effort, conditions, source."),
      S("Science has a human interface"),
      P("There is another reason the bridge matters. Environmental intelligence is often discussed as if it begins with satellites, models or databases. Much of it still begins with a person who arrives on time, knows what counts, notices the difference between species, records the boring hours and stays alert when something finally happens."),
      P("That is what makes this route useful as a 4PLANET pilot. It is easy to understand without being simple. The reader can follow a ship from A to B, but the deeper story is about how evidence is made: humans, method, movement and uncertainty held together long enough for the sea to become more legible."),
      S("What to notice next time you cross the sea"),
      P("If you are on a ferry and see a dolphin, enjoy the sighting. Then notice the invisible system around it. How long had nobody seen anything? What was the weather doing? What part of the route were you on? Who would record the absence as carefully as the encounter? Conservation starts to look different when attention itself becomes measurable."),
    ],
  },

  "air-filter-biodiversity-time-machine": {
    hero: "whyImage",
    secondary: "pressureDoc",
    secondaryKicker: "34 YEARS / ONE ARCHIVE",
    secondaryCaption: "An environmental archive can hold more than the question it was originally built to answer.",
    secondaryNote: "4PLANET boreal context image. It is not the Swedish radionuclide station or a research figure from the study.",
    blocks: [
      L("For decades, a monitoring station in northern Sweden pulled enormous volumes of air through glass-fibre filters and stored them away. The system was built to detect radioactive particles. It was also, without anyone designing it for the job, collecting fragments of forests, fungi, insects, birds and mammals."),
      P("A Nature Communications study published in December 2025 turned that accidental archive into a 34-year ecological record. Researchers sequenced environmental DNA trapped on weekly aerosol filters from the station at 67.84°N in the boreal forest. Their analysis reconstructed relative-abundance signals for more than 2,700 genera across the tree of life."),
      P("The surprise is not simply that DNA can travel through air. That has been demonstrated before. The deeper shift is temporal: a piece of infrastructure built for one environmental risk had quietly preserved material that could be re-read decades later to answer a different question."),
      S("Air as an ecological sampling medium"),
      P("Environmental DNA has already transformed aquatic monitoring because water gathers biological traces from many organisms into a substrate that can be sampled. Terrestrial ecosystems are harder. Soil, scat, vegetation and insects each capture different fragments of the living system. Air offers another route because the near-surface atmosphere carries particles from microbes, plants, fungi and animals."),
      P("The Swedish station made that idea unusually powerful. Air was continuously pumped through 0.2-micrometre filters at roughly 1,000 cubic metres per hour, and the filters were changed weekly. That meant the archive did not contain a few isolated snapshots. It contained a repeated sampling process stretching across decades."),
      Q("The most radical sensor in this story may be an old sensor whose data we had not yet learned how to read."),
      S("What the researchers could see"),
      P("The team detected organisms across broad branches of life and produced quantitative indices that, for some vertebrates, were congruent with traditional monitoring. Bird eDNA estimates, for example, showed a statistically significant relationship with point-transect counts during overlapping years. The researchers also identified a long-term decline in diversity consistent with changes in regional forest management."),
      P("That last sentence needs care. Airborne eDNA is not a magical census. The study is explicit about uncertainty in transport distance, reference databases, biological shedding, weather and sampling. Most sequence reads — 76% — could not be classified, largely because genetic reference libraries still represent only a fraction of life. Relative abundance is not the same thing as counting every animal in the landscape."),
      S("The infrastructure hiding in plain sight"),
      P("The paper points to a bigger opportunity. Radionuclide and air-quality stations already operate under standardised protocols in many countries. Europe alone has hundreds of radionuclide monitoring stations, while global networks built for nuclear-test surveillance are deliberately distributed across the planet. If archived filters from some of those systems preserve usable biological material, the world may already possess fragments of ecological history that have never been analysed as biodiversity records."),
      P("That possibility changes how we should think about environmental infrastructure. A sensor network does not have to belong to one problem forever. The physical act of sampling can outlive the question that justified it. As sequencing methods improve and reference databases grow, old material can become newly informative."),
      S("The useful question is not ‘can AI or DNA replace field ecology?’"),
      P("It cannot, and that framing misses the point. The interesting future is layered monitoring: field surveys, acoustic recorders, camera traps, satellites, environmental DNA and existing infrastructure each contributing different kinds of evidence. The result is not one perfect eye on nature. It is a denser, more resilient observation system — one in which an air filter stored for the wrong reason can still become a window into a forest that has already changed."),
    ],
  },

  "mine-that-became-wetland": {
    hero: "e4rthDomainHero",
    secondaryMission: "rewild-land",
    secondaryKicker: "PAUL DE TOIRÕES / PORTUGAL",
    secondaryCaption: "Restoration can begin by changing the conditions and allowing living processes to do more of the work.",
    secondaryNote: "4PLANET landscape context image. It is not Paul de Toirões or a before-and-after record of the site.",
    blocks: [
      L("A mine is designed to remove things. Rock comes out. Water is pushed away. Slopes, channels and pits are engineered around extraction. At Paul de Toirões in Portugal’s Greater Côa Valley, that logic left behind a landscape so heavily altered that its scars eventually became the raw material for something else."),
      P("Tin, tungsten and sand were extracted from the site for decades before mining ended in the early 2010s. The abandoned ground was a rough geometry of deep pits, steep banks and drainage systems. Then water began collecting in the hollows. What had been industrial damage started behaving like habitat."),
      P("Rewilding Portugal began managing the roughly 300-hectare site in late 2022. According to Rewilding Europe, the approach has combined targeted interventions with natural regeneration: retain more water, improve wildlife access, address non-native plantations and then allow ecological processes to take over where they can."),
      S("Do not erase the scar too quickly"),
      P("Conventional restoration can be tempted by the image of a clean reset — remove the damage, recreate the landscape that should have been there, plant the right things and declare the site repaired. Paul de Toirões suggests a different design instinct. The excavations themselves created variation: deep and shallow water, wet margins, ditches, islands of vegetation, dry ground and regenerating woodland."),
      P("That heterogeneity matters because living systems respond to conditions, not intentions. Different depths and moisture regimes create niches. Temporary ponds can become breeding habitat. Regenerating forest changes shade and shelter. A badly altered landscape can still contain physical structure that recovery is able to reuse."),
      Q("Restoration can be an act of design restraint: change the conditions, then allow the living system to answer."),
      S("What has actually been measured"),
      P("Rewilding Europe reports that surveys in 2023 and 2024 recorded 94 aquatic plant species across the site. Environmental DNA analysis detected more than 200 species, while bird and amphibian monitoring has documented use of the new wetlands by species including black storks, marsh harriers and spoonbills. The organisation also highlights the southern bladderwort, an insectivorous plant sensitive to water quality and rare inland in Portugal."),
      P("These are strong signs of ecological use, but they are not the same thing as proof of a completed restoration outcome. Rewilding Portugal field officer André Couto describes the surveys as baselines. That is important. A baseline tells you where you are. The harder question — what changed because of which intervention, and whether that change lasts — requires repeated monitoring over years."),
      S("A stepping stone, not an island"),
      P("Paul de Toirões also matters because habitats are rarely useful in isolation. Rewilding Europe describes the site as part of a wider effort to improve ecological connectivity through the Greater Côa Valley. Wetlands and regenerating forest can function as stepping stones for species moving through a broader landscape that is typically much drier."),
      P("This is where the story becomes bigger than an unusual wetland. Industrial landscapes are everywhere. Quarries, mines, canals, reservoirs, rail corridors and brownfield sites contain engineered forms that nature may be able to reuse. The question is not whether every scar should be celebrated. It is whether restoration teams can learn to see latent ecological structure before bulldozing it away."),
      S("The design lesson"),
      P("The most useful thing about Paul de Toirões may be the shift in posture. Restoration does not always mean manufacturing a finished picture of nature. Sometimes it means identifying the pressures that still prevent recovery, removing enough of them, keeping the system under observation and resisting the urge to control every next step. The site is not evidence that nature heals automatically. It is evidence that recovery can become surprisingly inventive when design leaves room for life to participate."),
    ],
  },

  "ai-coral-photomosaics": {
    hero: "cor4lHero",
    secondaryMission: "cor4l",
    secondaryKicker: "REEF → IMAGE → MODEL → DECISION",
    secondaryCaption: "Photomosaics turn thousands of underwater photographs into a spatial record that can be compared over time.",
    secondaryNote: "4PLANET coral context image. It is not a CeruleanAI output or a monitored CRF restoration site.",
    addedSources: [
      { label: "CeruleanAI: Democratizing Access to High Tech Reef Monitoring", publisher: "Coral Restoration Foundation", url: "https://coralrestoration.org/science-technology/ceruleanai/", publishedAt: "2026" },
      { label: "Photomosaics: Tracking Impact", publisher: "Coral Restoration Foundation", url: "https://coralrestoration.org/restoration/photomosaics/", publishedAt: "2026" },
    ],
    blocks: [
      L("Coral restoration has a labour problem hidden inside its most beautiful photographs. Divers can return corals to a reef, but somebody still has to measure what happened afterwards. At scale, that means thousands of images, giant files, repeated surveys and hours of tracing the same living surface over and over again."),
      P("Coral Restoration Foundation uses photomosaics to turn overlapping dive photographs into high-resolution maps of reef sites. The value is continuity. A team can create a baseline before restoration, return after outplanting and compare the same physical surface months or years later. Instead of following only individual corals, the mosaic can reveal changes in coral-covered area and the surrounding reefscape."),
      P("The catch is computational. A useful reef mosaic can be gigapixels in resolution and gigabytes in size. Stitching the images, storing them and tracing coral colonies traditionally requires specialised software, powerful hardware and trained people. The monitoring system can become a bottleneck precisely when restoration begins to scale."),
      S("Automating the unglamorous middle"),
      P("CRF built CeruleanAI to attack that bottleneck. The cloud-based platform automates photomosaic stitching and now includes AI-assisted analysis for identifying and measuring coral colonies. CRF says most of its own photomosaic stitching and monitoring workflows now run through the platform."),
      P("Its 2025 annual report says 76 new users joined during the year, taking the platform to more than 120 registered researchers and practitioners. The system includes models for identifying and mapping Acropora cervicornis, Acropora palmata and Orbicella species. CRF says the models are designed to improve as more imagery is processed."),
      Q("The most useful role for AI in conservation may be less ‘decide what nature needs’ and more ‘remove repetitive work from the evidence pipeline’."),
      S("Speed is not the same as truth"),
      P("This is where the hype needs to stop. A model that traces coral faster has not restored a reef. A photomosaic is not an ecosystem. An increase in mapped coral cover is important, but it still sits inside a larger biological story involving survival, reproduction, disease, heat stress, fish communities, storm damage and the structure of the reef itself."),
      P("CRF’s own materials make the practical case rather than a magical one: lower the time, computing and expertise required to create and analyse mosaics, and more restoration teams can monitor more consistently. That matters because restoration without repeated measurement risks becoming a sequence of interventions with attractive launch photographs and weak feedback."),
      S("What changes when monitoring gets cheaper"),
      P("The deeper opportunity is not just efficiency. It is frequency. If a small team can process a reef survey without weeks of specialised work, the threshold for checking what happened goes down. More sites can be compared. Problems can be noticed earlier. Restoration planning can respond to evidence rather than relying mainly on labour-intensive snapshots."),
      P("There is also a democratisation argument. CRF explicitly positions CeruleanAI as a tool for organisations that do not have access to high-end computing or photogrammetry expertise. That promise still has to be judged by performance, cost, support and model accuracy across different reef conditions, but the direction is important: conservation technology becomes more valuable when capability travels beyond the institution that invented it."),
      S("The interface between reef and record"),
      P("The strongest version of this system is a loop: diver → images → spatial model → human interpretation → next survey → next decision. AI sits in the middle, not at the top. It does the repetitive translation faster so scientists and field teams can spend more time asking what the reef is actually telling them. That is a less spectacular story than artificial intelligence saving coral reefs. It is also a far more credible one."),
    ],
  },

  "roads-that-warn-cars-about-moose": {
    hero: "circularCityHero",
    secondary: "s4piensDomainHero",
    secondaryKicker: "TRANSPORT / A LANDSCAPE THAT MOVES",
    secondaryCaption: "The collision problem is created where transport infrastructure cuts across animal movement.",
    secondaryNote: "4PLANET human-systems context image. It is not a WILDETECT deployment site.",
    blocks: [
      L("A moose does not know where the transport system begins. It knows the forest, the smell of other animals, forage, snow, fear and the routes it has learned to move through. The road arrives later — a strip of engineered certainty pushed through a landscape that is still alive."),
      P("Norway’s collision problem sits at that boundary. SINTEF reports that 9,350 deer died in collisions during the 2024/2025 hunting year. Roads and railways fragment habitat as well as move people, creating places where human speed and animal movement repeatedly intersect."),
      P("The conventional responses are familiar: fencing, crossings, signage and clearing vegetation. They can help, but they are expensive and their effectiveness varies by place and species. WILDETECT, a Norwegian research project led by SINTEF, is asking whether the next generation of prevention could be more dynamic — a system that detects risk earlier and delivers warnings where they are actually useful."),
      S("The problem is not a missing gadget"),
      P("SINTEF’s first finding is organisational. Responsibility and data are spread across road authorities, rail operators, wildlife managers, researchers, municipalities, vehicle manufacturers, technology companies and others. Collision records exist. Population data exist. Sensors, vehicle data and user reports exist. What is missing is a clean way to make those pieces work together."),
      P("That fragmentation matters because different data answer different questions. Historical records can indicate where collisions tend to occur. Real-time sensors may tell you that an animal is present now. Vehicle systems know where traffic is. Wildlife knowledge helps interpret behaviour. No single dataset is the solution, but together they could create a more responsive warning system."),
      Q("The design problem is not simply how to move an animal across a road. It is how to make transport infrastructure perceive the living landscape around it."),
      S("A warning has to arrive in time"),
      P("Physics makes the problem uneven. A train cannot swerve and needs a long distance to stop, so a driver seeing an animal may already be too late. A car can brake or steer, but only if the warning reaches the driver early enough and is precise enough to be trusted. Constant false alarms would quickly train people to ignore the system."),
      P("Animals learn too. SINTEF notes that wildlife can habituate to traffic sounds and light, and reactions can differ between species and situations. An acoustic deterrent that works at first may become background noise later. That makes this a behavioural system as much as a sensor system."),
      S("From roadside sign to network"),
      P("One possibility raised by the researchers is direct animal warnings to vehicles in a defined area. That requires roads and cars to exchange information — effectively turning wildlife risk into another layer of intelligent transport infrastructure. Drones, roadside sensors and communication systems are also being explored as potential components."),
      P("The technical ambition is straightforward to describe and difficult to govern. Data quality has to be good enough. Systems need common standards. Traffic safety cannot be compromised by experimental alerts. Animal welfare and privacy questions have to be handled. And the system has to keep working across agencies that do not naturally share one operational interface."),
      S("The bigger design question"),
      P("For most of the last century, transport intelligence focused overwhelmingly on people and vehicles. The landscape was treated as the fixed background. WILDETECT points towards a different model: infrastructure that can sense the living world it cuts through and adjust behaviour before impact."),
      P("That does not eliminate the need for crossings, fencing or better land-use planning. It adds another layer. The future road may need to be judged not only by how efficiently it moves traffic, but by whether it can perceive enough of the surrounding ecosystem to stop treating wildlife as an unpredictable obstacle that appears seconds before a collision."),
    ],
  },

  "sea-pen-instead-of-tank": {
    hero: "rewildMarineHero",
    secondaryMission: "rewild-marine",
    secondaryKicker: "SAN PAOLO / CARE AT THE EDGE OF THE SEA",
    secondaryCaption: "A sanctuary changes the conditions of captivity; it does not automatically turn a captive animal into a wild one.",
    secondaryNote: "4PLANET marine context image. It is not the San Paolo Dolphin Refuge or one of its future residents.",
    addedSources: [
      { label: "San Paolo Dolphin Refuge", publisher: "Jonian Dolphin Conservation", url: "https://www.joniandolphin.it/san-paolo-dolphin-refuge/", publishedAt: "2026" },
      { label: "Technical observations on semi-enclosed dolphin facilities", publisher: "ACCOBAMS Scientific Committee material", url: "https://accobams.org/wp-content/uploads/2026/01/SC17.Inf10_Letter-of-concern-from-the-ACCOBAMS-Advisory-Committee-on-Semi-enclosed-facilities-regarding-two-Dolphin-refuges-Sanctuaries-in-Italy-and-Greece.pdf", publishedAt: "2026-01" },
    ],
    blocks: [
      L("There is no clean ending for every dolphin that has lived for years in a tank. Some cannot simply be carried to the coast and released. They may never have learned to find food independently. Some require continuing veterinary care. The ethical question is therefore harder than ‘captivity or freedom’. It is what a better life can realistically mean for an animal that may still depend on humans."),
      P("In southern Italy, the San Paolo Dolphin Refuge has reached an important threshold. ORCA reported on 14 August that the project had received its final permits. Developed by Jonian Dolphin Conservation since 2018, the facility occupies a seven-hectare marine area beside San Paolo Island in the Gulf of Taranto."),
      P("At its centre is a 1,600-square-metre sea pen connected to a smaller enclosure and a veterinary platform. The site includes staff accommodation, food preparation and cold storage, shade, lighting, cameras and marine sensors linked to a control room at Kètos, Jonian Dolphin Conservation’s centre in Taranto."),
      S("More sea does not mean wild"),
      P("The promise of a coastal sanctuary is environmental complexity. Natural seawater moves. Weather changes. Sound travels differently. Fish, light, temperature and the rhythms of a real marine environment create sensory conditions a conventional tank cannot reproduce. For animals that still need feeding, monitoring and medical support, that can offer a larger and more variable life without pretending human care has disappeared."),
      Q("A sanctuary is not freedom. Its value has to be judged against the reality of the animals it is built to care for."),
      P("That distinction should remain visible in the language. A sea pen is still an enclosure. A resident is still managed. A camera and sensor network can improve oversight, but technology does not answer welfare questions by itself. The quality of the refuge will depend on space, depth, social grouping, enrichment, water quality, veterinary protocols, behavioural observation and the individual needs of the dolphins who arrive."),
      S("The hard questions belong inside the story"),
      P("Earlier in 2026, material submitted to the ACCOBAMS Scientific Committee by an advisory group on semi-enclosed facilities raised questions about the technical information then publicly available for San Paolo and another proposed sanctuary. The document was a preliminary assessment based on online documentation and explicitly noted that no on-site visit had been conducted. It asked for more detail on habitat dimensions, variability, enrichment and other compliance questions."),
      P("That scrutiny does not cancel the project’s permits, nor does it prove the refuge is inadequate. It does something more useful: it reminds us that ‘sanctuary’ should not function as a moral shortcut. If this model is to become an alternative to conventional dolphinaria, it needs the same thing good conservation needs everywhere else — transparent standards, independent scrutiny and evidence over time."),
      S("A pilot, not a universal answer"),
      P("ORCA says the refuge will begin with a small number of dolphins and expand gradually as the team gains experience. That is sensible because the residents will not be interchangeable units. Social compatibility, medical history and behaviour will shape what good care looks like for each animal."),
      P("Sanctuaries also cannot solve the captive-dolphin problem on their own. Even a well-run refuge has limited capacity. ORCA argues that breeding, future lifetime-care planning and standards within facilities that continue to hold dolphins remain part of the wider transition."),
      S("Architecture at the edge of biology"),
      P("What makes San Paolo worth watching is that it turns an ethical argument into a physical design problem. Nets, platforms, depth, currents, veterinary access, hydrophones, cameras, shade and human routines all become part of an animal’s daily environment. The success of the refuge will not be proved by the first dramatic photographs of dolphins entering blue water. It will be proved much later, in behaviour, health, welfare records and the quality of the lives the enclosure makes possible."),
    ],
  },
};
