export type FilmAccess = "FULL_FREE" | "STREAM" | "TRAILER" | "SOURCE";
export type FilmStatus = "PUBLISHED" | "RESEARCH";
export type FilmAccent = "blue" | "green" | "yellow" | "orange" | "pink" | "violet" | "cyan" | "ink";
export type FilmTopic = "OCEAN" | "LAND_WILDLIFE" | "FOOD" | "CLIMATE" | "ENERGY" | "SOLUTIONS" | "PEOPLE";

export type FilmRecord = {
  slug: string;
  title: string;
  year: number;
  focus: string;
  topics: FilmTopic[];
  status: FilmStatus;
  accent: FilmAccent;
  director: string;
  runtime: string;
  access: FilmAccess;
  platform: string;
  description: string;
  credit: string;
  watchUrl: string;
  trailerId?: string;
  imageUrl: string;
  fallbackImageUrl: string;
  imageAlt: string;
  imageCredit: string;
  imageRights: string;
  imageSourceUrl: string;
  sourceUrl: string;
  sourceLabel: string;
  sourceDescriptionUrl: string;
  selectionNote: string;
  availabilityNote: string;
};

const ASSETS = {
  earth: "/assets/brand/earth-iss.jpg",
  forest: "/assets/domains/e4rth/hero.jpg",
  amazon: "/assets/missions/am4zonia/hero.jpg",
  ocean: "/assets/domains/oce4n/hero.jpg",
  coral: "/assets/missions/cor4l/hero-real.jpg",
  marineRestore: "/assets/missions/rewild-marine/hero.jpg",
  plastic: "/assets/missions/pl4stic/hero.jpg",
  food: "/assets/missions/food/hero.jpg",
  energy: "/assets/missions/en3rgy/hero.jpg",
  species: "/assets/missions/species/hero.jpg",
  rewild: "/assets/missions/rewild/hero.jpg",
  people: "/assets/brand/participation-field-2.jpg",
} as const;

const PATAGONIA_CATALOGUE = "https://www.patagonia.com/films/all/";
const EARTH_FALLBACK = ASSETS.earth;
const contextualRights = "4PLANET CONTEXTUAL ASSET — NOT A FILM STILL";

function contextualImage(url: string, alt: string) {
  return {
    imageUrl: url,
    fallbackImageUrl: EARTH_FALLBACK,
    imageAlt: alt,
    imageCredit: "4PLANET contextual imagery",
    imageRights: contextualRights,
    imageSourceUrl: url,
  };
}

function researchFilm(input: {
  slug: string;
  title: string;
  year: number;
  focus: string;
  topics: FilmTopic[];
  sourceUrl: string;
  accent: FilmAccent;
  imageUrl?: string;
}): FilmRecord {
  const imageUrl = input.imageUrl ?? EARTH_FALLBACK;
  return {
    ...input,
    status: "RESEARCH",
    director: "EDITORIAL VERIFICATION PENDING",
    runtime: "TBC",
    access: "SOURCE",
    platform: "OFFICIAL / DISTRIBUTOR SOURCE",
    description: "Research candidate for a future 4PLANET FILMS selection. Publication requires a final source, availability and rights check.",
    credit: "Not yet published. Credits remain pending final editorial verification.",
    watchUrl: input.sourceUrl,
    ...contextualImage(imageUrl, `${input.title} — contextual 4PLANET image for editorial research`),
    sourceLabel: "OFFICIAL / DISTRIBUTOR RESEARCH SOURCE",
    sourceDescriptionUrl: input.sourceUrl,
    selectionNote: "Research candidate. Not yet part of the public selection.",
    availabilityNote: "Availability not yet verified for publication.",
  };
}

const published: FilmRecord[] = [
  {
    slug: "yanuni",
    title: "YANUNI",
    year: 2025,
    focus: "AMAZONIA / INDIGENOUS STEWARDSHIP",
    topics: ["LAND_WILDLIFE", "CLIMATE", "PEOPLE"],
    status: "PUBLISHED",
    accent: "green",
    director: "Richard Ladkani",
    runtime: "112 MIN",
    access: "FULL_FREE",
    platform: "YOUTUBE / LEONARDO DICAPRIO",
    description: "A cinematic portrait of Indigenous leader Juma Xipaia as her defence of Xipaya territory moves from the Amazon to the political front line of climate justice.",
    credit: "Directed by Richard Ladkani. Produced by Juma Xipaia, Leonardo DiCaprio, Anita Ladkani, Richard Ladkani, Jennifer Davisson and Phillip Watson.",
    watchUrl: "https://www.youtube.com/channel/UChlkJxkgWqVc11Cwuz1GSbg",
    trailerId: "80WKaCyAjUY",
    ...contextualImage(ASSETS.amazon, "Amazon rainforest — contextual 4PLANET image for YANUNI"),
    sourceUrl: "https://malaikapictures.com/portfolio/yanuni",
    sourceLabel: "MALAIKA PICTURES / OFFICIAL FILM PAGE",
    sourceDescriptionUrl: "https://malaikapictures.com/portfolio/yanuni",
    selectionNote: "Indigenous sovereignty, illegal mining, the Amazon and the human cost of defending a living system.",
    availabilityNote: "Released free globally on Leonardo DiCaprio’s official YouTube channel on 5 September 2026. The watch button currently opens that official channel because the exact full-film video URL was not independently recoverable from indexed source material during this pass.",
  },
  {
    slug: "the-territory",
    title: "The Territory",
    year: 2022,
    focus: "AMAZONIA / INDIGENOUS STEWARDSHIP",
    topics: ["LAND_WILDLIFE", "CLIMATE", "PEOPLE"],
    status: "PUBLISHED",
    accent: "orange",
    director: "Alex Pritz",
    runtime: "83 MIN",
    access: "TRAILER",
    platform: "NATIONAL GEOGRAPHIC / DISNEY+",
    description: "An on-the-ground account of the Uru-eu-wau-wau people confronting deforestation and encroachment in the Brazilian Amazon while taking control of how their story is recorded.",
    credit: "Directed by Alex Pritz. Official trailer published by National Geographic Documentary Films.",
    watchUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4",
    trailerId: "wL9wvdbk7A4",
    ...contextualImage(ASSETS.amazon, "Amazon rainforest — contextual 4PLANET image for The Territory"),
    sourceUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4",
    sourceLabel: "NATIONAL GEOGRAPHIC / OFFICIAL TRAILER",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4",
    selectionNote: "A crucial companion to YANUNI: territory, forest loss, Indigenous agency and control of the narrative.",
    availabilityNote: "Official trailer route verified. Full streaming availability varies by market.",
  },
  {
    slug: "seaspiracy",
    title: "Seaspiracy",
    year: 2021,
    focus: "OCEAN / FISHING",
    topics: ["OCEAN", "FOOD", "CLIMATE"],
    status: "PUBLISHED",
    accent: "cyan",
    director: "Ali Tabrizi",
    runtime: "89 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "A filmmaker investigates human pressures on marine life and the global fishing industry, following the trail from ocean damage to the systems behind it.",
    credit: "Directed by Ali Tabrizi. Streaming and official film information via Netflix.",
    watchUrl: "https://www.netflix.com/title/81014008",
    trailerId: "1Q5CXN7soQg",
    ...contextualImage(ASSETS.ocean, "Open ocean and whale — contextual 4PLANET image for Seaspiracy"),
    sourceUrl: "https://www.netflix.com/title/81014008",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/81014008",
    selectionNote: "A provocative entry point into fishing, marine biodiversity, seafood systems and contested sustainability claims.",
    availabilityNote: "Netflix availability can vary by country and subscription.",
  },
  {
    slug: "chasing-coral",
    title: "Chasing Coral",
    year: 2017,
    focus: "OCEAN / CLIMATE",
    topics: ["OCEAN", "CLIMATE"],
    status: "PUBLISHED",
    accent: "pink",
    director: "Jeff Orlowski",
    runtime: "93 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "Divers, scientists and photographers build a visual record of coral bleaching and the rapid changes unfolding across reef systems around the world.",
    credit: "Directed by Jeff Orlowski. A production of Exposure Labs. Official film information via Chasing Coral and Netflix.",
    watchUrl: "https://www.netflix.com/title/80168188",
    trailerId: "b6fHA9R2cKI",
    ...contextualImage(ASSETS.coral, "Living coral reef — contextual 4PLANET image for Chasing Coral"),
    sourceUrl: "https://chasingcoral.com/the-film/",
    sourceLabel: "CHASING CORAL / OFFICIAL",
    sourceDescriptionUrl: "https://chasingcoral.com/the-film/",
    selectionNote: "A direct bridge into coral heat stress, visual evidence and climate-driven ecosystem change.",
    availabilityNote: "Netflix availability can vary by country and subscription.",
  },
  {
    slug: "cowspiracy",
    title: "Cowspiracy: The Sustainability Secret",
    year: 2014,
    focus: "FOOD / LAND / CLIMATE",
    topics: ["FOOD", "CLIMATE", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "yellow",
    director: "Kip Andersen & Keegan Kuhn",
    runtime: "90 MIN",
    access: "SOURCE",
    platform: "OFFICIAL FILM",
    description: "An investigation into the environmental footprint of animal agriculture and why food-system impacts have often sat outside mainstream environmental campaigning.",
    credit: "Directed by Kip Andersen and Keegan Kuhn. Official film route provided by the Cowspiracy team.",
    watchUrl: "https://www.cowspiracy.com/",
    trailerId: "nV04zyfLyN4",
    ...contextualImage(ASSETS.food, "Agricultural landscape — contextual 4PLANET image for Cowspiracy"),
    sourceUrl: "https://www.cowspiracy.com/",
    sourceLabel: "COWSPIRACY / OFFICIAL",
    sourceDescriptionUrl: "https://www.cowspiracy.com/",
    selectionNote: "Directly relevant to FOOD_: land, water, emissions, consumption and contested systems claims.",
    availabilityNote: "Use the official film site for current viewing options; availability can change by market.",
  },
  {
    slug: "kiss-the-ground",
    title: "Kiss the Ground",
    year: 2020,
    focus: "FOOD / SOIL / REGENERATION",
    topics: ["FOOD", "CLIMATE", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "green",
    director: "Joshua Tickell & Rebecca Harrell Tickell",
    runtime: "84 MIN",
    access: "TRAILER",
    platform: "OFFICIAL FILM / STREAMING VARIES",
    description: "Scientists, farmers and advocates explore regenerative agriculture and soil restoration as tools for rebuilding ecosystems, food systems and climate resilience.",
    credit: "Directed by Joshua Tickell and Rebecca Harrell Tickell. Official trailer route published by the film team.",
    watchUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs",
    trailerId: "3iknWWKZOUs",
    ...contextualImage(ASSETS.food, "Farmland — contextual 4PLANET image for Kiss the Ground"),
    sourceUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs",
    sourceLabel: "OFFICIAL TRAILER",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs",
    selectionNote: "A solutions-led FOOD_ film connecting soil, farming, ecosystems and regeneration.",
    availabilityNote: "Official trailer route verified. Full-film streaming availability varies by market.",
  },
  {
    slug: "my-octopus-teacher",
    title: "My Octopus Teacher",
    year: 2020,
    focus: "OCEAN / SPECIES / KELP",
    topics: ["OCEAN", "LAND_WILDLIFE", "PEOPLE"],
    status: "PUBLISHED",
    accent: "violet",
    director: "Pippa Ehrlich & James Reed",
    runtime: "85 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "A filmmaker’s relationship with a wild octopus becomes an intimate route into the complexity of a South African kelp forest and the life within it.",
    credit: "Directed by Pippa Ehrlich and James Reed. Streaming and official film information via Netflix.",
    watchUrl: "https://www.netflix.com/title/81045007",
    trailerId: "3s0LTDhqe5A",
    ...contextualImage(ASSETS.marineRestore, "Coastal underwater habitat — contextual 4PLANET image for My Octopus Teacher"),
    sourceUrl: "https://www.netflix.com/title/81045007",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/81045007",
    selectionNote: "Life first: species behaviour, kelp forests and the emotional power of seeing an ecosystem through one animal.",
    availabilityNote: "Netflix availability can vary by country and subscription.",
  },
  {
    slug: "a-plastic-ocean",
    title: "A Plastic Ocean",
    year: 2016,
    focus: "OCEAN / PLASTIC",
    topics: ["OCEAN", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "blue",
    director: "Craig Leeson",
    runtime: "102 MIN",
    access: "SOURCE",
    platform: "OFFICIAL FILM",
    description: "A global expedition traces plastic pollution through marine environments, wildlife and food chains while also examining technologies and practical responses.",
    credit: "Directed by Craig Leeson. Official film and viewing information via the A Plastic Ocean team.",
    watchUrl: "https://aplasticocean.movie/",
    trailerId: "6zrn4-FfbXw",
    ...contextualImage(ASSETS.plastic, "Plastic pollution underwater — contextual 4PLANET image for A Plastic Ocean"),
    sourceUrl: "https://aplasticocean.movie/",
    sourceLabel: "A PLASTIC OCEAN / OFFICIAL",
    sourceDescriptionUrl: "https://aplasticocean.movie/",
    selectionNote: "Ocean plastic pressure, marine life, food chains and solution pathways in one accessible film.",
    availabilityNote: "Use the official film route for current viewing options.",
  },
  {
    slug: "common-ground",
    title: "Common Ground",
    year: 2023,
    focus: "FOOD / SOIL / SYSTEMS",
    topics: ["FOOD", "CLIMATE", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "orange",
    director: "Josh Tickell & Rebecca Tickell",
    runtime: "105 MIN",
    access: "SOURCE",
    platform: "OFFICIAL FILM / STREAMING VARIES",
    description: "Farmers, scientists and advocates examine the systems shaping American agriculture and the potential for regenerative farming and soil health to change them.",
    credit: "Directed by Josh Tickell and Rebecca Tickell. Official film information via Common Ground.",
    watchUrl: "https://commongroundfilm.org/",
    trailerId: "6-M4Hq0MKFA",
    ...contextualImage(ASSETS.food, "Agricultural landscape — contextual 4PLANET image for Common Ground"),
    sourceUrl: "https://commongroundfilm.org/",
    sourceLabel: "COMMON GROUND / OFFICIAL",
    sourceDescriptionUrl: "https://commongroundfilm.org/",
    selectionNote: "A contemporary systems film for FOOD_, connecting policy, farming, health, soil and regeneration.",
    availabilityNote: "Use the official film site for current viewing options; availability varies by market.",
  },
  {
    slug: "sea-of-shadows",
    title: "Sea of Shadows",
    year: 2019,
    focus: "OCEAN / SPECIES / WILDLIFE CRIME",
    topics: ["OCEAN", "LAND_WILDLIFE", "PEOPLE"],
    status: "PUBLISHED",
    accent: "ink",
    director: "Richard Ladkani",
    runtime: "104 MIN",
    access: "SOURCE",
    platform: "NATIONAL GEOGRAPHIC",
    description: "Scientists, investigators, journalists and activists confront an illegal wildlife-trafficking network whose fishing methods are pushing the vaquita toward extinction.",
    credit: "Directed by Richard Ladkani. Official trailer and film information via National Geographic.",
    watchUrl: "https://www.nationalgeographic.com/tv/movies-and-specials/5601e93d-e0e6-490c-b031-041463edeedf",
    trailerId: "QiFjJCUd9ro",
    ...contextualImage(ASSETS.ocean, "Open ocean — contextual 4PLANET image for Sea of Shadows"),
    sourceUrl: "https://www.youtube.com/watch?v=QiFjJCUd9ro",
    sourceLabel: "NATIONAL GEOGRAPHIC / OFFICIAL",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=QiFjJCUd9ro",
    selectionNote: "A species-level crisis connected to fishing, organised crime and conservation action.",
    availabilityNote: "Viewing availability varies by market; the official National Geographic route is linked.",
  },
  {
    slug: "artifishal",
    title: "Artifishal",
    year: 2019,
    focus: "RIVERS / SALMON / AQUACULTURE",
    topics: ["OCEAN", "FOOD", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "pink",
    director: "Liars & Thieves!",
    runtime: "79 MIN",
    access: "FULL_FREE",
    platform: "PATAGONIA FILMS / AU",
    description: "A film about wild salmon, hatcheries and fish farms — and the human decisions shaping rivers, fisheries and the future of wild fish.",
    credit: "2019 Patagonia film. Patagonia’s official film page credits direction to Liars & Thieves!.",
    watchUrl: "https://www.patagonia.com.au/blogs/films/artifishal",
    ...contextualImage(ASSETS.marineRestore, "Living coastal habitat — contextual 4PLANET image for Artifishal"),
    sourceUrl: "https://www.patagonia.com.au/blogs/films/artifishal",
    sourceLabel: "PATAGONIA FILMS / OFFICIAL",
    sourceDescriptionUrl: "https://www.patagonia.com.au/blogs/films/artifishal",
    selectionNote: "Wild salmon, aquaculture, river systems and the difference between managing nature and keeping it alive.",
    availabilityNote: "Full film is available free on Patagonia’s official Australia film page.",
  },
  {
    slug: "damnation",
    title: "DamNation",
    year: 2014,
    focus: "RIVERS / RESTORATION / INFRASTRUCTURE",
    topics: ["LAND_WILDLIFE", "ENERGY", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "cyan",
    director: "Ben Knight & Travis Rummel",
    runtime: "88 MIN",
    access: "FULL_FREE",
    platform: "PATAGONIA FILMS / AU",
    description: "A documentary about America’s changing relationship with dams, from infrastructure once celebrated as progress to river restoration and dam removal.",
    credit: "Directed by Ben Knight and Travis Rummel. Produced by Matt Stoecker and Travis Rummel.",
    watchUrl: "https://www.patagonia.com.au/blogs/films/damnation",
    ...contextualImage(ASSETS.energy, "Hydroelectric infrastructure — contextual 4PLANET image for DamNation"),
    sourceUrl: "https://www.patagonia.com.au/blogs/films/damnation",
    sourceLabel: "PATAGONIA FILMS / OFFICIAL",
    sourceDescriptionUrl: "https://www.patagonia.com.au/blogs/films/damnation",
    selectionNote: "A strong systems story about energy infrastructure, rivers, restoration and what happens when yesterday’s solution becomes today’s constraint.",
    availabilityNote: "Full film is available free on Patagonia’s official Australia film page.",
  },
  {
    slug: "public-trust",
    title: "Public Trust",
    year: 2020,
    focus: "PUBLIC LANDS / BIODIVERSITY / GOVERNANCE",
    topics: ["LAND_WILDLIFE", "CLIMATE", "PEOPLE"],
    status: "PUBLISHED",
    accent: "green",
    director: "David Garrett Byars",
    runtime: "96 MIN",
    access: "FULL_FREE",
    platform: "YOUTUBE / PATAGONIA",
    description: "A film about the fight over America’s public lands and the people defending shared landscapes from extraction, privatisation and political pressure.",
    credit: "Directed by David Garrett Byars. Full film published by Patagonia’s verified YouTube channel.",
    watchUrl: "https://www.youtube.com/watch?v=OGjnIG7puzY",
    trailerId: "OGjnIG7puzY",
    ...contextualImage(ASSETS.forest, "Forested landscape — contextual 4PLANET image for Public Trust"),
    sourceUrl: "https://www.youtube.com/watch?v=OGjnIG7puzY",
    sourceLabel: "PATAGONIA / OFFICIAL FULL FILM",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=OGjnIG7puzY",
    selectionNote: "Biodiversity is also a governance story: who decides what land is for, who benefits and what remains protected.",
    availabilityNote: "Full film is available free on Patagonia’s verified YouTube channel.",
  },
  {
    slug: "we-the-power",
    title: "We the Power",
    year: 2021,
    focus: "RENEWABLE ENERGY / COMMUNITY",
    topics: ["ENERGY", "SOLUTIONS", "PEOPLE", "CLIMATE"],
    status: "PUBLISHED",
    accent: "yellow",
    director: "David Garrett Byars",
    runtime: "39 MIN",
    access: "FULL_FREE",
    platform: "YOUTUBE / PATAGONIA",
    description: "A look at citizen-led renewable-energy cooperatives and the people trying to move energy ownership back into local communities.",
    credit: "Directed by David Garrett Byars. Full film published by Patagonia’s verified YouTube channel.",
    watchUrl: "https://www.youtube.com/watch?v=75A9WGxoUn8",
    trailerId: "75A9WGxoUn8",
    ...contextualImage(ASSETS.energy, "Energy infrastructure — contextual 4PLANET image for We the Power"),
    sourceUrl: "https://www.youtube.com/watch?v=75A9WGxoUn8",
    sourceLabel: "PATAGONIA / OFFICIAL FULL FILM",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=75A9WGxoUn8",
    selectionNote: "A practical energy-transition story about ownership, local incentives and renewable infrastructure rather than technology alone.",
    availabilityNote: "Full film is available free on Patagonia’s verified YouTube channel.",
  },
  {
    slug: "blue-heart",
    title: "Blue Heart",
    year: 2019,
    focus: "RIVERS / HYDROPOWER / EUROPE",
    topics: ["LAND_WILDLIFE", "ENERGY", "SOLUTIONS", "PEOPLE"],
    status: "PUBLISHED",
    accent: "blue",
    director: "Britton Caillouette",
    runtime: "43 MIN",
    access: "FULL_FREE",
    platform: "YOUTUBE / PATAGONIA",
    description: "A journey through some of Europe’s last wild rivers as communities and conservationists confront a wave of planned hydropower development.",
    credit: "Directed by Britton Caillouette. Full film published by Patagonia’s verified YouTube channel.",
    watchUrl: "https://www.youtube.com/watch?v=OhmHByZ0Xd8",
    trailerId: "OhmHByZ0Xd8",
    ...contextualImage(ASSETS.energy, "Hydropower infrastructure — contextual 4PLANET image for Blue Heart"),
    sourceUrl: "https://www.youtube.com/watch?v=OhmHByZ0Xd8",
    sourceLabel: "PATAGONIA / OFFICIAL FULL FILM",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=OhmHByZ0Xd8",
    selectionNote: "A useful tension inside the energy transition: renewable power can still carry major ecological costs when place and living systems are ignored.",
    availabilityNote: "Full film is available free on Patagonia’s verified YouTube channel.",
  },
  {
    slug: "the-custodians",
    title: "The Custodians",
    year: 2023,
    focus: "OCEAN / SEAGRASS / RESTORATION",
    topics: ["OCEAN", "CLIMATE", "SOLUTIONS", "PEOPLE"],
    status: "PUBLISHED",
    accent: "cyan",
    director: "Arthur Neumeier",
    runtime: "17 MIN",
    access: "FULL_FREE",
    platform: "YOUTUBE / PATAGONIA",
    description: "A short film about people on Scotland’s west coast working to restore seagrass and rebuild the relationship between coastal communities and the habitats around them.",
    credit: "Directed by Arthur Neumeier. Project lead and producer Patricia Simon. Full film published by Patagonia’s verified YouTube channel.",
    watchUrl: "https://www.youtube.com/watch?v=y8a8vuFx4N8",
    trailerId: "y8a8vuFx4N8",
    ...contextualImage(ASSETS.marineRestore, "Seagrass and coastal habitat — contextual 4PLANET image for The Custodians"),
    sourceUrl: "https://www.youtube.com/watch?v=y8a8vuFx4N8",
    sourceLabel: "PATAGONIA / OFFICIAL FULL FILM",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=y8a8vuFx4N8",
    selectionNote: "Small enough to watch now, concrete enough to act on: restoration, local knowledge and coastal stewardship in seventeen minutes.",
    availabilityNote: "Full film is available free on Patagonia’s verified YouTube channel.",
  },
  {
    slug: "mission-blue",
    title: "Mission Blue",
    year: 2014,
    focus: "OCEAN / CONSERVATION / EXPLORATION",
    topics: ["OCEAN", "CLIMATE", "PEOPLE", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "violet",
    director: "Robert Nixon & Fisher Stevens",
    runtime: "95 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "A portrait of oceanographer Sylvia Earle and her campaign to build public support for protecting critical places in the ocean.",
    credit: "Directed by Robert Nixon and Fisher Stevens. Official streaming route via Netflix.",
    watchUrl: "https://www.netflix.com/title/70308278",
    ...contextualImage(ASSETS.ocean, "Open ocean and whale — contextual 4PLANET image for Mission Blue"),
    sourceUrl: "https://www.netflix.com/title/70308278",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/70308278",
    selectionNote: "A foundational ocean-conservation film connecting one person’s lifetime of observation to the idea of protecting places at planetary scale.",
    availabilityNote: "Netflix availability can vary by country and subscription.",
  },
  {
    slug: "breaking-boundaries",
    title: "Breaking Boundaries: The Science of Our Planet",
    year: 2021,
    focus: "PLANETARY BOUNDARIES / BIODIVERSITY / CLIMATE",
    topics: ["CLIMATE", "LAND_WILDLIFE", "OCEAN", "SOLUTIONS"],
    status: "PUBLISHED",
    accent: "pink",
    director: "Jon Clay",
    runtime: "75 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "Johan Rockström and David Attenborough explain the planetary-boundaries framework, the risks of destabilising Earth systems and the space in which humanity can still act.",
    credit: "Directed by Jon Clay. Featuring Johan Rockström and Sir David Attenborough. Official Netflix film.",
    watchUrl: "https://www.netflix.com/title/81336476",
    ...contextualImage(ASSETS.earth, "Earth from orbit — contextual 4PLANET image for Breaking Boundaries"),
    sourceUrl: "https://www.netflix.com/title/81336476",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/81336476",
    selectionNote: "One of the clearest films for understanding the systems-level problem 4PLANET is trying to make navigable.",
    availabilityNote: "Netflix availability can vary by country and subscription.",
  },
  {
    slug: "the-ivory-game",
    title: "The Ivory Game",
    year: 2016,
    focus: "ELEPHANTS / WILDLIFE TRADE / CRIME",
    topics: ["LAND_WILDLIFE", "PEOPLE"],
    status: "PUBLISHED",
    accent: "ink",
    director: "Kief Davidson & Richard Ladkani",
    runtime: "112 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "An investigation into the illegal ivory trade, following activists and investigators across the networks connecting elephant poaching to international trafficking.",
    credit: "Directed by Kief Davidson and Richard Ladkani. Official streaming route via Netflix.",
    watchUrl: "https://www.netflix.com/title/80117533",
    ...contextualImage(ASSETS.species, "Wild animal in low light — contextual 4PLANET image for The Ivory Game"),
    sourceUrl: "https://www.netflix.com/title/80117533",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/80117533",
    selectionNote: "Species loss is often a network problem involving crime, demand, money, enforcement and local risk — not only a wildlife story.",
    availabilityNote: "Netflix availability can vary by country and subscription.",
  },
  {
    slug: "the-biggest-little-farm",
    title: "The Biggest Little Farm",
    year: 2018,
    focus: "FOOD / BIODIVERSITY / REGENERATIVE FARMING",
    topics: ["FOOD", "LAND_WILDLIFE", "SOLUTIONS", "PEOPLE"],
    status: "PUBLISHED",
    accent: "orange",
    director: "John Chester",
    runtime: "91 MIN",
    access: "STREAM",
    platform: "NEON / RENT OR BUY",
    description: "John and Molly Chester try to build a diverse farm by working with ecological relationships rather than against them, learning through pests, predators, soil and seasons.",
    credit: "Directed by John Chester. Official film and watch route via NEON.",
    watchUrl: "https://www.neonrated.com/film/the-biggest-little-farm",
    ...contextualImage(ASSETS.food, "Farmland — contextual 4PLANET image for The Biggest Little Farm"),
    sourceUrl: "https://www.neonrated.com/film/the-biggest-little-farm",
    sourceLabel: "NEON / OFFICIAL FILM PAGE",
    sourceDescriptionUrl: "https://www.neonrated.com/film/the-biggest-little-farm",
    selectionNote: "A highly accessible demonstration that food production is also ecology: relationships, feedback loops, diversity and adaptation.",
    availabilityNote: "Official NEON page provides current rent/buy routes; price and availability vary by market.",
  },
];

const research: FilmRecord[] = [
  researchFilm({ slug: "newtok", title: "Newtok", year: 2021, focus: "CLIMATE / COMMUNITY", topics: ["CLIMATE", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "cyan", imageUrl: ASSETS.people }),
  researchFilm({ slug: "the-scale-of-hope", title: "The Scale of Hope", year: 2022, focus: "CLIMATE / ACTION", topics: ["CLIMATE", "SOLUTIONS", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "yellow", imageUrl: ASSETS.earth }),
  researchFilm({ slug: "takayna", title: "Takayna", year: 2018, focus: "FOREST / CONSERVATION", topics: ["LAND_WILDLIFE", "CLIMATE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "green", imageUrl: ASSETS.forest }),
  researchFilm({ slug: "treeline", title: "Treeline", year: 2019, focus: "FOREST / CLIMATE", topics: ["LAND_WILDLIFE", "CLIMATE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "violet", imageUrl: ASSETS.forest }),
  researchFilm({ slug: "jalpi", title: "Jalpi", year: 2023, focus: "OCEAN / RESTORATION", topics: ["OCEAN", "SOLUTIONS", "PEOPLE"], sourceUrl: "https://www.patagonia.com/films/jalpi/", accent: "cyan", imageUrl: ASSETS.marineRestore }),
  researchFilm({ slug: "corazon-salado", title: "Corazón Salado", year: 2024, focus: "OCEAN / INDIGENOUS STEWARDSHIP", topics: ["OCEAN", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "pink", imageUrl: ASSETS.ocean }),
  researchFilm({ slug: "undammed", title: "Undammed", year: 2024, focus: "RIVERS / INDIGENOUS STEWARDSHIP", topics: ["LAND_WILDLIFE", "PEOPLE", "SOLUTIONS"], sourceUrl: PATAGONIA_CATALOGUE, accent: "blue", imageUrl: ASSETS.forest }),
  researchFilm({ slug: "laxathjod", title: "Laxaþjóð | A Salmon Nation", year: 2024, focus: "SALMON / AQUACULTURE", topics: ["OCEAN", "FOOD", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "cyan", imageUrl: ASSETS.marineRestore }),
  researchFilm({ slug: "range-rider", title: "Range Rider", year: 2023, focus: "WOLVES / COEXISTENCE", topics: ["LAND_WILDLIFE", "PEOPLE", "SOLUTIONS"], sourceUrl: PATAGONIA_CATALOGUE, accent: "violet", imageUrl: ASSETS.species }),
  researchFilm({ slug: "the-shitthropocene", title: "The Shitthropocene", year: 2024, focus: "CONSUMPTION / CIRCULARITY", topics: ["CLIMATE", "SOLUTIONS", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "pink", imageUrl: ASSETS.people }),
  researchFilm({ slug: "district-15", title: "District 15", year: 2020, focus: "JUSTICE / POLLUTION", topics: ["PEOPLE", "CLIMATE", "SOLUTIONS"], sourceUrl: PATAGONIA_CATALOGUE, accent: "orange", imageUrl: ASSETS.people }),
  researchFilm({ slug: "a-net-plus", title: "A Net Plus", year: 2018, focus: "OCEAN / CIRCULARITY", topics: ["OCEAN", "SOLUTIONS"], sourceUrl: PATAGONIA_CATALOGUE, accent: "blue", imageUrl: ASSETS.plastic }),
  researchFilm({ slug: "why-recycled", title: "Why Recycled?", year: 2020, focus: "FASHION / CIRCULARITY", topics: ["SOLUTIONS", "CLIMATE"], sourceUrl: "https://www.patagonia.com/why-recycled/", accent: "yellow", imageUrl: ASSETS.people }),
  researchFilm({ slug: "estado-salmonero", title: "Estado Salmonero", year: 2019, focus: "OCEAN / AQUACULTURE", topics: ["OCEAN", "FOOD", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "cyan", imageUrl: ASSETS.ocean }),
  researchFilm({ slug: "sea-country-malu-lag", title: "Sea Country / Malu Lag", year: 2025, focus: "ISLANDS / CLIMATE / CULTURE", topics: ["OCEAN", "CLIMATE", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "violet", imageUrl: ASSETS.ocean }),
  researchFilm({ slug: "running-up-for-air", title: "Running Up For Air", year: 2023, focus: "AIR / HEALTH / COMMUNITY", topics: ["CLIMATE", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "yellow", imageUrl: ASSETS.people }),
  researchFilm({ slug: "home-grown", title: "Home, Grown", year: 2023, focus: "BUILDINGS / LOW-CARBON MATERIALS", topics: ["CLIMATE", "SOLUTIONS"], sourceUrl: "https://www.patagonia.com/stories/culture/workwear/home-grown/video-141549.html", accent: "green", imageUrl: ASSETS.rewild }),
  researchFilm({ slug: "bring-hemp-home-colorado", title: "Bring Hemp Home: Colorado", year: 2021, focus: "AGRICULTURE / HEMP / SOIL", topics: ["FOOD", "CLIMATE", "SOLUTIONS"], sourceUrl: "https://eu.patagonia.com/nl/en/stories/culture/workwear/bring-hemp-home-colorado/video-96711.html", accent: "green", imageUrl: ASSETS.food }),
  researchFilm({ slug: "run-to-save-a-watershed", title: "Corriendo para salvar una Cuenca (Run to Save a Watershed)", year: 2021, focus: "WATER / HYDROPOWER / COMMUNITY", topics: ["ENERGY", "LAND_WILDLIFE", "PEOPLE"], sourceUrl: "https://eu.patagonia.com/dk/en/stories/sports/trail-running/corriendo-para-salvar-una-cuenca-run-to-save-a-watershed/video-101876.html", accent: "blue", imageUrl: ASSETS.energy }),
  researchFilm({ slug: "cochamo-por-siempre", title: "Cochamó Por Siempre", year: 2026, focus: "CONSERVATION / COMMUNITY", topics: ["LAND_WILDLIFE", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "green", imageUrl: ASSETS.forest }),
  researchFilm({ slug: "we-can-get-there-from-here", title: "We Can Get There from Here", year: 2024, focus: "OCEAN / WORKING WATERFRONTS", topics: ["OCEAN", "PEOPLE", "SOLUTIONS"], sourceUrl: PATAGONIA_CATALOGUE, accent: "cyan", imageUrl: ASSETS.ocean }),
  researchFilm({ slug: "the-green-buffalo", title: "The Green Buffalo", year: 2024, focus: "BUILDINGS / HEMP / INDIGENOUS", topics: ["SOLUTIONS", "PEOPLE", "CLIMATE"], sourceUrl: "https://www.patagonia.com/stories/culture/workwear/the-green-buffalo/video-154708.html", accent: "green", imageUrl: ASSETS.rewild }),
  researchFilm({ slug: "fire-lines", title: "Fire Lines", year: 2024, focus: "FIRE / FOREST MANAGEMENT / INDIGENOUS KNOWLEDGE", topics: ["LAND_WILDLIFE", "CLIMATE", "PEOPLE", "SOLUTIONS"], sourceUrl: "https://eu.patagonia.com/ee/en/films/fire-lines/", accent: "orange", imageUrl: ASSETS.forest }),
  researchFilm({ slug: "totoganashi", title: "Totoganashi", year: 2024, focus: "OCEAN / COMMUNITY", topics: ["OCEAN", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "blue", imageUrl: ASSETS.ocean }),
  researchFilm({ slug: "this-is-not-a-drill", title: "This Is Not a Drill", year: 2026, focus: "FOSSIL FUELS / CLIMATE / ACTIVISM", topics: ["CLIMATE", "ENERGY", "PEOPLE"], sourceUrl: "https://www.patagonia.com/stories/planet/activism/this-is-not-a-drill/video-174878.html", accent: "orange", imageUrl: ASSETS.energy }),
  researchFilm({ slug: "hot-pink-dolphins", title: "Hot Pink Dolphins", year: 2024, focus: "DOLPHINS / OCEAN", topics: ["OCEAN", "LAND_WILDLIFE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "pink", imageUrl: ASSETS.ocean }),
  researchFilm({ slug: "the-last-observers", title: "The Last Observers", year: 2024, focus: "CLIMATE / OBSERVATION", topics: ["CLIMATE", "PEOPLE"], sourceUrl: PATAGONIA_CATALOGUE, accent: "violet", imageUrl: ASSETS.earth }),
  researchFilm({ slug: "before-the-flood", title: "Before the Flood", year: 2016, focus: "CLIMATE / SYSTEMS", topics: ["CLIMATE", "PEOPLE", "SOLUTIONS"], sourceUrl: "https://www.beforetheflood.com/", accent: "blue", imageUrl: ASSETS.earth }),
  researchFilm({ slug: "2040", title: "2040", year: 2019, focus: "SOLUTIONS / ENERGY / FOOD", topics: ["SOLUTIONS", "ENERGY", "FOOD", "CLIMATE"], sourceUrl: "https://www.modernfilms.com/2040", accent: "yellow", imageUrl: ASSETS.energy }),
  researchFilm({ slug: "reinventing-power", title: "Reinventing Power: America’s Renewable Energy Boom", year: 2018, focus: "RENEWABLE ENERGY / JOBS", topics: ["ENERGY", "SOLUTIONS", "PEOPLE", "CLIMATE"], sourceUrl: "https://www.sierraclub.org/reinventing-power", accent: "green", imageUrl: ASSETS.energy }),
];

export const FILMS: FilmRecord[] = [...published, ...research];
export const PUBLISHED_FILMS = FILMS.filter((film) => film.status === "PUBLISHED");
export const RESEARCH_FILMS = FILMS.filter((film) => film.status === "RESEARCH");

export function filmBySlug(slug?: string) {
  return PUBLISHED_FILMS.find((film) => film.slug === slug);
}

export function relatedFilms(slug: string, limit = 3) {
  const source = filmBySlug(slug);
  if (!source) return [];
  return PUBLISHED_FILMS
    .filter((film) => film.slug !== slug)
    .map((film) => ({ film, score: film.topics.filter((topic) => source.topics.includes(topic)).length }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score || PUBLISHED_FILMS.indexOf(a.film) - PUBLISHED_FILMS.indexOf(b.film))
    .slice(0, limit)
    .map(({ film }) => film);
}
