const ARTICLE_STANDFIRSTS: Record<string, string> = {
  "ocean-watch-1-8-million-kilometres": "ORCA’s volunteer surveyors have spent more than 60,000 hours looking for cetaceans across 1.8 million kilometres of sea. The sightings matter — but the quiet hours may matter just as much, because they turn encounters into evidence.",
  "five-am-bay-of-biscay": "At 5 a.m. on a ferry bridge between Portsmouth and Santander, trained observers start reading the sea before most passengers wake. Their route through the Bay of Biscay shows how an ordinary ship can become a moving field station — and why a spectacular dolphin sighting means little without the hours of looking around it.",
  "air-filter-biodiversity-time-machine": "For 34 years, a Swedish monitoring station stored air filters designed to catch radioactive particles. Scientists have now found that those same filters were preserving traces of thousands of organisms — turning old infrastructure into an accidental archive of ecological change.",
  "mine-that-became-wetland": "A disused mine in Portugal filled with water after extraction stopped. Instead of erasing the scars, rewilding teams are using them as the bones of a new wetland — a test of whether restoration can sometimes work better when design knows when to stop.",
  "ai-coral-photomosaics": "Restoring coral is only half the job; teams still have to prove what survives. An AI-assisted photomosaic workflow is trying to turn thousands of underwater images into repeatable measurements — shifting one of restoration’s hardest problems from planting coral to tracking recovery at scale.",
  "roads-that-warn-cars-about-moose": "Norway’s wildlife-collision problem is still largely managed after animals reach the road. Researchers are testing a different idea: connect sensors, wildlife data and vehicles early enough that the road itself can warn a driver before a moose becomes an emergency.",
  "sea-pen-instead-of-tank": "Some captive dolphins can never safely return to the wild. In southern Italy, a new sea-based refuge is testing a harder question: can lifelong human care give animals more of the complexity of the ocean without pretending an enclosure is freedom?",
  "why-4planet-exists": "The environmental crisis is not short of data, projects or people who care. What is missing is a reliable way to connect what is happening, who is working on it, what evidence supports them and what a person can actually do next. 4PLANET is being built around that gap.",
  "the-four-domains": "A whale, a city, a meal and a film may look like four different stories. Ecologically, they are entangled. 4PLANET’s four Domains are a navigation system for that complexity — four entrances that should lead back to one living planet, not four separate silos.",
  "wh4les-migratory-intelligence": "A whale can cross national borders, shipping lanes, fishing grounds and changing climate zones in a single migration. Following that movement reveals the conservation problem: the animal travels as one life through systems that humans monitor, govern and protect in fragments.",
  "credible-tree-pathway": "A tree can be planted in minutes; a forest takes decades, and a functioning ecosystem takes more than trees. Before restoration becomes a product or a checkout button, the hard questions are ecological: what belongs here, what caused the damage, who can deliver the work and what evidence would count as success?",
  "amazonia-more-than-a-forest": "The Amazon does more than store carbon. Its forests move water through the atmosphere, shape rainfall, sustain immense biological networks and influence places far beyond the trees. Understanding its risk means following those relationships — not reducing a continental living system to a single deforestation number.",
  "making-impact-easy": "A payment is instant. Ecological change is not. The challenge for environmental products is to make action simple without collapsing money, delivery, monitoring and outcome into one reassuring claim. 4PLANET’s Impact model starts by keeping those layers separate.",
};

export function standfirstForStory(slug: string, fallback: string): string {
  return ARTICLE_STANDFIRSTS[slug] ?? fallback;
}
