import type { MagazineTopicId } from "@/content/magazineOperating";

export interface MagazineSignal {
  slug: string;
  title: string;
  dek: string;
  signal: string;
  whyItMatters: string;
  boundary: string;
  publisher: string;
  sourceUrl: string;
  publishedAt: string;
  asOf: string;
  topics: MagazineTopicId[];
  accent: "blue" | "green" | "yellow" | "orange" | "pink" | "violet" | "cyan";
}

/**
 * PLANET SIGNAL is the fast editorial desk: one primary or peer-reviewed source,
 * one bounded observation, one reason to care, one explicit limit.
 */
export const MAGAZINE_SIGNALS: MagazineSignal[] = [
  {
    slug: "cities-climate-biodiversity-health-blind-spots",
    title: "Cities keep solving connected problems in separate rooms",
    dek: "A 2026 study of four European cities found recurring gaps between climate, biodiversity and health goals, even where nature-based solutions were already part of policy.",
    signal: "The study reports fragmented mid-level targets, sectoral silos, weak treatment of indirect emissions and heavy reliance on softer governance tools across the cases it examined.",
    whyItMatters: "Urban nature is not just a parks question. Heat, health, biodiversity, food, materials and infrastructure cross the same streets, budgets and institutions. Better city design needs metrics and governance that can see those interactions rather than optimise one department at a time.",
    boundary: "This is a qualitative policy-document study of four European case cities. It does not establish that the same institutional pattern exists in every city or prove that a specific governance reform will produce a particular ecological outcome.",
    publisher: "npj Urban Sustainability / Nature",
    sourceUrl: "https://www.nature.com/articles/s42949-026-00345-w",
    publishedAt: "2026-02-09",
    asOf: "2026-08-24",
    topics: ["CITIES", "CLIMATE", "NATURE", "DESIGN", "SOLUTIONS"],
    accent: "orange",
  },
  {
    slug: "urban-forests-measure-biodiversity",
    title: "A city tree count is useful. It is not the same thing as biodiversity.",
    dek: "UNECE’s 2026 technical review asks how practical urban-forest indicators can become better proxies for biodiversity without pretending that one simple number captures a living city.",
    signal: "The review highlights canopy cover, species diversity and structural complexity as accessible metrics that can strengthen urban-forest assessment, while also stressing gaps in current measurement frameworks.",
    whyItMatters: "Cities need indicators that are cheap enough to use repeatedly and rich enough to guide decisions. The design challenge is to make proxies operational without allowing the proxy to replace the ecological question it was meant to illuminate.",
    boundary: "The proposed indicators are measurement aids and proxies. They are not universal biodiversity scores and should not be interpreted as direct measurements of every taxonomic group or ecological function.",
    publisher: "UNECE",
    sourceUrl: "https://unece.org/info/publications/pub/414020",
    publishedAt: "2026-05",
    asOf: "2026-08-24",
    topics: ["CITIES", "NATURE", "SCIENCE", "DESIGN"],
    accent: "green",
  },
  {
    slug: "bluenature-ocean-space-cumulative-pressure",
    title: "The ocean is becoming a planning problem with no spare layer",
    dek: "SINTEF’s new BlueNature centre is built around a hard question: how do offshore industry, food, ports, restoration and biodiversity share the same marine space without hiding cumulative pressure?",
    signal: "BlueNature describes an eight-year programme spanning ecosystem pressures, regulation, mapping, data-driven knowledge, tools and real-world use cases in restoration, industrial development and integrated spatial planning.",
    whyItMatters: "Marine decisions are often made project by project while animals, currents, noise, climate and cumulative pressure ignore administrative boundaries. Better marine intelligence has to keep those layers visible at the same time.",
    boundary: "BlueNature is a research programme and its intended methods and demonstrations are not equivalent to proven ecological outcomes. 4PLANET is reporting the programme’s stated scope, not endorsing future performance claims.",
    publisher: "SINTEF",
    sourceUrl: "https://www.sintef.no/en/projects/2026/bluenature/",
    publishedAt: "2026",
    asOf: "2026-08-24",
    topics: ["OCEAN", "SCIENCE", "TECHNOLOGY", "SOLUTIONS", "FIELD"],
    accent: "blue",
  },
  {
    slug: "automated-edna-erna-water-monitoring",
    title: "Biodiversity sampling is learning how to stay in the water longer",
    dek: "A 2026 Scientific Reports study tested automated preserved eDNA and eRNA sampling across freshwater, brackish and marine sites, including a multi-event harbour deployment.",
    signal: "The researchers report environment-consistent species turnover, detection of invasive freshwater fish, a strong rainfall-associated bacterial signal in Halifax Harbour and eRNA detections below the study’s eDNA limit of detection.",
    whyItMatters: "Remote sampling can capture time-sensitive ecological events that manual field visits miss. The deeper opportunity is not automation for its own sake, but denser environmental time series with methods and uncertainty attached.",
    boundary: "The authors describe this as a pilot and call for broader validation across habitats and water chemistries. Detection does not automatically equal abundance, and automated sampling does not remove laboratory, reference-database or interpretation constraints.",
    publisher: "Scientific Reports / Nature",
    sourceUrl: "https://www.nature.com/articles/s41598-026-58421-1",
    publishedAt: "2026-06-25",
    asOf: "2026-08-24",
    topics: ["SCIENCE", "TECHNOLOGY", "INNOVATION", "OCEAN", "FIELD"],
    accent: "cyan",
  },
  {
    slug: "urban-rewilding-design-method",
    title: "What if urban design left more room for succession?",
    dek: "A 2026 systematic review from TU Delft reframes urban rewilding as a process-led design approach rather than simply adding more green elements to a finished plan.",
    signal: "The review synthesised 1,184 records at macro level and 103 spatially explicit studies in detail, finding urban rewilding research still relatively scarce and proposing a four-level path from design intent to operational application.",
    whyItMatters: "Architecture and landscape practice usually specify finished objects. Rewilding asks designers to work with change, succession, connectivity and ecological autonomy, a different relationship between plan and living system.",
    boundary: "The review finds only a small urban subset in the detailed evidence base. Its framework is a proposed design translation, not proof that rewilding will outperform other approaches in every urban context.",
    publisher: "TU Delft / Landscape and Urban Planning",
    sourceUrl: "https://research.tudelft.nl/en/publications/exploring-rewilding-as-a-potential-design-approach-to-improve-urb/",
    publishedAt: "2026",
    asOf: "2026-08-24",
    topics: ["CITIES", "DESIGN", "NATURE", "SOLUTIONS", "SCIENCE"],
    accent: "green",
  },
  {
    slug: "nature-water-design-cities",
    title: "Stormwater infrastructure could be designed for more than water",
    dek: "A 2026 open-access paper argues that biodiversity and water-sensitive urban design are still too often planned in parallel, even when the same urban spaces are doing both jobs.",
    signal: "Workshops with ecology, hydrology, architecture and urban-planning experts identified a practical opportunity to integrate water and biodiversity objectives earlier in nature-based urban design.",
    whyItMatters: "A pond, roof or planted basin can be drainage infrastructure, habitat, heat adaptation and public space at once. The question is whether the design brief and measurement system allow those functions to coexist rather than letting one dominate by default.",
    boundary: "The work develops an integrated design approach from expert workshops and literature. It does not imply that every multi-purpose nature-based solution delivers all intended benefits without site-specific design and monitoring.",
    publisher: "Nature-Based Solutions",
    sourceUrl: "https://www.sciencedirect.com/science/article/pii/S2772411526000121",
    publishedAt: "2026-06",
    asOf: "2026-08-24",
    topics: ["CITIES", "DESIGN", "NATURE", "CLIMATE", "SOLUTIONS"],
    accent: "blue",
  },
  {
    slug: "oecd-nature-positive-cities",
    title: "Nature-positive cities need a framework that survives the budget meeting",
    dek: "OECD’s 2026 Nature-Positive Cities paper moves biodiversity from a greening aspiration toward planning, investment, monitoring and trade-off management.",
    signal: "The paper identifies recurring barriers including competing urban priorities, limited technical guidance, constrained finance and weak monitoring, then proposes an integrated framework spanning biodiversity, climate, wellbeing and economic objectives.",
    whyItMatters: "Urban nature competes for land and money. A credible nature-positive city model therefore has to work where priorities collide, not only in renderings where every objective fits comfortably together.",
    boundary: "The OECD framework is policy guidance and synthesis. It does not certify any city as nature-positive or establish that adopting the framework alone will reverse biodiversity loss.",
    publisher: "OECD",
    sourceUrl: "https://www.oecd.org/en/publications/nature-positive-cities_c2ca2a9a-en.html",
    publishedAt: "2026",
    asOf: "2026-08-24",
    topics: ["CITIES", "NATURE", "CLIMATE", "SOLUTIONS", "DESIGN"],
    accent: "violet",
  },
  {
    slug: "agriculture-needs-system-not-gadgets",
    title: "The farm of the future probably needs fewer isolated miracles",
    dek: "Researchers from the University of Bonn’s PhenoRob cluster argue that agricultural technology will not become sustainable by stacking disconnected innovations on top of the same system.",
    signal: "Their 2026 systems argument links technological change with policy and business-model design, calling for a shared vision that can coordinate innovations rather than treating soil, biodiversity, productivity and emissions as separate engineering briefs.",
    whyItMatters: "Robotics, sensing and precision tools can change farming, but optimisation at field level does not automatically redesign the incentives around a food system. Technology is most interesting when the surrounding rules make better outcomes possible.",
    boundary: "This is a research-led transformation framework, not evidence that any single technology package has already delivered a sustainable agricultural system at scale.",
    publisher: "University of Bonn / PhenoRob",
    sourceUrl: "https://www.uni-bonn.de/en/news/007-2026",
    publishedAt: "2026-01-09",
    asOf: "2026-08-24",
    topics: ["FOOD", "TECHNOLOGY", "INNOVATION", "SCIENCE", "SOLUTIONS"],
    accent: "yellow",
  },
  {
    slug: "food-waste-biopolymers-loop",
    title: "Fruit waste is being asked to do a second job",
    dek: "SINTEF’s LOOP project is testing whether fruit, vegetable and grain residues can become feedstock for coatings, packaging, biofertilisers and biostimulants.",
    signal: "The 2026–2029 project combines microbial fermentation, chemical functionalisation, materials development and agricultural applications with industry partners across the food and materials chain.",
    whyItMatters: "Circularity gets more interesting when waste prevention and material substitution meet. A residue that becomes useful is not automatically sustainable, but it creates a measurable design question around energy, chemistry, performance and end-of-life.",
    boundary: "LOOP describes research goals and intended applications. Product performance, environmental benefit and commercial scalability remain claims to be demonstrated through the project rather than assumed at launch.",
    publisher: "SINTEF",
    sourceUrl: "https://www.sintef.no/en/projects/2026/loop/",
    publishedAt: "2026",
    asOf: "2026-08-24",
    topics: ["FOOD", "INNOVATION", "TECHNOLOGY", "DESIGN", "SOLUTIONS"],
    accent: "orange",
  },
  {
    slug: "fooddiverse-diversity-at-every-level",
    title: "A resilient food system may need diversity far beyond the field",
    dek: "A new €15 million collaborative research centre led from Bonn will study diversification across crops, farms, landscapes, markets, trade and diets rather than treating diversity as one agricultural variable.",
    signal: "FoodDiverse begins in October 2026 and links agricultural, nutritional, environmental, economic, social and medical research across Germany and Ghana to examine benefits, costs and context-specific trade-offs.",
    whyItMatters: "The idea is deceptively simple: resilience may depend on diversity at multiple connected layers. That makes food diversification a systems-design question spanning what grows, what sells, what people eat and which shocks the network can absorb.",
    boundary: "FoodDiverse is a newly funded research programme. Its hypotheses and future findings should not be presented as demonstrated outcomes before the work is carried out and published.",
    publisher: "University of Bonn / DFG",
    sourceUrl: "https://www.aei.uni-bonn.de/en/faculty/news/press-archive/2026/new-crc-1780",
    publishedAt: "2026-05-15",
    asOf: "2026-08-24",
    topics: ["FOOD", "SCIENCE", "NATURE", "PEOPLE", "SOLUTIONS"],
    accent: "pink",
  },
  {
    slug: "seaweed-preservation-bluegreenfood",
    title: "Seaweed has a supply-chain problem before it has a recipe problem",
    dek: "BlueGreenFood is investigating low-energy preservation and fermentation so European seaweed can move from highly perishable biomass toward a more reliable food ingredient.",
    signal: "The project studies cold salty fermentation, microbial cultures, nutrient and bioactive compounds, full-biomass use and consumer acceptance across several European partners.",
    whyItMatters: "Alternative foods do not scale on ecological promise alone. Preservation, flavour, safety, logistics, processing energy and culture decide whether a raw material becomes something people actually eat.",
    boundary: "The project’s statements about climate and circular potential describe the rationale for research. Specific product footprints, health benefits and market adoption require product-level evidence and should not be inferred from the project description.",
    publisher: "SINTEF Ocean / FutureFoodS",
    sourceUrl: "https://www.sintef.no/en/projects/2026/bluegreenfood-innovating-sustainable-and-healthy-food-alternatives-with-seaweed-and-plant-based-proteins/",
    publishedAt: "2026",
    asOf: "2026-08-24",
    topics: ["FOOD", "OCEAN", "INNOVATION", "SCIENCE", "DESIGN"],
    accent: "cyan",
  },
  {
    slug: "carbon-farming-biodiversity-context",
    title: "Carbon-friendly farming does not produce one biodiversity response",
    dek: "A 2026 Finnish farm study found that biodiversity responses varied by practice, taxonomic group and metric, a useful warning against turning regenerative labels into ecological shortcuts.",
    signal: "Across 19 boreal farms, the researchers compared cover crops, mixed stands, adaptive grazing and ley mixtures using plants, arthropods, nematodes and birds. Abundance was often the most sensitive early metric, while responses remained context-dependent.",
    whyItMatters: "Farm interventions are frequently marketed with a single environmental story. Multi-taxa monitoring shows why the real ecological answer can be messier: a practice may help one group, do little for another and look different depending on what is measured.",
    boundary: "This is a 19-farm study in boreal Finland. It does not justify universal conclusions about carbon farming, regenerative agriculture or biodiversity outcomes in other landscapes and management systems.",
    publisher: "University of Helsinki / Agriculture, Ecosystems & Environment",
    sourceUrl: "https://researchportal.helsinki.fi/en/publications/impacts-of-carbon-farming-practices-on-biodiversity-at-the-farm-s/",
    publishedAt: "2026-04-15",
    asOf: "2026-08-24",
    topics: ["FOOD", "NATURE", "SCIENCE", "FIELD", "SOLUTIONS"],
    accent: "green",
  },
];

export function signalBySlug(slug?: string) {
  return MAGAZINE_SIGNALS.find((signal) => signal.slug === slug);
}
