import type { MagazineFeature } from "@/content/magazineFeatureTypes";
import { L, P, Q, S } from "@/content/magazineFeatureTypes";

export const MAGAZINE_EXPLAINER_FEATURES: Record<string, MagazineFeature> = {
  "why-4planet-exists": {
    hero: "earthrise",
    secondary: "participationField",
    secondaryKicker: "THE MISSING MIDDLE / KNOWING → DOING",
    secondaryCaption: "The environmental problem is not a shortage of concern. It is a broken route between understanding, credible work and action people can trust.",
    secondaryNote: "4PLANET context image. It represents participation and scale, not evidence of a specific programme or result.",
    addedSources: [
      { label: "Nexus Assessment — biodiversity, water, food and health", publisher: "IPBES", url: "https://ict.ipbes.net/ipbes-ict-guide/data-and-knowledge-management/citations-of-ipbes-assessments/nexus-assessment", publishedAt: "2024" },
    ],
    blocks: [
      L("The environmental crisis has a strange interface problem. We know more about the living planet than any generation before us. Satellites can see forest loss in near real time. Researchers can recover biodiversity from DNA floating in air. Volunteers can turn ferry routes into decades-long marine monitoring systems. Yet for an ordinary person trying to understand what matters — and what to do next — the path still feels fragmented."),
      P("Concern is not the scarce resource. People care about clean water, wildlife, food, climate, places they love and the futures of their children. What is scarce is a trustworthy route from that concern to useful understanding, from understanding to credible action, and from action to evidence of what actually happened."),
      P("That gap is where environmental communication often breaks. One side gives us crisis at planetary scale: huge numbers, red maps, collapsing trends. The other gives us frictionless action: click, donate, offset, plant, save. Between the alarm and the button sits the part people most need — context."),
      S("Nature does not arrive in departments"),
      P("The real world is connected in ways our institutions rarely are. A forest is biodiversity, water, carbon, food, livelihoods and culture at once. A city heat plan can affect health, energy, public space and urban wildlife. A fishing rule changes an economic system as well as an ecosystem. IPBES devoted an entire global assessment to the interlinkages among biodiversity, water, food and health because treating those systems separately can hide both trade-offs and opportunities."),
      P("But most public information is still organised by institution, issue or campaign. Research lives in papers. Species data live in databases. NGOs explain projects. Governments publish policy. Companies publish sustainability claims. News organisations tell stories. Investors track capital. The same place can appear in all of them without any of those systems making the relationships easy to see."),
      Q("The missing product is not more environmental information. It is a better way to move through the information we already have without losing the truth on the way."),
      S("The problem with the perfect dashboard"),
      P("There is a tempting answer: put everything on one giant dashboard. That usually creates a new failure. Complexity gets compressed until incomparable things start to look equivalent. A species occurrence becomes a population. Money paid becomes impact delivered. A partner logo becomes an endorsement. A satellite layer becomes proof of causation. The interface looks clean because the uncertainty has been deleted."),
      P("A useful system has to do the opposite. It should make the public experience simpler while preserving the distinctions underneath. Observation is not interpretation. Delivery is not outcome. A listed organisation is not automatically a partner. A dramatic image is not field evidence. When those boundaries stay attached, simplicity becomes earned rather than cosmetic."),
      S("Start with a vivid object"),
      P("Humans do not naturally enter the world through ontologies. We enter through things: an orca surfacing beside a ferry, a jaguar moving through forest, a street that becomes intolerably hot, a meal, a photograph, a river, a question. Good storytelling respects that. Start somewhere tangible, then reveal the system around it."),
      P("That is the editorial idea behind 4PLANET. A species can lead to an ecosystem. The ecosystem can reveal pressures. Pressures can connect to research, solutions and the people working on them. Those actors can connect to projects, evidence and — only when authority and delivery are real — actions a person can support."),
      S("Action should be the last simplification"),
      P("Environmental products often begin with the transaction because transactions are easy to measure. A payment creates a clean data point. Ecology rarely does. Trees die. Animals move. Weather interferes. Interventions interact with forces outside anyone’s control. The honest sequence is therefore slower: define the work, establish authority, understand cost and capacity, decide what evidence should exist, then decide whether a public action can be offered without making a larger claim than the system can prove."),
      P("Once that work is done, the public interface can become extremely simple. One tap is not the enemy. An undefined tap is. The burden of complexity should sit behind the interface, where it can be inspected, rather than on the reader who simply wants to know what a contribution means."),
      S("What 4PLANET is trying to build"),
      P("4PLANET is an attempt to build that missing middle as shared infrastructure for a living planet: a place where evidence, stories, species, ecosystems, people, solutions and action can connect without becoming the same thing. It is not a claim that one organisation can know the planet. It is a design claim that we can make the relationships between what is known, what is being tried and what remains uncertain much easier to navigate."),
      P("The test is human. A reader should leave with more than information. They should understand why something matters, what evidence supports it, where the limits are, who is doing credible work, and what a proportionate next step looks like. If the system cannot do that, it is just another place to scroll past the crisis."),
    ],
  },

  "the-four-domains": {
    hero: "heroEarth",
    secondary: "homepageBonus",
    secondaryKicker: "ONE PLANET / MULTIPLE ENTRANCES",
    secondaryCaption: "A useful map of complexity should help you enter somewhere without convincing you that the boundaries are real.",
    secondaryNote: "4PLANET planetary context image. The four Domains are navigation lenses, not scientific partitions.",
    addedSources: [
      { label: "Nexus Assessment — biodiversity, water, food and health", publisher: "IPBES", url: "https://ict.ipbes.net/ipbes-ict-guide/data-and-knowledge-management/citations-of-ipbes-assessments/nexus-assessment", publishedAt: "2024" },
    ],
    blocks: [
      L("Try to hold the whole planet in your head at once. Oceans, forests, farms, cities, microbes, markets, music, migration, weather, energy, law, food, money, memory. The exercise fails almost immediately. Planetary complexity is not only large; it is tangled."),
      P("So we divide it. Science divides by discipline. Governments divide by department. Companies divide by sector. Newsrooms divide by desk. Maps divide by layer. These divisions are useful because attention needs structure. They become dangerous when the structure starts pretending to be reality."),
      P("A drought is not just climate. It can become food prices, migration, forest fire, public health and political pressure. A whale is not just wildlife. Its life crosses prey, ocean temperature, shipping, sound, fisheries and national borders. IPBES’s Nexus Assessment formalises the same problem at policy scale: biodiversity, water, food, health and climate interact, and decisions in one part of the system can produce consequences elsewhere."),
      S("Navigation needs doors"),
      P("4PLANET uses four broad Domains — OCE4N_, E4RTH_, S4PIENS_ and 4CULTURE_ — as doors into that complexity. They are not four parts of nature. They are four ways a human might begin exploring the same living system."),
      Q("The point of a category is to help you enter the world, not to persuade you that the world respects the category."),
      S("OCE4N_ / the moving world"),
      P("Ocean stories refuse to stay still. Currents move heat. Animals migrate through jurisdictions. Sound travels farther than sight. Nutrients rise and sink. Shipping routes cut across feeding grounds. A point on a marine map can be useful, but movement and time are often the real story."),
      P("That is why OCE4N_ is less a blue container than a way of thinking about mobility, depth and connection. A ferry survey can lead to a cetacean record, then to shipping pressure, then to a monitoring method, then to a conservation decision. The object changes; the system underneath remains connected."),
      S("E4RTH_ / the slow architecture"),
      P("Land can look fixed until you pay attention to the processes. Water enters soil. Fungi connect roots. Animals move seeds. Fire resets succession. Rivers cut and deposit. Forests alter local and regional climate. Recovery can take decades while degradation can happen in a season."),
      P("E4RTH_ is where the temptation to reduce nature to area becomes especially strong. Hectares are useful, but two equally green hectares can hold very different histories, species, functions and futures. The deeper question is whether the relationships that allow a living landscape to work are intact, recovering or being lost."),
      S("S4PIENS_ / the systems we made"),
      P("Humans did not step outside ecology when we built cities, farms, power grids and global supply chains. We reorganised it. Food connects soil to supermarkets. Fashion connects fibre to chemistry, labour, water and waste. Energy connects mines, landscapes, grids, politics and atmosphere. Cities concentrate those systems until their dependencies become easier to see."),
      P("S4PIENS_ follows the designed world because many planetary pressures are produced through design decisions: materials, incentives, standards, infrastructure, convenience. That also makes human systems unusually changeable. A road, building code, business model or procurement rule can lock in pressure — or remove it."),
      S("4CULTURE_ / what a society notices"),
      P("Facts do not travel alone. Images, films, music, language, fashion and stories decide what people notice, remember and imagine. Culture can trivialise environmental problems, romanticise them or make them feel impossibly distant. It can also turn an abstract system into something people can see themselves inside."),
      P("4CULTURE_ treats attention as infrastructure. Not because a photograph replaces field work, but because field work that nobody can understand or care about struggles to shape public life. The ethical constraint is simple: beauty should open the door to evidence, not stand in for it."),
      S("The borders should leak"),
      P("The four Domains are working properly when they stop feeling like silos. A jaguar can lead from E4RTH_ into cattle supply chains in S4PIENS_. A whale can move from OCE4N_ into underwater noise created by human industry. A fashion material can begin in S4PIENS_ and end in E4RTH_ through land use. A film can begin in 4CULTURE_ and lead to a real conservation actor."),
      P("That is the design principle: separate entrances, shared infrastructure, controlled depth. Give people enough structure to find a way in. Then let the living planet break the boxes open again."),
    ],
  },

  "wh4les-migratory-intelligence": {
    hero: "wh4lesHero",
    secondary: "speciesHero",
    secondaryKicker: "MOVEMENT / THE MAP IS NEVER THE ANIMAL",
    secondaryCaption: "A migratory species turns a conservation map into a moving problem of place, time, pressure and jurisdiction.",
    secondaryNote: "4PLANET wildlife context image. It is not a live whale position or migration record.",
    addedSources: [
      { label: "IWC Strategic Plan to Mitigate Ship Strikes", publisher: "International Whaling Commission", url: "https://iwc.int/public/documents/dr1UJ/IWC_Strategic_Plan_on_Ship_Strikes_Working_Group_FINAL.pdf", publishedAt: "2017" },
    ],
    blocks: [
      L("Follow a whale for long enough and the map begins to fail. A protected area ends at a line. The animal does not. It keeps moving through shipping lanes, fishing grounds, deep water, coastlines, noise fields and political borders — carrying one biological life across a patchwork of human jurisdictions."),
      P("That movement is what makes whales powerful guides to the modern ocean. They force us to stop thinking about conservation as a set of isolated places. The relevant conditions change with season, population, prey, migration, weather and human activity. What is safe water in one month can become a high-risk corridor in another."),
      P("The same animal can encounter very different pressures along one route: entanglement risk from fishing gear, vessel traffic, underwater noise, prey shifts, heat stress and disturbance. None of those pressures is uniformly distributed. Conservation therefore becomes a problem of matching moving life with changing context."),
      S("A whale is not a dot"),
      P("Public wildlife maps often begin with observations. Someone sees an animal, a record is submitted and a point appears. That point can be scientifically useful. It is also easy to over-read. An occurrence record is not a real-time tracker. A cluster is not automatically abundance. A blank area can mean no animals, no observers or no usable data."),
      Q("The more beautiful the map becomes, the more important it is to say exactly what the map knows."),
      P("For migratory animals, time matters as much as space. A location without a date can conceal seasonality. A sighting without survey effort can conceal how hard people were looking. A route drawn between two points can imply movement that was never observed. Good marine intelligence keeps those distinctions visible instead of hiding them beneath a compelling animation."),
      S("Shipping shows why context matters"),
      P("Ship strikes are a clear example. The International Whaling Commission has documented high-risk areas where dense vessel traffic overlaps whale habitat and has promoted measures including route changes, speed management, reporting and better data. The appropriate response depends on the place. In some areas, moving shipping routes can reduce overlap. In others, whales are too broadly distributed for rerouting alone to solve the problem."),
      P("That is a useful lesson for all conservation technology: there is rarely one global lever. Risk emerges from the geometry of a specific system — animal distribution, traffic, behaviour, season, detection and the options available to people operating there."),
      S("Monitoring effort belongs beside sightings"),
      P("This is why a whale-monitoring system needs more than charismatic encounters. If trained observers searched a ferry route for six hours, those six hours are part of the record whether they saw 60 dolphins or nothing at all. Effort allows the observation to be interpreted in relation to the search."),
      P("The result is less immediately glamorous than a live animal map, but far more useful. Instead of asking only ‘where are the whales?’, the system can ask ‘where have we looked, under which conditions, what did we observe, how confident are we, and which pressure layers matter here?’"),
      S("A species becomes a systems interface"),
      P("WH4LES_ is being built around that idea. The species is the human entry point, not the endpoint. From one animal, a reader should be able to move into habitat, prey, monitoring, pressures, actors, research and possible responses while still knowing which layer is evidence and which is interpretation."),
      P("That is a more demanding way to tell a whale story. It refuses the fantasy that the ocean can be reduced to one migration line or one population number. But it gives the animal something more valuable than spectacle: context large enough to match the life it actually lives."),
    ],
  },

  "credible-tree-pathway": {
    hero: "clim4teHero",
    secondary: "rewildHero",
    secondaryKicker: "RESTORATION / THE UNIT IS NOT THE ECOSYSTEM",
    secondaryCaption: "A tree can be counted in seconds. Whether a landscape is recovering takes longer to know.",
    secondaryNote: "4PLANET forest context image. It is not evidence of a delivered Tree Unit, partner site or restoration outcome.",
    addedSources: [
      { label: "Principles and Practice of Forest Landscape Restoration", publisher: "IUCN", url: "https://portals.iucn.org/library/sites/library/files/documents/2011-017.pdf", publishedAt: "2011" },
      { label: "Improving tree planting practices — right tree, right place, right purpose", publisher: "IUCN World Conservation Congress", url: "https://portals.iucn.org/library/sites/library/files/resrecfiles/WCC_2025_RES_001_EN.pdf", publishedAt: "2025" },
    ],
    blocks: [
      L("A seedling is almost too perfect as an environmental product. It is alive, visible, countable and emotionally satisfying. Put one in the ground, take a photograph, attach a number and the story appears complete. Ecology is less cooperative."),
      P("A forest is not the sum of its trunks. It is water, soil, fungi, insects, birds, mammals, genetic diversity, disturbance, succession and human use unfolding over time. Planting can be a valuable restoration tool. It can also produce monocultures, fail in unsuitable sites, displace other ecosystems or distract from the simpler job of protecting forest that already exists."),
      P("That is why credible restoration begins before the tree. It begins with a place, the pressures acting on it, the people with rights and knowledge there, and a clear idea of what ecological function is being restored."),
      S("The right intervention may be no planting at all"),
      P("IUCN’s forest landscape restoration framework has long treated restoration as a landscape-scale process rather than a planting campaign. Depending on the context, the appropriate mix can include natural regeneration, agroforestry, enrichment planting, protection of existing forest, removal of degrading pressures and changes in policy or land management."),
      P("This matters because ecosystems recover differently. If native seed sources remain, grazing pressure is removed and fire is controlled, natural regeneration can sometimes restore complexity more effectively than planting rows of nursery-grown trees. In a severely degraded site, active planting may be necessary. The method should follow the ecology, not the marketing format."),
      Q("The easiest thing to count in restoration is not necessarily the thing that matters most."),
      S("Right tree, right place, right reason"),
      P("In 2025, the IUCN World Conservation Congress adopted a resolution warning against large-scale, short-rotation monocultures focused mainly on tree numbers and calling for stronger attention to species selection, genetic diversity, site choice and aftercare. The message is almost embarrassingly simple: planting more trees is not automatically better restoration."),
      P("A credible pathway therefore needs specific answers. What ecosystem belongs here? Which species and genetic material are appropriate? What was the land before intervention? Who has authority to act? What pressures could make the work fail? What happens to the site after the first year? Which evidence will show delivery, survival and ecological change?"),
      S("Payment is one event in a longer chain"),
      P("Environmental products often compress that chain into the moment of purchase. Money moves, a tree unit appears and the user receives a feeling of completion. But payment proves only that money moved. A planting record can show work occurred. Later monitoring can show survival. Longer-term measurements can indicate changes in habitat, carbon or ecological function. Attribution — whether those changes happened because of the intervention — is a further question."),
      P("Separating those layers does not make the experience less satisfying. It makes satisfaction honest. A person can still support a bounded piece of work quickly, but the interface should tell them what has happened now, what is expected later and what remains impossible to claim."),
      S("Why the pathway stays closed until it is real"),
      P("Inside 4PLANET, the future Tree Unit is designed around this sequence rather than around the fastest route to checkout. A pathway should remain closed while delivery authority, location, cost, ecological method, capacity, evidence requirements and reporting are unresolved. That is not missing commerce. It is unfinished truth."),
      P("When those pieces are established, simplicity becomes powerful. One action can connect a person to a real place, a real delivery partner and a visible evidence trail. The tree may still be the symbol people remember. The system underneath is what makes the symbol worth trusting."),
    ],
  },

  "amazonia-more-than-a-forest": {
    hero: "amazoniaHero",
    secondaryMission: "am4zonia",
    secondaryKicker: "AMAZON / A FOREST THAT MAKES WEATHER",
    secondaryCaption: "The Amazon is not only shaped by climate. Its trees help move moisture through the atmosphere, linking one part of the forest to another.",
    secondaryNote: "4PLANET rainforest context image. It is not a live fire, deforestation event or monitored project site.",
    addedSources: [
      { label: "Deforestation-induced drying lowers Amazon climate threshold", publisher: "Nature", url: "https://www.nature.com/articles/s41586-026-10456-0", publishedAt: "2026-05-06" },
      { label: "Impact of Amazonian deforestation on precipitation reverses between seasons", publisher: "Nature", url: "https://www.nature.com/articles/s41586-024-08570-y", publishedAt: "2025-03-05" },
    ],
    blocks: [
      L("From an aeroplane, the Amazon can look deceptively simple: green to the horizon, a surface so continuous that the forest seems almost static. Underneath that canopy is one of the most complicated pieces of living infrastructure on Earth — a system that moves water, builds its own climate, stores carbon and holds relationships among millions of organisms."),
      P("The mistake is to treat the Amazon as a collection of trees occupying a certain number of hectares. Area matters enormously, but the forest’s stability also depends on connections that are harder to photograph: moisture moving through air, animals dispersing seeds, rivers linking land and water, large trees pulling water from deep soil, fungi exchanging nutrients with roots, fire and drought reshaping which species survive."),
      P("Once you see those processes, deforestation stops looking like a purely local subtraction. Removing forest can change conditions far beyond the cleared patch because the remaining system is connected through atmosphere, hydrology and ecology."),
      S("The forest helps make its own rain"),
      P("Amazonian trees draw water from soil and release it through transpiration. Water also evaporates from intercepted rainfall on the canopy. That moisture re-enters the atmosphere and can later fall again as rain elsewhere in the basin. A 2026 Nature study notes that, locally, as much as half of forest precipitation can originate from moisture recycled within the Amazon basin."),
      P("This is not a poetic metaphor. It is a physical feedback. The study models atmospheric moisture connections and finds that deforestation can weaken the forest’s self-stabilising water cycle, allowing drought stress in one region to propagate downwind across hundreds or thousands of kilometres."),
      Q("In the Amazon, a tree can be part of the weather system experienced by another forest far away."),
      S("There is no single ‘rainfall effect’"),
      P("The science is also more complicated than a slogan such as ‘cut forest, lose rain’. A separate Nature study found that the precipitation response can reverse between seasons and spatial scales. During the wet season, circulation changes can increase rainfall locally around deforested areas while reducing it farther away. During the dry season, reduced evapotranspiration produces more consistent drying across the analysed areas."),
      P("That complexity is exactly why annual averages can hide important risk. A forest may be most vulnerable when water is already scarce. Dry-season length, drought intensity and the timing of wet-season onset can matter as much as an annual rainfall total."),
      S("A network can lose resilience before it disappears"),
      P("The 2026 modelling study explores how warming, deforestation and moisture recycling can interact. Under scenarios with minimal land-use change, it estimates widespread transition risk at much higher warming levels. When substantial deforestation is added, the model produces large cascading transition risks at considerably lower warming. These are modelled thresholds, not a countdown clock, and the authors test multiple assumptions because future land use, climate and vegetation responses remain uncertain."),
      P("The important insight is structural: risks compound. Heat makes drought more damaging. Deforestation weakens moisture recycling. Drier conditions can reduce forest resilience. A less resilient forest can become more vulnerable to further disturbance. The question is therefore not whether one magic percentage flips the Amazon from forest to savannah. It is how multiple pressures alter the probability of self-reinforcing change across a connected system."),
      S("Biodiversity is part of the machinery"),
      P("Water is only one layer. Fruit-eating birds and mammals move seeds. Pollinators connect plants across space. Predators reshape behaviour and food webs. Rivers carry nutrients and link aquatic and terrestrial life. Large old trees store carbon and move disproportionate amounts of water. Lose enough of those relationships and a satellite can still see green while ecological function has already changed."),
      P("This is why a credible Amazon interface needs more than one deforestation layer. Forest cover, drought, fire, rivers, species, land use, Indigenous territories, infrastructure, monitoring and restoration are different views of the same system. None should be allowed to pretend it explains the whole forest."),
      S("What protecting a system looks like"),
      P("The practical implication is not mysterious. Avoiding further deforestation matters. Protecting intact and regenerating forest matters. Limiting global warming matters. Restoring degraded areas matters. Where those actions happen matters too, because atmospheric and ecological connections mean one region can influence another."),
      P("The Amazon becomes easier to understand when we stop asking only ‘how much forest is left?’ and add a second question: ‘how well is the forest still functioning as a connected living system?’ The first can be mapped quickly. The second is the work of a generation."),
    ],
  },

  "making-impact-easy": {
    hero: "frontHero",
    secondary: "founderFieldImage",
    secondaryKicker: "ONE TAP / MANY DIFFERENT TRUTHS",
    secondaryCaption: "A simple action can be honest only when payment, delivery, monitoring and outcome remain separate underneath it.",
    secondaryNote: "4PLANET context image. It does not document a funded or completed Impact pathway.",
    blocks: [
      L("The best action button on the internet is almost invisible. You understand what it does. You trust the result. You tap once and move on. Environmental action should be able to feel that simple. The problem is that ecology does not happen at checkout speed."),
      P("A payment can clear in seconds. A field team may work weeks later. Trees need seasons. Wildlife monitoring takes repetition. Water quality changes with weather. Habitat recovery can take years. If an interface collapses all of those events into one word — impact — it becomes easy to use by becoming difficult to trust."),
      P("That is the design problem 4PLANET is trying to solve: move complexity behind the interface without hiding it. The person taking action should not need to become an auditor. But the system should be able to show, precisely, what their action meant and what it did not mean."),
      S("There are at least five different events"),
      P("Start with payment. A receipt can prove that money moved. Then comes authority: was the organisation receiving or directing the money actually entitled and capable of delivering the stated work? Then delivery: did the agreed activity happen? Then observation: what changed afterwards? Finally attribution: how much of that change can credibly be linked to the intervention?"),
      P("Those events are related, but they are not synonyms. A photograph of a planted seedling can support a delivery record. It does not prove survival. Survival does not prove a restored ecosystem. A cleaner beach after one intervention does not prove the wider pollution system has changed. A transaction interface becomes trustworthy when it refuses to make those leaps on the user’s behalf."),
      Q("The goal is not to make impact complicated. It is to make the complexity happen before the promise."),
      S("The wrong order starts with the product"),
      P("Many environmental offers begin by inventing a unit that is easy to sell: one tree, one kilogram, one square metre, one tonne. Then the system works backwards to find delivery and evidence. That order is commercially convenient because the unit exists before the field reality has been fully defined."),
      P("A stronger order starts with the work. What needs to happen? Who can legitimately do it? Where? At what real cost? With what capacity? What can be measured cheaply and repeatedly? Which claims would require longer monitoring? Only then should the interface decide whether there is a bounded unit a member of the public can understand and support."),
      S("Proof should arrive in layers"),
      P("Imagine supporting a restoration action. At first, your record might show only that payment was received and allocated to an approved pathway. Later, a delivery record could attach location, date, partner evidence and the specific activity completed. Monitoring might then add survival, habitat or other ecological observations. Each new layer should expand what can be said without rewriting the earlier event into something it never proved."),
      P("This makes corrections easier too. If delivery is delayed, the system can say delivery is delayed. If monitoring shows weaker results than expected, the outcome layer can change without pretending the payment never happened. Good evidence architecture is not only about proving success; it is about making reality survivable when reality is messy."),
      S("Why simplicity matters"),
      P("None of this argues for a miserable user experience full of disclaimers. Quite the opposite. When definitions, evidence and responsibilities are settled underneath, the front end can become radically calm. The user can see the essential promise, the price, who is responsible, what evidence will follow and which outcome claims remain outside scope."),
      P("That is how trust can reduce friction instead of adding it. A person does not need twelve legalistic screens if the system has already done the hard work of making the action truthful."),
      S("Closed is a product state"),
      P("There is one final implication that matters during 4PLANET’s build phase: a pathway that cannot yet prove its delivery should remain closed. ‘Not available yet’ is better product design than a persuasive checkout attached to uncertain execution. The ability to refuse a transaction is part of the trust model."),
      P("The ambition is ultimately simple: make useful action easier than indifference without making the evidence weaker than the story. One tap at the surface. A real chain of responsibility underneath. And enough proof afterwards that the person who acted can come back and see what actually happened."),
    ],
  },
};
