export type FilmAccess = "FULL_FREE" | "STREAM" | "TRAILER";

export type FilmCandidate = {
  slug: string;
  title: string;
  year: number;
  focus: string;
  sourceUrl: string;
};

export type PublishedFilm = FilmCandidate & {
  director: string;
  runtime: string;
  access: FilmAccess;
  platform: string;
  description: string;
  credit: string;
  watchUrl: string;
  trailerId?: string;
  imageUrl?: string;
  sourceLabel: string;
  sourceDescriptionUrl: string;
  selectionNote: string;
};

const PATAGONIA_CATALOGUE = "https://www.patagonia.com/films/all/";

export const FILM_CANDIDATES: FilmCandidate[] = [
  { slug: "yanuni", title: "YANUNI", year: 2025, focus: "AMAZONIA / INDIGENOUS STEWARDSHIP", sourceUrl: "https://malaikapictures.com/portfolio/yanuni" },
  { slug: "the-territory", title: "The Territory", year: 2022, focus: "AMAZONIA / INDIGENOUS STEWARDSHIP", sourceUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4" },
  { slug: "seaspiracy", title: "Seaspiracy", year: 2021, focus: "OCEAN / FISHING", sourceUrl: "https://www.netflix.com/title/81014008" },
  { slug: "chasing-coral", title: "Chasing Coral", year: 2017, focus: "OCEAN / CLIMATE", sourceUrl: "https://chasingcoral.com/the-film/" },
  { slug: "cowspiracy", title: "Cowspiracy: The Sustainability Secret", year: 2014, focus: "FOOD / LAND / CLIMATE", sourceUrl: "https://www.cowspiracy.com/" },
  { slug: "kiss-the-ground", title: "Kiss the Ground", year: 2020, focus: "FOOD / SOIL / REGENERATION", sourceUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs" },
  { slug: "my-octopus-teacher", title: "My Octopus Teacher", year: 2020, focus: "OCEAN / SPECIES / KELP", sourceUrl: "https://www.netflix.com/title/81045007" },
  { slug: "a-plastic-ocean", title: "A Plastic Ocean", year: 2016, focus: "OCEAN / PLASTIC", sourceUrl: "https://aplasticocean.movie/" },
  { slug: "common-ground", title: "Common Ground", year: 2023, focus: "FOOD / SOIL / SYSTEMS", sourceUrl: "https://commongroundfilm.org/" },
  { slug: "sea-of-shadows", title: "Sea of Shadows", year: 2019, focus: "OCEAN / SPECIES / WILDLIFE CRIME", sourceUrl: "https://www.youtube.com/watch?v=QiFjJCUd9ro" },
  { slug: "artifishal", title: "Artifishal", year: 2019, focus: "RIVERS / SALMON / RESTORATION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "damnation", title: "DamNation", year: 2014, focus: "RIVERS / RESTORATION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "public-trust", title: "Public Trust", year: 2020, focus: "PUBLIC LANDS / BIODIVERSITY", sourceUrl: "https://www.patagonia.com/films/public-trust/" },
  { slug: "we-the-power", title: "We the Power", year: 2021, focus: "ENERGY / COMMUNITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "blue-heart", title: "Blue Heart", year: 2018, focus: "RIVERS / HYDROPOWER", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "newtok", title: "Newtok", year: 2021, focus: "CLIMATE / COMMUNITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-scale-of-hope", title: "The Scale of Hope", year: 2022, focus: "CLIMATE / ACTION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "takayna", title: "Takayna", year: 2018, focus: "FOREST / CONSERVATION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "treeline", title: "Treeline", year: 2019, focus: "FOREST / CLIMATE", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-custodians", title: "The Custodians", year: 2024, focus: "OCEAN / SEAGRASS / RESTORATION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "jalpi", title: "Jalpi", year: 2023, focus: "OCEAN / RESTORATION", sourceUrl: "https://www.patagonia.com/films/jalpi/" },
  { slug: "corazon-salado", title: "Corazón Salado", year: 2024, focus: "OCEAN / INDIGENOUS STEWARDSHIP", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "undammed", title: "Undammed", year: 2024, focus: "RIVERS / INDIGENOUS STEWARDSHIP", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "laxathjod", title: "Laxaþjóð | A Salmon Nation", year: 2024, focus: "SALMON / AQUACULTURE", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "range-rider", title: "Range Rider", year: 2023, focus: "WOLVES / COEXISTENCE", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-shitthropocene", title: "The Shitthropocene", year: 2024, focus: "CONSUMPTION / CIRCULARITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "district-15", title: "District 15", year: 2020, focus: "JUSTICE / POLLUTION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "a-net-plus", title: "A Net Plus", year: 2018, focus: "OCEAN / CIRCULARITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "why-recycled", title: "Why Recycled?", year: 2020, focus: "FASHION / CIRCULARITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "estado-salmonero", title: "Estado Salmonero", year: 2019, focus: "OCEAN / AQUACULTURE", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "sea-country-malu-lag", title: "Sea Country / Malu Lag", year: 2025, focus: "ISLANDS / CLIMATE / CULTURE", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "running-up-for-air", title: "Running Up For Air", year: 2023, focus: "AIR / HEALTH / COMMUNITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "home-grown", title: "Home, Grown", year: 2023, focus: "BUILDINGS / MATERIALS", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "bring-hemp-home-colorado", title: "Bring Hemp Home: Colorado", year: 2022, focus: "AGRICULTURE / MATERIALS", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-high-life", title: "The High Life", year: 2022, focus: "WATER / HYDROPOWER", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "cochamo-por-siempre", title: "Cochamó Por Siempre", year: 2026, focus: "CONSERVATION / COMMUNITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "we-can-get-there-from-here", title: "We Can Get There from Here", year: 2024, focus: "OCEAN / WORKING WATERFRONTS", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-green-buffalo", title: "The Green Buffalo", year: 2024, focus: "BUILDINGS / HEMP / INDIGENOUS", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "fire-lines", title: "Fire Lines", year: 2024, focus: "FIRE / INDIGENOUS KNOWLEDGE", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "totoganashi", title: "Totoganashi", year: 2024, focus: "OCEAN / COMMUNITY", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "this-is-not-a-drill", title: "This Is Not a Drill", year: 2026, focus: "CLIMATE / ACTIVISM", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "hot-pink-dolphins", title: "Hot Pink Dolphins", year: 2024, focus: "DOLPHINS / OCEAN", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "tom", title: "Tom", year: 2024, focus: "FISH / OCEAN", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-last-observers", title: "The Last Observers", year: 2024, focus: "CLIMATE / OBSERVATION", sourceUrl: PATAGONIA_CATALOGUE },
  { slug: "the-ivory-game", title: "The Ivory Game", year: 2016, focus: "ELEPHANTS / WILDLIFE TRADE", sourceUrl: "https://www.netflix.com/title/80117533" },
  { slug: "mission-blue", title: "Mission Blue", year: 2014, focus: "OCEAN / CONSERVATION", sourceUrl: "https://www.netflix.com/title/70308278" },
  { slug: "breaking-boundaries", title: "Breaking Boundaries: The Science of Our Planet", year: 2021, focus: "PLANETARY BOUNDARIES / BIODIVERSITY", sourceUrl: "https://www.netflix.com/title/81336476" },
  { slug: "before-the-flood", title: "Before the Flood", year: 2016, focus: "CLIMATE / SYSTEMS", sourceUrl: "https://www.beforetheflood.com/" },
  { slug: "2040", title: "2040", year: 2019, focus: "SOLUTIONS / ENERGY / FOOD", sourceUrl: "https://www.modernfilms.com/2040" },
  { slug: "reinventing-power", title: "Reinventing Power: America’s Renewable Energy Boom", year: 2018, focus: "RENEWABLE ENERGY / JOBS", sourceUrl: "https://www.sierraclub.org/reinventing-power" },
];

export const PUBLISHED_FILMS: PublishedFilm[] = [
  {
    slug: "yanuni",
    title: "YANUNI",
    year: 2025,
    focus: "AMAZONIA / INDIGENOUS STEWARDSHIP",
    sourceUrl: "https://malaikapictures.com/portfolio/yanuni",
    director: "Richard Ladkani",
    runtime: "112 MIN",
    access: "FULL_FREE",
    platform: "YOUTUBE / LEONARDO DICAPRIO",
    description: "A cinematic portrait of Indigenous leader Juma Xipaia as her defence of Xipaya territory moves from the Amazon to the political front line of climate justice.",
    credit: "Directed by Richard Ladkani. Produced by Juma Xipaia, Leonardo DiCaprio, Anita Ladkani, Richard Ladkani, Jennifer Davisson and Phillip Watson.",
    watchUrl: "https://www.youtube.com/channel/UChlkJxkgWqVc11Cwuz1GSbg",
    sourceLabel: "MALAIKA PICTURES / OFFICIAL FILM PAGE",
    sourceDescriptionUrl: "https://malaikapictures.com/portfolio/yanuni",
    selectionNote: "Indigenous sovereignty, illegal mining, the Amazon and the human cost of defending a living system.",
  },
  {
    slug: "the-territory",
    title: "The Territory",
    year: 2022,
    focus: "AMAZONIA / INDIGENOUS STEWARDSHIP",
    sourceUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4",
    director: "Alex Pritz",
    runtime: "83 MIN",
    access: "STREAM",
    platform: "NATIONAL GEOGRAPHIC / DISNEY+",
    description: "An on-the-ground account of the Uru-eu-wau-wau people confronting deforestation and encroachment in the Brazilian Amazon while taking control of how their story is recorded.",
    credit: "Directed by Alex Pritz. Official trailer published by National Geographic Documentary Films.",
    watchUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4",
    trailerId: "wL9wvdbk7A4",
    imageUrl: "https://i.ytimg.com/vi/wL9wvdbk7A4/maxresdefault.jpg",
    sourceLabel: "NATIONAL GEOGRAPHIC / OFFICIAL TRAILER",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=wL9wvdbk7A4",
    selectionNote: "A crucial companion to YANUNI: territory, forest loss, Indigenous agency and control of the narrative.",
  },
  {
    slug: "seaspiracy",
    title: "Seaspiracy",
    year: 2021,
    focus: "OCEAN / FISHING",
    sourceUrl: "https://www.netflix.com/title/81014008",
    director: "Ali Tabrizi",
    runtime: "89 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "A filmmaker investigates human pressures on marine life and the global fishing industry, following the trail from ocean damage to the systems behind it.",
    credit: "Directed by Ali Tabrizi. Official trailer and streaming page by Netflix.",
    watchUrl: "https://www.netflix.com/title/81014008",
    trailerId: "1Q5CXN7soQg",
    imageUrl: "https://i.ytimg.com/vi/1Q5CXN7soQg/maxresdefault.jpg",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/81014008",
    selectionNote: "A provocative entry point into fishing, marine biodiversity, seafood systems and contested sustainability claims.",
  },
  {
    slug: "chasing-coral",
    title: "Chasing Coral",
    year: 2017,
    focus: "OCEAN / CLIMATE",
    sourceUrl: "https://chasingcoral.com/the-film/",
    director: "Jeff Orlowski",
    runtime: "93 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "Divers, scientists and photographers build a visual record of coral bleaching and the rapid changes unfolding across reef systems around the world.",
    credit: "Directed by Jeff Orlowski. A production of Exposure Labs. Official trailer published by Netflix.",
    watchUrl: "https://www.netflix.com/title/80168188",
    trailerId: "b6fHA9R2cKI",
    imageUrl: "https://i.ytimg.com/vi/b6fHA9R2cKI/maxresdefault.jpg",
    sourceLabel: "CHASING CORAL / NETFLIX",
    sourceDescriptionUrl: "https://chasingcoral.com/the-film/",
    selectionNote: "A direct bridge into COR4L_, ocean heat stress, visual evidence and climate-driven ecosystem change.",
  },
  {
    slug: "cowspiracy",
    title: "Cowspiracy: The Sustainability Secret",
    year: 2014,
    focus: "FOOD / LAND / CLIMATE",
    sourceUrl: "https://www.cowspiracy.com/",
    director: "Kip Andersen & Keegan Kuhn",
    runtime: "90 MIN",
    access: "STREAM",
    platform: "OFFICIAL FILM / STREAMING AVAILABILITY VARIES",
    description: "An investigation into the environmental footprint of animal agriculture and why food-system impacts have often sat outside mainstream environmental campaigning.",
    credit: "Directed by Kip Andersen and Keegan Kuhn. Official trailer published by the Cowspiracy film team.",
    watchUrl: "https://www.cowspiracy.com/",
    trailerId: "nV04zyfLyN4",
    imageUrl: "https://i.ytimg.com/vi/nV04zyfLyN4/maxresdefault.jpg",
    sourceLabel: "COWSPIRACY / OFFICIAL",
    sourceDescriptionUrl: "https://www.cowspiracy.com/",
    selectionNote: "Directly relevant to S4PIENS_ FOOD_: land, water, emissions, consumption and contested systems claims.",
  },
  {
    slug: "kiss-the-ground",
    title: "Kiss the Ground",
    year: 2020,
    focus: "FOOD / SOIL / REGENERATION",
    sourceUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs",
    director: "Joshua Tickell & Rebecca Harrell Tickell",
    runtime: "84 MIN",
    access: "STREAM",
    platform: "PRIME VIDEO / OFFICIAL FILM",
    description: "Scientists, farmers and advocates explore regenerative agriculture and soil restoration as tools for rebuilding ecosystems, food systems and climate resilience.",
    credit: "Directed by Joshua Tickell and Rebecca Harrell Tickell. Official trailer published by Groundswell Film.",
    watchUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs",
    trailerId: "3iknWWKZOUs",
    imageUrl: "https://i.ytimg.com/vi/3iknWWKZOUs/maxresdefault.jpg",
    sourceLabel: "GROUNDSWELL FILM / OFFICIAL TRAILER",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=3iknWWKZOUs",
    selectionNote: "A solutions-led FOOD_ film connecting soil, farming, ecosystems and regeneration.",
  },
  {
    slug: "my-octopus-teacher",
    title: "My Octopus Teacher",
    year: 2020,
    focus: "OCEAN / SPECIES / KELP",
    sourceUrl: "https://www.netflix.com/title/81045007",
    director: "Pippa Ehrlich & James Reed",
    runtime: "85 MIN",
    access: "STREAM",
    platform: "NETFLIX",
    description: "A filmmaker’s relationship with a wild octopus becomes an intimate route into the complexity of a South African kelp forest and the life within it.",
    credit: "Directed by Pippa Ehrlich and James Reed. Official trailer published by Netflix.",
    watchUrl: "https://www.netflix.com/title/81045007",
    trailerId: "3s0LTDhqe5A",
    imageUrl: "https://i.ytimg.com/vi/3s0LTDhqe5A/maxresdefault.jpg",
    sourceLabel: "NETFLIX / OFFICIAL",
    sourceDescriptionUrl: "https://www.netflix.com/title/81045007",
    selectionNote: "Life first: species behaviour, kelp forests and the emotional power of seeing an ecosystem through one animal.",
  },
  {
    slug: "a-plastic-ocean",
    title: "A Plastic Ocean",
    year: 2016,
    focus: "OCEAN / PLASTIC",
    sourceUrl: "https://aplasticocean.movie/",
    director: "Craig Leeson",
    runtime: "102 MIN",
    access: "STREAM",
    platform: "OFFICIAL FILM",
    description: "A global expedition traces plastic pollution through marine environments, wildlife and food chains while also examining technologies and practical responses.",
    credit: "Directed by Craig Leeson. Official film and trailer from the A Plastic Ocean team.",
    watchUrl: "https://aplasticocean.movie/",
    trailerId: "6zrn4-FfbXw",
    imageUrl: "https://i.ytimg.com/vi/6zrn4-FfbXw/maxresdefault.jpg",
    sourceLabel: "A PLASTIC OCEAN / OFFICIAL",
    sourceDescriptionUrl: "https://aplasticocean.movie/",
    selectionNote: "OCE4N_ plastic pressure, marine life, food chains and solution pathways in one accessible film.",
  },
  {
    slug: "common-ground",
    title: "Common Ground",
    year: 2023,
    focus: "FOOD / SOIL / SYSTEMS",
    sourceUrl: "https://commongroundfilm.org/",
    director: "Josh Tickell & Rebecca Tickell",
    runtime: "105 MIN",
    access: "STREAM",
    platform: "PRIME VIDEO / OFFICIAL FILM",
    description: "Farmers, scientists and advocates examine the systems shaping American agriculture and the potential for regenerative farming and soil health to change them.",
    credit: "Directed by Josh Tickell and Rebecca Tickell. Official trailer published by Groundswell Film.",
    watchUrl: "https://commongroundfilm.org/",
    trailerId: "6-M4Hq0MKFA",
    imageUrl: "https://i.ytimg.com/vi/6-M4Hq0MKFA/maxresdefault.jpg",
    sourceLabel: "COMMON GROUND / OFFICIAL",
    sourceDescriptionUrl: "https://commongroundfilm.org/",
    selectionNote: "A contemporary systems film for FOOD_, connecting policy, farming, health, soil and regeneration.",
  },
  {
    slug: "sea-of-shadows",
    title: "Sea of Shadows",
    year: 2019,
    focus: "OCEAN / SPECIES / WILDLIFE CRIME",
    sourceUrl: "https://www.youtube.com/watch?v=QiFjJCUd9ro",
    director: "Richard Ladkani",
    runtime: "104 MIN",
    access: "STREAM",
    platform: "NATIONAL GEOGRAPHIC",
    description: "Scientists, investigators, journalists and activists confront an illegal wildlife-trafficking network whose fishing methods are pushing the vaquita toward extinction.",
    credit: "Directed by Richard Ladkani. Official trailer published by National Geographic.",
    watchUrl: "https://www.nationalgeographic.com/tv/movies-and-specials/5601e93d-e0e6-490c-b031-041463edeedf",
    trailerId: "QiFjJCUd9ro",
    imageUrl: "https://i.ytimg.com/vi/QiFjJCUd9ro/maxresdefault.jpg",
    sourceLabel: "NATIONAL GEOGRAPHIC / OFFICIAL",
    sourceDescriptionUrl: "https://www.youtube.com/watch?v=QiFjJCUd9ro",
    selectionNote: "A species-level crisis connected to fishing, organised crime and conservation action — strong WH4LES_/OCE4N_ territory.",
  },
];

export function filmBySlug(slug?: string) {
  return PUBLISHED_FILMS.find((film) => film.slug === slug);
}
