const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const ctx={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../source/4sapien-csv.js"),"utf8"),ctx);
const p=ctx.module.exports;
assert.equal(p.amount("-1 250,00").kr,1250);
assert.equal(p.amount("-1 250,00").sign,-1);
assert.equal(p.amount("1250,50").wholeKroner,false);
assert.equal(p.amount("0"),null);
assert.equal(p.date("29.02.2024"),"2024-02-29");
assert.equal(p.date("31.02.2026"),null);
const r=p.interpret('Dato;Beskrivelse;Beløp\n19.09.2026;"Butikk; Mat";-125,00\n20.09.2026;Intern overføring til egen konto;-100,00\n21.09.2026;Refund;50,50');
assert.equal(r.rows.length,3);
assert.equal(r.rows[0].name,"Butikk; Mat");
assert.equal(r.rows[0].type,"spend");
assert.equal(r.rows[0].eligible,true);
assert.equal(r.rows[1].eligible,false);
assert.equal(r.rows[2].eligible,false);
const split=p.interpret('Date,Description,Debit,Credit\n2026-09-19,Coffee,100.00,\n2026-09-20,Salary,,5000.00');
assert.equal(split.rows.length,2);assert.equal(split.rows[0].type,"spend");assert.equal(split.rows[1].type,"income");
assert.throws(()=>p.interpret('foo;bar\na;b'),/CSV_HEADERS_UNRECOGNISED/);
assert.throws(()=>p.parseDelimited('Dato;Tekst;Beløp\n"unfinished'),/CSV_UNTERMINATED_QUOTES/);
console.log("PASS CSV: synthetic parsing, quotes, dates, whole-kroner, transfers and explicit review");
