/* CAP-PLATFORM-01 — GitHub-built universal finance interface. Demonstration until canonical data+RLS are integrated. */
import {useEffect,useMemo,useRef,useState,type FormEvent,type ReactNode} from "react";
import {Link,useLocation,useNavigate} from "react-router-dom";
import {getIdentityClient,type FourPlanetSession} from "@/identity/identityClient";
import {CALLS,FUNDERS,PROGRAMMES,REGIONS,THEMES,STATUS,amount,prettyDate,programmeFor,funderFor,readState,saveState,emptyState,validTransition,type Call,type FinanceState,type PipelineItem,type Project,type Status,type Theme,type Workspace} from "./financeData";
import {readFinanceWorkspace,writeFinanceWorkspace} from "./financeRemote";
import FinanceTeamDesk from "./FinanceTeamDesk";
import FinanceGraph from "./FinanceGraph";
import "./finance.css";
import "./finance-shell.css";

function currentPath(path:string){return path.replace(/^\/finance(?=\/|$)/,"")||"/"}
function toPath(p:string){return window.location.pathname.startsWith("/finance")?"/finance"+p:p}
function Nav({to,children,className=""}:{to:string;children:ReactNode;className?:string}){return <Link className={className} to={toPath(to)}>{children}</Link>}
function Icon({name}:{name:string}){const strokes:Record<string,ReactNode>={overview:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,discover:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/></>,pipeline:<><path d="M4 6h16M4 12h16M4 18h10"/></>,project:<><path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/></>,actors:<><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></>,graph:<><circle cx="5" cy="6" r="2"/><circle cx="19" cy="7" r="2"/><circle cx="12" cy="19" r="2"/><path d="m7 6 10 1M6 8l5 9M18 9l-5 8"/></>,applications:<><path d="M7 4h10l4 4v13H3V4zM17 4v5h4M7 14h10M7 18h7"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M4.93 4.93l2.13 2.13m9.88 9.88 2.13 2.13M4.93 19.07l2.13-2.13M16.94 7.06l2.13-2.13"/></>,arrow:<><path d="M5 12h14m-6-6 6 6-6 6"/></>,chevron:<><path d="m9 5 7 7-7 7"/></>,back:<><path d="m15 5-7 7 7 7M8 12h13"/></>,plus:<><path d="M12 4v16M4 12h16"/></>,close:<><path d="M5 5 19 19M19 5 5 19"/></>,menu:<><path d="M4 6h16M4 12h16M4 18h16"/></>};return <svg className="fc-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{strokes[name]||strokes.arrow}</svg>}
function Initial({name}:{name:string}){return <span className="fc-initial" aria-hidden="true">{name.split(" ").map(w=>w[0]).slice(0,2).join("")}</span>}
function Section({label,title,children,aside}:{label?:string;title:string;children?:ReactNode;aside?:ReactNode}){return <section className="fc-section"><div className="fc-sectionheading"><div>{label&&<p className="fc-eyebrow">{label}</p>}<h2>{title}</h2></div>{aside}</div>{children}</section>}
function Tag({children,tone=""}:{children:ReactNode;tone?:string}){return <span className={"fc-tag "+tone}>{children}</span>}
function Empty({title,text}:{title:string;text:string}){return <div className="fc-empty"><strong>{title}</strong><p>{text}</p></div>}
function DemoNote({signedIn}:{signedIn:boolean}){return <div className="fc-demo" role="note"><span className="fc-demo-dot"/> <strong>DEMONSTRATION</strong><span>All funding actors, dates and amounts are fictional. {signedIn?"Private project/pipeline drafts sync to your 4PLANET ID account, not to BRAIN.":"Guest workspace is stored on this device only."}</span></div>}
function MonthLabel({value}:{value:string}){return <>{new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(value+"-01T12:00:00Z"))}</>}
function OpportunityRow({call,saved,onSave,compact=false}:{call:Call;saved:boolean;onSave:(id:string)=>void;compact?:boolean}){const f=funderFor(call);return <article className={"fc-opportunity "+(compact?"fc-opportunity-compact":"")}><div className="fc-opp-date"><strong>{call.deadline.slice(8,10)}</strong><span>{new Date(call.deadline+"T12:00:00Z").toLocaleString("en-GB",{month:"short",timeZone:"UTC"})}</span></div><div className="fc-opp-body"><div className="fc-kicker">{f.name} <span className="fc-dot">·</span> {call.instrument}</div><Nav to={"/opportunities/"+call.id} className="fc-opp-title">{call.title} <span></span></Nav><div className="fc-inline"><Tag>{call.region}</Tag>{call.themes.slice(0,compact?1:2).map(t=><Tag key={t}>{t}</Tag>)}<span className="fc-muted fc-small">{call.confidence}</span></div></div><div className="fc-opp-right"><strong>{amount(call)}</strong><span className="fc-muted fc-small">{call.amountKind}</span><button className={"fc-save "+(saved?"is-saved":"")} onClick={()=>onSave(call.id)}>{saved?"Saved":"Save"}</button></div></article>}
const CATALOGUE_NAV=[{path:"/",title:"Home"},{path:"/discover",title:"Discover"},{path:"/funders",title:"Funders"},{path:"/calendar",title:"Year wheel"}];
const MOBILE_NAV=[{path:"/my",title:"Overview",icon:"overview"},{path:"/discover",title:"Discover",icon:"discover"},{path:"/my/pipeline",title:"CRM",icon:"pipeline"},{path:"/my/calendar",title:"Year wheel",icon:"calendar"},{path:"/my/projects",title:"Mine",icon:"project"}];
const WORKSPACE_NAV=[{path:"/my",title:"Overview",icon:"overview"},{path:"/my/pipeline",title:"My CRM",icon:"pipeline"},{path:"/my/calendar",title:"Year wheel",icon:"calendar"},{path:"/my/projects",title:"My projects",icon:"project"},{path:"/my/applications",title:"Applications",icon:"applications"},{path:"/my/graph",title:"Relationship graph",icon:"graph"},{path:"/my/teams",title:"Team finance",icon:"actors"}];
export default function FinanceHub(){
 const loc=useLocation(),navigate=useNavigate(),path=currentPath(loc.pathname);
 const [state,setState]=useState<FinanceState>(readState),[menu,setMenu]=useState(false),[session,setSession]=useState<FourPlanetSession|null>(null),[authChecked,setAuthChecked]=useState(false);
 const [profileOpen,setProfileOpen]=useState(false),[searchText,setSearchText]=useState("");
 const [appearance,setAppearance]=useState<"dark"|"light">(()=>{
   try{const p=localStorage.getItem("4planet-finance-theme");if(p==="light"||p==="dark")return p;
     return window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"}catch{return "dark"}
 });
 const [remoteStatus,setRemoteStatus]=useState<"demo"|"loading"|"ready"|"saving"|"error">("demo"),[remoteError,setRemoteError]=useState("");
 const revision=useRef(0),pending=useRef(0),writeQueue=useRef<Promise<void>>(Promise.resolve());
 const stateRef=useRef(state);
 const workspace=state.workspaces[state.active];
 const change=(mutator:(s:FinanceState)=>FinanceState)=>{
  if(session && (remoteStatus==="loading"||remoteStatus==="error"))return;
  const next=mutator(stateRef.current);stateRef.current=next;setState(next);
  if(!session){saveState(next);return}
  pending.current+=1;setRemoteStatus("saving");const currentSession=session;
  writeQueue.current=writeQueue.current.then(async ()=>{
   const result=await writeFinanceWorkspace(currentSession,next,revision.current);
   revision.current=result.revision;
   pending.current-=1;
   if(pending.current===0)setRemoteStatus("ready");
  }).catch(error=>{pending.current=0;setRemoteStatus("error");setRemoteError(error instanceof Error?error.message:"Unable to save private finance data");});
 };
 useEffect(()=>{let active=true;let unsubscribe=()=>{};getIdentityClient().then(client=>{client.auth.getSession().then(r=>{if(active){setSession(r.data.session);setAuthChecked(true)}}).catch(()=>{if(active)setAuthChecked(true)});unsubscribe=client.auth.onAuthStateChange((_ev,s)=>{if(active)setSession(s)}).data.subscription.unsubscribe}).catch(()=>{if(active)setAuthChecked(true)});return()=>{active=false;unsubscribe()}},[]);
 useEffect(()=>{setMenu(false);setProfileOpen(false)},[loc.pathname]);
 useEffect(()=>{try{localStorage.setItem("4planet-finance-theme",appearance)}catch{/* browser blocked */}},[appearance]);
 const activePath=(p:string)=>p==="/" ? path==="/" : path===p||path.startsWith(p+"/");
 const upperTabs=isMine?[
   {path:"/my",title:"Overview"},{path:"/my/pipeline",title:"CRM"},
   {path:"/my/projects",title:"Projects"},{path:"/my/calendar",title:"Year wheel"},
   {path:"/my/graph",title:"Funding map"},{path:"/my/teams",title:"Team"},
   {path:"/my/settings",title:"Settings"}]:[
   {path:"/",title:"Home"},{path:"/discover",title:"Discover"},
   {path:"/funders",title:"Funders"},{path:"/calendar",title:"Year wheel"},
   {path:"/my",title:"My portfolio"}];
 const searchSubmit=(event:FormEvent)=>{event.preventDefault();navigate(toPath("/discover?q="+encodeURIComponent(searchText.trim())))};
 const topSignOut=async()=>{try{const client=await getIdentityClient();await client.auth.signOut({scope:"local"});setProfileOpen(false)}catch{navigate(toPath("/my/settings"))}};
 useEffect(()=>{
  if(!authChecked)return;
  if(!session){const guest=readState();stateRef.current=guest;setState(guest);setRemoteStatus("demo");setRemoteError("");return}
  let alive=true;setRemoteStatus("loading");setRemoteError("");
  readFinanceWorkspace(session).then(record=>{
   if(!alive)return;
   revision.current=record.revision;pending.current=0;writeQueue.current=Promise.resolve();
   stateRef.current=record.app_state;setState(record.app_state);setRemoteStatus("ready");
  }).catch(error=>{if(alive){setRemoteStatus("error");setRemoteError(error instanceof Error?error.message:"Cannot access finance account")}}); 
  return()=>{alive=false};
 },[authChecked,session?.user.id]);

 const savedSet=useMemo(()=>new Set(workspace.pipeline.map(i=>i.callId)),[workspace]);
 const save=(id:string)=>change(s=>{const w=s.workspaces[s.active];if(w.pipeline.some(i=>i.callId===id))return {...s,workspaces:{...s.workspaces,[s.active]:{...w,pipeline:w.pipeline.filter(i=>i.callId!==id)}}};const now=new Date().toISOString();const item:PipelineItem={id:"pipe-"+crypto.randomUUID(),callId:id,projectId:"",status:"Saved",createdAt:now,updatedAt:now,notes:"",receipt:""};return {...s,workspaces:{...s.workspaces,[s.active]:{...w,pipeline:[...w.pipeline,item]}}}});
 const patchItem=(id:string,patch:Partial<PipelineItem>)=>change(s=>{const w=s.workspaces[s.active];return {...s,workspaces:{...s.workspaces,[s.active]:{...w,pipeline:w.pipeline.map(item=>item.id===id?{...item,...patch,updatedAt:new Date().toISOString()}:item)}}}});
 const switchWorkspace=(next:"4planet"|"personal")=>change(s=>({...s,active:next}));
 const addProject=(p:Project)=>change(s=>{const w=s.workspaces[s.active];return {...s,workspaces:{...s.workspaces,[s.active]:{...w,projects:[...w.projects,p]}}};});
 const deleteProject=(id:string)=>change(s=>{const w=s.workspaces[s.active];return {...s,workspaces:{...s.workspaces,[s.active]:{...w,projects:w.projects.filter(p=>p.id!==id),pipeline:w.pipeline.map(i=>i.projectId===id?{...i,projectId:""}:i)}}};});
 const signIn=()=>{navigate(toPath("/sign-in"))};
 const isMine=path==="/my"||path.startsWith("/my/");
 return <div className="fc-root" data-theme={appearance}>
  <DemoNote signedIn={!!session}/>
  <header className="fc-header">
    <div className="fc-wrap fc-header-inner">
      <Nav to="/my" className="fc-brand" aria-label="4PLANET Finance" ><span className="fc-brandmark">4P<span>.</span></span><span className="fc-brandname">FINANCE <small>by 4PLANET</small></span></Nav>
      <form className="fc-topbar-search" role="search" onSubmit={searchSubmit}>
        <Icon name="discover"/>
        <input aria-label="Search all funding opportunities" placeholder="Search funders, funding, projects…" value={searchText} onChange={event=>setSearchText(event.target.value)}/>
        {searchText&&<button type="submit" aria-label="Submit search"><Icon name="arrow"/></button>}
      </form>
      <div className="fc-mode-switch" aria-label="Colour scheme">
        <button type="button" className={appearance==="light"?"active":""} onClick={()=>setAppearance("light")}>Light</button>
        <button type="button" className={appearance==="dark"?"active":""} onClick={()=>setAppearance("dark")}>Dark</button>
      </div>
      <div className="fc-header-right">
        <Nav to="/my/calendar" className="fc-topbar-action" aria-label="Open deadline calendar"><Icon name="calendar"/></Nav>
        <div className="fc-profile-anchor">
          <button type="button" className="fc-topbar-action" aria-label="Open profile and settings" aria-expanded={profileOpen} onClick={()=>setProfileOpen(!profileOpen)}><Icon name="actors"/></button>
          {profileOpen&&<div className="fc-profile-menu" role="menu" aria-label="Profile and settings">
            <div className="fc-menu-identity"><strong>{session?.user.email||"4PLANET ID"}</strong><span>{session?"Signed in to Finance":"Guest preview · saved on this device"}</span></div>
            <Nav to="/my" >My overview</Nav>
            <Nav to="/my/projects">My projects</Nav>
            <Nav to="/my/teams">Team workspace</Nav>
            <Nav to="/my/settings">Settings and export</Nav>
            <div className="fc-menu-divider"/>
            <button onClick={()=>setAppearance(appearance==="dark"?"light":"dark")}>Use {appearance==="dark"?"light":"dark"} mode</button>
            {session?<button onClick={topSignOut}>Sign out</button>:<Nav to="/sign-in">Sign in with 4PLANET ID</Nav>}
          </div>}
        </div>
      </div>
    </div>
  </header>
  <nav className="fc-section-tabs" aria-label="Finance sections">
    {upperTabs.map(tab=><Nav key={tab.path} to={tab.path} className={activePath(tab.path)?"active":""}>{tab.title}</Nav>)}
  </nav>
  <div className={isMine?"fc-app-grid fc-wrap":"fc-wrap fc-public"}>
   {isMine&&<aside className="fc-sidebar"><div className="fc-eyebrow">MY SPACE</div><select aria-label="Demo workspace" value={state.active} onChange={e=>switchWorkspace(e.target.value as "4planet"|"personal")}><option value="4planet">4PLANET · Demo</option><option value="personal">Personal · Demo</option></select><nav>{WORKSPACE_NAV.map(i=><Nav key={i.path} to={i.path} className={"fc-side-link "+(path===i.path?"current":"")}><Icon name={i.icon}/>{i.title}</Nav>)}</nav><div className="fc-sidebar-footer"><Nav to="/my/settings" className="fc-side-link"><Icon name="settings"/>Settings</Nav><span>Finance Intelligence · v0.1</span></div></aside>}
   <main className="fc-main">
    {session&&remoteStatus==="loading"&&<div className="fc-sync-banner">Loading your private 4PLANET ID workspace…</div>}
    {session&&remoteStatus==="saving"&&<div className="fc-sync-banner">Saving securely to your 4PLANET ID account…</div>}
    {session&&remoteStatus==="error"&&<div className="fc-sync-error" role="alert">Private finance synchronisation unavailable: {remoteError}. Changes are blocked; reload after connectivity is restored.</div>}
    {session&&remoteStatus!=="ready"&&remoteStatus!=="saving"?null:<>

    {path==="/"&&<><div className="fc-hero"><p className="fc-eyebrow">A MORE INTELLIGENT WAY TO FUND CHANGE</p><h1>Find the funding<br/>behind <em>change.</em></h1><p>Discover funders. Understand recurring programmes. Build your own pipeline and organise funding around real projects.</p><div className="fc-actions"><Nav className="fc-btn fc-btn-primary" to="/discover">Explore opportunities <Icon name="arrow"/></Nav><Nav className="fc-btn" to="/my">Open my workspace</Nav></div><div className="fc-hero-meta"><span>ONE GLOBAL DIRECTORY</span><span>ANNUAL FUNDING CYCLES</span><span>YOUR OWN WORKSPACE</span></div></div><div className="fc-landing-grid"><div><p className="fc-eyebrow">DISCOVER</p><h2>Funding intelligence that compounds.</h2><p>Each funder has a durable profile. Each programme has its own history. Each annual call can be saved to your projects and deadline calendar.</p></div><div className="fc-category-grid">{THEMES.slice(0,6).map((t,i)=><Nav key={t} to={"/discover?theme="+encodeURIComponent(t)} className="fc-category"><span>0{(i+1)}</span><strong>{t}</strong><Icon name="arrow"/></Nav>)}</div></div></>}
    {path==="/sign-in"&&<FinanceSignIn onSignedIn={()=>navigate(toPath("/my"))} signedIn={!!session}/>}
    {path==="/discover"&&<Discover key={loc.search} saved={savedSet} save={save}/>}
    {path==="/funders"&&<FunderDirectory/>}
    {path.startsWith("/funders/")&&<FunderDetail slug={path.split("/")[2]} saved={savedSet} save={save}/>}
    {path.startsWith("/programmes/")&&<ProgrammeDetail id={path.split("/")[2]} saved={savedSet} save={save}/>}
    {path.startsWith("/opportunities/")&&<OpportunityDetail id={path.split("/")[2]} saved={savedSet} save={save} projects={workspace.projects} pipeline={workspace.pipeline} patchItem={patchItem}/>}
    {path==="/calendar"&&<Calendar saved={savedSet} save={save} mine={false}/>}
    {isMine&&<div className="fc-my-top"><span className="fc-eyebrow">{state.active==="4planet"?"4PLANET DEMO WORKSPACE":"PERSONAL DEMO WORKSPACE"}</span><div className="fc-my-auth">{authChecked&&session?"4PLANET ID · "+(remoteStatus==="ready"?"Private account state connected":remoteStatus):authChecked?"Preview mode · no verified 4PLANET ID session":"Checking 4PLANET ID…"}</div></div>}
    {path==="/my"&&<Dashboard state={state} saved={savedSet} save={save} signIn={signIn} hasSession={!!session}/>}
    {path==="/my/pipeline"&&<Pipeline workspace={workspace} patch={patchItem} remove={save}/>}
    {path==="/my/calendar"&&<Calendar saved={savedSet} save={save} mine pipeline={workspace.pipeline}/>}
    {path==="/my/projects"&&<Projects workspace={workspace} onSave={addProject} onDelete={deleteProject}/> }
    {path.startsWith("/my/projects/")&&<ProjectDetail id={path.split("/")[3]} workspace={workspace} patch={patchItem}/>}
    {path==="/my/applications"&&<Applications pipeline={workspace.pipeline}/>}
    {path==="/my/graph"&&<FinanceGraph projects={workspace.projects} pipeline={workspace.pipeline} onNavigate={p=>navigate(toPath(p))}/>}
    {path==="/my/teams"&&<FinanceTeamDesk session={session}/>}
    {path==="/my/settings"&&<Settings state={state} changeWorkspace={switchWorkspace} reset={()=>{const s=emptyState();stateRef.current=s;saveState(s);setState(s)}} session={session} signIn={signIn}/>}
    {!["/","/sign-in","/discover","/funders","/calendar","/my","/my/pipeline","/my/calendar","/my/projects","/my/applications","/my/graph","/my/teams","/my/settings"].includes(path)&&!["/funders/","/programmes/","/opportunities/","/my/projects/"].some(p=>path.startsWith(p))&&<Empty title="Page not found" text="This route does not exist."/>}
   </>}
   </main>
  </div>
  <footer className="fc-footer"><div className="fc-wrap"><strong>4PLANET_</strong><span>For a Living Planet.</span><span>CAP-PLATFORM-01 · Demonstration data, not verified grants</span></div></footer>
  <nav className="fc-bottom-nav" aria-label="Primary mobile navigation">
   {MOBILE_NAV.map(tab=><Nav key={tab.path} to={tab.path} className={activePath(tab.path)?"active":""}><Icon name={tab.icon}/><span>{tab.title}</span></Nav>)}
  </nav>
 </div>;
}
function Discover({saved,save}:{saved:Set<string>;save:(id:string)=>void}){
 const loc=useLocation();const [q,setQ]=useState(new URLSearchParams(loc.search).get("q")||"");
 const [theme,setTheme]=useState(new URLSearchParams(loc.search).get("theme")||"All");
 const [region,setRegion]=useState("All"),[month,setMonth]=useState("All"),[instrument,setInstrument]=useState("All"),[applicant,setApplicant]=useState("All"),[currency,setCurrency]=useState("All"),[minAmount,setMinAmount]=useState(""),[sort,setSort]=useState("Soonest");
 const filtered=useMemo(()=>CALLS.filter(c=>{const f=funderFor(c);const query=q.toLowerCase();return (!q||[c.title,f.name,programmeFor(c).name,c.description,...c.themes].join(" ").toLowerCase().includes(query))&&(theme==="All"||c.themes.includes(theme as Theme))&&(region==="All"||c.region===region)&&(month==="All"||c.deadline.slice(0,7)===month)&&(instrument==="All"||c.instrument===instrument)&&(applicant==="All"||c.applicant.toLowerCase().includes(applicant.toLowerCase()))&&(currency==="All"||c.currency===currency)&&(!minAmount||(currency!=="All"&&c.amount>=Number(minAmount)))}).sort((a,b)=>sort==="Soonest"?a.deadline.localeCompare(b.deadline):b.amount-a.amount),[q,theme,region,month,instrument,applicant,currency,minAmount,sort]);
 const months=Array.from(new Set(CALLS.map(c=>c.deadline.slice(0,7)))).sort();
 return <><Section label="UNIVERSAL CATALOGUE · DEMO" title="Discover funding" aside={<span className="fc-muted">{filtered.length} illustrative calls</span>}/><div className="fc-searchbar"><Icon name="discover"/><input aria-label="Search opportunities" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search funders, projects, issues, grants…"/>{q&&<button onClick={()=>setQ("")}>Clear</button>}</div><div className="fc-filters"><select aria-label="Topic" value={theme} onChange={e=>setTheme(e.target.value)}><option>All</option>{THEMES.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Location" value={region} onChange={e=>setRegion(e.target.value)}><option>All</option>{REGIONS.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Month" value={month} onChange={e=>setMonth(e.target.value)}><option>All</option>{months.map(m=><option key={m} value={m}>{m}</option>)}</select><select aria-label="Funding instrument" value={instrument} onChange={e=>setInstrument(e.target.value)}><option>All</option>{["Grant","Prize","Fellowship"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Applicant type" value={applicant} onChange={e=>setApplicant(e.target.value)}><option>All</option>{["NGO","Founder","Research","Individual","Company","Public"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Currency" value={currency} onChange={e=>{setCurrency(e.target.value);setMinAmount("")}}><option>All</option>{["NOK","EUR","USD"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Minimum award in selected currency" type="number" min="0" disabled={currency==="All"} value={minAmount} onChange={e=>setMinAmount(e.target.value)} placeholder="Min. amount"/><select aria-label="Sort" value={sort} onChange={e=>setSort(e.target.value)}><option>Soonest</option><option>Largest</option></select></div><div className="fc-resultshead"><strong>Opportunities</strong><span>Demo data · No verified external deadlines</span></div>{filtered.length?filtered.map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save}/>):<Empty title="No results" text="Try adjusting a filter or search term."/>}</>;
}
function FunderDirectory(){const [q,setQ]=useState("");const results=FUNDERS.filter(f=>[f.name,f.summary,...f.themes].join(" ").toLowerCase().includes(q.toLowerCase()));return <><Section label="PUBLIC ACTOR DIRECTORY · DEMO" title="The people behind funding"/><div className="fc-searchbar"><Icon name="discover"/><input placeholder="Search actor, region, mission…" aria-label="Search funders" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="fc-funder-grid">{results.map(f=><Nav to={"/funders/"+f.slug} className="fc-funder-card" key={f.id}><div className="fc-funder-top"><Initial name={f.name}/><span className="fc-muted fc-small">{f.kind}</span></div><h3>{f.name}</h3><p>{f.summary}</p><div className="fc-inline"><Tag>{f.region}</Tag>{f.themes.map(t=><Tag key={t}>{t}</Tag>)}</div><div className="fc-card-foot"><span>{PROGRAMMES.filter(p=>p.funderId===f.id).length} demo programmes</span><Icon name="arrow"/></div></Nav>)}</div></>}
function FunderDetail({slug,saved,save}:{slug:string;saved:Set<string>;save:(id:string)=>void}){const f=FUNDERS.find(x=>x.slug===slug);if(!f)return <Empty title="Funder not found" text="No actor matches this ID."/>;const ps=PROGRAMMES.filter(p=>p.funderId===f.id);return <><Nav to="/funders" className="fc-back"><Icon name="back"/> All funders</Nav><div className="fc-actor-hero"><Initial name={f.name}/><p className="fc-eyebrow">ACTOR PROFILE · DEMONSTRATION</p><h1>{f.name}</h1><p>{f.summary}</p><div className="fc-inline"><Tag>{f.kind}</Tag><Tag>{f.region}</Tag>{f.themes.map(t=><Tag key={t}>{t}</Tag>)}</div></div><div className="fc-profile-grid"><div><Section label="LONG-TERM KNOWLEDGE" title="Programmes & annual rounds"/>{ps.map(p=><div className="fc-profile-program" key={p.id}><Nav to={"/programmes/"+p.id} className="fc-opp-title">{p.name} <Icon name="arrow"/></Nav><p>{p.overview}</p><div className="fc-inline">{CALLS.filter(c=>c.programmeId===p.id).map(c=><Nav key={c.id} className="fc-linkchip" to={"/opportunities/"+c.id}>{c.year} · {prettyDate(c.deadline)}</Nav>)}</div></div>)}</div><aside className="fc-info-panel"><h3>Actor intelligence</h3><dl><dt>Geography</dt><dd>{f.region}</dd><dt>Topics</dt><dd>{f.themes.join(" · ")}</dd><dt>Evidence / source</dt><dd>FICTIONAL FIXTURE — no external source</dd><dt>Last verified</dt><dd>Not connected</dd></dl><p>Real actor pages will show public evidence, award history, updated funding terms and workspace-private relationship notes.</p></aside></div></>}
function ProgrammeDetail({id,saved,save}:{id:string;saved:Set<string>;save:(id:string)=>void}){const p=PROGRAMMES.find(x=>x.id===id);if(!p)return <Empty title="Programme not found" text="This programme is not in the catalogue."/>;const f=FUNDERS.find(x=>x.id===p.funderId)!;return <><Nav className="fc-back" to={"/funders/"+f.slug}><Icon name="back"/> {f.name}</Nav><Section label="PERSISTENT PROGRAMME PROFILE · DEMO" title={p.name}/><p className="fc-lead">{p.overview}</p><div className="fc-resultshead"><strong>Annual funding cycles</strong><span>Each year retains its own terms and deadline</span></div>{CALLS.filter(c=>c.programmeId===p.id).map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save}/>)}</>}
function OpportunityDetail({id,saved,save,projects,pipeline,patchItem}:{id:string;saved:Set<string>;save:(id:string)=>void;projects:Project[];pipeline:PipelineItem[];patchItem:(id:string,p:Partial<PipelineItem>)=>void}){const c=CALLS.find(x=>x.id===id);if(!c)return <Empty title="Opportunity not found" text="This funding round does not exist."/>;const f=funderFor(c),p=programmeFor(c),item=pipeline.find(i=>i.callId===c.id);return <><Nav to="/discover" className="fc-back"><Icon name="back"/> Discover</Nav><div className="fc-detail-hero"><p className="fc-eyebrow">ILLUSTRATIVE CALL · {c.year}</p><h1>{c.title}</h1><p className="fc-lead">{c.description}</p><div className="fc-actions"><button className={"fc-btn "+(saved.has(c.id)?"":"fc-btn-primary")} onClick={()=>save(c.id)}>{saved.has(c.id)?" Remove from my CRM":" Save to my CRM"}</button></div></div><div className="fc-profile-grid"><div><Section label="PROGRAMME" title="What this opportunity covers"/><p>{p.overview}</p><div className="fc-feature-grid"><div><span>Potential amount</span><strong>{amount(c)}</strong><small>{c.amountKind}</small></div><div><span>Deadline</span><strong>{prettyDate(c.deadline)}</strong><small>DEMO EXPECTED · not verified</small></div><div><span>Applicant type</span><strong>{c.applicant}</strong></div><div><span>Geography</span><strong>{c.region}</strong></div></div><Section label="ELIGIBILITY" title="Requirements & source"/><p>Actual official requirements, licensing, and source verification are not connected. No eligibility recommendation or application is possible from this preview.</p><Section label="CALL HISTORY" title="Other years"/>{CALLS.filter(x=>x.programmeId===c.programmeId&&x.id!==c.id).map(x=><Nav key={x.id} className="fc-linkchip" to={"/opportunities/"+x.id}>{x.year} · {prettyDate(x.deadline)}</Nav>)}</div><aside className="fc-info-panel"><Nav className="fc-funder-identity" to={"/funders/"+f.slug}><Initial name={f.name}/><span><strong>{f.name}</strong><small>View permanent actor profile </small></span></Nav><h3>Private project link</h3>{item?<select aria-label="Connect to project" value={item.projectId} onChange={e=>patchItem(item.id,{projectId:e.target.value})}><option value="">No project assigned</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<p>Save the opportunity to connect it to one of your demo projects.</p>}<hr/><p className="fc-muted fc-small">No live source · no external application link · do not rely on illustrative dates.</p></aside></div></>}

function FinanceAnalytics({workspace}:{workspace:Workspace}){
 const total=workspace.pipeline.length,attached=workspace.pipeline.filter(i=>i.projectId).length,preparing=workspace.pipeline.filter(i=>["Qualified","Preparing","Quality review","Ready for release"].includes(i.status)).length;
 const stageCounts=["Saved","Qualified","Preparing","Quality review","Ready for release"].map(stage=>workspace.pipeline.filter(i=>i.status===stage).length);
 const max=Math.max(1,...stageCounts);
 const linkedPercent=total?Math.round(attached/total*100):0;
 return <section className="fc-dashboard-analytics" aria-label="Pipeline analysis">
   <div className="fc-sectionheading"><div><p className="fc-eyebrow">AT A GLANCE</p><h2>Pipeline analysis</h2></div><span className="fc-tag">Illustrative workspace data</span></div>
   <div className="fc-analytics-grid">
    <div className="fc-analytics-card"><h3>Project coverage</h3><div className="fc-analytics-main"><div><strong>{linkedPercent}%</strong><small>{attached} of {total} saved calls linked to projects</small></div><div className="fc-mini-donut" role="img" aria-label={linkedPercent+" percent of saved calls linked to projects"} style={{"--fc-progress":linkedPercent+"%"} as import("react").CSSProperties}/></div></div>
    <div className="fc-analytics-card"><h3>Preparation pipeline</h3><div className="fc-analytics-main"><div><strong>{preparing}</strong><small>Internal cases under preparation</small></div><div className="fc-mini-bars" role="img" aria-label="Saved calls by internal stage">{stageCounts.map((v,i)=><i key={i} style={{height:(Math.max(5,v/max*76))+"px"}}/>)}</div></div></div>
    <div className="fc-analytics-card"><h3>Active projects</h3><div className="fc-analytics-main"><div><strong>{workspace.projects.length}</strong><small>Projects in selected workspace</small></div><div className="fc-mini-stages" aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i} className={i<Math.min(18,workspace.projects.length)?"filled":""}/>)}</div></div></div>
   </div>
 </section>;
}

function Dashboard({state,saved,save,signIn,hasSession}:{state:FinanceState;saved:Set<string>;save:(id:string)=>void;signIn:()=>void;hasSession:boolean}){const w=state.workspaces[state.active],dated=w.pipeline.map(i=>CALLS.find(c=>c.id===i.callId)).filter(Boolean) as Call[];const soon=dated.slice().sort((a,b)=>a.deadline.localeCompare(b.deadline));return <><div className="fc-dash-title"><div><p className="fc-eyebrow">MY FINANCING DESK</p><h1>My overview<span>.</span></h1><p>Funding, projects and decisions in one view.</p></div><Nav to="/discover" className="fc-btn fc-btn-primary">Explore funding <Icon name="arrow"/></Nav></div><div className="fc-kpi-grid"><div><span>Saved opportunities</span><strong>{w.pipeline.length}</strong><small>Demo pipeline</small></div><div><span>In preparation</span><strong>{w.pipeline.filter(i=>["Qualified","Preparing","Quality review","Ready for release"].includes(i.status)).length}</strong><small>Internal stages only</small></div><div><span>Deadline in next 30 days</span><strong>{dated.filter(c=>{const delta=(new Date(c.deadline).getTime()-new Date().getTime())/86400000;return delta>=0&&delta<=30}).length}</strong><small>Illustrative dates</small></div><div><span>Money received</span><strong>—</strong><small>No official funding payment data</small></div></div><FinanceAnalytics workspace={w}/><div className="fc-dash-columns"><div><Section label="MY PIPELINE" title="Next deadlines" aside={<Nav className="fc-minilink" to="/my/calendar">Year wheel </Nav>}/>{soon.length?soon.slice(0,4).map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save} compact/>):<Empty title="Your pipeline is empty" text="Save an opportunity from the global catalogue to make it appear here."/>}<div className="fc-section-footer"><Nav to="/my/pipeline">View my CRM </Nav></div></div><div><Section label="WORKSPACE INTELLIGENCE" title="Projects"/>{w.projects.length?w.projects.map(p=><Nav key={p.id} className="fc-project-snippet" to={"/my/projects/"+p.id}><strong>{p.name}</strong><span>{p.theme} · {w.pipeline.filter(i=>i.projectId===p.id).length} linked calls</span></Nav>):<Empty title="No projects yet" text="Create a project and attach financing opportunities."/>}<Nav to="/my/projects" className="fc-btn fc-full">Manage projects <Icon name="arrow"/></Nav><div className="fc-login-note"><strong>4PLANET ID</strong><p>{hasSession?"An identity session was detected. Your demo-only CRM drafts are stored in your private account; real organisation roles remain pending.":"Sign in using the shared identity when its production bridge is verified. This demonstration stays device-local."}</p>{!hasSession&&<button onClick={signIn}>Open 4PLANET ID </button>}</div></div></div></>}
function Pipeline({workspace,patch,remove}:{workspace:{pipeline:PipelineItem[];projects:Project[]};patch:(id:string,p:Partial<PipelineItem>)=>void;remove:(id:string)=>void}){const [filter,setFilter]=useState("All");const items=workspace.pipeline.filter(i=>filter==="All"||i.status===filter);return <><Section label="MY WORKSPACE · DEMO" title="My CRM" aside={<Nav to="/discover" className="fc-btn fc-btn-primary"> Add opportunity</Nav>}/><p className="fc-muted">Save opportunities from the global catalogue. Organise internal preparation without inventing formal applications, grants or payments.</p><div className="fc-filters"><select aria-label="Filter pipeline stage" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{STATUS.map(t=><option key={t}>{t}</option>)}</select></div>{items.length?items.map(i=>{const c=CALLS.find(x=>x.id===i.callId);if(!c)return null;return <div key={i.id} className="fc-pipe-row"><div className="fc-pipe-main"><Nav className="fc-opp-title" to={"/opportunities/"+c.id}>{c.title}</Nav><small>{funderFor(c).name} · {prettyDate(c.deadline)} · {amount(c)}</small></div><select aria-label={"Stage for "+c.title} value={i.status} onChange={e=>{const next=e.target.value as Status;if(!validTransition(next,i.receipt)){alert("Formal submission, award or decision states require verified external evidence and cannot be set manually in this MVP.");return}patch(i.id,{status:next})}}>{STATUS.map(t=><option key={t} disabled={!validTransition(t,i.receipt)}>{t}</option>)}</select><select aria-label={"Project for "+c.title} value={i.projectId} onChange={e=>patch(i.id,{projectId:e.target.value})}><option value="">No project</option>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label={"Private reference for "+c.title} value={i.receipt} onChange={e=>patch(i.id,{receipt:e.target.value})} placeholder="Internal notes/reference only"/><button className="fc-textbutton" onClick={()=>remove(i.callId)}>Remove</button></div>}):<Empty title="No saved opportunities" text="Discover funding and save calls to build this pipeline."/>}</>}
function Calendar({saved,save,mine,pipeline=[]}:{saved:Set<string>;save:(id:string)=>void;mine:boolean;pipeline?:PipelineItem[]}){const [year,setYear]=useState(2026),[month,setMonth]=useState(9),[scope,setScope]=useState("All");const visible=CALLS.filter(c=>c.year===year&&c.deadline.slice(5,7)===String(month+1).padStart(2,"0")&&(!mine||scope!=="Mine"||saved.has(c.id))).sort((a,b)=>a.deadline.localeCompare(b.deadline));const months=Array.from({length:12},(_,i)=>new Date(Date.UTC(year,i,1)).toLocaleString("en-GB",{month:"short",timeZone:"UTC"}));function changeMonth(direction:number){let y=year,m=month+direction;if(m<0){m=11;y--}if(m>11){m=0;y++}setYear(y);setMonth(m)}return <><Section label="ANNUAL FUNDING INTELLIGENCE" title="Your year wheel" aside={mine&&<select aria-label="Calendar scope" value={scope} onChange={e=>setScope(e.target.value)}><option>All</option><option>Mine</option></select>}/><p className="fc-muted">Browse all illustrative annual rounds. The real product will separate verified deadlines, expected re-opening dates and your internal work milestones.</p><div className="fc-calendar-controls"><button aria-label="Previous month" onClick={()=>changeMonth(-1)}></button><strong><MonthLabel value={year+"-"+String(month+1).padStart(2,"0")}/></strong><button aria-label="Next month" onClick={()=>changeMonth(1)}></button><select aria-label="Select year" value={year} onChange={e=>setYear(Number(e.target.value))}>{[2026,2027,2028].map(y=><option key={y}>{y}</option>)}</select></div><div className="fc-month-strip">{months.map((m,i)=>{const count=CALLS.filter(c=>c.deadline.startsWith(String(year)+"-"+String(i+1).padStart(2,"0"))).length;return <button key={m} className={i===month?"current":""} onClick={()=>setMonth(i)}><strong>{m}</strong><span>{count?count+" calls":"—"}</span><i style={{height:Math.max(3,count*8)+"px"}}/></button>})}</div><div className="fc-resultshead"><strong>{months[month]} {year}</strong><span>{visible.length} demo funding deadlines · different currencies are not summed</span></div>{visible.length?visible.map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save}/>):<Empty title="No calls in this month" text="Change month or switch the calendar filter."/>}{mine&&pipeline.length>0&&<p className="fc-muted fc-small">Saved opportunities can be linked to projects in My CRM. No reminders are scheduled by this demo.</p>}</>}
function Projects({workspace,onSave,onDelete}:{workspace:{pipeline:PipelineItem[];projects:Project[]};onSave:(p:Project)=>void;onDelete:(id:string)=>void}){const [name,setName]=useState(""),[theme,setTheme]=useState<Theme>("Climate"),[description,setDescription]=useState(""),[region,setRegion]=useState("Worldwide");const add=(e:FormEvent)=>{e.preventDefault();if(!name.trim())return;onSave({id:"proj-"+crypto.randomUUID(),name:name.trim(),theme,description:description.trim(),region,fundingNeed:""});setName("");setDescription("")};return <><Section label="YOUR OWN FUNDING PROJECTS" title="My projects"/><div className="fc-project-layout"><div><div className="fc-project-list">{workspace.projects.map(p=><div className="fc-project-card" key={p.id}><Nav to={"/my/projects/"+p.id}><strong>{p.name} </strong><span>{p.description||"No description"}</span><small>{p.theme} · {p.region} · {workspace.pipeline.filter(i=>i.projectId===p.id).length} linked opportunities</small></Nav><button className="fc-textbutton" onClick={()=>{if(window.confirm("Delete this demo project? Linked opportunities will remain in your pipeline."))onDelete(p.id)}}>Delete</button></div>)}</div>{!workspace.projects.length&&<Empty title="Create your first project" text="Project pages collect every linked funding opportunity."/>}</div><form onSubmit={add} className="fc-form-panel"><h3>New project</h3><label>Project name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="E.g. Oslofjord restoration"/></label><label>Topic<select value={theme} onChange={e=>setTheme(e.target.value as Theme)}>{THEMES.map(t=><option key={t}>{t}</option>)}</select></label><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}>{REGIONS.map(t=><option key={t}>{t}</option>)}</select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What will this project achieve?" rows={3}/></label><button className="fc-btn fc-btn-primary" type="submit"> Create demo project</button><small className="fc-muted">Stored on this device only, not in BRAIN.</small></form></div></>}
function ProjectDetail({id,workspace,patch}:{id:string;workspace:{projects:Project[];pipeline:PipelineItem[]};patch:(id:string,p:Partial<PipelineItem>)=>void}){const p=workspace.projects.find(x=>x.id===id);if(!p)return <Empty title="Project not found" text="Create a project in My projects."/>;const items=workspace.pipeline.filter(i=>i.projectId===id);return <><Nav className="fc-back" to="/my/projects"><Icon name="back"/> My projects</Nav><Section label={p.theme+" · "+p.region} title={p.name}/><p className="fc-lead">{p.description||"No description yet."}</p><div className="fc-resultshead"><strong>Linked funding opportunities</strong><span>{items.length} calls</span></div>{items.map(i=>{const c=CALLS.find(c=>c.id===i.callId)!;return <article key={i.id} className="fc-opportunity"><div className="fc-opp-body"><Nav className="fc-opp-title" to={"/opportunities/"+c.id}>{c.title}</Nav><p>{prettyDate(c.deadline)} · {amount(c)}</p></div><button onClick={()=>patch(i.id,{projectId:""})} className="fc-textbutton">Unlink</button></article>})}{!items.length&&<Empty title="Nothing linked yet" text="Visit My CRM and assign a saved opportunity to this project."/>}</>}
function Applications({pipeline}:{pipeline:PipelineItem[]}){return <><Section label="APPLICATION CASES · DEMO" title="Applications & decisions"/><p className="fc-muted">A saved opportunity is not an application. Formal submissions require external receipts and explicit human authorisation.</p><div className="fc-resultshead"><strong>Recorded stages</strong><span>No provider integrations or payments</span></div>{pipeline.filter(i=>["Submitted","Awaiting decision","Awarded","Rejected"].includes(i.status)).map(i=>{const c=CALLS.find(x=>x.id===i.callId);return c?<div key={i.id} className="fc-application-row"><Nav to={"/opportunities/"+c.id}>{c.title}</Nav><Tag>{i.status}</Tag><span>{i.receipt||"No external receipt recorded"}</span></div>:null})}{!pipeline.some(i=>["Submitted","Awaiting decision","Awarded","Rejected"].includes(i.status))&&<Empty title="No application cases recorded" text="Applications and receipt evidence will be preserved here once integrated with the canonical Capital Control Tower."/>}</>}
function Graph({workspace}:{workspace:{projects:Project[];pipeline:PipelineItem[]}}){const [selected,setSelected]=useState<string>("");const nodes:({id:string;label:string;kind:string;href:string})[]=[],edges:[string,string][]=[];workspace.projects.forEach(p=>nodes.push({id:p.id,label:p.name,kind:"Project",href:"/my/projects/"+p.id}));workspace.pipeline.forEach(i=>{const c=CALLS.find(x=>x.id===i.callId);if(!c)return;const pr=programmeFor(c),f=funderFor(c);[{id:c.id,label:c.title,kind:"Opportunity",href:"/opportunities/"+c.id},{id:pr.id,label:pr.name,kind:"Programme",href:"/programmes/"+pr.id},{id:f.id,label:f.name,kind:"Funder",href:"/funders/"+f.slug}].forEach(n=>{if(!nodes.some(x=>x.id===n.id))nodes.push(n)});edges.push([i.projectId||"workspace",c.id],[c.id,pr.id],[pr.id,f.id])});if(workspace.pipeline.some(i=>!i.projectId))nodes.push({id:"workspace",label:"Unassigned pipeline",kind:"Workspace",href:"/my/pipeline"});const chosen=nodes.find(n=>n.id===selected);const width=760,height=470;return <><Section label="ECONOMIC ORGANISATION MAP" title="Relationship graph"/><p className="fc-muted">Graph is an optional view of your saved projects and financing relationships, not another database.</p>{nodes.length?<><div className="fc-graph"><svg viewBox={"0 0 "+width+" "+height} role="img" aria-label="Funding actors, programmes, opportunities and projects graph">{edges.map(([a,b],i)=>{const ia=nodes.findIndex(n=>n.id===a),ib=nodes.findIndex(n=>n.id===b);if(ia<0||ib<0)return null;const point=(index:number)=>{const angle=(index/nodes.length)*Math.PI*2;return {x:width/2+260*Math.cos(angle),y:height/2+175*Math.sin(angle)}};const x=point(ia),y=point(ib);return <line key={i} x1={x.x} y1={x.y} x2={y.x} y2={y.y} stroke="#bbc0c9" strokeWidth="1.5"/>})}{nodes.map((n,i)=>{const angle=i/nodes.length*Math.PI*2,x=width/2+260*Math.cos(angle),y=height/2+175*Math.sin(angle);return <g key={n.id} onClick={()=>setSelected(n.id)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")setSelected(n.id)}} style={{cursor:"pointer"}}><circle cx={x} cy={y} r={n.kind==="Funder"?30:23} fill={selected===n.id?"#2e2eff":n.kind==="Project"?"#161a21":"#fff"} stroke={selected===n.id?"#2e2eff":"#abb3c2"} strokeWidth="2"/><text x={x} y={y+4} fontSize="9" fill={selected===n.id||n.kind==="Project"?"white":"#151515"} textAnchor="middle">{n.kind.slice(0,4)}</text><text x={x} y={y+45} fill="#262b37" textAnchor="middle" fontSize="10">{n.label.slice(0,27)}</text></g>})}</svg></div>{chosen&&<div className="fc-graph-inspector"><strong>{chosen.label}</strong><Tag>{chosen.kind}</Tag><Nav to={chosen.href}>Open profile </Nav></div>}<div className="fc-graph-list">{nodes.map(n=><Nav to={n.href} key={n.id}>{n.kind} — {n.label} </Nav>)}</div></>:<Empty title="Your graph is empty" text="Save funding opportunities and connect them to projects to create relationships."/>}</>}
function Settings({state,changeWorkspace,reset,session,signIn}:{state:FinanceState;changeWorkspace:(v:"4planet"|"personal")=>void;reset:()=>void;session:FourPlanetSession|null;signIn:()=>void}){const [signOutError,setSignOutError]=useState("");function exportWorkspace(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),scope:"4planet-finance-private-workspace",workspace:state.active,data:state.workspaces[state.active]},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="4planet-finance-"+state.active+"-export.json";a.click();URL.revokeObjectURL(url);}async function signOut(){try{const client=await getIdentityClient();const response=await client.auth.signOut({scope:"local"});if(response.error)throw new Error(response.error.message)}catch(error){setSignOutError(error instanceof Error?error.message:"Unable to sign out")}}return <><Section label="USER CONTROL" title="Workspace settings"/><div className="fc-settings-panel"><h3>Active workspace</h3><select value={state.active} onChange={e=>changeWorkspace(e.target.value as "4planet"|"personal")}><option value="4planet">4PLANET (demo only)</option><option value="personal">Personal (demo only)</option></select><p>These two workspaces are separate views owned by this one user account. Organisation/team multi-tenancy is not yet enabled.</p><hr/><h3>4PLANET ID</h3><p>{session?"Identity session detected: "+(session.user.email||"signed in"):"No verified identity session detected."} Existing 4PLANET ID is used. Private account state is RLS-backed when signed in; shared organisation roles and source-backed funding remain pending.</p>{!session&&<button className="fc-btn" onClick={signIn}>Sign in through 4PLANET ID</button>}{session&&<button className="fc-btn" onClick={signOut}>Sign out of Finance</button>}{signOutError&&<p role="alert">{signOutError}</p>}<hr/><h3>Data portability</h3><p>Export the current private workspace, including project drafts and your saved funding pipeline, as a JSON file. Funding facts are still fictional in this release.</p><button className="fc-btn" onClick={exportWorkspace}>Export workspace data</button><hr/><h3>Reset demonstration</h3><p>Reset only guest/device-local demo projects. Do not use this button for an authenticated account reset.</p><button className="fc-btn" disabled={!!session} onClick={()=>{if(window.confirm("Erase all finance demonstration data stored on this device?"))reset()}}>Clear demonstration data</button></div></>}

function FinanceSignIn({onSignedIn,signedIn}:{onSignedIn:()=>void;signedIn:boolean}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError("");
  try {const client=await getIdentityClient();const response=await client.auth.signInWithPassword({email:email.trim(),password});
   if(response.error||!response.data.session)throw new Error(response.error?.message||"Unable to authenticate");
   setPassword("");onSignedIn();
  }catch(err){setError(err instanceof Error?err.message:"Authentication unavailable");}finally{setBusy(false)}
 }
 return <div className="fc-signin">
  <p className="fc-eyebrow">CANONICAL ACCOUNT · 4PLANET ID</p>
  <h1>Sign in to Finance.</h1>
  <p className="fc-lead">Use your existing 4PLANET ID. Finance uses the same Supabase Auth account as other 4PLANET products — no second identity is created.</p>
  {signedIn?<div className="fc-login-note">You are signed in. <Nav to="/my">Open private workspace </Nav></div>:
   <form onSubmit={submit} className="fc-form-panel">
    <label>Email address<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>
    <label>Password<input type="password" minLength={1} required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>
    {error&&<p role="alert" className="fc-sync-error">{error}</p>}
    <button disabled={busy} className="fc-btn fc-btn-primary" type="submit">{busy?"Signing in…":"Sign in with 4PLANET ID"}</button>
    <p className="fc-muted fc-small">Account recovery and registration remain under the existing <a href="https://id.4planet.org/login?mode=forgot">4PLANET ID account service </a>. Seamless cross-domain single-sign-on is pending the canonical ID site release; this direct sign-in uses the same account and avoids a duplicate auth provider.</p>
   </form>}
 </div>;
}
