/* CAP-PLATFORM-01 — GitHub-built universal finance interface. Demonstration until canonical data+RLS are integrated. */
import {useEffect,useMemo,useState,type FormEvent,type ReactNode} from "react";
import {Link,useLocation,useNavigate} from "react-router-dom";
import {getIdentityClient,identityLoginUrl,type FourPlanetSession} from "@/identity/identityClient";
import {CALLS,FUNDERS,PROGRAMMES,REGIONS,THEMES,STATUS,amount,prettyDate,programmeFor,funderFor,readState,saveState,emptyState,validTransition,type Call,type FinanceState,type PipelineItem,type Project,type Status,type Theme} from "./financeData";
import "./finance.css";

function currentPath(path:string){return path.replace(/^\/finance(?=\/|$)/,"")||"/"}
function toPath(p:string){return window.location.pathname.startsWith("/finance")?"/finance"+p:p}
function Nav({to,children,className=""}:{to:string;children:ReactNode;className?:string}){return <Link className={className} to={toPath(to)}>{children}</Link>}
function Icon({name}:{name:string}){const glyphs:Record<string,string>={overview:"▦",discover:"⌕",calendar:"▤",pipeline:"≡",project:"▧",actors:"◈",graph:"◇",applications:"▤",settings:"⚙",arrow:"↗",chevron:"›",back:"←",plus:"+",close:"×",menu:"☰"};return <span className="fc-icon" aria-hidden="true">{glyphs[name]||"·"}</span>}
function Initial({name}:{name:string}){return <span className="fc-initial" aria-hidden="true">{name.split(" ").map(w=>w[0]).slice(0,2).join("")}</span>}
function Section({label,title,children,aside}:{label?:string;title:string;children?:ReactNode;aside?:ReactNode}){return <section className="fc-section"><div className="fc-sectionheading"><div>{label&&<p className="fc-eyebrow">{label}</p>}<h2>{title}</h2></div>{aside}</div>{children}</section>}
function Tag({children,tone=""}:{children:ReactNode;tone?:string}){return <span className={"fc-tag "+tone}>{children}</span>}
function Empty({title,text}:{title:string;text:string}){return <div className="fc-empty"><strong>{title}</strong><p>{text}</p></div>}
function DemoNote(){return <div className="fc-demo" role="note"><span className="fc-demo-dot"/> <strong>DEMONSTRATION</strong><span>Illustrative organisations, calls, dates and amounts. No live funding data. Demo workspace saved on this device only.</span></div>}
function MonthLabel({value}:{value:string}){return <>{new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(value+"-01T12:00:00Z"))}</>}
function OpportunityRow({call,saved,onSave,compact=false}:{call:Call;saved:boolean;onSave:(id:string)=>void;compact?:boolean}){const f=funderFor(call);return <article className={"fc-opportunity "+(compact?"fc-opportunity-compact":"")}><div className="fc-opp-date"><strong>{call.deadline.slice(8,10)}</strong><span>{new Date(call.deadline+"T12:00:00Z").toLocaleString("en-GB",{month:"short",timeZone:"UTC"})}</span></div><div className="fc-opp-body"><div className="fc-kicker">{f.name} <span className="fc-dot">·</span> {call.instrument}</div><Nav to={"/opportunities/"+call.id} className="fc-opp-title">{call.title} <span>↗</span></Nav><div className="fc-inline"><Tag>{call.region}</Tag>{call.themes.slice(0,compact?1:2).map(t=><Tag key={t}>{t}</Tag>)}<span className="fc-muted fc-small">{call.confidence}</span></div></div><div className="fc-opp-right"><strong>{amount(call)}</strong><span className="fc-muted fc-small">{call.amountKind}</span><button className={"fc-save "+(saved?"is-saved":"")} onClick={()=>onSave(call.id)}>{saved?"Saved ✓":"＋ Save"}</button></div></article>}
const CATALOGUE_NAV=[{path:"/",title:"Home"},{path:"/discover",title:"Discover"},{path:"/funders",title:"Funders"},{path:"/calendar",title:"Year wheel"}];
const WORKSPACE_NAV=[{path:"/my",title:"Overview",icon:"overview"},{path:"/my/pipeline",title:"My CRM",icon:"pipeline"},{path:"/my/calendar",title:"Year wheel",icon:"calendar"},{path:"/my/projects",title:"My projects",icon:"project"},{path:"/my/applications",title:"Applications",icon:"applications"},{path:"/my/graph",title:"Relationship graph",icon:"graph"}];
export default function FinanceHub(){
 const loc=useLocation(),navigate=useNavigate(),path=currentPath(loc.pathname);
 const [state,setState]=useState<FinanceState>(readState),[menu,setMenu]=useState(false),[session,setSession]=useState<FourPlanetSession|null>(null),[authChecked,setAuthChecked]=useState(false);
 const workspace=state.workspaces[state.active];
 const change=(mutator:(s:FinanceState)=>FinanceState)=>setState(prev=>{const next=mutator(prev);saveState(next);return next});
 useEffect(()=>{let active=true;let unsubscribe=()=>{};getIdentityClient().then(client=>{client.auth.getSession().then(r=>{if(active){setSession(r.data.session);setAuthChecked(true)}}).catch(()=>{if(active)setAuthChecked(true)});unsubscribe=client.auth.onAuthStateChange((_ev,s)=>{if(active)setSession(s)}).data.subscription.unsubscribe}).catch(()=>{if(active)setAuthChecked(true)});return()=>{active=false;unsubscribe()}},[]);
 useEffect(()=>{setMenu(false)},[loc.pathname]);
 const savedSet=useMemo(()=>new Set(workspace.pipeline.map(i=>i.callId)),[workspace]);
 const save=(id:string)=>change(s=>{const w=s.workspaces[s.active];if(w.pipeline.some(i=>i.callId===id))return {...s,workspaces:{...s.workspaces,[s.active]:{...w,pipeline:w.pipeline.filter(i=>i.callId!==id)}}};const now=new Date().toISOString();const item:PipelineItem={id:"pipe-"+crypto.randomUUID(),callId:id,projectId:"",status:"Saved",createdAt:now,updatedAt:now,notes:"",receipt:""};return {...s,workspaces:{...s.workspaces,[s.active]:{...w,pipeline:[...w.pipeline,item]}}}});
 const patchItem=(id:string,patch:Partial<PipelineItem>)=>change(s=>{const w=s.workspaces[s.active];return {...s,workspaces:{...s.workspaces,[s.active]:{...w,pipeline:w.pipeline.map(item=>item.id===id?{...item,...patch,updatedAt:new Date().toISOString()}:item)}}}});
 const switchWorkspace=(next:"4planet"|"personal")=>change(s=>({...s,active:next}));
 const addProject=(p:Project)=>change(s=>{const w=s.workspaces[s.active];return {...s,workspaces:{...s.workspaces,[s.active]:{...w,projects:[...w.projects,p]}}};});
 const deleteProject=(id:string)=>change(s=>{const w=s.workspaces[s.active];return {...s,workspaces:{...s.workspaces,[s.active]:{...w,projects:w.projects.filter(p=>p.id!==id),pipeline:w.pipeline.map(i=>i.projectId===id?{...i,projectId:""}:i)}}};});
 const signIn=()=>{window.location.href=identityLoginUrl(window.location.href)};
 const isMine=path==="/my"||path.startsWith("/my/");
 return <div className="fc-root">
  <DemoNote/>
  <header className="fc-header"><div className="fc-wrap fc-header-inner"><Nav to="/" className="fc-brand"><span className="fc-brandmark">4P<span>.</span></span><span className="fc-brandname">CAPITAL <small>by 4PLANET</small></span></Nav><nav className="fc-topnav">{CATALOGUE_NAV.map(i=><Nav key={i.path} to={i.path} className={path===i.path?"active":""}>{i.title}</Nav>)}</nav><div className="fc-header-right"><Nav to="/my" className="fc-smallbutton">My workspace <Icon name="arrow"/></Nav>{session?<span className="fc-avatar" title={session.user.email||"4PLANET ID"}>ID</span>:<button className="fc-ghost" onClick={signIn}>Sign in</button>}<button className="fc-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?"close":"menu"}/></button></div></div>{menu&&<nav className="fc-mobilemenu">{[...CATALOGUE_NAV,...WORKSPACE_NAV].map(i=><Nav key={i.path} to={i.path}>{i.title}</Nav>)}</nav>}</header>
  <div className={isMine?"fc-app-grid fc-wrap":"fc-wrap fc-public"}>
   {isMine&&<aside className="fc-sidebar"><div className="fc-eyebrow">MY SPACE</div><select aria-label="Demo workspace" value={state.active} onChange={e=>switchWorkspace(e.target.value as "4planet"|"personal")}><option value="4planet">4PLANET · Demo</option><option value="personal">Personal · Demo</option></select><nav>{WORKSPACE_NAV.map(i=><Nav key={i.path} to={i.path} className={"fc-side-link "+(path===i.path?"current":"")}><Icon name={i.icon}/>{i.title}</Nav>)}</nav><div className="fc-sidebar-footer"><Nav to="/my/settings" className="fc-side-link"><Icon name="settings"/>Settings</Nav><span>Finance Intelligence · v0.1</span></div></aside>}
   <main className="fc-main">
    {path==="/"&&<><div className="fc-hero"><p className="fc-eyebrow">FINANCING INTELLIGENCE FOR CHANGE</p><h1>Find the funding<br/>behind <em>change.</em></h1><p>Discover funders. Understand recurring programmes. Build your own pipeline and organise funding around real projects.</p><div className="fc-actions"><Nav className="fc-btn fc-btn-primary" to="/discover">Explore opportunities <Icon name="arrow"/></Nav><Nav className="fc-btn" to="/my">Open my workspace</Nav></div><div className="fc-hero-meta"><span>ONE GLOBAL DIRECTORY</span><span>ANNUAL FUNDING CYCLES</span><span>YOUR OWN WORKSPACE</span></div></div><div className="fc-landing-grid"><div><p className="fc-eyebrow">DISCOVER</p><h2>Funding intelligence that compounds.</h2><p>Each funder has a durable profile. Each programme has its own history. Each annual call can be saved to your projects and deadline calendar.</p></div><div className="fc-category-grid">{THEMES.slice(0,6).map((t,i)=><Nav key={t} to={"/discover?theme="+encodeURIComponent(t)} className="fc-category"><span>0{(i+1)}</span><strong>{t}</strong><Icon name="arrow"/></Nav>)}</div></div></>}
    {path==="/discover"&&<Discover saved={savedSet} save={save}/>}
    {path==="/funders"&&<FunderDirectory/>}
    {path.startsWith("/funders/")&&<FunderDetail slug={path.split("/")[2]} saved={savedSet} save={save}/>}
    {path.startsWith("/programmes/")&&<ProgrammeDetail id={path.split("/")[2]} saved={savedSet} save={save}/>}
    {path.startsWith("/opportunities/")&&<OpportunityDetail id={path.split("/")[2]} saved={savedSet} save={save} projects={workspace.projects} pipeline={workspace.pipeline} patchItem={patchItem}/>}
    {path==="/calendar"&&<Calendar saved={savedSet} save={save} mine={false}/>}
    {isMine&&<div className="fc-my-top"><span className="fc-eyebrow">{state.active==="4planet"?"4PLANET DEMO WORKSPACE":"PERSONAL DEMO WORKSPACE"}</span><div className="fc-my-auth">{authChecked&&session?"4PLANET ID session detected · demo data only":authChecked?"Preview mode · no verified 4PLANET ID session":"Checking 4PLANET ID…"}</div></div>}
    {path==="/my"&&<Dashboard state={state} saved={savedSet} save={save} signIn={signIn} hasSession={!!session}/>}
    {path==="/my/pipeline"&&<Pipeline workspace={workspace} patch={patchItem} remove={save}/>}
    {path==="/my/calendar"&&<Calendar saved={savedSet} save={save} mine pipeline={workspace.pipeline}/>}
    {path==="/my/projects"&&<Projects workspace={workspace} onSave={addProject} onDelete={deleteProject}/> }
    {path.startsWith("/my/projects/")&&<ProjectDetail id={path.split("/")[3]} workspace={workspace} patch={patchItem}/>}
    {path==="/my/applications"&&<Applications pipeline={workspace.pipeline}/>}
    {path==="/my/graph"&&<Graph workspace={workspace}/>}
    {path==="/my/settings"&&<Settings state={state} changeWorkspace={switchWorkspace} reset={()=>{const s=emptyState();saveState(s);setState(s)}} session={session} signIn={signIn}/>}
    {!["/","/discover","/funders","/calendar","/my","/my/pipeline","/my/calendar","/my/projects","/my/applications","/my/graph","/my/settings"].includes(path)&&!["/funders/","/programmes/","/opportunities/","/my/projects/"].some(p=>path.startsWith(p))&&<Empty title="Page not found" text="This route does not exist."/>}
   </main>
  </div>
  <footer className="fc-footer"><div className="fc-wrap"><strong>4PLANET_</strong><span>For a Living Planet.</span><span>CAP-PLATFORM-01 · Preview candidate, not production finance data</span></div></footer>
 </div>;
}
function Discover({saved,save}:{saved:Set<string>;save:(id:string)=>void}){
 const loc=useLocation();const [q,setQ]=useState(new URLSearchParams(loc.search).get("q")||"");
 const [theme,setTheme]=useState(new URLSearchParams(loc.search).get("theme")||"All");
 const [region,setRegion]=useState("All"),[month,setMonth]=useState("All"),[instrument,setInstrument]=useState("All"),[applicant,setApplicant]=useState("All"),[currency,setCurrency]=useState("All"),[minAmount,setMinAmount]=useState(""),[sort,setSort]=useState("Soonest");
 const filtered=useMemo(()=>CALLS.filter(c=>{const f=funderFor(c);const query=q.toLowerCase();return (!q||[c.title,f.name,programmeFor(c).name,c.description,...c.themes].join(" ").toLowerCase().includes(query))&&(theme==="All"||c.themes.includes(theme as Theme))&&(region==="All"||c.region===region)&&(month==="All"||c.deadline.slice(0,7)===month)&&(instrument==="All"||c.instrument===instrument)&&(applicant==="All"||c.applicant.toLowerCase().includes(applicant.toLowerCase()))&&(currency==="All"||c.currency===currency)&&(!minAmount||(currency!=="All"&&c.amount>=Number(minAmount)))}).sort((a,b)=>sort==="Soonest"?a.deadline.localeCompare(b.deadline):b.amount-a.amount),[q,theme,region,month,instrument,applicant,currency,minAmount,sort]);
 const months=Array.from(new Set(CALLS.map(c=>c.deadline.slice(0,7)))).sort();
 return <><Section label="UNIVERSAL CATALOGUE · DEMO" title="Discover funding" aside={<span className="fc-muted">{filtered.length} illustrative calls</span>}/><div className="fc-searchbar"><Icon name="discover"/><input aria-label="Search opportunities" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search funders, projects, issues, grants…"/>{q&&<button onClick={()=>setQ("")}>Clear</button>}</div><div className="fc-filters"><select aria-label="Topic" value={theme} onChange={e=>setTheme(e.target.value)}><option>All</option>{THEMES.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Location" value={region} onChange={e=>setRegion(e.target.value)}><option>All</option>{REGIONS.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Month" value={month} onChange={e=>setMonth(e.target.value)}><option>All</option>{months.map(m=><option key={m} value={m}>{m}</option>)}</select><select aria-label="Funding instrument" value={instrument} onChange={e=>setInstrument(e.target.value)}><option>All</option>{["Grant","Prize","Fellowship"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Applicant type" value={applicant} onChange={e=>setApplicant(e.target.value)}><option>All</option>{["NGO","Founder","Research","Individual","Company","Public"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Currency" value={currency} onChange={e=>{setCurrency(e.target.value);setMinAmount("")}}><option>All</option>{["NOK","EUR","USD"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Minimum award in selected currency" type="number" min="0" disabled={currency==="All"} value={minAmount} onChange={e=>setMinAmount(e.target.value)} placeholder="Min. amount"/><select aria-label="Sort" value={sort} onChange={e=>setSort(e.target.value)}><option>Soonest</option><option>Largest</option></select></div><div className="fc-resultshead"><strong>Opportunities</strong><span>Demo data · No verified external deadlines</span></div>{filtered.length?filtered.map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save}/>):<Empty title="No results" text="Try adjusting a filter or search term."/>}</>;
}
function FunderDirectory(){const [q,setQ]=useState("");const results=FUNDERS.filter(f=>[f.name,f.summary,...f.themes].join(" ").toLowerCase().includes(q.toLowerCase()));return <><Section label="PUBLIC ACTOR DIRECTORY · DEMO" title="The people behind funding"/><div className="fc-searchbar"><Icon name="discover"/><input placeholder="Search actor, region, mission…" aria-label="Search funders" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="fc-funder-grid">{results.map(f=><Nav to={"/funders/"+f.slug} className="fc-funder-card" key={f.id}><div className="fc-funder-top"><Initial name={f.name}/><span className="fc-muted fc-small">{f.kind}</span></div><h3>{f.name}</h3><p>{f.summary}</p><div className="fc-inline"><Tag>{f.region}</Tag>{f.themes.map(t=><Tag key={t}>{t}</Tag>)}</div><div className="fc-card-foot"><span>{PROGRAMMES.filter(p=>p.funderId===f.id).length} demo programmes</span><Icon name="arrow"/></div></Nav>)}</div></>}
function FunderDetail({slug,saved,save}:{slug:string;saved:Set<string>;save:(id:string)=>void}){const f=FUNDERS.find(x=>x.slug===slug);if(!f)return <Empty title="Funder not found" text="No actor matches this ID."/>;const ps=PROGRAMMES.filter(p=>p.funderId===f.id);return <><Nav to="/funders" className="fc-back"><Icon name="back"/> All funders</Nav><div className="fc-actor-hero"><Initial name={f.name}/><p className="fc-eyebrow">ACTOR PROFILE · DEMONSTRATION</p><h1>{f.name}</h1><p>{f.summary}</p><div className="fc-inline"><Tag>{f.kind}</Tag><Tag>{f.region}</Tag>{f.themes.map(t=><Tag key={t}>{t}</Tag>)}</div></div><div className="fc-profile-grid"><div><Section label="LONG-TERM KNOWLEDGE" title="Programmes & annual rounds"/>{ps.map(p=><div className="fc-profile-program" key={p.id}><Nav to={"/programmes/"+p.id} className="fc-opp-title">{p.name} <Icon name="arrow"/></Nav><p>{p.overview}</p><div className="fc-inline">{CALLS.filter(c=>c.programmeId===p.id).map(c=><Nav key={c.id} className="fc-linkchip" to={"/opportunities/"+c.id}>{c.year} · {prettyDate(c.deadline)}</Nav>)}</div></div>)}</div><aside className="fc-info-panel"><h3>Actor intelligence</h3><dl><dt>Geography</dt><dd>{f.region}</dd><dt>Topics</dt><dd>{f.themes.join(" · ")}</dd><dt>Evidence / source</dt><dd>FICTIONAL FIXTURE — no external source</dd><dt>Last verified</dt><dd>Not connected</dd></dl><p>Real actor pages will show public evidence, award history, updated funding terms and workspace-private relationship notes.</p></aside></div></>}
function ProgrammeDetail({id,saved,save}:{id:string;saved:Set<string>;save:(id:string)=>void}){const p=PROGRAMMES.find(x=>x.id===id);if(!p)return <Empty title="Programme not found" text="This programme is not in the catalogue."/>;const f=FUNDERS.find(x=>x.id===p.funderId)!;return <><Nav className="fc-back" to={"/funders/"+f.slug}><Icon name="back"/> {f.name}</Nav><Section label="PERSISTENT PROGRAMME PROFILE · DEMO" title={p.name}/><p className="fc-lead">{p.overview}</p><div className="fc-resultshead"><strong>Annual funding cycles</strong><span>Each year retains its own terms and deadline</span></div>{CALLS.filter(c=>c.programmeId===p.id).map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save}/>)}</>}
function OpportunityDetail({id,saved,save,projects,pipeline,patchItem}:{id:string;saved:Set<string>;save:(id:string)=>void;projects:Project[];pipeline:PipelineItem[];patchItem:(id:string,p:Partial<PipelineItem>)=>void}){const c=CALLS.find(x=>x.id===id);if(!c)return <Empty title="Opportunity not found" text="This funding round does not exist."/>;const f=funderFor(c),p=programmeFor(c),item=pipeline.find(i=>i.callId===c.id);return <><Nav to="/discover" className="fc-back"><Icon name="back"/> Discover</Nav><div className="fc-detail-hero"><p className="fc-eyebrow">ILLUSTRATIVE CALL · {c.year}</p><h1>{c.title}</h1><p className="fc-lead">{c.description}</p><div className="fc-actions"><button className={"fc-btn "+(saved.has(c.id)?"":"fc-btn-primary")} onClick={()=>save(c.id)}>{saved.has(c.id)?"✓ Remove from my CRM":"＋ Save to my CRM"}</button></div></div><div className="fc-profile-grid"><div><Section label="PROGRAMME" title="What this opportunity covers"/><p>{p.overview}</p><div className="fc-feature-grid"><div><span>Potential amount</span><strong>{amount(c)}</strong><small>{c.amountKind}</small></div><div><span>Deadline</span><strong>{prettyDate(c.deadline)}</strong><small>DEMO EXPECTED · not verified</small></div><div><span>Applicant type</span><strong>{c.applicant}</strong></div><div><span>Geography</span><strong>{c.region}</strong></div></div><Section label="ELIGIBILITY" title="Requirements & source"/><p>Actual official requirements, licensing, and source verification are not connected. No eligibility recommendation or application is possible from this preview.</p><Section label="CALL HISTORY" title="Other years"/>{CALLS.filter(x=>x.programmeId===c.programmeId&&x.id!==c.id).map(x=><Nav key={x.id} className="fc-linkchip" to={"/opportunities/"+x.id}>{x.year} · {prettyDate(x.deadline)}</Nav>)}</div><aside className="fc-info-panel"><Nav className="fc-funder-identity" to={"/funders/"+f.slug}><Initial name={f.name}/><span><strong>{f.name}</strong><small>View permanent actor profile ↗</small></span></Nav><h3>Private project link</h3>{item?<select aria-label="Connect to project" value={item.projectId} onChange={e=>patchItem(item.id,{projectId:e.target.value})}><option value="">No project assigned</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:<p>Save the opportunity to connect it to one of your demo projects.</p>}<hr/><p className="fc-muted fc-small">No live source · no external application link · do not rely on illustrative dates.</p></aside></div></>}
function Dashboard({state,saved,save,signIn,hasSession}:{state:FinanceState;saved:Set<string>;save:(id:string)=>void;signIn:()=>void;hasSession:boolean}){const w=state.workspaces[state.active],dated=w.pipeline.map(i=>CALLS.find(c=>c.id===i.callId)).filter(Boolean) as Call[];const soon=dated.slice().sort((a,b)=>a.deadline.localeCompare(b.deadline));return <><div className="fc-dash-title"><div><p className="fc-eyebrow">MY FINANCING DESK</p><h1>Good afternoon<span>.</span></h1><p>Your capital opportunities, deadlines and project decisions in one place.</p></div><Nav to="/discover" className="fc-btn fc-btn-primary">Explore funding <Icon name="arrow"/></Nav></div><div className="fc-kpi-grid"><div><span>Saved opportunities</span><strong>{w.pipeline.length}</strong><small>Demo pipeline</small></div><div><span>In preparation</span><strong>{w.pipeline.filter(i=>["Qualified","Preparing","Quality review","Ready for release"].includes(i.status)).length}</strong><small>Internal stages only</small></div><div><span>Deadline in next 30 days</span><strong>{dated.filter(c=>{const delta=(new Date(c.deadline).getTime()-new Date().getTime())/86400000;return delta>=0&&delta<=30}).length}</strong><small>Illustrative dates</small></div><div><span>Money received</span><strong>—</strong><small>No financial backend connected</small></div></div><div className="fc-dash-columns"><div><Section label="MY PIPELINE" title="Next deadlines" aside={<Nav className="fc-minilink" to="/my/calendar">Year wheel ↗</Nav>}/>{soon.length?soon.slice(0,4).map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save} compact/>):<Empty title="Your pipeline is empty" text="Save an opportunity from the global catalogue to make it appear here."/>}<div className="fc-section-footer"><Nav to="/my/pipeline">View my CRM →</Nav></div></div><div><Section label="WORKSPACE INTELLIGENCE" title="Projects"/>{w.projects.length?w.projects.map(p=><Nav key={p.id} className="fc-project-snippet" to={"/my/projects/"+p.id}><strong>{p.name}</strong><span>{p.theme} · {w.pipeline.filter(i=>i.projectId===p.id).length} linked calls</span></Nav>):<Empty title="No projects yet" text="Create a project and attach financing opportunities."/>}<Nav to="/my/projects" className="fc-btn fc-full">Manage projects <Icon name="arrow"/></Nav><div className="fc-login-note"><strong>4PLANET ID</strong><p>{hasSession?"An identity session was detected. Actual CRM persistence and workspace permissions are still pending server integration.":"Sign in using the shared identity when its production bridge is verified. This demonstration stays device-local."}</p>{!hasSession&&<button onClick={signIn}>Open 4PLANET ID ↗</button>}</div></div></div></>}
function Pipeline({workspace,patch,remove}:{workspace:{pipeline:PipelineItem[];projects:Project[]};patch:(id:string,p:Partial<PipelineItem>)=>void;remove:(id:string)=>void}){const [filter,setFilter]=useState("All");const items=workspace.pipeline.filter(i=>filter==="All"||i.status===filter);return <><Section label="MY WORKSPACE · DEMO" title="My CRM" aside={<Nav to="/discover" className="fc-btn fc-btn-primary">＋ Add opportunity</Nav>}/><p className="fc-muted">Save opportunities from the global catalogue. Organise internal preparation without inventing formal applications, grants or payments.</p><div className="fc-filters"><select aria-label="Filter pipeline stage" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{STATUS.map(t=><option key={t}>{t}</option>)}</select></div>{items.length?items.map(i=>{const c=CALLS.find(x=>x.id===i.callId);if(!c)return null;return <div key={i.id} className="fc-pipe-row"><div className="fc-pipe-main"><Nav className="fc-opp-title" to={"/opportunities/"+c.id}>{c.title}</Nav><small>{funderFor(c).name} · {prettyDate(c.deadline)} · {amount(c)}</small></div><select aria-label={"Stage for "+c.title} value={i.status} onChange={e=>{const next=e.target.value as Status;if(!validTransition(next,i.receipt)){alert("A recorded external receipt/reference is required for Submitted, Awaiting decision or Awarded. Demo does not submit an application.");return}patch(i.id,{status:next})}}>{STATUS.map(t=><option key={t}>{t}</option>)}</select><select aria-label={"Project for "+c.title} value={i.projectId} onChange={e=>patch(i.id,{projectId:e.target.value})}><option value="">No project</option>{workspace.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label={"Receipt reference for "+c.title} value={i.receipt} onChange={e=>patch(i.id,{receipt:e.target.value})} placeholder="External receipt ref (if any)"/><button className="fc-textbutton" onClick={()=>remove(i.callId)}>Remove</button></div>}):<Empty title="No saved opportunities" text="Discover funding and save calls to build this pipeline."/>}</>}
function Calendar({saved,save,mine,pipeline=[]}:{saved:Set<string>;save:(id:string)=>void;mine:boolean;pipeline?:PipelineItem[]}){const [year,setYear]=useState(2026),[month,setMonth]=useState(9),[scope,setScope]=useState("All");const visible=CALLS.filter(c=>c.year===year&&c.deadline.slice(5,7)===String(month+1).padStart(2,"0")&&(!mine||scope!=="Mine"||saved.has(c.id))).sort((a,b)=>a.deadline.localeCompare(b.deadline));const months=Array.from({length:12},(_,i)=>new Date(Date.UTC(year,i,1)).toLocaleString("en-GB",{month:"short",timeZone:"UTC"}));function changeMonth(direction:number){let y=year,m=month+direction;if(m<0){m=11;y--}if(m>11){m=0;y++}setYear(y);setMonth(m)}return <><Section label="ANNUAL FUNDING INTELLIGENCE" title="Your year wheel" aside={mine&&<select aria-label="Calendar scope" value={scope} onChange={e=>setScope(e.target.value)}><option>All</option><option>Mine</option></select>}/><p className="fc-muted">Browse all illustrative annual rounds. The real product will separate verified deadlines, expected re-opening dates and your internal work milestones.</p><div className="fc-calendar-controls"><button aria-label="Previous month" onClick={()=>changeMonth(-1)}>←</button><strong><MonthLabel value={year+"-"+String(month+1).padStart(2,"0")}/></strong><button aria-label="Next month" onClick={()=>changeMonth(1)}>→</button><select aria-label="Select year" value={year} onChange={e=>setYear(Number(e.target.value))}>{[2026,2027,2028].map(y=><option key={y}>{y}</option>)}</select></div><div className="fc-month-strip">{months.map((m,i)=>{const count=CALLS.filter(c=>c.deadline.startsWith(String(year)+"-"+String(i+1).padStart(2,"0"))).length;return <button key={m} className={i===month?"current":""} onClick={()=>setMonth(i)}><strong>{m}</strong><span>{count?count+" calls":"—"}</span><i style={{height:Math.max(3,count*8)+"px"}}/></button>})}</div><div className="fc-resultshead"><strong>{months[month]} {year}</strong><span>{visible.length} demo funding deadlines · different currencies are not summed</span></div>{visible.length?visible.map(c=><OpportunityRow key={c.id} call={c} saved={saved.has(c.id)} onSave={save}/>):<Empty title="No calls in this month" text="Change month or switch the calendar filter."/>}{mine&&pipeline.length>0&&<p className="fc-muted fc-small">Saved opportunities can be linked to projects in My CRM. No reminders are scheduled by this demo.</p>}</>}
function Projects({workspace,onSave,onDelete}:{workspace:{pipeline:PipelineItem[];projects:Project[]};onSave:(p:Project)=>void;onDelete:(id:string)=>void}){const [name,setName]=useState(""),[theme,setTheme]=useState<Theme>("Climate"),[description,setDescription]=useState(""),[region,setRegion]=useState("Worldwide");const add=(e:FormEvent)=>{e.preventDefault();if(!name.trim())return;onSave({id:"proj-"+crypto.randomUUID(),name:name.trim(),theme,description:description.trim(),region,fundingNeed:""});setName("");setDescription("")};return <><Section label="YOUR OWN FUNDING PROJECTS" title="My projects"/><div className="fc-project-layout"><div><div className="fc-project-list">{workspace.projects.map(p=><div className="fc-project-card" key={p.id}><Nav to={"/my/projects/"+p.id}><strong>{p.name} ↗</strong><span>{p.description||"No description"}</span><small>{p.theme} · {p.region} · {workspace.pipeline.filter(i=>i.projectId===p.id).length} linked opportunities</small></Nav><button className="fc-textbutton" onClick={()=>{if(window.confirm("Delete this demo project? Linked opportunities will remain in your pipeline."))onDelete(p.id)}}>Delete</button></div>)}</div>{!workspace.projects.length&&<Empty title="Create your first project" text="Project pages collect every linked funding opportunity."/>}</div><form onSubmit={add} className="fc-form-panel"><h3>New project</h3><label>Project name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="E.g. Oslofjord restoration"/></label><label>Topic<select value={theme} onChange={e=>setTheme(e.target.value as Theme)}>{THEMES.map(t=><option key={t}>{t}</option>)}</select></label><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}>{REGIONS.map(t=><option key={t}>{t}</option>)}</select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What will this project achieve?" rows={3}/></label><button className="fc-btn fc-btn-primary" type="submit">＋ Create demo project</button><small className="fc-muted">Stored on this device only, not in BRAIN.</small></form></div></>}
function ProjectDetail({id,workspace,patch}:{id:string;workspace:{projects:Project[];pipeline:PipelineItem[]};patch:(id:string,p:Partial<PipelineItem>)=>void}){const p=workspace.projects.find(x=>x.id===id);if(!p)return <Empty title="Project not found" text="Create a project in My projects."/>;const items=workspace.pipeline.filter(i=>i.projectId===id);return <><Nav className="fc-back" to="/my/projects"><Icon name="back"/> My projects</Nav><Section label={p.theme+" · "+p.region} title={p.name}/><p className="fc-lead">{p.description||"No description yet."}</p><div className="fc-resultshead"><strong>Linked funding opportunities</strong><span>{items.length} calls</span></div>{items.map(i=>{const c=CALLS.find(c=>c.id===i.callId)!;return <article key={i.id} className="fc-opportunity"><div className="fc-opp-body"><Nav className="fc-opp-title" to={"/opportunities/"+c.id}>{c.title}</Nav><p>{prettyDate(c.deadline)} · {amount(c)}</p></div><button onClick={()=>patch(i.id,{projectId:""})} className="fc-textbutton">Unlink</button></article>})}{!items.length&&<Empty title="Nothing linked yet" text="Visit My CRM and assign a saved opportunity to this project."/>}</>}
function Applications({pipeline}:{pipeline:PipelineItem[]}){return <><Section label="APPLICATION CASES · DEMO" title="Applications & decisions"/><p className="fc-muted">A saved opportunity is not an application. Formal submissions require external receipts and explicit human authorisation.</p><div className="fc-resultshead"><strong>Recorded stages</strong><span>No provider integrations or payments</span></div>{pipeline.filter(i=>["Submitted","Awaiting decision","Awarded","Rejected"].includes(i.status)).map(i=>{const c=CALLS.find(x=>x.id===i.callId);return c?<div key={i.id} className="fc-application-row"><Nav to={"/opportunities/"+c.id}>{c.title}</Nav><Tag>{i.status}</Tag><span>{i.receipt||"No external receipt recorded"}</span></div>:null})}{!pipeline.some(i=>["Submitted","Awaiting decision","Awarded","Rejected"].includes(i.status))&&<Empty title="No application cases recorded" text="Applications and receipt evidence will be preserved here once integrated with the canonical Capital Control Tower."/>}</>}
function Graph({workspace}:{workspace:{projects:Project[];pipeline:PipelineItem[]}}){const [selected,setSelected]=useState<string>("");const nodes:({id:string;label:string;kind:string;href:string})[]=[],edges:[string,string][]=[];workspace.projects.forEach(p=>nodes.push({id:p.id,label:p.name,kind:"Project",href:"/my/projects/"+p.id}));workspace.pipeline.forEach(i=>{const c=CALLS.find(x=>x.id===i.callId);if(!c)return;const pr=programmeFor(c),f=funderFor(c);[{id:c.id,label:c.title,kind:"Opportunity",href:"/opportunities/"+c.id},{id:pr.id,label:pr.name,kind:"Programme",href:"/programmes/"+pr.id},{id:f.id,label:f.name,kind:"Funder",href:"/funders/"+f.slug}].forEach(n=>{if(!nodes.some(x=>x.id===n.id))nodes.push(n)});edges.push([i.projectId||"workspace",c.id],[c.id,pr.id],[pr.id,f.id])});if(workspace.pipeline.some(i=>!i.projectId))nodes.push({id:"workspace",label:"Unassigned pipeline",kind:"Workspace",href:"/my/pipeline"});const chosen=nodes.find(n=>n.id===selected);const width=760,height=470;return <><Section label="ECONOMIC ORGANISATION MAP" title="Relationship graph"/><p className="fc-muted">Graph is an optional view of your saved projects and financing relationships, not another database.</p>{nodes.length?<><div className="fc-graph"><svg viewBox={"0 0 "+width+" "+height} role="img" aria-label="Funding actors, programmes, opportunities and projects graph">{edges.map(([a,b],i)=>{const ia=nodes.findIndex(n=>n.id===a),ib=nodes.findIndex(n=>n.id===b);if(ia<0||ib<0)return null;const point=(index:number)=>{const angle=(index/nodes.length)*Math.PI*2;return {x:width/2+260*Math.cos(angle),y:height/2+175*Math.sin(angle)}};const x=point(ia),y=point(ib);return <line key={i} x1={x.x} y1={x.y} x2={y.x} y2={y.y} stroke="#bbc0c9" strokeWidth="1.5"/>})}{nodes.map((n,i)=>{const angle=i/nodes.length*Math.PI*2,x=width/2+260*Math.cos(angle),y=height/2+175*Math.sin(angle);return <g key={n.id} onClick={()=>setSelected(n.id)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")setSelected(n.id)}} style={{cursor:"pointer"}}><circle cx={x} cy={y} r={n.kind==="Funder"?30:23} fill={selected===n.id?"#2e2eff":n.kind==="Project"?"#161a21":"#fff"} stroke={selected===n.id?"#2e2eff":"#abb3c2"} strokeWidth="2"/><text x={x} y={y+4} fontSize="9" fill={selected===n.id||n.kind==="Project"?"white":"#151515"} textAnchor="middle">{n.kind.slice(0,4)}</text><text x={x} y={y+45} fill="#262b37" textAnchor="middle" fontSize="10">{n.label.slice(0,27)}</text></g>})}</svg></div>{chosen&&<div className="fc-graph-inspector"><strong>{chosen.label}</strong><Tag>{chosen.kind}</Tag><Nav to={chosen.href}>Open profile →</Nav></div>}<div className="fc-graph-list">{nodes.map(n=><Nav to={n.href} key={n.id}>{n.kind} — {n.label} ↗</Nav>)}</div></>:<Empty title="Your graph is empty" text="Save funding opportunities and connect them to projects to create relationships."/>}</>}
function Settings({state,changeWorkspace,reset,session,signIn}:{state:FinanceState;changeWorkspace:(v:"4planet"|"personal")=>void;reset:()=>void;session:FourPlanetSession|null;signIn:()=>void}){return <><Section label="USER CONTROL" title="Workspace settings"/><div className="fc-settings-panel"><h3>Active workspace</h3><select value={state.active} onChange={e=>changeWorkspace(e.target.value as "4planet"|"personal")}><option value="4planet">4PLANET (demo only)</option><option value="personal">Personal (demo only)</option></select><p>This switch isolates two fictional example workspaces in local browser storage. It does not establish production multi-tenancy.</p><hr/><h3>4PLANET ID</h3><p>{session?"Identity session detected: "+(session.user.email||"signed in"):"No verified identity session detected."} The existing 4PLANET ID adapter is used; durable private workspace storage and RLS are not connected.</p>{!session&&<button className="fc-btn" onClick={signIn}>Sign in through 4PLANET ID</button>}<hr/><h3>Reset demonstration</h3><p>Remove all device-local demo projects and saved opportunity decisions.</p><button className="fc-btn" onClick={()=>{if(window.confirm("Erase all finance demonstration data stored on this device?"))reset()}}>Clear demonstration data</button></div></>}
