begin;
drop table if exists public.product_contexts cascade;
drop table if exists public.impacts cascade;
drop table if exists public.outcomes cascade;
drop table if exists public.deliveries cascade;
drop table if exists public.contributions cascade;
drop table if exists public.impact_unit_definitions cascade;
drop table if exists public.interpretations cascade;
drop table if exists public.signals cascade;
drop table if exists public.taxon_observations cascade;
drop trigger if exists source_records_immutable on public.source_records;
drop table if exists public.source_records cascade;
drop function if exists public.reject_source_record_mutation();
commit;
