import type { LabProject } from "./labsFreshProjection";

export type ProjectContractProjection = {
  source: string;
  goalContractStatus: string;
  theory: string;
  scopeIn: string;
  outLater: string;
  operatingModel: string;
  decisionRights: string;
  capitalRouting: string;
  proofRisk: string;
  strategicRole: string;
};

const SOURCE = "Founder Control 11_PROJECT PACKS · public-safe snapshot read 21 Aug 2026";

function pack(input: Omit<ProjectContractProjection, "source">): ProjectContractProjection {
  return { source: SOURCE, ...input };
}

// Read-only projection of stable Project Pack fields. Current state, current gate,
// money state and code/deployment state are intentionally NOT copied here because
// those can move faster than the Project Pack. LABS reads those through the
// current-control/WBS adapters instead. BRAIN / Founder Control remains authority.
const byProjectId: Record<string, ProjectContractProjection> = {
  "SYS-P00-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Shared reusable infrastructure creates leverage across all Missions.",
    scopeIn: "Shared build and orchestration across product, truth, organisation, capital and proof.",
    outLater: "Do not absorb all detailed work into one opaque mega-project.",
    operatingModel: "AXE programme control + bounded specialist agents + Odin authority.",
    decisionRights: "AI executes safe internals; Founder retains DECIDE / JUDGE / RELEASE and irreversible authority.",
    capitalRouting: "Unrestricted/catalytic founding capital + paid pilots + public/research funding + partners.",
    proofRisk: "Proof must roll up from child Projects. Main risks: P00 opacity, double counting and maturity inflation.",
    strategicRole: "SC1–SC7 shared foundation · Truth · Incentive · Federation · Complete Loop · Transferability · AI-first.",
  }),
  "SYS-P00-STRAT": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Better strategic input + common project grammar + evidence loops increase speed, comparability and learning without management theatre.",
    scopeIn: "Goal v4, capability mapping, Project/WBS propagation, economics, dependencies, KPI/roadmap and runtime learning.",
    outLater: "No new master system, no seven departments and no deletion of superseded strategy lineage.",
    operatingModel: "AXE lead with bounded specialist agents; Founder enters only for genuine Canon or strategic exceptions.",
    decisionRights: "AI executes safe work under v4; Founder retains Canon and irreversible authority.",
    capitalRouting: "P00 internal allocation; catalytic systems-change / founding capital where appropriate.",
    proofRisk: "Proof is clean recovery/readback, no orphan capability/mechanism, lower Founder burden and real outcome movement.",
    strategicRole: "Strategy authority across SC1–SC7 · all v4 doctrines · no-orphan · no half-migration.",
  }),
  "SYS-P00-PRODUCT": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "One coherent product proof multiplies user learning, capital and trust.",
    scopeIn: "ONE INTERFACE candidate; ATLAS / SPECIES / LIVING SYSTEMS / IMPACT coherence; release, source, rights, mobile and runtime gates.",
    outLater: "No ground-up rewrite and no deferred product expansion disguised as release work.",
    operatingModel: "AXE/Product executes and audits bounded internal work; Founder visually judges the exact accepted artifact.",
    decisionRights: "AI owns reversible build/QA. Founder owns final visual acceptance and production release authority.",
    capitalRouting: "Founding Build, Proof Pilot, paid pilot and innovation/research funding.",
    proofRisk: "Exact remote artifact + source/rights/mobile/runtime proof. Risks: provenance, runtime defects, rights and false maturity.",
    strategicRole: "SC1 Living Planet Intelligence · SC2/SC7 support · Truth · Minimum Complete Loop · AI-first.",
  }),
  "SYS-P00-TRUTH": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Federation of the strongest sources beats unnecessary centralisation; truth quality compounds across Projects.",
    scopeIn: "Science/evidence model, source federation, claims, provenance, Gold source closure and external challenge interfaces.",
    outLater: "No terabyte raw-data warehouse in Drive and no parallel science database.",
    operatingModel: "AXE truth control + researchers/reviewers + federated source owners.",
    decisionRights: "AI executes source work; experts challenge; Founder enters for release/sensitive rights decisions.",
    capitalRouting: "Research/innovation grants, AI/open-data philanthropy and Founding Build where fit.",
    proofRisk: "Proof = source provenance, readback and reviewer correction. Risks: licence, stale data, false consensus and IP/data custody.",
    strategicRole: "SC1 primary · SC5/SC7 support · Truth/Trust · Federation · Controlled Depth · Transferability.",
  }),
  "SYS-P00-PROOF": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "External challenge increases truth and conversion value; proof must precede scale.",
    scopeIn: "Observed user sessions, scientific review packets, institutional challenge and correction writeback.",
    outLater: "No adviser/validation/public attribution without evidence or permission.",
    operatingModel: "AXE recruits and coordinates asynchronously; users/researchers supply evidence; no Founder meeting default.",
    decisionRights: "AI prepares/coordinates under current authority; Founder only for unusual high-risk or irreversible exceptions.",
    capitalRouting: "Proof Pilot, research collaboration, foundations and explicitly evidenced in-kind support.",
    proofRisk: "Proof = observed sessions/reviews + corrections. Risks: selection bias, social desirability, overclaim and COI; review is not endorsement.",
    strategicRole: "SC1 + SC2 proof bridge · Minimum Complete Loop · Truth · scientific challenge · participant evidence.",
  }),
  "SYS-P00-CAPITAL": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Capital is a routing/matching problem; projectised value propositions improve fit and conversion.",
    scopeIn: "Project Capital Plans, First Money, applications, conversion, data room and capital-learning/collision controls.",
    outLater: "No vanity inventory expansion and no actor-first forced asks.",
    operatingModel: "AXE Capital owns qualification, writing, routing and authorised normal-risk execution; external actors decide funding.",
    decisionRights: "AI owns reversible capital work within standing authority; Founder/professional gates binding, Norway/high-risk, debt/equity, IP and material commitments.",
    capitalRouting: "Philanthropy, grants, paid pilots, procurement, research, sponsorship and investment only where genuine fit exists.",
    proofRisk: "Proof = award/contract/cash, never pipeline. Risks: forced fit, legal/applicant issues, IP disclosure and actor collision.",
    strategicRole: "SC4 Capital Engine · SC7/SC5/SC3 support · Incentive Design · project-first routing · Truth · async-first.",
  }),
  "SYS-P00-COMPANY": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Reusable trust infrastructure lowers friction across every capital and Project route.",
    scopeIn: "Entity/applicant truth, ownership/signing, IP, accounts/tax/VAT, privacy/security, contracts and minimal data room.",
    outLater: "No unsupported legal/accounting conclusions; professional gates remain explicit.",
    operatingModel: "AXE prepares; Founder supplies genuinely required founder-held facts; lawyer/accountant/security reviewers decide bounded professional questions.",
    decisionRights: "Professionals own legal/accounting conclusions; Founder decides entity/control; AI prepares and reconciles evidence.",
    capitalRouting: "Normally unrestricted/Founding capital; eligible project grants may cover bounded admin/legal work.",
    proofRisk: "Proof = official/current records + professional conclusions. Risks: tax/VAT/IP/privacy and false company claims.",
    strategicRole: "Shared enabler across SC1–SC7 · Truth · legal/IP boundaries · reusable trust infrastructure.",
  }),
  "SYS-P00-REL": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Actor-specific legitimate value + async-first lowers friction and Founder load.",
    scopeIn: "Capital, Field, R&I, Media, Ambassador and Corporate relationship processes on one actor spine.",
    outLater: "No unqualified mass outreach; relationship meanings remain separate; meetings are not default.",
    operatingModel: "AXE owns async dialogue; Founder HUMAN only where direct interaction materially improves expected outcome.",
    decisionRights: "AI handles qualified low-risk work within standing rules; Founder retains geography/risk/meeting and binding exceptions.",
    capitalRouting: "Relationship engine is P00 infrastructure; it converts to pilots, Founding partners, support and revenue rather than owning a separate ask.",
    proofRisk: "Proof = meaningful replies, proposals, closes and cycle-time learning. Risks: spam, collision, deliverability and status inflation.",
    strategicRole: "SC7 Collaboration/Coordination · SC2/SC4/SC5/SC3 support · Incentive Design · async-first · relationship semantics.",
  }),
  "SYS-P00-BRAND": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Proof → Story → Trust can amplify people and capital when claims remain truthful.",
    scopeIn: "Brand implementation, Founder story, Media, channels, thesis assets and proof-led content.",
    outLater: "No vanity content factory and no broad publication before proof/rights gates.",
    operatingModel: "Brand/Media AI + Founder judgement; external creators enter later where useful.",
    decisionRights: "AI prepares; Founder JUDGE/RELEASES public materials.",
    capitalRouting: "Brand partners/sponsors, philanthropy, culture grants and Founding capital; culture Mission budgets remain separate.",
    proofRisk: "Proof = comprehension, trust and qualified inbound. Risks: hype, rights, Founder overexposure and fame replacing mission.",
    strategicRole: "SC6 4CULTURE · SC2/SC4 support · Truth · meaning capacity · Megamomentum · proof-before-story.",
  }),
  "SYS-P00-SOLUTIONS": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "4PLANET creates more leverage by finding and strengthening strong existing solutions than by reflexively building its own intervention.",
    scopeIn: "Existing 1,000-solution spine, representative deepening, effectiveness/implementation evidence, actor/capital/resource links and bounded acceleration cases.",
    outLater: "No parallel solution database, no mass-expansion vanity and no assumption that listed/innovative means effective.",
    operatingModel: "AXE PSI/Truth + Actor/Capital/Relations; external researchers/practitioners/solution owners provide challenge and evidence.",
    decisionRights: "AI owns internal research/mapping/case preparation; Founder only strategic exceptions or binding/high-risk commitments.",
    capitalRouting: "Founding Build, research/innovation/public-interest funding and project-specific philanthropy/procurement/pilots where a bounded acceleration object fits.",
    proofRisk: "Proof = effectiveness/implementation evidence + real resource/match intervention + improved external capacity. Risks: COI, stale evidence, attribution and double counting.",
    strategicRole: "SC5 Solution Engine · SC1/SC4/SC7/SC3 support · Federation · Controlled Depth · BUILD only verified gap.",
  }),
  "SYS-P00-LABS": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Separating production authority from development visibility increases creativity, testing, AI throughput and learning while reducing release/brand risk and fork debt.",
    scopeIn: "LABS Overview, idea intake/triage, bounded prototype factory, project status/control views, repeat-upgrade loop, selected safe Founder/public projections and promotion/funding/spin-out routing.",
    outLater: "No second canonical codebase; no duplicate roadmap/task database; no public private-Founder truth; no uncontrolled production writes; no automatic ownership/funding promise.",
    operatingModel: "AXE orchestrates; engineering/product/design agents work on bounded branches/previews; source owners feed truth; Founder supplies ideas/taste and JUDGE where high-value.",
    decisionRights: "AI owns capture, triage, projectisation, reversible prototyping, QA and documentation. Founder retains public production and binding finance/legal/IP/entity gates.",
    capitalRouting: "If a LAB becomes fundable it routes through the existing Project Capital Plan / Capital Engine. Non-4PLANET ventures require explicit ownership/entity route first.",
    proofRisk: "Proof = repeatable preview path, no core divergence, useful Founder testing, propagated learning, low-cost kill path and exact promotion. Risks: distraction, novelty bias, brand leakage, fork drift, private-data exposure and vanity prototypes.",
    strategicRole: "SC1/LT2 with SC2/SC4/SC5/SC6/LT5 support · Truth · Federation · Founder Leverage · Transferability · bounded experimentation.",
  }),
  "OCE-WH4LES-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "A compelling species can prove the Living Planet Intelligence relationship model and create reusable product/science/story proof.",
    scopeIn: "Orca/whale product proof, science review, rights-safe assets and a protection/partner pathway.",
    outLater: "No claim that storytelling or intelligence alone protects whales; no sensitive-location exposure.",
    operatingModel: "AXE + Product + R&I; external marine scientists/operators; Founder only rights/judgement/release.",
    decisionRights: "AI prepares/audits; Founder JUDGE/RELEASES; external experts/partners supply missing evidence.",
    capitalRouting: "Marine philanthropy, documentary/culture funding, research, Mission Pilot Funder and Founding Partner.",
    proofRisk: "Proof = source/provenance + expert challenge + real action route. Risks: rights, sensitive ecology and story→impact inflation.",
    strategicRole: "SC1 primary · SC3/SC5/SC6 support · Truth · Federation · Complete Loop · sensitive ecology · proof-before-story.",
  }),
  "OCE-COR4L-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Existing global reef data plus specialist operators can be federated rather than rebuilt.",
    scopeIn: "Reference geography, heat-stress intelligence, resilience solution, operator/economics/reporting.",
    outLater: "No broad coral restoration platform now and no outcome claim before delivery.",
    operatingModel: "AXE prepares; marine science/operator/local stakeholders own specialised and delivery work.",
    decisionRights: "Founder only project activation/partner release; specialists own field/science reality.",
    capitalRouting: "Ocean/climate philanthropy, corporate reef sponsor, research and Mission Pilot Funder.",
    proofRisk: "Risks: local legitimacy, permits, attribution, restoration failure and monitoring burden.",
    strategicRole: "SC3 primary · SC1/SC5/SC4 support · Federation · absolute outcome · claims separation.",
  }),
  "OCE-PL4STIC-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Partner-led plastic delivery may be a comparatively fast real-world action proof if claims and economics are tightly controlled.",
    scopeIn: "Norway-first operator route, prevention/removal distinction and contract/evidence/payment chain.",
    outLater: "No global plastic marketplace and no mixed prevented/removed unit.",
    operatingModel: "AXE Impact + qualified field operator; external operator owns physical work.",
    decisionRights: "AI prepares; Founder DECIDE/RELEASES partner/funding model; operator owns delivery evidence.",
    capitalRouting: "Mission Pilot Funder, brand sponsor, ocean/plastic philanthropy, corporate sustainability and local/public funding.",
    proofRisk: "Risks: PL4STIC/CLE4N identity conflict, double counting, waste custody, claims and economics.",
    strategicRole: "SC3 primary · SC4/SC5/SC7 support · Truth · Incentive · Federation · no double count · Complete Loop.",
  }),
  "OCE-REWILD-M-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "4PLANET should coordinate and intelligently fund strong operators rather than become a field-restoration organisation.",
    scopeIn: "Science/gap review, geography, operator, permits, economics and monitoring.",
    outLater: "No own field organisation and no generic restoration unit before operator reality.",
    operatingModel: "AXE + external operator/scientist; partner/professional authorities own permits/delivery.",
    decisionRights: "AI prepares; Founder activation/release; external operator owns field execution.",
    capitalRouting: "Marine/nature philanthropy, public restoration funds and corporate Mission sponsor.",
    proofRisk: "Risks: permits, site tenure, ecological uncertainty, monitoring and local legitimacy.",
    strategicRole: "SC3 primary · SC1/SC5/SC7 support · Federation · operator/science complementarity · absolute outcomes.",
  }),
  "EAR-CLIM4TE-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Decision Intelligence is credible when tied to a real decision owner and observed decision rather than a generic dashboard.",
    scopeIn: "One decision class, federated/live sources, decision workflow and evaluation.",
    outLater: "No broad climate platform and no automated prescription now.",
    operatingModel: "AXE/Product + domain expert + external decision owner.",
    decisionRights: "AI prepares; Founder releases external pilot; expert/decision owner validates usefulness.",
    capitalRouting: "Paid Proof Pilot, public innovation/procurement, climate/nature research and corporate pilot.",
    proofRisk: "Risks: weak decision owner, causality overclaim, data timeliness and generic-tool trap.",
    strategicRole: "SC1 primary · SC7/SC5 support · Multi-lever · Truth · Incentive · decision evidence.",
  }),
  "EAR-AM4ZONIA-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Global coordination is legitimate only when local/Indigenous rights and authority are real, not symbolic.",
    scopeIn: "Protocol, representation, consent, evidence/rights and bounded pilot.",
    outLater: "No public Impact Unit or extractive storytelling; no remote design without local authority.",
    operatingModel: "Local/Indigenous actor must own relevant authority; AXE supports; Founder may release only after legitimacy exists.",
    decisionRights: "External authorised consent is required; Founder cannot substitute for local authority.",
    capitalRouting: "Indigenous stewardship/nature philanthropy and appropriate public/international project funds.",
    proofRisk: "Risks: legitimacy, FPIC/consent, representation, safety, land/rights and extractive funding.",
    strategicRole: "SC7 primary · SC1/SC3/SC2 support · Federation · FPIC · legitimacy · distinct relationship meaning.",
  }),
  "EAR-SPECIES-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Species are intuitive entry points; traversable progressive depth can make species/place/ecosystem/relationship objects useful without flattening truth.",
    scopeIn: "Jaguar + Orca Gold references, Species Card/profile grammar, ATLAS Window, reported observations, ecosystem links, dependency traversal and rights-safe immersive media.",
    outLater: "No mass catalogue before reusable grammar/proof; no observations presented as range/population/live tracking; no unsupported ecosystem/solution claims.",
    operatingModel: "Product agents + AXE truth; external experts/users; Founder final judgement.",
    decisionRights: "AI build/audit; Founder JUDGE release; science review external.",
    capitalRouting: "Founding Build, Proof Pilot, biodiversity/research/open-data funding and institutional pilots.",
    proofRisk: "Proof = exact identities, sourced facts, clear observation/range semantics, performant media, traversable nodes, continuity and external correction. Risks: rights, geoprivacy, false range inference, graph complexity and performance.",
    strategicRole: "SC1 primary · SC2/SC5/SC6/SC7 support · Truth · Federation · Controlled Depth · progressive disclosure · Minimum Complete Loop.",
  }),
  "EAR-REWILD-L-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Use strong existing operators and define units from field reality rather than marketing-first Impact units.",
    scopeIn: "Geography/operator, tenure, standard, economics, monitoring and capital.",
    outLater: "No generic 1m² claim without site/operator methodology.",
    operatingModel: "External operator/landholder + AXE; partner/professional authority required.",
    decisionRights: "AI prepares; Founder releases; external operator owns delivery.",
    capitalRouting: "Restoration/nature philanthropy, corporate Mission sponsor and public funds.",
    proofRisk: "Risks: additionality, permanence, tenure, monitoring and double counting.",
    strategicRole: "SC3 primary · SC5/SC4/SC7 support · Federation · operator-first · absolute outcome · evidence-backed unit.",
  }),
  "SAP-FOOD-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "If better choices are truthful, understandable and create legitimate user value, decision-useful intelligence can change understanding/choice while producing reusable problem→solution→actor→capital learning.",
    scopeIn: "PERSON × FOOD × NORWAY v1; one ordinary protein choice; 4–6 audited alternatives; price, bounded nutrient attributes, convenience and defensible ecological trade-offs; user/expert test; one action/resource route; transfer adapter.",
    outLater: "No total-food database, medical advice, universal best food, single green score, global transfer claim or scale build before first reference evidence.",
    operatingModel: "AXE Product/Truth owns evidence contract and integration; Product Gate Watch owns implementation; users and food/health/ecology reviewers supply challenge.",
    decisionRights: "Founder scope is closed; AI executes bounded build/test work; Founder returns only for genuine public health/science, binding partner/capital, release or scale gates.",
    capitalRouting: "Project Capital Plan derives only from verified bounded v1 need/timing/restrictions after bottom-up costing.",
    proofRisk: "Risks: health overclaim, false green-score aggregation, price/data volatility, category heterogeneity and transfer overclaim. UNKNOWN remains visible and dimensions remain separate.",
    strategicRole: "SC1 primary · SC5/SC2/SC7/SC4 support · Incentive · Multi-lever · Complete Loop · Transferability · Truth.",
  }),
  "SAP-EN3RGY-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Energy is a repeatable human/system need, but decision context and regulation vary strongly.",
    scopeIn: "One decision class, data, policy, economics and owner/user proof.",
    outLater: "No broad energy platform now.",
    operatingModel: "AXE + energy expert + real decision owner.",
    decisionRights: "Founder activates later; AI may prepare bounded evidence only.",
    capitalRouting: "Energy/public innovation/procurement/research and corporate pilot routes.",
    proofRisk: "Risks: regulation, system complexity, privacy/security and EN3RGY/EN4RGY identity conflict.",
    strategicRole: "SC1 primary · SC7/SC5 support · Multi-lever · Decision Intelligence · Incentive · Truth.",
  }),
  "SAP-CIRCULAR-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Cities repeat many system needs, making modular reference cases plausible with local adapters.",
    scopeIn: "One material flow, city actors, solution map, bounded intervention and measured proof.",
    outLater: "No whole-city digital twin or giant collaboration platform now.",
    operatingModel: "AXE + city/municipal/data actors; legitimate external participation required.",
    decisionRights: "AI prepares; Founder only release/high-value human moment.",
    capitalRouting: "Municipal procurement/innovation, circular-economy grants, corporate consortium and philanthropy.",
    proofRisk: "Risks: convening without action, data access, unclear owner and process overhead.",
    strategicRole: "SC7 primary · SC1/SC3/SC5 support · Incentive · shared intelligence · legitimate coordination · Complete Loop.",
  }),
  "SAP-F4SHION-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Consumer categories can become modular S4PIENS cases if value chains and trade-offs are explicit.",
    scopeIn: "One material/category, value chain, impact/health trade-offs, alternatives and buyer/user test.",
    outLater: "No universal green score and no traceability=good claim.",
    operatingModel: "AXE + fashion/material experts + a real brand/platform/data partner when activated.",
    decisionRights: "Founder activates later; AI prepares only bounded evidence/method work.",
    capitalRouting: "Fashion/circular grants, brand/retailer pilot, research and philanthropy.",
    proofRisk: "Risks: complex LCAs, greenwashing, incomplete supply-chain data and commercial conflicts.",
    strategicRole: "SC1 primary · SC5/SC7/SC2 support · Choice/Incentive · Truth · absolute-pressure · actor/solution intelligence.",
  }),
  "CUL-M4GAZINE-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Story can scale understanding/trust, but only when downstream of truth and proof.",
    scopeIn: "Editorial charter, thesis/science stories, proof-led issues and rights/source controls.",
    outLater: "No content factory or publication schedule detached from actual evidence.",
    operatingModel: "AXE editorial + contributors; Founder editor/judgement.",
    decisionRights: "AI prepares; Founder public JUDGE/RELEASES.",
    capitalRouting: "Editorial/culture grants, philanthropy and brand support where independence is preserved.",
    proofRisk: "Risks: vanity publishing, rights, unsupported claims and distraction from proof.",
    strategicRole: "SC6 primary · SC2/SC1 support · Truth · meaning · participant multiplication · Megamomentum · rights.",
  }),
  "CUL-4FILM-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Culture/story can amplify care and participation but cannot substitute for product or ecological proof.",
    scopeIn: "Flagship film/application, rights/access, producer, production, distribution and learning.",
    outLater: "No broad film-studio build now.",
    operatingModel: "External producer/rights holders + AXE; Founder creative/founder role.",
    decisionRights: "Founder final creative/release; professional rights/contracts.",
    capitalRouting: "Film/culture funds, philanthropy and mission-aligned distribution/brand support.",
    proofRisk: "Risks: rights, production burden, story overclaim and Founder time.",
    strategicRole: "SC6 primary · SC2/SC1 support · Truth · meaning · rights · Megamomentum · proof-before-story.",
  }),
  "CUL-4RT-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Culture can become a capital/distribution mechanism if economics and ecological claims stay separate and transparent.",
    scopeIn: "Artist model, rights, production economics, linked Impact route and release proof.",
    outLater: "No environmental claim before a valid underlying delivery route.",
    operatingModel: "Artist/producer + AXE; external operator owns environmental delivery.",
    decisionRights: "Founder/artist own rights/release; external operator owns ecological delivery evidence.",
    capitalRouting: "Art/culture grants, sales, brand/collector support and linked Mission sponsor.",
    proofRisk: "Risks: rights, VAT/tax, production economics and impact-claim coupling.",
    strategicRole: "SC6 primary · SC4/SC3/SC2 support · Incentive · meaning/value · transparent economics · verified Impact · rights.",
  }),
  "CUL-4PLAY-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "Existing cultural networks may provide distribution/identity scale when real value and incentives align.",
    scopeIn: "One future bounded activation, artist value proposition, rights, distribution and participation measurement.",
    outLater: "No music organisation/studio build now.",
    operatingModel: "Artists/producer + AXE; Founder relationship/creative only when valuable.",
    decisionRights: "Founder release later; AI only prepares bounded option evidence while on HOLD.",
    capitalRouting: "Culture/music grants, brand/cultural partners and philanthropy.",
    proofRisk: "Risks: distraction, high production burden, vanity attention and rights.",
    strategicRole: "SC6 primary · SC2/SC7 support · Meaning · participant multiplication · Incentive · rights · collaboration.",
  }),
  "SYS-P00-PMAP": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "A shared scientific/knowledge world model beneath modular Missions improves reuse, truth consistency and problem→solution coordination.",
    scopeIn: "Planetary ontology, ecosystem hierarchy, pressures/drivers, human-system links, problem graph, solution/actor/capital relationships, source interfaces and recovery contract.",
    outLater: "No exhaustive world database, raw-data warehouse, forced Mission renaming or public completeness claim.",
    operatingModel: "AXE Truth/BRAIN leads; source owners and domain authorities are federated; external scientific challenge later.",
    decisionRights: "AI may execute bounded internal modelling/research; Founder retains strategic/Canon/Mission-identity authority.",
    capitalRouting: "Founding/unrestricted and possible research/open-data/digital-public-infrastructure routes later; not an activation gate.",
    proofRisk: "Risks: false completeness, ontological overreach, duplicate truth, stale/incompatible taxonomies and complexity without user value.",
    strategicRole: "SC1 primary · SC5/SC7 support · Federation · Controlled Depth · Truth · Transferability.",
  }),
  "SAP-SAPIENS-01": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "ATLAS-first spatial navigation + Homo sapiens identity + shared relation grammar can make human-system complexity legible without guilt/footprint scoring.",
    scopeIn: "Homo sapiens profile, DEPENDENCY/PRESSURE/RESPONSE grammar, FOOD chain, shared ATLAS/data handoffs, source/claim states and solution/Mission path.",
    outLater: "No fifth public product, second map/backend/truth model, personal footprint score, unsupported causality or exhaustive global economy model in V1.",
    operatingModel: "Founder = final product JUDGE; AXE = architecture/truth/programme control; Product Gate Watch = bounded implementation/QA/deploy.",
    decisionRights: "AI cannot self-accept Gold or production; public causal/actor/Impact claims require explicit evidence gates.",
    capitalRouting: "No active project-specific ask; any later plan derives from verified unique SAPIENS need, timing, restrictions and shared-vs-unique cost allocation.",
    proofRisk: "Risks: causal oversimplification, scale mismatch, misleading attribution, data rights, privacy/surveillance creep, overloaded interface and unsupported Impact claims.",
    strategicRole: "SC1 Living Planet Intelligence · source/truth + S4PIENS value-chain intelligence + cross-product transferability.",
  }),
  "SYS-P00-DPITCH": pack({
    goalContractStatus: "BASELINE COMPLETE",
    theory: "A coded proposition can outperform generic PDFs by combining personalisation, product proof, art direction and interaction at low marginal customisation cost.",
    scopeIn: "Template-driven recipient surface, actor intelligence, human-first narrative, incentive design, product proof, private URL controls and conversion learning.",
    outLater: "No separate app/repo/design system, public indexing, unpermitted partner logo/endorsement, fabricated ROI or broad outreach activation.",
    operatingModel: "AXE owns architecture/intelligence/incentive design; bounded Product/code agents refine the isolated line.",
    decisionRights: "AI builds/refines safely; Founder retains external release, production judgement, binding terms and unusual reputation/IP exceptions.",
    capitalRouting: "Conversion infrastructure for Brand Capital, paid pilots, founding partnerships and strategic collaboration; not a separate fundraising track.",
    proofRisk: "Risks: overdesign, false personalisation, invented upside, partner-brand misuse, accidental indexing, link leakage and confusing prototype with endorsement.",
    strategicRole: "SC7 primary · SC4/SC6/SC1/SC2 support · Incentive Design · Truth · human-first · Founder Leverage · one-core/multi-output.",
  }),
  "SYS-P00-ECONOMY": pack({
    goalContractStatus: "BASELINE COMPLETE / CODE V0.1 ACTIVE",
    theory: "A single event-based management-economics model with strict state separation and reconciliation can scale complexity without proportional Founder cognitive load.",
    scopeIn: "Project Economic Contracts, economic events, Project/Product roll-ups, management statements, source adapters, reconciliation, capital-to-cash linkage and shared/unallocated controls.",
    outLater: "No statutory-ledger replacement, payment execution, tax/accounting substitution, private ODIN data or hard-coded live finance truth.",
    operatingModel: "AXE/Project Lead owns architecture/reconciliation; finance/company sources remain authority; Product owns bounded UI; professionals validate statutory/tax treatment.",
    decisionRights: "AI executes safe schema/mapping/code/QA; Founder owns architecture override, production, payments/signing and material finance policy.",
    capitalRouting: "No standalone ask required; future build/data/professional need must derive from verified scope/timing. Pipeline never enters income/cash.",
    proofRisk: "Proof = deterministic roll-up, source traceability, correct states and 100% controlled-period reconciliation. Risks: parallel finance truth, false realtime, allocation error and private leakage.",
    strategicRole: "Shared enabler across SC1–SC7 / SC4 · Truth · no double counting · explicit financial states · reconciliation · Founder Leverage.",
  }),
  "SYS-SONIC-01": pack({
    goalContractStatus: "BASELINE COMPLETE / ACTIVE BUILD",
    theory: "If audio, acoustic intelligence and creator rights/economics share one canonical graph, 4PLANET can increase understanding, awe, participation and creator value without duplicating product stacks.",
    scopeIn: "AudioAsset, AcousticObservation, Soundscape, CreativeWork, CreatorPermissionGrant, premium player, Hear This Species/Place, Sound Atlas, Learn by Ear and bounded 4PLAY/creator proof.",
    outLater: "No streaming-platform rebuild, parallel truth database, broad creator marketplace, autoplay-heavy default or default rights transfer/exclusivity.",
    operatingModel: "AXE/Project Lead architecture; Product reusable code; Truth provenance; SPECIES/WH4LES/ATLAS/4PLAY consume shared objects; professional rights review where needed.",
    decisionRights: "AI executes reversible research/schema/code/QA; Founder JUDGE/RELEASES material creative direction and binding licence/IP/spend exceptions.",
    capitalRouting: "Possible later culture/arts innovation, bioacoustics/research, sponsorship-funded commissions, artist collaborations and licensing; no ask locked.",
    proofRisk: "Proof must preserve source/rights, composition-vs-recording ownership, observation semantics, accessibility and measurable creator outcomes.",
    strategicRole: "SC1 + SC6 primary · SC2/SC7/SC4 support · Truth · Rights · Federation · One Core · Incentive Design · participant multiplication.",
  }),
  "LAB-CREATOR-01": pack({
    goalContractStatus: "V0.3 TECHNICAL PASS / HUMAN VALIDATION NEXT",
    theory: "A holistic operating-intelligence layer can be more valuable than isolated creator tools because creators experience portfolio, demand, rights, money, obligations and life security as one system.",
    scopeIn: "Creator identity/work/rights graph, opportunity matching, demo economy, business autopilot, safety/runway view, path-to-independence model, SONIC/4CULTURE seam and private validation.",
    outLater: "No social network, full marketplace at birth, statutory ledger, tax/legal/insurance advice, livelihood guarantee, shared private data plane or public scale claim.",
    operatingModel: "AXE/Project Lead owns architecture/writeback; Product owns LABS code; ECONOMY contributes method; SONIC/4CULTURE provide first demand/rightsholder seam.",
    decisionRights: "AI executes reversible LABS research/code/QA; Founder JUDGES material direction/spinout; binding financial/legal/regulatory actions remain human/professional gates.",
    capitalRouting: "No capital ask at birth. Possible later SaaS/service, partner briefs, transaction/licensing economics, grants or spinout only after demand proof.",
    proofRisk: "Risks: mission sprawl, privacy, regulatory/accounting complexity, false livelihood/safety claims, supply-only marketplace failure, rights extraction and integration brittleness.",
    strategicRole: "SC2 + SC6 primary · SC4/SC5/SC7 support · Incentive Design · Minimum Complete Loop · One Core · Transferability · privacy · proof-before-scale.",
  }),
};

export function projectContractFor(project: LabProject): ProjectContractProjection | undefined {
  return project.projectId ? byProjectId[project.projectId] : undefined;
}

export const projectedProjectContractIds = Object.keys(byProjectId);
