import { withProjectMeta } from "./labsProjectMeta";
import type { LabProject } from "./labsFreshProjection";

export type ProjectControl = {
  classification: string;
  goalId?: string;
  mainGoal: string;
  success: string;
  phase: string;
  nextGate: string;
  economicGoal: string;
  economics: string;
  moneyTruth: string;
  source: string;
  links: NonNullable<LabProject["assets"]>;
  technical: string[];
};

export type GoldLabProject = LabProject & { control: ProjectControl };

type PartialControl = Partial<ProjectControl> & Pick<ProjectControl, "mainGoal" | "success">;
type MissionRow = { id: string; goal: string; success: string; phase: string; next: string; min: string; base: string; economic: string };

const AUTH = "Founder Control · Strategy & Goal Cascade v4.0 · 20 Aug 2026";
const P00_ECON = "Shared P00 component. No separate additive Project budget is approved; actual AI/tool/professional costs stay UNKNOWN until source evidence is mapped.";
const P00_MONEY = "No verified project-specific revenue, award, contract or cash. Shared costs are not silently allocated.";

const missionRows: Record<string, MissionRow> = {
  "4planet/oce4n/wh4les": { id:"OCE-WH4LES-01-G01", goal:"Use whales and Orca as a life-first, source-aware reference case connecting living-system intelligence to credible protection/action pathways.", success:"One source/rights-safe whale reference implementation is externally usable, scientifically challenged and connected to a credible protection/operator route.", phase:"ACTIVE GOLD / PROOF", next:"External scientific challenge + credible protection/operator proof.", min:"NOK 450k", base:"NOK 950k", economic:"Separate whale intelligence/protection economics from shared 4FILM assets; close proof before large delivery spend." },
  "4planet/oce4n/cor4l": { id:"OCE-COR4L-01-G01", goal:"Connect authoritative reef heat-stress intelligence to a credible partner-led resilience/restoration route.", success:"One geography + trusted data + qualified operator + bounded restoration/resilience proof path.", phase:"MONITOR", next:"Do not activate major spend until a credible geography/operator route exists.", min:"NOK 500k", base:"NOK 1.1m", economic:"Do not reserve the full planning envelope while the Project remains on monitor." },
  "4planet/oce4n/plastic-clean": { id:"OCE-PL4STIC-01-G01", goal:"Separate prevention from removal and create a traceable partner-executed plastic action route.", success:"Qualified operator + clear unit/economics/reporting chain + funded bounded delivery + no double counting.", phase:"FIRST DELIVERY PREP", next:"Get comparable operator method/economics/assurance evidence before any priced Impact claim.", min:"NOK 350k", base:"NOK 800k", economic:"Real pilot economics must come from qualified operators; prevention and removal remain separate." },
  "4planet/oce4n/rewild-marine": { id:"OCE-REWILD-M-01-G01", goal:"Create a source-aware, partner-led coastal habitat recovery pathway.", success:"One geography/operator/permit/economics/reporting chain supports a real funded habitat pilot.", phase:"DEVELOP NEXT", next:"Qualify site/operator/permit path before major build or spend.", min:"NOK 650k", base:"NOK 1.6m", economic:"Field cost is geography/operator dependent; defer major spend until the delivery route is real." },
  "4planet/e4rth/clim4te": { id:"EAR-CLIM4TE-01-G01", goal:"Prove a bounded signal-to-decision use case for a real institutional or corporate decision owner.", success:"Named decision class/user + current data/evidence + observed decision value without impact inflation.", phase:"DEVELOP NEXT", next:"Name and test a real decision owner before expanding a generic climate surface.", min:"NOK 600k", base:"NOK 1.5m", economic:"Decision-owner proof can begin cheaply; do not spend into a generic climate dashboard." },
  "4planet/e4rth/am4zonia": { id:"EAR-AM4ZONIA-01-G01", goal:"Create an Indigenous-first, consent-based intelligence/protection pathway without extractive representation.", success:"Authorised local representation/partner + protocol/consent/rights + bounded fundable pilot before public action.", phase:"HOLD", next:"Do not activate until a genuinely authorised local route and consent/rights protocol exist.", min:"NOK 550k", base:"NOK 1.3m", economic:"Funding must not bypass consent or create extractive pressure; no spend activation while legitimacy is open." },
  "4planet/e4rth/species": { id:"EAR-SPECIES-01-G01", goal:"Make each species a human-first, immersive and source-aware entry into the living planet: identity → habitat/place → ATLAS → ecosystem → dependencies → pressures → causes → solutions → action.", success:"Jaguar proves a reusable Species World grammar and transfers to Orca without truth, rights, performance or interaction regression.", phase:"ACTIVE NOW / GOLD", next:"Repair the current Journey/XR exact-head failure, then rerun full acceptance before shared-contract extraction.", min:"NOK 700k", base:"NOK 1.8m", economic:"Separate reusable shared Product infrastructure from species-specific content/media cost; prove value before catalogue scale." },
  "4planet/e4rth/rewild-land": { id:"EAR-REWILD-L-01-G01", goal:"Build a realistic restoration intelligence pathway and partner-defined unit/pilot.", success:"One geography/operator/tenure/standard/cost/monitoring route supports a credible funded restoration delivery.", phase:"HOLD → DEVELOP NEXT", next:"Require operator/site/standard evidence before costing a real unit.", min:"NOK 650k", base:"NOK 1.7m", economic:"Cost/unit cannot be set before site/operator; hold major spend." },
  "4planet/s4piens/food": { id:"SAP-FOOD-01-G01", goal:"Prove the smallest complete 4PLANET loop on one familiar Norwegian food decision with trustworthy health, price, ecological and choice intelligence.", success:"Everyday Protein Choice: 4–6 audited alternatives, separate dimensions/no synthetic green score, 6–10 observed users, 2–3 expert challenges, correction, one bounded action/resource route and transfer adapter.", phase:"P0 / GOLD + USER PROOF", next:"Run the user/expert loop on the bounded PICK/CHOICE implementation and correct from evidence.", min:"NOK 500k historical corridor", base:"NOK 1.2m historical corridor", economic:"Current CHOICE v1 planning ceiling: ≤NOK 250k minimum / ≤NOK 500k base / ≤NOK 1.2m scale. Rebuild bottom-up for current scope; this is not approved spend." },
  "4planet/s4piens/energy": { id:"SAP-EN3RGY-01-G01", goal:"Create decision-aware local energy-transition intelligence for a bounded real owner.", success:"One real decision owner uses a source-aware energy decision view and generates observed learning.", phase:"MONITOR / NAME CONFLICT", next:"Resolve real decision-owner fit when evidence justifies activation; keep EN3RGY/EN4RGY conflict explicit.", min:"NOK 700k", base:"NOK 1.9m", economic:"No spend expansion before decision-owner fit." },
  "4planet/s4piens/circular-city": { id:"SAP-CIRCULAR-01-G01", goal:"Map one city material flow from problem to actors/solutions/capital and coordinate a bounded action pilot.", success:"One flow + legitimate participants/data + defined intervention + measured result creates a reusable city-system module.", phase:"DEVELOP NEXT", next:"Choose one real material flow and owner before budget expansion.", min:"NOK 500k", base:"NOK 1.25m", economic:"Convene/process only if it leads to an actual intervention and measured learning." },
  "4planet/s4piens/f4shion": { id:"SAP-F4SHION-01-G01", goal:"Map one fashion category/material and test traceable decision intelligence without equating traceability with lower impact.", success:"Partner/data access + traceability evidence + user/decision learning + controlled environmental/health/value claims.", phase:"DEVELOP AFTER FOOD", next:"Use FOOD transfer learning before choosing category/partner/data route.", min:"NOK 400k", base:"NOK 1m", economic:"Need supply-chain data and methodology before meaningful spend." },
  "4planet/4culture/m4gazine": { id:"CUL-M4GAZINE-01-G01", goal:"Translate real intelligence/proof into high-quality editorial understanding, trust and cultural relevance.", success:"A low-frequency source-grounded programme produces meaningful audience/media response and reusable story assets tied to real proof.", phase:"ACTIVE / PREMIUM CANDIDATE", next:"Judge the current premium M4GAZINE surface and publish only through proof/rights gates.", min:"NOK 320k", base:"NOK 750k", economic:"Low-frequency by design; preserve highest-EV funding work and avoid detached content production." },
  "4planet/4culture/4film": { id:"CUL-4FILM-01-G01", goal:"Translate living-system truth and action into emotionally powerful documentary storytelling.", success:"One rights/producer/access-safe flagship film gains distribution/audience evidence and strengthens verified Mission/story.", phase:"ACTIVE FUNDING / RIGHTS", next:"Advance high-EV financing/rights routes; deeper production waits for financing and authority.", min:"NOK 500k", base:"NOK 1.2m", economic:"Avoid double counting WH4LES story assets; production burden and rights are hard gates." },
  "4planet/4culture/4rt": { id:"CUL-4RT-01-G01", goal:"Test whether cultural value can transparently finance verified living-planet action.", success:"One artist-edition model has clear rights/economics and only funds a valid underlying Impact route.", phase:"DEVELOP / FUNDING", next:"Close artist/rights/economics and underlying Impact route before any ecological value claim.", min:"NOK 250k", base:"NOK 650k", economic:"Commercial art economics and environmental delivery remain separate." },
  "4planet/4culture/4play": { id:"CUL-4PLAY-01-G01", goal:"Test music/live culture as a participation and attention multiplier for a living planet.", success:"One bounded artist/release/live activation produces observed participation/partner learning without mission dilution.", phase:"HOLD", next:"Activate only when proof, brand and capital create an unusually high-leverage opportunity.", min:"NOK 300k", base:"NOK 750k", economic:"Do not spend simply to create attention without a proof trigger." },
};

const missionUrls: Record<string,string> = {
  "4planet/oce4n/wh4les":"https://4planet.org/missions/wh4les", "4planet/oce4n/cor4l":"https://4planet.org/missions/cor4l", "4planet/oce4n/plastic-clean":"https://4planet.org/missions/cle4n", "4planet/oce4n/rewild-marine":"https://4planet.org/missions/rewild-marine",
  "4planet/e4rth/clim4te":"https://4planet.org/missions/clim4te", "4planet/e4rth/am4zonia":"https://4planet.org/missions/am4zonia", "4planet/e4rth/species":"https://4planet.org/missions/species", "4planet/e4rth/rewild-land":"https://4planet.org/missions/rewild-land",
  "4planet/s4piens/food":"https://4planet.org/missions/food", "4planet/s4piens/energy":"https://4planet.org/missions/en4rgy", "4planet/s4piens/circular-city":"https://4planet.org/missions/circular-city", "4planet/s4piens/f4shion":"https://4planet.org/missions/f4shion",
  "4planet/4culture/m4gazine":"https://4planet.org/missions/m4gazine", "4planet/4culture/4film":"https://4planet.org/missions/4film", "4planet/4culture/4rt":"https://4planet.org/missions/4rt", "4planet/4culture/4play":"https://4planet.org/missions/4play",
};

const direct: Record<string,PartialControl> = {
  "4planet": { classification:"PRIMARY PROJECT HOME", goalId:"N1 / Q90", mainGoal:"Build the world’s most useful integrated intelligence, coordination and action infrastructure for a living planet.", success:"90-day proof: ≥1,000 real product users; ≥25 observed sessions; ≥5 substantive expert/scientific reviews; ≥10 authoritative live/refreshable integrations; first-money target ≥NOK 1.5m; ≥1 financed/paid pilot; ≥70% of AI-eligible work closes without Founder.", phase:"90-DAY BREAKOUT", nextGate:"Founder visual judgement on the current public candidate, then controlled release of the same accepted artifact.", economicGoal:"12-month target ≥NOK 15m secured/contracted/awarded/received and ≥NOK 5m cash received; 90-day first-money target ≥NOK 1.5m.", economics:"Founding Build planning model: NOK 1.5m minimum / NOK 5m base. Planning ≠ approved spend or forecast.", moneyTruth:"15 historical submissions · 14 awaiting · 1 rejected · 0 awarded/secured · 0 contracted · 0 cash received.", source:AUTH, links:[{label:"OPEN 4PLANET",href:"https://4planet.org",kind:"WEB"}] },
  "4planet/strategy": { classification:"PROJECT HOME", goalId:"SYS-P00-STRAT-G01", mainGoal:"Keep the entire programme goal-directed, projectised and evidence-linked under Strategy & Goal Cascade v4.0.", success:"Every material work item maps from U0/N1 through a Project Home and real evidence path; priorities change from dated evidence, not chat momentum.", phase:"PERMANENT CONTROL", nextGate:"Keep Project Homes, WBS, capital, proof and bottleneck readback aligned as execution changes.", economicGoal:"Maximise verified value moved per Founder hour without management-system overhead.", economics:P00_ECON, moneyTruth:P00_MONEY, source:AUTH },
  "4planet/product": { classification:"PROJECT HOME", goalId:"SYS-P00-PRODUCT-G01", mainGoal:"Ship the strongest coherent ATLAS / SPECIES / LIVING SYSTEMS / IMPACT public candidate without false maturity.", success:"Founder-accepted public release with source, rights, mobile, accessibility and runtime evidence intact.", phase:"FOUNDER JUDGE / RELEASE", nextGate:"Open the immutable candidate and make one bounded visual decision: accept, edit or hold.", economicGoal:"Create public proof strong enough to unlock users, external challenge and first-money conversion before expensive breadth.", economics:P00_ECON, moneyTruth:P00_MONEY, source:`${AUTH} · PR #90`, links:[{label:"OPEN CURRENT PREVIEW",href:"https://80023f08.4planet-05.pages.dev",kind:"PREVIEW"},{label:"OPEN CURRENT PR #90",href:"https://github.com/odinskogen-dev/4Planet.05/pull/90",kind:"REPO"},{label:"OPEN PRODUCTION",href:"https://4planet.org",kind:"WEB"}], technical:["PR #90 · OPEN / DRAFT / UNMERGED","Exact candidate e01025ca53414e94ccb8f2c4385edc4edae72ec2","Convergence runs 32320623989 + 32320624577: SUCCESS","Production unchanged until Founder release"] },
  "4planet/product/one-interface": { classification:"PRODUCT SURFACE", goalId:"SYS-P00-PRODUCT-G01", mainGoal:"Make 4PLANET feel like one coherent public experience while its major interfaces stay distinct on one canonical core.", success:"A first-time recipient can understand, explore and trust 4PLANET on desktop/mobile and move naturally between products and Missions.", phase:"FOUNDER VISUAL JUDGE", nextGate:"Judge the current immutable preview — no SHA copying or GitHub archaeology required.", economicGoal:"Convert product quality into real users, qualified relationships and first-money evidence; no standalone revenue claim yet.", economics:"Non-additive child of shared Product/P00. Actual cost remains UNKNOWN until source-mapped.", moneyTruth:"No product-specific revenue/cash verified.", source:`${AUTH} · PR #90`, links:[{label:"OPEN CURRENT PREVIEW",href:"https://80023f08.4planet-05.pages.dev",kind:"PREVIEW"},{label:"OPEN CURRENT PR #90",href:"https://github.com/odinskogen-dev/4Planet.05/pull/90",kind:"REPO"},{label:"OPEN 4PLANET.ORG",href:"https://4planet.org",kind:"WEB"}], technical:["PR #90 · OPEN / DRAFT / UNMERGED","Exact head e01025ca53414e94ccb8f2c4385edc4edae72ec2","Technical + rights gates PASS","Founder visual JUDGE remains"] },
  "4planet/product/atlas": { classification:"PRODUCT SURFACE", goalId:"SYS-P00-PRODUCT-G01 / ATLAS", mainGoal:"Make ATLAS the source-aware spatial workbench for the living planet, useful from planetary to local scale without losing time, source or uncertainty semantics.", success:"ATLAS remains independently useful while sharing one Planet Model, source contract and journey grammar with SPECIES, Living Systems and Missions.", phase:"PUBLIC PRODUCT + DATA LAB", nextGate:"Use the accepted ONE INTERFACE Atlas showcase and promote only qualified Data Lab improvements after source/browser QA.", economicGoal:"Reuse one map engine and shared connectors so data breadth grows without duplicated infrastructure cost.", economics:"Non-additive Product/P00 surface; unique infrastructure cost not separately reconciled.", moneyTruth:"No ATLAS-specific revenue, award or cash verified.", source:AUTH, links:[{label:"OPEN ATLAS",href:"https://4planet.org/atlas",kind:"WEB"},{label:"OPEN CURRENT ATLAS PREVIEW",href:"https://80023f08.4planet-05.pages.dev/atlas",kind:"PREVIEW"}] },
  "4planet/product/living-systems": { classification:"PRODUCT SURFACE", mainGoal:"Turn isolated ecological facts into source-aware relationship intelligence while preserving dependency, pressure, response, uncertainty and provenance.", success:"Reusable relationship truth travels correctly across ATLAS, SPECIES, Missions and decisions and improves real understanding.", phase:"PUBLIC PRODUCT / SHARED CORE", nextGate:"Prove the strongest relationship grammar inside current Gold journeys and external challenge.", economicGoal:"Increase reuse and decision value per shared evidence object instead of funding a separate data silo.", economics:"Non-additive Product/Truth shared component.", moneyTruth:"No Living Systems-specific revenue/cash verified.", source:AUTH, links:[{label:"OPEN LIVING SYSTEMS",href:"https://4planet.org/living-systems",kind:"WEB"}] },
  "4planet/product/impact": { classification:"PRODUCT SURFACE", goalId:"Q90-4 / IMPACT", mainGoal:"Make credible action easy while keeping contribution, partner delivery, evidence, ecological outcome and 4PLANET impact explicitly separate.", success:"At least one qualified operator and financed/paid pilot path has auditable method, economics, claims, delivery and proof states.", phase:"FIRST DELIVERY PREP", nextGate:"Qualify the first operator/method/economics chain before any public Impact Unit or outcome claim.", economicGoal:"First financed/paid pilot within 90 days; build a repeatable partner-led delivery model without double counting.", economics:"Shared Product/P00 surface; delivery economics belong to the owning Mission/operator.", moneyTruth:"0 verified financed deliveries / 0 verified delivery cash in this projection.", source:AUTH, links:[{label:"OPEN IMPACT",href:"https://4planet.org/impact",kind:"WEB"}] },
  "4planet/naturebrain": { classification:"PROJECT HOME", goalId:"SYS-P00-TRUTH-G01", mainGoal:"Build a trusted, reusable science/evidence/source federation that lets every 4PLANET surface show what is known, uncertain, disputed and correctable.", success:"Source/claim/identity semantics converge once and can be safely projected without a second truth store.", phase:"PERMANENT SHARED CORE", nextGate:"Close current identity/source/projection seams and keep Planetary Map as one permanent world-description layer.", economicGoal:"Federate authoritative sources and reuse evidence rather than replicate expensive data infrastructure.", economics:P00_ECON, moneyTruth:P00_MONEY, source:AUTH },
  "4planet/proof": { classification:"PROJECT HOME", goalId:"SYS-P00-PROOF-G01", mainGoal:"Get real external users, expert challenge and correction into the product loop before scale.", success:"90 days: ≥25 observed sessions, ≥5 substantive expert/scientific reviews and ≥2 organisational tests, with corrections written back.", phase:"PREP NOW → ACTIVATE AFTER PUBLIC GATE", nextGate:"Release the first bounded user and scientific-review cohorts after public candidate acceptance.", economicGoal:"Buy only minimum test/expert capacity needed to expose errors and value before larger spend.", economics:P00_ECON, moneyTruth:"Current controlled baseline: 0 completed real participants and 0 completed current external reviews.", source:AUTH },
  "4planet/capital": { classification:"PROJECT HOME", goalId:"SYS-P00-CAPITAL-G01 / Q90-3", mainGoal:"Turn Project-first capital intelligence into real awards, contracts and cash rather than a larger pipeline.", success:"90 days: first external money hard gate; target ≥NOK 1.5m, 20–30 qualified active dialogues, ≥10 bespoke asks and ≥3 late-stage processes.", phase:"FIRST MONEY CONVERSION", nextGate:"Push strongest existing routes toward award/contract/cash; expand inventory only for a verified gap.", economicGoal:"12 months: ≥NOK 15m secured/contracted/awarded/received and ≥NOK 5m cash received from ≥3 independent sources.", economics:P00_ECON, moneyTruth:"15 historical submissions · 14 awaiting · 1 rejected · 0 award/secured · 0 contracted · 0 cash.", source:AUTH },
  "4planet/company": { classification:"PROJECT HOME", goalId:"SYS-P00-COMPANY-G01", mainGoal:"Create the minimum trustworthy company, legal, IP, finance, privacy and data-room foundation needed for public release and first transactions.", success:"Operator identity, rights, privacy and transaction-critical evidence are inspectable enough for the next real external gate.", phase:"MINIMUM TRUST CLOSURE", nextGate:"Close exact release/transaction-critical evidence gaps and obtain professional judgement where AI cannot certify.", economicGoal:"Enable revenue/funding and reduce transaction friction without overbuilding administration.", economics:P00_ECON, moneyTruth:P00_MONEY, source:AUTH, links:[{label:"OPEN COMPANY + TRUST PR #38",href:"https://github.com/odinskogen-dev/4Planet.05/pull/38",kind:"REPO"}] },
  "4planet/relations": { classification:"PROJECT HOME", goalId:"SYS-P00-REL-G01", mainGoal:"Create a repeatable path from proof → right actor → useful async dialogue → proposal/ask → close/adoption/support.", success:"Qualified relationships produce measurable replies, proposals, adoption, money, delivery or useful learning without spam or founder meeting overload.", phase:"PREP NOW / ACTIVATE AFTER PUBLIC GATE", nextGate:"Activate qualified routes from accepted public proof under current Norway/risk/meeting approval rules.", economicGoal:"Increase conversion quality and value per Founder hour; treat Founder meetings as a real cost.", economics:P00_ECON, moneyTruth:"Pipeline is never counted as money or partnership until evidence exists.", source:AUTH },
  "4planet/brand": { classification:"PROJECT HOME", goalId:"SYS-P00-BRAND-G01", mainGoal:"Make 4PLANET unmistakable, trustworthy and culturally powerful while translating proof into discovery, understanding and participation.", success:"One coherent identity works across public product, Founder, capital and culture surfaces and improves qualified response without weakening truth.", phase:"PUBLIC EXPERIENCE CONVERGENCE", nextGate:"Founder visual judgement on the current public experience, then propagate accepted patterns.", economicGoal:"Use brand as a multiplier for users, capital, talent and partnerships; no vanity content factory.", economics:P00_ECON, moneyTruth:P00_MONEY, source:AUTH, links:[{label:"OPEN CURRENT PUBLIC PREVIEW",href:"https://80023f08.4planet-05.pages.dev",kind:"PREVIEW"}] },
  "4planet/solutions": { classification:"PROJECT HOME", goalId:"SYS-P00-SOLUTIONS-G01", mainGoal:"Find and strengthen the best existing solutions and actors; build directly only for an important verified gap where 4PLANET has a defensible reason.", success:"External solutions gain useful evidence, capital, partners, talent, demand or coordination and repeated support gets cheaper/better.", phase:"CONTINUOUS COMPOUNDING", nextGate:"Apply shared solution/effectiveness grammar to active Mission and decision cases and measure transfer rather than list volume.", economicGoal:"Increase external capacity per 4PLANET resource and route good capital to evidence-backed needs.", economics:"Shared P00 intelligence component; no approved standalone additive budget.", moneyTruth:"No solution listing is treated as revenue, funding, partnership or verified effectiveness.", source:AUTH },
  "4planet/economy": { classification:"PROJECT HOME", goalId:"SYS-P00-ECONOMY-G01", mainGoal:"Create one trustworthy economic nervous system across Projects, products and capital without creating a parallel statutory ledger.", success:"One bounded source period reconciles to 100% while PLAN, PIPELINE, AWARD, CONTRACT, commitments, accounting states and CASH remain distinct and freshness/coverage are visible.", phase:"CODE V0.1 / SOURCE RECONCILIATION NEXT", nextGate:"QA the current prototype, map one bounded real source period, prove reconciliation, then connect a read-only LABS projection.", economicGoal:"Make resource needs, economics, capital gaps and cash decision-useful without double counting Projects/shared infrastructure.", economics:"No approved build budget. Bottom-up model pending; any new cash need remains UNKNOWN until evidence-backed.", moneyTruth:"Project funding/contract/cash: 0 verified. Actual cost/commitment: UNKNOWN. Prototype values are DEMO / NOT LIVE.", source:`${AUTH} · 13_ECONOMICS · 4PLANET-05 PR #2`, links:[{label:"OPEN ECONOMY_ PR #2",href:"https://github.com/odinskogen-dev/4PLANET-05/pull/2",kind:"REPO"}], technical:["PR #2 · OPEN / DRAFT / UNMERGED","Current head 0c804c0eb3bce3bb01a62bf725a631cf3c68caad","Route /sandbox/economy","No pull-request workflow run observed on this exact head"] },
  "4planet/digital-pitch": { classification:"PROJECT HOME", goalId:"SYS-P00-DPITCH-G01", mainGoal:"Make high-value recipients understand 4PLANET through a concise tailored digital proof experience rather than generic decks or long emails.", success:"A qualified recipient can quickly understand fit, proof, ask and next action while claims remain source/authority-safe.", phase:"P1 ACTIVE PROTOTYPE", nextGate:"Use Patagonia Gold only on a qualified recipient route after current release/outreach gates.", economicGoal:"Improve qualified conversion per Founder hour and reduce pitch-production cost through reusable grammar.", economics:"Shared P00/Capital/Brand component; no standalone approved budget.", moneyTruth:"No recipient preview is partnership, revenue or capital until independently evidenced.", source:AUTH, links:[{label:"OPEN PATAGONIA GOLD PREVIEW",href:"https://proto-digital-pitch-pack-v1.4planet05.pages.dev/brands/patagonia",kind:"PREVIEW"}] },
  "4planet/labs-system": { classification:"PROJECT HOME", goalId:"SYS-P00-LABS-G01", mainGoal:"Keep one safe, useful public-development and Founder-control surface where real 4PLANET artifacts can be inspected without destabilising production or replacing BRAIN.", success:"Every important Project Home and bounded prototype is findable; status, goal, economics, next gate and leading link are human-readable; internal routes/mobile/link contracts pass; private truth never leaks.", phase:"PREMIUM GOLD DEBUG PASS", nextGate:"Complete this usability/data/link reconciliation and exact-head browser QA.", economicGoal:"Increase Founder decision speed and prevent forgotten work without creating a costly parallel management system.", economics:"Shared P00 system; no standalone approved build budget.", moneyTruth:"LABS itself is not a money claim or statutory finance source.", source:`${AUTH} · PR #54`, links:[{label:"OPEN LABS PR #54",href:"https://github.com/odinskogen-dev/4Planet.05/pull/54",kind:"REPO"}] },
  "4planet/naturebrain/planetary-map": { classification:"BOUNDED PROJECT / PERMANENT LAYER", goalId:"SYS-P00-PMAP-G01", mainGoal:"Materialise the minimum useful Planetary Map as the permanent world-description layer beneath Missions without a competing ontology or map engine.", success:"Canonical place/life/pressure/source semantics support shared products and Missions while the bounded PMAP build can close cleanly.", phase:"INCUBATING / INTERNAL P1", nextGate:"Advance only highest-reuse world-description seams required by active Product/Mission work.", economicGoal:"Reduce duplicated world modelling and future integration cost through one shared model.", economics:"Shared infrastructure; no separately approved current budget.", moneyTruth:"No standalone revenue/capital claim.", source:AUTH },
  "4planet/s4piens/food-gold-lab": { classification:"PROJECT HOME / GOLD BUILD", goalId:"SAP-SAPIENS-01-G01", mainGoal:"Build one genuinely impressive ATLAS-first Homo sapiens × FOOD experience using the shared Planet Model, ATLAS, SPECIES and Living Systems infrastructure.", success:"Complete HUMAN → FOOD SYSTEM → PLACE/DATA → LIVING SYSTEM/SPECIES → SOLUTION/MISSION with provenance and no false causal/Impact claim.", phase:"GOLD PROTOTYPE", nextGate:"Close current Gold candidate QA while keeping host/domain routing as a separate gate.", economicGoal:"Prove S4PIENS interaction grammar before funding broad human-system expansion.", economics:"No approved Project budget; build-cost model pending. Shared ATLAS/SPECIES/FOOD/P00 components non-additive.", moneyTruth:"Income/revenue/funding/cash: 0 verified. Actual cost/commitment: UNKNOWN.", source:AUTH, links:[{label:"OPEN S4PIENS GOLD PR #81",href:"https://github.com/odinskogen-dev/4Planet.05/pull/81",kind:"REPO"},{label:"OPEN DOMAIN PR #83",href:"https://github.com/odinskogen-dev/4Planet.05/pull/83",kind:"REPO"}] },
  "4planet/s4piens/food/pick": { classification:"CHILD PROTOTYPE / ECONOMIC OBJECT", mainGoal:"Make a normal household food choice easier with separate evidence-bounded HEALTH, WALLET and PLANET information and fair alternatives.", success:"Private user proof shows the surface is useful, understandable and safe without universal scoring or missing-data advantage.", phase:"PRIVATE REVIEW / USER PROOF NEXT", nextGate:"Run bounded real-user and expert validation before standalone product/unit-economics/capital claims.", economicGoal:"Learn whether decision utility is strong enough to justify promotion; do not finance as a separate Project yet.", economics:"Non-additive child of FOOD/CHOICE. Incremental cash need UNKNOWN.", moneyTruth:"Revenue/funding/cash 0 verified. Actual prototype cost UNKNOWN.", source:`${AUTH} · 13_ECONOMICS · PR #85`, links:[{label:"OPEN PICK_ PR #85",href:"https://github.com/odinskogen-dev/4Planet.05/pull/85",kind:"REPO"}], technical:["PR #85 exact head 7abd18e0a66992c339b1654d9f01dd540d3441ae","Dedicated Prototype Gate 32310081759: SUCCESS","Private review / draft / unmerged"] },
  "4planet/tree-of-life": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Make the 4PLANET ecosystem legible as one interactive system map showing how truth, living systems, problems, solutions, actors, capital, action, proof, story and people connect.", success:"The map improves understanding without becoming a fifth product, second truth system or false funding/delivery claim.", phase:"PRIVATE SANDBOX", nextGate:"Use as architecture/overview prototype; promote only proven interaction grammar after Founder judgement.", economicGoal:"Improve system legibility and capital/coordination explanation with minimal new infrastructure.", economics:"Prototype track under shared Product/portfolio coding; no standalone approved budget.", moneyTruth:"No depicted relationship is money, partnership, delivery or impact unless separately verified.", source:"Founder concept + PR #80", links:[{label:"OPEN TREE OF LIFE PR #80",href:"https://github.com/odinskogen-dev/4Planet.05/pull/80",kind:"REPO"}] },
  "4planet/choice-lab": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Prove explainable Innovation × Capital decision intelligence without collapsing the decision into one opaque score.", success:"A user can inspect problem → solution → innovation → actor → capital → impact → proof with explicit maturity and uncertainty.", phase:"PRIVATE SANDBOX / TRUTH DEFECT OPEN", nextGate:"Replace unsupported maturity semantics with evidence-bound or DEMO/HYPOTHESIS/UNKNOWN states and rerun exact-head QA.", economicGoal:"Test whether better solution/capital matching has decision value before financing it as a product capability.", economics:"Prototype track; no standalone approved budget/capital plan.", moneyTruth:"Generic demo objects are not real companies, funders, funding relationships or ecological outcomes.", source:`${AUTH} · PR #82`, links:[{label:"OPEN CHOICE PR #82",href:"https://github.com/odinskogen-dev/4Planet.05/pull/82",kind:"REPO"}] },
  "4planet/product/nature-xr": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Use browser-first immersive interaction to improve understanding/felt relevance while canonical truth remains the only ecological authority.", success:"Browser experience works on desktop/mobile; WebXR remains progressive enhancement; real headset comfort/comprehension tested separately.", phase:"VERIFIED BROWSER PROTOTYPE / HEADSET UNVERIFIED", nextGate:"Run real physical-headset validation before claiming headset quality.", economicGoal:"Test AWE/learning upside cheaply before rights-heavy 3D/audio/institution modes.", economics:"Shared Product prototype; no standalone approved budget.", moneyTruth:"No revenue/funding/impact claim.", source:"PR #73", links:[{label:"OPEN JAGUAR XR PREVIEW",href:"https://86609c96.4planet-05.pages.dev/xr/jaguar/",kind:"PREVIEW"},{label:"OPEN NATURE XR PR #73",href:"https://github.com/odinskogen-dev/4Planet.05/pull/73",kind:"REPO"}] },
  "4planet/product/jaguar-journey": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Create a reusable cinematic Browser Journey from species → habitat → relationships → pressure → response using canonical truth and progressive media.", success:"Jaguar and Orca can share the interaction contract without viewport, truth, rights or performance regressions.", phase:"REPAIR / EXACT GATE FAILED", nextGate:"Fix the Nature XR flat-browser failure and rerun the complete gate before shared-contract extraction.", economicGoal:"Prove reusable interaction value before bespoke media/3D spend or multiplying journeys.", economics:"Shared Product/SPECIES prototype; no standalone approved budget.", moneyTruth:"No revenue/funding/Impact claim.", source:"PR #79 / run #511", links:[{label:"OPEN JAGUAR JOURNEY PR #79",href:"https://github.com/odinskogen-dev/4Planet.05/pull/79",kind:"REPO"}], technical:["Current exact head 94bb168bfc411ea525ce3791bbfa0baff2b26786","Run 32356696261 / #511: FAILURE","Typecheck/build/contracts/Jaguar Chromium+WebKit PASS","Nature XR flat-browser runtime FAIL; later route/security/source steps skipped"] },
  "4planet/product/atlas-data-lab": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Expand ATLAS data breadth and multiscale cartography safely inside the existing map engine with explicit source/product/map gates.", success:"Each promoted layer/cartography change passes source contract, rendered map, mobile, attribution/rights, performance and regression proof.", phase:"SANDBOX", nextGate:"Rerun exact current source/product/browser acceptance before promotion.", economicGoal:"Scale data capability through reusable adapters and one map runtime rather than parallel products.", economics:"Shared Product/ATLAS prototype; no standalone approved budget.", moneyTruth:"No standalone revenue/funding claim.", source:"PR #72", links:[{label:"OPEN ATLAS DATA LAB PR #72",href:"https://github.com/odinskogen-dev/4Planet.05/pull/72",kind:"REPO"}] },
  "4planet/product/organisations": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Make organisations, knowledge institutions and actor geographies source-aware and discoverable without treating indexing as partnership or endorsement.", success:"Reusable actor identity/claim/geography/source machinery supports active Projects and ATLAS without a duplicate Actor truth store.", phase:"PRIVATE-BETA LINEAGE", nextGate:"Reuse the source/actor graph where current Projects need it; promote only after rights/identity/integration gates.", economicGoal:"Reduce relationship/search friction and increase coordination value; no standalone monetisation claim.", economics:"Portfolio-coded Product/Actor component; no standalone budget.", moneyTruth:"Indexing/data use is not partnership, contract, revenue or Impact.", source:"P17 lineage", links:[{label:"OPEN ORGANISATIONS_ PR #21",href:"https://github.com/odinskogen-dev/4Planet.05/pull/21",kind:"REPO"},{label:"OPEN KNOWLEDGE GRAPH PR #28",href:"https://github.com/odinskogen-dev/4Planet.05/pull/28",kind:"REPO"}] },
  "4planet/product/oslofjorden": { classification:"REFERENCE BUILD / PROTOTYPE", mainGoal:"Prove the shared place/life/data product on one real local place with geometry, provenance, source Watch and human-evidence boundaries intact.", success:"A reusable real-place pattern survives source complexity and later real-user testing without turning source changes into ecological claims.", phase:"INTERNAL PROOF / HUMAN VALIDATION OPEN", nextGate:"Run genuine human validation and close remaining rights/source/security release gaps.", economicGoal:"Use one bounded place to reduce future local-product adaptation cost before scale.", economics:"Shared Product/Truth reference build; no standalone current budget.", moneyTruth:"No revenue/partner/Impact claim.", source:"PR #32", links:[{label:"OPEN OSLOFJORDEN PR #32",href:"https://github.com/odinskogen-dev/4Planet.05/pull/32",kind:"REPO"}] },
  "4planet/naturebrain/decision-intelligence": { classification:"LAB / PROTOTYPE TRACK", mainGoal:"Turn evidence into practical decision support while keeping evidence, uncertainty, judgement and observed outcomes separate and refusing a hidden universal score.", success:"Real decision owners compare bounded options with provenance/uncertainty visible and later outcomes correct the intelligence.", phase:"TECHNICAL CLOSURE / HUMAN PROOF OPEN", nextGate:"Use capability on bounded real decision-owner cases and obtain independent challenge before broader promotion.", economicGoal:"Increase decision usefulness and later paid-pilot/procurement potential only after real owner value is observed.", economics:"Shared Truth/Product capability; no standalone current budget.", moneyTruth:"No paid decision service or procurement outcome verified.", source:"PR #34 + Founder Control", links:[{label:"OPEN DECISION INTELLIGENCE PR #34",href:"https://github.com/odinskogen-dev/4Planet.05/pull/34",kind:"REPO"}] },
};

const productLinks: Record<string,NonNullable<LabProject["assets"]>> = {
  "4planet/e4rth/species":[{label:"OPEN SPECIES",href:"https://4planet.org/species",kind:"WEB"},{label:"OPEN JAGUAR JOURNEY PR #79",href:"https://github.com/odinskogen-dev/4Planet.05/pull/79",kind:"REPO"}],
  "4planet/4culture/m4gazine":[{label:"OPEN CURRENT M4GAZINE PREVIEW",href:"https://80023f08.4planet-05.pages.dev/magazine",kind:"PREVIEW"},{label:"OPEN M4GAZINE PR #88",href:"https://github.com/odinskogen-dev/4Planet.05/pull/88",kind:"REPO"}],
};

function fallback(project: LabProject): ProjectControl {
  const links = (project.assets ?? []).filter((a,i,all)=>all.findIndex((b)=>b.href===a.href)===i);
  return {
    classification: project.projectClass ?? (project.kind === "ROOT" ? "UNIVERSE" : project.kind),
    mainGoal: project.why || project.next,
    success: project.milestones?.find((m)=>!m.done)?.label ?? "Use the owning Project Home and current authority before counting this view complete.",
    phase: project.roadmap?.[0]?.title ?? project.priority,
    nextGate: project.tasks?.find((t)=>["ACTIVE","NEXT","GATED"].includes(t.state))?.text ?? project.next,
    economicGoal: project.universe === "4PLANET" ? "Tracked through the owning Project Home unless a separate current economic contract exists." : "Not projected on this public-safe view.",
    economics: project.universe === "4PLANET" ? "No separate additive economics projected. UNKNOWN stays UNKNOWN." : "PRIVATE / NOT PROJECTED.",
    moneyTruth: project.universe === "4PLANET" ? "No money state is inferred from activity, code, pipeline or prototype status." : "PRIVATE / NOT PROJECTED.",
    source: project.evidence || project.authority,
    links,
    technical: [],
  };
}

export function currentControlFor(project: LabProject): ProjectControl {
  const m = missionRows[project.slug];
  if (m) {
    const links = [...(productLinks[project.slug] ?? [])];
    if (missionUrls[project.slug]) links.push({label:`OPEN ${project.title} MISSION`,href:missionUrls[project.slug],kind:"WEB"});
    return { classification:"MISSION PROJECT HOME", goalId:m.id, mainGoal:m.goal, success:m.success, phase:m.phase, nextGate:m.next, economicGoal:m.economic, economics:`Planning model: ${m.min} minimum / ${m.base} base. Planning ≠ approved spend, forecast or cash need.`, moneyTruth:"Funding received 0 · awarded 0 · contracted 0 in current Project Economics unless separately verified; actual spend/committed cost remains UNKNOWN.", source:`${AUTH} · 11_PROJECT PACKS · 13_ECONOMICS`, links, technical:[] };
  }
  const base = fallback(project);
  const d = direct[project.slug];
  if (!d) return base;
  return { ...base, ...d, links:d.links ?? base.links, technical:d.technical ?? base.technical } as ProjectControl;
}

export function withGoldMeta(project: LabProject): GoldLabProject {
  const enriched = withProjectMeta(project) as LabProject;
  const control = currentControlFor(enriched);
  return { ...enriched, assets:control.links, control };
}
