import { useEffect, useMemo, useState, type CSSProperties } from "react";
import {
  childrenOf,
  founderQueue,
  labTracks,
  portfolioStats,
  productSurfaces,
  projectBySlug,
  projectHomes,
  projects,
  projectionState,
  recentSystemMoves,
  universeRoots,
  verifiedAt,
  type LabProject,
} from "./labsCurrentProjection";
import { completeControlFor, withCompleteMeta } from "./labsCompleteMeta";
import { humanStateFor } from "./labsHumanState";
import "./labs.css";
import "./labsGold.css";

type Theme = "dark" | "light";
type InspectHandler = (project: LabProject) => void;
type IndexFilter = "ALL" | "PROJECT HOMES" | "ACTIVE" | "PRODUCT" | "LABS" | "CONFLICTS";

function isLabsHost() { return typeof window !== "undefined" && window.location.hostname.toLowerCase() === "labs.4planet.org"; }
function labHref(slug = "") { const clean=slug.replace(/^\/+|\/+$/g,""); if(isLabsHost()) return clean?`/${clean}`:"/"; return clean?`/labs?project=${encodeURIComponent(clean)}`:"/labs"; }
function accentStyle(project: LabProject) { const accent=project.accent==="brand"?"var(--accent-fourplanet)":`var(--accent-${project.accent})`; return {"--accent":accent} as CSSProperties; }
function humanText(text:string){ return text.replace(/\b[a-f0-9]{32,40}\b/gi,"exact tested artifact").replace(/\b(?:run|workflow)\s+\d{8,}\b/gi,"exact QA run").replace(/\s+/g," ").trim(); }
function GridRails(){ return <div className="labs-rails" aria-hidden="true">{Array.from({length:13},(_,index)=><span key={index}/>)}</div>; }
function Glyph({project}:{project:LabProject}){ const glyph=project.kind==="DOMAIN"?"◫":project.kind==="MISSION"?"·":project.kind==="PRODUCT"?"▣":project.kind==="LAB"?"◇":project.title.includes("BRAIN")?"◎":project.slug==="odin"?"✦":"＋"; return <span className="labs-glyph" aria-hidden="true">{glyph}</span>; }
function Status({project}:{project:LabProject}){ return <span className={`labs-status labs-status--${project.state.toLowerCase()}`}>{project.state}</span>; }

function Header({theme,setTheme}:{theme:Theme;setTheme:(theme:Theme)=>void}){
  return <header className="labs-header"><a className="labs-brand" href={labHref()}><span className="labs-online-dot" aria-hidden="true"/>4PLANET LABS</a><div className="labs-header-center"><span>HUMAN PROJECT OS</span><span>{projectionState}</span><span className="labs-online"><i/> ONLINE</span></div><div className="labs-header-tools"><span className="labs-snapshot">SNAPSHOT {verifiedAt}</span><div className="labs-theme-switch" aria-label="Appearance"><button type="button" className={theme==="dark"?"is-active":""} onClick={()=>setTheme("dark")} aria-pressed={theme==="dark"}>DARK</button><button type="button" className={theme==="light"?"is-active":""} onClick={()=>setTheme("light")} aria-pressed={theme==="light"}>WHITE</button></div></div></header>;
}
function FreshnessStrip(){ return <div className="labs-freshness labs-grid-section"><span>TRUTH MODE</span><strong>{projectionState}</strong><span>BRAIN remains authority · goals + economics from Founder Control · current code/prototype state from controlled GitHub readback · missing values stay UNKNOWN</span></div>; }
function scrollTo(id:string){ document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"}); }

function CommandStrip({filter,setFilter}:{filter:IndexFilter;setFilter:(filter:IndexFilter)=>void}){
  const cards:Array<{value:number;label:string;note:string;filter:IndexFilter;target:string}>=[
    {value:portfolioStats.projectHomes,label:"PROJECT HOMES",note:"Canonical 4PLANET Projects",filter:"PROJECT HOMES",target:"project-index"},
    {value:portfolioStats.activeProjectHomes,label:"ACTIVE NOW",note:"Active / building Project Homes",filter:"ACTIVE",target:"project-index"},
    {value:productSurfaces.length,label:"PRODUCT SURFACES",note:"ATLAS · SPECIES · LIVING SYSTEMS · IMPACT",filter:"PRODUCT",target:"project-index"},
    {value:portfolioStats.labTracks,label:"LAB / PROTOTYPES",note:"Bounded code + reference tracks",filter:"LABS",target:"project-index"},
    {value:portfolioStats.conflicts,label:"OPEN CONFLICTS",note:"Explicit — never silently resolved",filter:"CONFLICTS",target:"project-index"},
  ];
  return <section className="labs-command labs-grid-section" aria-label="Founder command"><div className="labs-section-head labs-section-head--command"><span>FOUNDER COMMAND</span><span>click = filter project index · never jumps to an arbitrary project</span></div><div className="labs-command-grid">{cards.map(item=><button type="button" className={`labs-command-card ${filter===item.filter?"is-selected":""}`} key={item.label} onClick={()=>{setFilter(item.filter);scrollTo(item.target);}}><strong>{item.value}</strong><span>{item.label}</span><small>{item.note}</small><b aria-hidden="true">↓</b></button>)}</div></section>;
}

function HoverIntel({project}:{project:LabProject}){ const control=completeControlFor(project); return <div className="labs-box-hover" aria-hidden="true"><span>GOAL</span><p>{control.mainGoal}</p><span>NOW</span><p>{humanText(humanStateFor(project))}</p><span>NEXT</span><p>{control.nextGate}</p></div>; }
function ProjectBox({project,onInspect,compact=false,early=false}:{project:LabProject;onInspect:InspectHandler;compact?:boolean;early?:boolean}){ return <a className={`labs-project-box ${compact?"labs-project-box--compact":""} ${early?"labs-project-box--early":""}`} style={accentStyle(project)} href={labHref(project.slug)} onMouseEnter={()=>onInspect(project)} onFocus={()=>onInspect(project)} data-state={project.state} data-kind={project.kind}><div className="labs-box-top"><Glyph project={project}/><Status project={project}/></div><div className="labs-box-title"><strong>{project.title}</strong><span>{project.eyebrow}</span></div><div className="labs-box-bottom"><span>{project.projectClass??project.kind}</span><span>{project.priority}</span></div><HoverIntel project={project}/></a>; }
function DomainPanel({project,onInspect}:{project:LabProject;onInspect:InspectHandler}){ const missions=childrenOf(project.slug).filter(item=>item.kind==="MISSION"); return <section className="labs-domain" style={accentStyle(project)}><a href={labHref(project.slug)} className="labs-domain-head" onMouseEnter={()=>onInspect(project)} onFocus={()=>onInspect(project)}><div><Glyph project={project}/><span>{project.title}</span></div><small>{missions.length} MISSIONS</small></a><div className="labs-domain-missions">{missions.map(mission=><a className="labs-mission-row" href={labHref(mission.slug)} key={mission.slug} onMouseEnter={()=>onInspect(mission)} onFocus={()=>onInspect(mission)} data-state={mission.state}><span>{mission.title}</span><small>{mission.state==="CONFLICT"?"CONFLICT":mission.priority}</small></a>)}</div></section>; }

const coreOrder=["4planet/strategy","4planet/product","4planet/naturebrain","4planet/proof","4planet/capital","4planet/company","4planet/relations","4planet/solutions","4planet/economy","4planet/brand","4planet/content","4planet/sonic","4planet/field-partners","4planet/research","4planet/4mbassadors","4planet/digital-pitch","4planet/labs-system"];
const leadingProductSlugs=["4planet/product/one-interface","4planet/product/atlas","4planet/e4rth/species","4planet/product/living-systems","4planet/product/impact"];

function FourPlanetUniverse({root,onInspect}:{root:LabProject;onInspect:InspectHandler}){
  const children=childrenOf(root.slug);
  const core=children.filter(project=>project.kind==="CORE"||project.kind==="SYSTEM"||project.projectClass==="PROJECT HOME").sort((a,b)=>(coreOrder.indexOf(a.slug)<0?999:coreOrder.indexOf(a.slug))-(coreOrder.indexOf(b.slug)<0?999:coreOrder.indexOf(b.slug)));
  const leading=leadingProductSlugs.map(slug=>projectBySlug(slug)).filter((project):project is LabProject=>Boolean(project));
  const domains=children.filter(project=>project.kind==="DOMAIN");
  return <section className="labs-universe labs-universe--4planet" style={accentStyle(root)}><a href={labHref(root.slug)} className="labs-universe-head labs-universe-head--hero" onMouseEnter={()=>onInspect(root)} onFocus={()=>onInspect(root)}><div><span className="labs-label">01 / PRIMARY PROJECT UNIVERSE</span><h2>4PLANET</h2><p>{root.summary}</p></div><div className="labs-planet-visual" aria-hidden="true"><span/></div><div className="labs-universe-meta"><Status project={root}/><span>{projectHomes.length} PROJECT HOMES</span><span>4 DOMAINS</span></div></a><div className="labs-subhead"><span>ORGANISATION + SHARED MACHINE</span><span>Project Homes / truth / proof / capital / company / economy</span></div><div className="labs-core-grid">{core.map(project=><ProjectBox key={project.slug} project={project} onInspect={onInspect} compact/>)}</div><div className="labs-subhead"><span>LEADING PRODUCT SURFACES</span><span>same canonical projects · direct access</span></div><div className="labs-core-grid labs-leading-product-grid">{leading.map(project=><ProjectBox key={project.slug} project={project} onInspect={onInspect} compact/>)}</div><div className="labs-subhead"><span>DOMAINS → MISSIONS</span><span>16 Wave-01 Mission Project Homes</span></div><div className="labs-domain-grid">{domains.map(domain=><DomainPanel key={domain.slug} project={domain} onInspect={onInspect}/>)}</div><div id="labs-tracks" className="labs-subhead labs-subhead--early"><span>LAB / PROTOTYPE / REFERENCE TRACKS</span><span>{labTracks.length} bounded tracks · not automatically Project Homes</span></div><div className="labs-early-grid">{labTracks.map(project=><ProjectBox key={project.slug} project={project} onInspect={onInspect} compact early/>)}</div></section>;
}
function UniversePanel({root,index,onInspect}:{root:LabProject;index:number;onInspect:InspectHandler}){ if(root.slug==="4planet")return <FourPlanetUniverse root={root} onInspect={onInspect}/>; const children=childrenOf(root.slug); return <section className={`labs-universe labs-universe--${root.universe.toLowerCase()}`} style={accentStyle(root)}><a href={labHref(root.slug)} className="labs-universe-head labs-universe-head--compact" onMouseEnter={()=>onInspect(root)} onFocus={()=>onInspect(root)}><div className="labs-universe-symbol"><Glyph project={root}/></div><div><span className="labs-label">{String(index+1).padStart(2,"0")} / {root.eyebrow}</span><h2>{root.title}</h2><p>{root.summary}</p></div><div className="labs-universe-meta"><Status project={root}/><span>{children.length} SUBPROJECTS</span></div></a><div className="labs-secondary-grid">{children.map(project=><ProjectBox key={project.slug} project={project} onInspect={onInspect} compact/>)}</div></section>; }

function Inspector({project}:{project:LabProject}){ const complete=withCompleteMeta(project); const control=complete.control; return <aside className="labs-inspector labs-inspector--gold" style={accentStyle(project)} aria-live="polite"><div className="labs-inspector-head"><div><span className="labs-label">PROJECT INSPECTOR</span><h2>{project.title}</h2><p>{control.classification}</p></div><Status project={project}/></div><section className="labs-inspector-block labs-inspector-block--truth"><span className="labs-label">MAIN GOAL</span><p>{control.mainGoal}</p></section><section className="labs-inspector-block"><span className="labs-label">NOW</span><p>{humanText(humanStateFor(project))}</p></section><section className="labs-inspector-block"><span className="labs-label">NEXT GATE</span><p>{control.nextGate}</p></section><section className="labs-inspector-block"><span className="labs-label">ECONOMICS</span><p>{control.economics}</p></section>{!!control.links.length&&<div className="labs-inspector-links">{control.links.slice(0,2).map((link,index)=><a className={index===0?"is-primary":""} href={link.href} target="_blank" rel="noreferrer" key={link.href}>{link.label}<b>↗</b></a>)}</div>}<a className="labs-open-project" href={labHref(project.slug)}>OPEN FULL PROJECT <span>→</span></a></aside>; }

function ProjectIndex({filter,setFilter,onInspect}:{filter:IndexFilter;setFilter:(filter:IndexFilter)=>void;onInspect:InspectHandler}){
  const [query,setQuery]=useState("");
  const indexProjects=useMemo(()=>projects.filter(project=>project.universe==="4PLANET"&&project.slug!=="4planet"),[]);
  const filtered=indexProjects.filter(project=>{ const control=completeControlFor(project); const matchesQuery=!query.trim()||`${project.title} ${project.eyebrow} ${project.projectId??""} ${control.mainGoal}`.toLowerCase().includes(query.trim().toLowerCase()); if(!matchesQuery)return false; if(filter==="PROJECT HOMES")return project.projectClass==="PROJECT HOME"||control.classification.includes("PROJECT HOME"); if(filter==="ACTIVE")return (project.projectClass==="PROJECT HOME"||control.classification.includes("PROJECT HOME"))&&["ACTIVE","BUILDING","PUBLIC"].includes(project.state); if(filter==="PRODUCT")return productSurfaces.some(item=>item.slug===project.slug)||project.slug==="4planet/e4rth/species"; if(filter==="LABS")return labTracks.some(item=>item.slug===project.slug)||control.classification.includes("PROTOTYPE")||control.classification.includes("REFERENCE"); if(filter==="CONFLICTS")return project.state==="CONFLICT"; return true; }).sort((a,b)=>a.title.localeCompare(b.title));
  return <section id="project-index" className="labs-project-index"><div className="labs-section-head"><span>ALL 4PLANET PROJECTS + CONTROLLED TRACKS</span><span>{filtered.length} shown · every row opens a real LABS detail view</span></div><div className="labs-index-tools"><label><span>FIND PROJECT</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ATLAS, TREE OF LIFE, SONIC, CREATOR, ECONOMY_, FOOD…"/></label><div>{(["ALL","PROJECT HOMES","ACTIVE","PRODUCT","LABS","CONFLICTS"] as IndexFilter[]).map(item=><button type="button" key={item} className={filter===item?"is-active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div></div><div className="labs-index-list">{filtered.map(project=>{ const control=completeControlFor(project); return <a href={labHref(project.slug)} style={accentStyle(project)} key={project.slug} onMouseEnter={()=>onInspect(project)} onFocus={()=>onInspect(project)}><div><Status project={project}/><span>{control.classification}</span></div><strong>{project.title}</strong><p>{control.mainGoal}</p><small>{control.phase}</small><b>→</b></a>; })}{!filtered.length&&<p className="labs-unknown-copy">No project matches this filter/search.</p>}</div></section>;
}
function FounderQueue(){ const items=founderQueue.filter(item=>item.slug.startsWith("4planet")); return <section id="founder-queue" className="labs-founder-queue"><div className="labs-section-head"><span>FOUNDER QUEUE</span><span>{items.length} public-safe decisions</span></div>{items.length?<div className="labs-founder-list">{items.map((item,index)=><a href={labHref(item.slug)} key={`${item.slug}-${index}`}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.project}</strong><p>{humanText(item.decision)}</p><b>→</b></a>)}</div>:<p className="labs-unknown-copy">No public-safe Founder decision is projected.</p>}</section>; }
function SystemFeed(){ return <section className="labs-feed-section"><div className="labs-section-head"><span>SYSTEM FEED</span><span>latest controlled changes</span></div><div className="labs-feed">{recentSystemMoves.slice(0,10).map(([id,text,state])=><div className="labs-feed-row" key={id}><span>{id}</span><strong>{humanText(text)}</strong><b>{state}</b></div>)}</div></section>; }
function PortfolioView(){ const root=projectBySlug("4planet")!; const [selected,setSelected]=useState<LabProject>(root); const [filter,setFilter]=useState<IndexFilter>("ALL"); return <main className="labs-page labs-page--portfolio"><GridRails/><section className="labs-portfolio-layout labs-grid-section"><div className="labs-portfolio-main"><CommandStrip filter={filter} setFilter={setFilter}/><FreshnessStrip/><div className="labs-section-head labs-section-head--portfolio"><span>PROJECT MAZE / CONTROL MAP</span><span>organisation → products → Missions → controlled experiments</span></div><div className="labs-universe-stack">{universeRoots.map((universe,index)=><UniversePanel key={universe.slug} root={universe} index={index} onInspect={setSelected}/>)}</div><ProjectIndex filter={filter} setFilter={setFilter} onInspect={setSelected}/><FounderQueue/><SystemFeed/></div><Inspector project={selected}/></section></main>; }

export default function LabsOverviewCurrent(){ const [theme,setTheme]=useState<Theme>(()=>typeof window!=="undefined"&&window.localStorage.getItem("4planet-labs-theme")==="light"?"light":"dark"); useEffect(()=>{window.localStorage.setItem("4planet-labs-theme",theme);},[theme]); useEffect(()=>{document.title="4PLANET LABS — Human Project OS";let robots=document.querySelector('meta[name="robots"]') as HTMLMetaElement|null;if(!robots){robots=document.createElement("meta");robots.name="robots";document.head.appendChild(robots);}const previous=robots.content;robots.content="noindex,nofollow,noarchive";return()=>{if(robots)robots.content=previous;};},[]); return <div className="labs-shell" data-theme={theme}><Header theme={theme} setTheme={setTheme}/><PortfolioView/><footer className="labs-footer"><span>4PLANET LABS · NOINDEX · READ-ONLY PROJECTION</span><span>GOAL → PROJECT → WBS → EVIDENCE → ECONOMICS → NEXT GATE</span><a href="https://4planet.org">4PLANET.ORG ↗</a></footer></div>; }
