export type LabState = "ACTIVE" | "BUILDING" | "QUEUED" | "HOLD" | "EXPERIMENT" | "PUBLIC";
export type LabUniverse = "4PLANET" | "ODIN" | "P4NTHER";
export type AccentToken = "brand" | "ocean" | "earth" | "species" | "impact" | "culture" | "food" | "violet" | "odin" | "panther";

export type Milestone = { label: string; done: boolean; note?: string };
export type RoadmapItem = { stage: string; title: string; text: string };
export type ProcessItem = { name: string; state: string; text: string };
export type TaskItem = { text: string; owner: "AI" | "FOUNDER" | "MIXED"; state: string };

export type LabProject = {
  slug: string;
  universe: LabUniverse;
  parent?: string;
  title: string;
  eyebrow: string;
  state: LabState;
  priority: string;
  accent: AccentToken;
  summary: string;
  why: string;
  now: string;
  next: string;
  aiPlan: string;
  evidence: string;
  owner: string;
  authority: string;
  freshness: string;
  externalUrl?: string;
  milestones?: Milestone[];
  roadmap?: RoadmapItem[];
  processes?: ProcessItem[];
  tasks?: TaskItem[];
  founderDecisions?: string[];
};

export const verifiedAt = "18 AUG 2026";
export const projectionState = "MANUAL BRAIN PROJECTION · READ ONLY";

const common4PlanetRoadmap: RoadmapItem[] = [
  { stage: "NOW", title: "BUILD + PROVE + FUND", text: "Public proof, semantic core, Gold References, users/science and first money move together." },
  { stage: "NEXT", title: "CONNECT THE MACHINE", text: "Intelligence → useful decision → challenge → solution/actor → capital → delivery → evidence." },
  { stage: "LATER", title: "TRANSFER + SCALE", text: "Repeat proven shared machinery without multiplying truth systems." },
];

export const projects: LabProject[] = [
  {
    slug: "4planet",
    universe: "4PLANET",
    title: "4PLANET",
    eyebrow: "CORE PROJECT / ORGANISATION",
    state: "ACTIVE",
    priority: "P0",
    accent: "brand",
    summary: "Living Planet Intelligence — one integrated system connecting truth, understanding, action and proof.",
    why: "Build the world's most useful integrated intelligence, coordination and action infrastructure for a living planet.",
    now: "Public product proof, canonical truth convergence, Gold References, users/science and first money move in parallel.",
    next: "Strengthen public proof while shared semantic core, release system and capital conversion mature underneath it.",
    aiPlan: "Protect P0 product lineage; converge truth contracts; advance Gold References; convert capital; keep BRAIN/release evidence current.",
    evidence: "Strategy & Goal Cascade v4.0 · D13–D17 · Founder Control / WBS",
    owner: "ODIN / AXE",
    authority: "BRAIN / FOUNDER CONTROL",
    freshness: "Verified against current 18 Aug Founder Control",
    externalUrl: "https://4planet.org",
    milestones: [
      { label: "Goal Cascade v4 locked", done: true },
      { label: "ONE CORE doctrine locked", done: true },
      { label: "LABS Human Project OS activated", done: true },
      { label: "First external money", done: false },
      { label: "First funded partner-led delivery", done: false },
    ],
    roadmap: common4PlanetRoadmap,
    processes: [
      { name: "PRODUCT", state: "ACTIVE", text: "ONE INTERFACE + ATLAS + SPECIES + LIVING SYSTEMS + IMPACT" },
      { name: "TRUTH", state: "P0", text: "Identity / claim / source / quality convergence" },
      { name: "PROOF", state: "ACTIVE", text: "Jaguar + Orca Product Gold; FOOD organisational Gold" },
      { name: "CAPITAL", state: "ACTIVE", text: "First money + diversified runway conversion" },
      { name: "BRAIN", state: "CONTINUOUS", text: "Recovery / learning / control of control" },
    ],
    tasks: [
      { text: "Finish strongest recipient-ready public proof without ground-up rewrite", owner: "AI", state: "ACTIVE" },
      { text: "Converge source / identity / claim seams", owner: "AI", state: "ACTIVE" },
      { text: "Advance first-money routes and deadline queue", owner: "AI", state: "ACTIVE" },
      { text: "Founder JUDGE only at material release/creative decisions", owner: "FOUNDER", state: "AS NEEDED" },
    ],
    founderDecisions: ["Judge major public-product/release candidates when AXE presents a bounded decision."],
  },
  {
    slug: "4planet/one-interface",
    universe: "4PLANET",
    parent: "4planet",
    title: "ONE INTERFACE",
    eyebrow: "PUBLIC INTEGRATION",
    state: "PUBLIC",
    priority: "P0",
    accent: "brand",
    summary: "The coherent public front door bringing the 4PLANET product family together.",
    why: "Give a real visitor one credible world instead of disconnected prototypes.",
    now: "Accepted public baseline remains protected while improvements move through bounded exact-SHA candidates.",
    next: "Advance premium coherence and truthful product integration without a ground-up rewrite.",
    aiPlan: "Use small candidate branches, browser QA, exact-SHA evidence and release promotion only after acceptance.",
    evidence: "Current production lineage / release controls",
    owner: "AXE / PRODUCT",
    authority: "PRODUCT CANON / RELEASE",
    freshness: "Current release-line projection",
    externalUrl: "https://4planet.org",
    milestones: [
      { label: "Public production baseline", done: true },
      { label: "Exact-SHA convergence gate", done: true },
      { label: "Premium final coherence", done: false },
    ],
    processes: [
      { name: "BUILD", state: "ACTIVE", text: "Bounded product deltas" },
      { name: "QA", state: "ACTIVE", text: "Desktop/mobile/browser contracts" },
      { name: "RELEASE", state: "CONTROLLED", text: "Exact artifact promotion" },
    ],
    tasks: [
      { text: "Resolve remaining product/brand seams", owner: "AI", state: "NEXT" },
      { text: "Founder JUDGE final premium release candidate", owner: "FOUNDER", state: "GATED" },
    ],
  },
  {
    slug: "4planet/atlas",
    universe: "4PLANET",
    parent: "4planet",
    title: "ATLAS",
    eyebrow: "PUBLIC PRODUCT",
    state: "ACTIVE",
    priority: "P0",
    accent: "ocean",
    summary: "Spatial interface for records, observations, signals, places, species and living-system context.",
    why: "Let people see where living-planet intelligence exists without collapsing source, place or time semantics.",
    now: "Shared identity, context preservation and Gold Reference integration are the highest-value seams.",
    next: "Deepen Jaguar/Orca and reusable ATLAS Window integration on the shared core.",
    aiPlan: "Keep map rendering subordinate to canonical identity/provenance; build reusable spatial projections rather than another data world.",
    evidence: "D13 Gold doctrine · current ATLAS product authority",
    owner: "AXE / CODEX",
    authority: "ATLAS / BRAIN",
    freshness: "Current 18 Aug product context",
    externalUrl: "https://4planet.org/atlas",
    milestones: [
      { label: "MapLibre world engine", done: true },
      { label: "Context-preserving product switching", done: true },
      { label: "Reusable ATLAS Window", done: false },
    ],
    processes: [
      { name: "MAP ENGINE", state: "ACTIVE", text: "Spatial rendering + camera/context" },
      { name: "TRUTH", state: "ACTIVE", text: "Occurrence / place / time semantics" },
      { name: "GOLD", state: "ACTIVE", text: "Jaguar + Orca transfer" },
    ],
    tasks: [{ text: "Integrate reusable ATLAS Window with shared entity context", owner: "AI", state: "NEXT" }],
  },
  {
    slug: "4planet/species",
    universe: "4PLANET",
    parent: "4planet",
    title: "SPECIES",
    eyebrow: "PUBLIC PRODUCT",
    state: "ACTIVE",
    priority: "P0",
    accent: "species",
    summary: "Discover, understand and care about life on Earth — with evidence always available.",
    why: "Create a compelling doorway into species, relationships, places and living systems without becoming an AI-guess encyclopedia.",
    now: "Jaguar and Orca are Product Gold References; transferability and shared machinery matter more than feature count.",
    next: "Close shared Gold contracts, then prove an unlike-species transfer test.",
    aiPlan: "Build Emotion first → Understanding second → Evidence always available; reuse the same claim/source/identity contracts.",
    evidence: "SPECIES Canon · D13 · SPEC-11/12",
    owner: "AXE / PRODUCT",
    authority: "SPECIES / BRAIN",
    freshness: "Current 18 Aug SPECIES authority",
    externalUrl: "https://4planet.org/species",
    milestones: [
      { label: "SPECIES Canon", done: true },
      { label: "Jaguar Gold candidate", done: true },
      { label: "Orca Gold shared machinery", done: false },
      { label: "Unlike-species transfer test", done: false },
    ],
    processes: [
      { name: "IDENTITY", state: "ACTIVE", text: "Species identity + external assertions" },
      { name: "PROFILE", state: "ACTIVE", text: "Encounter → understand → inspect" },
      { name: "GOLD", state: "P0", text: "Jaguar + Orca reusable proof" },
    ],
    tasks: [
      { text: "Close Orca/Jaguar shared Gold machinery", owner: "AI", state: "ACTIVE" },
      { text: "Prove sparse/unlike-species transfer", owner: "AI", state: "NEXT" },
    ],
    founderDecisions: ["Judge premium product quality before a new production release."],
  },
  {
    slug: "4planet/living-systems",
    universe: "4PLANET",
    parent: "4planet",
    title: "LIVING SYSTEMS",
    eyebrow: "INTELLIGENCE ENGINE",
    state: "ACTIVE",
    priority: "P0/P1",
    accent: "earth",
    summary: "Relationship and dependency intelligence: what depends on what, what functions matter and where evidence is incomplete.",
    why: "Turn isolated records into system understanding while preserving uncertainty and provenance.",
    now: "Shared engine is converging on the same canonical identity/claim/source contracts as ATLAS and SPECIES.",
    next: "Strengthen source-linked decision-grade relationships and product projections.",
    aiPlan: "Deepen evidence and relation quality before breadth; propagate corrected semantics into every public projection.",
    evidence: "D13 ONE CORE doctrine · current Living Systems authority",
    owner: "AXE / TRUTH",
    authority: "BRAIN / LIVING SYSTEMS",
    freshness: "Current 18 Aug truth context",
    externalUrl: "https://4planet.org/living-systems",
    processes: [
      { name: "RELATIONS", state: "ACTIVE", text: "Evidence-linked dependency graph" },
      { name: "CLAIMS", state: "ACTIVE", text: "Scope / evidence / uncertainty" },
      { name: "PROJECTION", state: "NEXT", text: "Reusable public views" },
    ],
    tasks: [{ text: "Converge relation/claim model with shared truth spine", owner: "AI", state: "ACTIVE" }],
  },
  {
    slug: "4planet/impact",
    universe: "4PLANET",
    parent: "4planet",
    title: "IMPACT",
    eyebrow: "ACTION PRODUCT",
    state: "ACTIVE",
    priority: "P0/P1",
    accent: "impact",
    summary: "Action and proof layer that keeps contribution, delivery, outcome and impact explicitly separate.",
    why: "Make credible action easier without pretending payment or participation automatically equals ecological impact.",
    now: "First operator/method/economics/proof/delivery pathway is being matured in parallel with the public system.",
    next: "Close one qualified operator and one financed/paid pilot path with auditable proof states.",
    aiPlan: "Build one complete delivery chain before multiplying units; preserve proof boundaries in product and commercial material.",
    evidence: "Goal v4 · D13 · current IMPACT/business-model authority",
    owner: "AXE / IMPACT",
    authority: "IMPACT / BRAIN",
    freshness: "Current 18 Aug business-model context",
    externalUrl: "https://4planet.org/impact",
    processes: [
      { name: "OPERATOR", state: "ACTIVE", text: "Qualified delivery partner path" },
      { name: "ECONOMICS", state: "ACTIVE", text: "Pilot economics / proof grammar" },
      { name: "DELIVERY", state: "NEXT", text: "Financed pilot → evidence" },
    ],
    tasks: [{ text: "Close first operator + financed pilot route", owner: "AI", state: "ACTIVE" }],
  },
  {
    slug: "founder-control",
    universe: "4PLANET",
    parent: "4planet",
    title: "FOUNDER CONTROL",
    eyebrow: "HUMAN CONTROL INTERFACE",
    state: "BUILDING",
    priority: "P1 LAB",
    accent: "violet",
    summary: "Human-readable control surface for goals, projects, proof, money, learning and Founder-only actions.",
    why: "Make the organisation inspectable without turning chats into the operating system.",
    now: "LABS is becoming the first human Project OS; safe public/private projection remains the structural boundary.",
    next: "Connect a verified read-only BRAIN projection adapter.",
    aiPlan: "Compress canonical state into useful human views; never become a second status database.",
    evidence: "D17 · LABS-5/6/7 · BRAIN-13",
    owner: "AXE / BRAIN",
    authority: "FOUNDER CONTROL / BRAIN",
    freshness: "Current LABS build projection",
    milestones: [
      { label: "D17 architecture locked", done: true },
      { label: "Reusable project grammar", done: true },
      { label: "Safe automatic projection adapter", done: false },
    ],
    tasks: [{ text: "Build BRAIN → LABS safe projection adapter", owner: "AI", state: "NEXT" }],
    founderDecisions: ["Judge whether LABS mosaic becomes preferred daily Founder project interface."],
  },
  {
    slug: "4planet-university",
    universe: "4PLANET",
    parent: "4planet",
    title: "4PLANET UNIVERSITY",
    eyebrow: "LEARNING EXPERIMENT",
    state: "QUEUED",
    priority: "LAB QUEUE",
    accent: "culture",
    summary: "Source-linked learning paths for understanding life, living systems and planetary action.",
    why: "Test whether the same truth core can become a compelling learning product without a parallel knowledge system.",
    now: "Concept retained; not displacing current product, proof or capital work.",
    next: "Define one tiny learning journey against an already mature Gold Reference.",
    aiPlan: "Use existing verified intelligence only; start with one bounded learning loop.",
    evidence: "D16 idea intake · LABS-2/3",
    owner: "AXE / PRODUCT",
    authority: "LABS / PROJECT FACTORY",
    freshness: "Idea state verified 18 Aug",
    tasks: [{ text: "Define one Gold-backed learning journey", owner: "AI", state: "QUEUED" }],
  },
  {
    slug: "food-app",
    universe: "4PLANET",
    parent: "4planet",
    title: "FOOD APP",
    eyebrow: "DECISION INTERFACE EXPERIMENT",
    state: "QUEUED",
    priority: "AFTER FOOD GOLD",
    accent: "food",
    summary: "Interactive expression of the Everyday Protein Choice reference — no fake green score and no medical advice.",
    why: "Test whether decision-grade FOOD intelligence can become an actually useful everyday interface.",
    now: "Waiting for the underlying FOOD Gold loop to become strong enough to deserve a product expression.",
    next: "Prototype after evidence, choice framing and limitations survive user/expert challenge.",
    aiPlan: "Hold feature work; strengthen FOOD Gold evidence first, then prototype a no-score decision interface.",
    evidence: "D12 FOOD Gold Reference · D16 LABS",
    owner: "AXE / FOOD",
    authority: "FOOD PROJECT / BRAIN",
    freshness: "Current 18 Aug FOOD gate",
    tasks: [{ text: "Finish FOOD Gold evidence / user / expert loop", owner: "AI", state: "DEPENDENCY" }],
  },
  {
    slug: "nature-game",
    universe: "4PLANET",
    parent: "4planet",
    title: "NATURE GAME",
    eyebrow: "WILD LAB",
    state: "EXPERIMENT",
    priority: "SURPLUS CAPACITY",
    accent: "culture",
    summary: "Playful ecological relationship experiment with simulation kept visibly separate from observed truth.",
    why: "Keep room for strange ideas with asymmetric learning or cultural upside.",
    now: "Idea retained, not active P0 work.",
    next: "Build the smallest playable relationship mechanic when surplus capacity is real.",
    aiPlan: "Do nothing until surplus capacity is genuine; then test one mechanic, not a game universe.",
    evidence: "D16 idea intake · LABS-3",
    owner: "AXE / 4CULTURE",
    authority: "LABS / PROJECT FACTORY",
    freshness: "Idea state verified 18 Aug",
    tasks: [{ text: "Tiny playable relationship mechanic", owner: "AI", state: "HOLD" }],
  },
  {
    slug: "odin",
    universe: "ODIN",
    title: "ODIN",
    eyebrow: "FOUNDER / PERSONAL PROJECT UNIVERSE",
    state: "ACTIVE",
    priority: "PROTECTED",
    accent: "odin",
    summary: "Public and personal project universe around Odin Oddekalv, kept separate from 4PLANET truth and company systems.",
    why: "Keep Founder work, creative projects and personal ventures legible without contaminating 4PLANET authority.",
    now: "Only public-safe project references are shown here; private finance/health/legal systems are intentionally excluded.",
    next: "Add verified public projects through the same project grammar as they become relevant to LABS.",
    aiPlan: "Maintain separation of worlds; only project public-safe canonical state into this surface.",
    evidence: "D17 separation rule · public site references",
    owner: "ODIN / AXE",
    authority: "ODIN BRAIN / relevant project authority",
    freshness: "Public-safe placeholder projection",
    externalUrl: "https://odinoddekalv-site.pages.dev/",
    processes: [{ name: "PUBLIC", state: "ACTIVE", text: "Founder-facing public identity/projects only" }],
    tasks: [{ text: "Keep private Founder systems off public LABS", owner: "AI", state: "CONTINUOUS" }],
  },
  {
    slug: "odin/oo-foto",
    universe: "ODIN",
    parent: "odin",
    title: "OO FOTO",
    eyebrow: "PHOTOGRAPHY",
    state: "ACTIVE",
    priority: "SELECTIVE",
    accent: "odin",
    summary: "Odin's photography practice and related creative opportunities.",
    why: "Preserve a distinct creative/professional project path outside 4PLANET product authority.",
    now: "Included only as a public-safe project identity; operational/private details are not exposed here.",
    next: "Project deeper only when a public-safe canonical pack is selected for LABS.",
    aiPlan: "Avoid inventing portfolio/project state; use verified project records when connected.",
    evidence: "Existing OO FOTO project authority",
    owner: "ODIN / AXE",
    authority: "OO FOTO PROJECT",
    freshness: "Identity-only projection",
  },
  {
    slug: "p4nther",
    universe: "P4NTHER",
    title: "P4NTHER",
    eyebrow: "INDEPENDENT PROJECT UNIVERSE",
    state: "ACTIVE",
    priority: "SEPARATE WORLD",
    accent: "panther",
    summary: "A separate project universe with shared infrastructure where appropriate, but independent meaning and product logic.",
    why: "Preserve P4NTHER as its own world while benefiting from reusable operating infrastructure.",
    now: "Public P4NTHER OS2 prototype exists; LABS only surfaces a clean entry and project-state shell.",
    next: "Project verified P4NTHER subprojects through the same grammar without merging its truth with 4PLANET.",
    aiPlan: "Reuse project-system mechanics, not 4PLANET semantics.",
    evidence: "4P Websider · P4NTHER OS2 public reference",
    owner: "ODIN / P4NTHER PL",
    authority: "P4NTHER PROJECT",
    freshness: "Public-reference projection",
    externalUrl: "https://p4nther-os2-cx.pages.dev/",
    processes: [{ name: "OS", state: "PUBLIC", text: "Current public prototype entry" }],
    tasks: [{ text: "Add verified P4NTHER project hierarchy when canonical state is selected", owner: "AI", state: "NEXT" }],
  },
  {
    slug: "p4nther/os",
    universe: "P4NTHER",
    parent: "p4nther",
    title: "P4NTHER OS",
    eyebrow: "PUBLIC PRODUCT / CONTROL SURFACE",
    state: "PUBLIC",
    priority: "REFERENCE",
    accent: "panther",
    summary: "Current public P4NTHER front + OS prototype referenced from the 4P websites register.",
    why: "Give the P4NTHER world a direct working interface while preserving its separate identity.",
    now: "Public reference exists; LABS does not infer deeper current state from the URL alone.",
    next: "Connect verified P4NTHER project data if/when selected for active LABS projection.",
    aiPlan: "Keep state explicit; do not infer roadmap or delivery claims from a prototype surface.",
    evidence: "4P Websider public reference",
    owner: "P4NTHER PL",
    authority: "P4NTHER PROJECT",
    freshness: "URL verified from Drive register",
    externalUrl: "https://p4nther-os2-cx.pages.dev/",
  },
];

export const projectBySlug = (slug: string) => projects.find((project) => project.slug === slug);
export const childrenOf = (slug: string) => projects.filter((project) => project.parent === slug);
export const universeRoots = projects.filter((project) => !project.parent && ["4planet", "odin", "p4nther"].includes(project.slug));
export const universeProjects = (universe: LabUniverse) => projects.filter((project) => project.universe === universe);

export const founderQueue = projects.flatMap((project) =>
  (project.founderDecisions ?? []).map((decision) => ({ project: project.title, slug: project.slug, decision }))
);

export const recentSystemMoves = [
  ["LABS V2", "Project-universe mosaic + deeper project grammar", "BUILDING"],
  ["D17", "LABS + Project Overview separated but connected", "LOCKED"],
  ["BRAIN-13", "AXE fresh-context recovery guard", "ACTIVE"],
  ["LABS-7", "Safe BRAIN projection adapter", "NEXT"],
  ["TRUTH-10", "Source authority + corroboration policy", "ACTIVE"],
] as const;
