export type LabState = "ACTIVE" | "BUILDING" | "QUEUED" | "HOLD" | "EXPERIMENT" | "PUBLIC" | "CONFLICT";
export type LabUniverse = "4PLANET" | "ODIN" | "P4NTHER" | "SANDBOX";
export type LabKind = "ROOT" | "CORE" | "DOMAIN" | "MISSION" | "PRODUCT" | "SYSTEM" | "LAB";
export type AccentToken =
  | "brand"
  | "nature"
  | "ocean"
  | "earth"
  | "sapiens"
  | "culture"
  | "capital"
  | "content"
  | "research"
  | "field"
  | "ambassadors"
  | "product"
  | "odin"
  | "panther"
  | "sandbox";

export type Milestone = { label: string; done: boolean; note?: string };
export type RoadmapItem = { stage: string; title: string; text: string };
export type ProcessItem = { name: string; state: string; text: string };
export type TaskItem = { text: string; owner: "AI" | "FOUNDER" | "MIXED"; state: string };
export type ProjectAsset = { label: string; href: string; kind: "WEB" | "REPO" | "DOC" | "PREVIEW" | "SYSTEM" };

export type LabProject = {
  slug: string;
  universe: LabUniverse;
  kind: LabKind;
  parent?: string;
  title: string;
  eyebrow: string;
  state: LabState;
  priority: string;
  accent: AccentToken;
  summary: string;
  why: string;
  now: string;
  next: string;
  aiPlan: string;
  evidence: string;
  owner: string;
  authority: string;
  freshness: string;
  externalUrl?: string;
  milestones?: Milestone[];
  roadmap?: RoadmapItem[];
  processes?: ProcessItem[];
  tasks?: TaskItem[];
  founderDecisions?: string[];
  assets?: ProjectAsset[];
  relatedSlugs?: string[];
};

export const verifiedAt = "19 AUG 2026";
export const projectionState = "MANUAL BRAIN PROJECTION · READ ONLY";

const activeProjectRoadmap: RoadmapItem[] = [
  { stage: "NOW", title: "MOVE THE NEXT VERIFIED THING", text: "Protect the current critical path and close the smallest evidence-backed unit that changes reality." },
  { stage: "NEXT", title: "CONNECT THE OUTPUT", text: "Propagate accepted learning into product, truth, capital, delivery or the next project gate." },
  { stage: "LATER", title: "TRANSFER WITHOUT FORKING", text: "Reuse the proven pattern through the same BRAIN, contracts and project grammar." },
];

const commonAssets: ProjectAsset[] = [
  { label: "4PLANET website", href: "https://4planet.org", kind: "WEB" },
  { label: "4PLANET repository", href: "https://github.com/odinskogen-dev/4Planet.05", kind: "REPO" },
];

function mission(input: {
  slug: string;
  parent: string;
  title: string;
  accent: AccentToken;
  state?: LabState;
  priority?: string;
  summary: string;
  now: string;
  next: string;
  authority: string;
  founderDecisions?: string[];
  externalUrl?: string;
}): LabProject {
  return {
    slug: input.slug,
    universe: "4PLANET",
    kind: "MISSION",
    parent: input.parent,
    title: input.title,
    eyebrow: "MISSION / WAVE 01",
    state: input.state ?? "QUEUED",
    priority: input.priority ?? "MISSION",
    accent: input.accent,
    summary: input.summary,
    why: "Turn one bounded planetary problem into an intelligence → ecosystem → solutions → acceleration pathway without creating a separate truth system.",
    now: input.now,
    next: input.next,
    aiPlan: "Use the shared 4PLANET truth spine, source controls, actor/solution intelligence and Project Factory. Deepen only when evidence or current priority justifies it.",
    evidence: "Current 4PLANET Mission architecture / Knowledge OS / Project Factory",
    owner: "AXE / MISSION ENGINE",
    authority: input.authority,
    freshness: "Current manual BRAIN projection · 19 Aug 2026",
    externalUrl: input.externalUrl,
    roadmap: activeProjectRoadmap,
    processes: [
      { name: "INTEL", state: "SHARED", text: "Source-linked problem and system intelligence" },
      { name: "ECOSYSTEM", state: "SHARED", text: "Actors, dependencies, places and delivery routes" },
      { name: "SOLUTIONS", state: "SHARED", text: "Existing solutions, evidence, gaps and constraints" },
      { name: "ACCELERATE", state: "GATED", text: "Capital, partner, user or field acceleration only when justified" },
    ],
    founderDecisions: input.founderDecisions,
    assets: input.externalUrl ? [{ label: "Public surface", href: input.externalUrl, kind: "WEB" }] : undefined,
  };
}

export const projects: LabProject[] = [
  {
    slug: "4planet",
    universe: "4PLANET",
    kind: "ROOT",
    title: "4PLANET",
    eyebrow: "PRIMARY PROJECT UNIVERSE",
    state: "ACTIVE",
    priority: "P0",
    accent: "brand",
    summary: "Living Planet Intelligence — one integrated system connecting truth, understanding, action, proof and learning.",
    why: "Build the world's most useful integrated intelligence, coordination and action infrastructure for a living planet.",
    now: "Public product proof, shared truth infrastructure, Gold References, users/science, capital and delivery move in parallel.",
    next: "Keep the strongest public proof moving while the shared core, first money and first verified delivery route close underneath it.",
    aiPlan: "Protect the two-lane runtime: build/intelligence/proof plus capital/runway/delivery. Re-rank from evidence, not chat momentum.",
    evidence: "Strategy & Goal Cascade v4.0 · D13–D17 · current Founder Control / WBS",
    owner: "ODIN / AXE",
    authority: "4PLANET BRAIN / FOUNDER CONTROL",
    freshness: "Fresh-context recovery 19 Aug 2026",
    externalUrl: "https://4planet.org",
    assets: commonAssets,
    milestones: [
      { label: "Goal Cascade v4 locked", done: true },
      { label: "ONE CORE product/truth doctrine locked", done: true },
      { label: "LABS Human Project OS activated", done: true },
      { label: "First external money", done: false },
      { label: "First funded partner-led delivery", done: false },
    ],
    roadmap: [
      { stage: "NOW", title: "BUILD + PROVE + FUND", text: "Public proof, semantic core, Gold References, real users/science and first money move together." },
      { stage: "NEXT", title: "CONNECT THE MACHINE", text: "Intelligence → useful decision → challenge → solution/actor → capital → delivery → evidence." },
      { stage: "LATER", title: "TRANSFER + SCALE", text: "Repeat proven shared machinery without multiplying truth systems." },
    ],
    processes: [
      { name: "PRODUCT", state: "ACTIVE", text: "ONE INTERFACE + ATLAS + SPECIES + LIVING SYSTEMS + IMPACT" },
      { name: "TRUTH", state: "P0", text: "Identity / claim / source / quality convergence" },
      { name: "PROOF", state: "ACTIVE", text: "Jaguar + Orca Product Gold; FOOD organisational Gold" },
      { name: "CAPITAL", state: "ACTIVE", text: "First money + diversified runway conversion" },
      { name: "DELIVERY", state: "ACTIVE", text: "First qualified operator + financed pilot path" },
      { name: "BRAIN", state: "CONTINUOUS", text: "Recovery / learning / control of control" },
    ],
    tasks: [
      { text: "Finish strongest recipient-ready public proof without ground-up rewrite", owner: "AI", state: "ACTIVE" },
      { text: "Converge source / identity / claim seams", owner: "AI", state: "ACTIVE" },
      { text: "Advance first-money routes and application/deadline queue", owner: "AI", state: "ACTIVE" },
      { text: "Judge bounded release/creative decisions presented by AXE", owner: "FOUNDER", state: "AS NEEDED" },
    ],
    founderDecisions: ["Judge major public-product/release candidates when AXE presents a bounded decision."],
  },
  {
    slug: "4planet/naturebrain",
    universe: "4PLANET",
    kind: "SYSTEM",
    parent: "4planet",
    title: "NATUREBRAIN",
    eyebrow: "SHARED NATURE INTELLIGENCE",
    state: "ACTIVE",
    priority: "P0",
    accent: "nature",
    summary: "Human-facing project view over 4PLANET's canonical nature intelligence, Planet Model and source/claim system.",
    why: "Make accumulated nature intelligence inspectable and reusable without creating a second truth store beside BRAIN.",
    now: "BRAIN remains the authority; NATUREBRAIN is a project/projection layer for planetary truth, source quality and relationships.",
    next: "Strengthen shared identity, claim, relation, source-quality and safe projection contracts used by every public product.",
    aiPlan: "Converge semantics once, preserve raw sources, score source dimensions separately, and propagate accepted corrections to every consumer.",
    evidence: "D13 ONE CORE doctrine · TRUTH workstream · Source Trust doctrine",
    owner: "AXE / BRAIN / TRUTH",
    authority: "4PLANET BRAIN / KNOWLEDGE OS",
    freshness: "Fresh-context recovery 19 Aug 2026",
    milestones: [
      { label: "Single canonical truth-core doctrine", done: true },
      { label: "Source authority/corroboration doctrine", done: true },
      { label: "Stable internal identity convergence", done: false },
      { label: "Verified LABS projection adapter", done: false },
    ],
    processes: [
      { name: "SOURCE", state: "ACTIVE", text: "Authority, method, recency, relevance, independence, rights, uncertainty" },
      { name: "CLAIMS", state: "ACTIVE", text: "Evidence, scope, limitations, review and conflicts" },
      { name: "RELATIONS", state: "ACTIVE", text: "Dependency / pressure / response without semantic collapse" },
      { name: "PROJECTION", state: "BUILDING", text: "Safe product and LABS views over canonical truth" },
    ],
    tasks: [
      { text: "Close remaining semantic/type convergence seams", owner: "AI", state: "ACTIVE" },
      { text: "Build BRAIN → LABS safe projection contract", owner: "AI", state: "NEXT" },
    ],
  },
  {
    slug: "4planet/brand",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "BRAND",
    eyebrow: "IDENTITY / EXPERIENCE",
    state: "ACTIVE",
    priority: "P1",
    accent: "content",
    summary: "The visual, verbal and behavioural system that keeps 4PLANET recognisable across products and public proof.",
    why: "Make separate interfaces feel like one premium 4PLANET universe without flattening their distinct purposes.",
    now: "Premium black/white master surfaces, technical grid language, strong typography and controlled accent behaviour remain the base.",
    next: "Carry the strongest brand grammar consistently through ONE INTERFACE, LABS and Gold Reference surfaces.",
    aiPlan: "Reuse established Brand OS rules, test visually, preserve accessibility and prevent decorative UI noise from outranking information.",
    evidence: "Brand OS / public prototype brand controls / current product runtime",
    owner: "AXE / PRODUCT",
    authority: "4PLANET BRAND AUTHORITY",
    freshness: "Manual projection 19 Aug 2026",
    tasks: [{ text: "Propagate approved premium grammar into active product candidates", owner: "AI", state: "ACTIVE" }],
  },
  {
    slug: "4planet/content",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "CONTENT",
    eyebrow: "EDITORIAL / STORY / PROOF",
    state: "ACTIVE",
    priority: "P1",
    accent: "content",
    summary: "Editorial, documentary and narrative production tied back to verified source packs and product journeys.",
    why: "Translate living-planet truth into understanding and culture without separating story from evidence.",
    now: "Human Voice, M4GAZINE, media relationships and product narrative systems exist as controlled workstreams.",
    next: "Turn strongest proof events and Gold journeys into reusable editorial/story assets without AI-sounding filler.",
    aiPlan: "Source pack → claim map → story → audit → founder judgement → reuse; no publication without release authority.",
    evidence: "Human Voice programme · M4GAZINE / Media x100 controls",
    owner: "AXE / CONTENT",
    authority: "BRAIN / EDITORIAL CONTROLS",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "4planet/capital",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "CAPITAL",
    eyebrow: "RUNWAY / FIRST MONEY",
    state: "ACTIVE",
    priority: "P0",
    accent: "capital",
    summary: "Applications, funders, pilots, patrons and partners routed against live project capital plans and proof readiness.",
    why: "Convert the strongest 4PLANET work into enough non-dilutive and commercial capital to build and deliver the mission.",
    now: "Canonical capital truth remains 14 submissions / 0 awarded / 0 contracted / 0 cash. First-money conversion is a hard 90-day gate.",
    next: "Push the strongest current application, patron/funder, paid-proof and Founding Partner routes toward actual money — not pipeline theatre.",
    aiPlan: "Deadline-first qualification, Project Capital Plans, reusable proposals, proof packs and async-first conversion under Founder release authority.",
    evidence: "Current Capital authority / Founder Control / Active Engine",
    owner: "AXE / CAPITAL",
    authority: "CAPITAL BRAIN / FOUNDER RELEASE",
    freshness: "Fresh-context projection 19 Aug 2026",
    milestones: [
      { label: "Capital architecture + target systems built", done: true },
      { label: "14 submissions recorded", done: true },
      { label: "First external money", done: false },
    ],
    tasks: [
      { text: "Complete live Project Capital Plans for fundable active projects", owner: "AI", state: "ACTIVE" },
      { text: "Advance qualified applications before deadline", owner: "AI", state: "ACTIVE" },
      { text: "Release only messages/asks that require Founder authority", owner: "FOUNDER", state: "GATED" },
    ],
    founderDecisions: ["Approve only bounded sends/asks that cross Founder release authority."],
  },
  {
    slug: "4planet/product",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "PRODUCT",
    eyebrow: "PUBLIC PRODUCT FAMILY",
    state: "ACTIVE",
    priority: "P0",
    accent: "product",
    summary: "ONE INTERFACE, ATLAS, SPECIES, LIVING SYSTEMS and IMPACT — separate interfaces on one canonical core.",
    why: "Turn accumulated intelligence into a coherent, useful and compelling public product family.",
    now: "Product Gold work, premium ONE INTERFACE completion and exact-SHA release controls are active.",
    next: "Close the strongest visible proof and reusable Gold machinery before multiplying surfaces.",
    aiPlan: "Build small exact-SHA candidates, browser-test them, preserve public truth boundaries and propagate reusable components across the family.",
    evidence: "D13 Product Gold doctrine · current ONE INTERFACE release lineage",
    owner: "AXE / PRODUCT / CODEX",
    authority: "PRODUCT CANON / RELEASE CONTROLS",
    freshness: "Manual projection 19 Aug 2026",
    assets: commonAssets,
    relatedSlugs: ["4planet/e4rth/species"],
  },
  {
    slug: "4planet/research",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "RESEARCH",
    eyebrow: "SCIENCE / SOURCE / REVIEW",
    state: "ACTIVE",
    priority: "P0/P1",
    accent: "research",
    summary: "Primary-source research, expert challenge, rights checking and scientific review feeding the shared truth core.",
    why: "Keep the public system useful and trustworthy by making evidence quality and challenge part of production.",
    now: "Researchers & Institutions x100 and source-quality controls exist; Gold domains require evidence-linked challenge rather than self-certification.",
    next: "Route the most material Gold/solution claims through independent expert challenge and update the system from what survives.",
    aiPlan: "Primary sources first; independent corroboration over link count; preserve conflicts and limitations; never let AI summary become authority.",
    evidence: "Research x100 programme · Source Trust doctrine",
    owner: "AXE / RESEARCH",
    authority: "BRAIN / SOURCE + CLAIM CONTROLS",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "4planet/field-partners",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "FIELD PARTNERS",
    eyebrow: "DELIVERY / OPERATOR NETWORK",
    state: "ACTIVE",
    priority: "P0/P1",
    accent: "field",
    summary: "Qualified real-world operators, technical adapters and proof/MRV routes for delivery-ready Impact pathways.",
    why: "Connect intelligence and capital to credible execution without allowing 4PLANET to claim work it did not deliver.",
    now: "Provider/actor intelligence exists; no provider should be treated as qualified/contracted without current evidence.",
    next: "Close one qualified operator/method/economics/proof chain for the first financed pilot pathway.",
    aiPlan: "Diligence actors, preserve delivery/proof separation, surface only real gates to Founder and avoid partnership inflation.",
    evidence: "IMP-PARTNER controls · current Impact/Field Partner authority",
    owner: "AXE / IMPACT",
    authority: "IMPACT / PARTNER CONTROL",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "4planet/4mbassadors",
    universe: "4PLANET",
    kind: "CORE",
    parent: "4planet",
    title: "4MBASSADORS",
    eyebrow: "PEOPLE / RELATIONSHIPS",
    state: "ACTIVE",
    priority: "P1",
    accent: "ambassadors",
    summary: "Strategic creators, scientists, explorers, athletes and public figures developed from connection toward meaningful collaboration.",
    why: "Extend reach, credibility and participation through real relationships rather than transactional influencer theatre.",
    now: "x100 universe, TOP 20 and FIRST x10 relationship conversion are prepared under async-first controls.",
    next: "Advance only the strongest contextual relationship paths and preserve Founder involvement for high-value moments.",
    aiPlan: "Warm-path intelligence, bespoke asks, collision control and low-burden async progression; no send without authority.",
    evidence: "4MBASSADORS x100 / closure controls",
    owner: "AXE / RELATIONSHIPS",
    authority: "BRAIN / RELATIONSHIP CONTROL",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "4planet/product/one-interface",
    universe: "4PLANET",
    kind: "PRODUCT",
    parent: "4planet/product",
    title: "ONE INTERFACE",
    eyebrow: "PUBLIC FRONT DOOR",
    state: "PUBLIC",
    priority: "P0",
    accent: "brand",
    summary: "The coherent public 4PLANET experience that connects the product family and flagship journeys.",
    why: "Give a first-time visitor one credible world instead of disconnected prototypes.",
    now: "A protected public baseline exists; new candidates move through exact-SHA gates rather than ground-up rewrites.",
    next: "Finish premium coherence, human-first narrative and product integration toward Founder JUDGE/RELEASE.",
    aiPlan: "Small bounded deltas → browser QA → exact-SHA evidence → Founder judgement → promote the same accepted artifact.",
    evidence: "Current release lineage / PR gates / product controls",
    owner: "AXE / PRODUCT",
    authority: "PRODUCT / RELEASE",
    freshness: "Current release-line projection",
    externalUrl: "https://4planet.org",
    assets: commonAssets,
    milestones: [
      { label: "Public production baseline", done: true },
      { label: "Exact-SHA convergence gate", done: true },
      { label: "Founder-approved premium release candidate", done: false },
    ],
    tasks: [
      { text: "Resolve remaining product/brand/narrative seams", owner: "AI", state: "ACTIVE" },
      { text: "Judge final premium candidate", owner: "FOUNDER", state: "GATED" },
    ],
    founderDecisions: ["Founder JUDGE the bounded premium release candidate when presented."],
  },
  {
    slug: "4planet/product/atlas",
    universe: "4PLANET",
    kind: "PRODUCT",
    parent: "4planet/product",
    title: "ATLAS",
    eyebrow: "SPATIAL INTELLIGENCE",
    state: "ACTIVE",
    priority: "P0",
    accent: "ocean",
    summary: "Spatial interface for records, observations, signals, places, species and living-system context.",
    why: "Let people explore where living-planet intelligence exists without collapsing source, place, time or uncertainty semantics.",
    now: "Shared identity, context preservation, source-aware layers and Gold Reference integration remain the highest-value seams.",
    next: "Deepen reusable ATLAS Window / project context and reduce bugs while preserving the same canonical model.",
    aiPlan: "Keep map rendering subordinate to truth contracts; scale through layers and reusable projections rather than a replacement map engine.",
    evidence: "ATLAS authority · D13 · current Product Gold work",
    owner: "AXE / CODEX",
    authority: "ATLAS / BRAIN",
    freshness: "Manual projection 19 Aug 2026",
    externalUrl: "https://4planet.org/atlas",
    assets: [{ label: "ATLAS", href: "https://4planet.org/atlas", kind: "WEB" }, commonAssets[1]],
    milestones: [
      { label: "Shared world/map runtime", done: true },
      { label: "Context-preserving product switching", done: true },
      { label: "Reusable ATLAS Window", done: false },
    ],
    tasks: [{ text: "Integrate reusable ATLAS Window with shared entity context", owner: "AI", state: "ACTIVE" }],
  },
  {
    slug: "4planet/product/living-systems",
    universe: "4PLANET",
    kind: "PRODUCT",
    parent: "4planet/product",
    title: "LIVING SYSTEMS",
    eyebrow: "RELATIONSHIP INTELLIGENCE",
    state: "ACTIVE",
    priority: "P0/P1",
    accent: "earth",
    summary: "Relationship and dependency intelligence: what depends on what, what functions matter and where evidence is incomplete.",
    why: "Turn isolated records into system understanding while preserving uncertainty and provenance.",
    now: "Shared relation/claim machinery is converging with the same canonical source and identity core used by ATLAS and SPECIES.",
    next: "Strengthen source-linked decision-grade relationships and reusable public projections.",
    aiPlan: "Deepen evidence quality before breadth; propagate corrected semantics into every consumer product.",
    evidence: "D13 ONE CORE doctrine · Living Systems authority",
    owner: "AXE / TRUTH",
    authority: "NATUREBRAIN / BRAIN",
    freshness: "Manual projection 19 Aug 2026",
    externalUrl: "https://4planet.org/living-systems",
    assets: [{ label: "Living Systems", href: "https://4planet.org/living-systems", kind: "WEB" }],
  },
  {
    slug: "4planet/product/impact",
    universe: "4PLANET",
    kind: "PRODUCT",
    parent: "4planet/product",
    title: "IMPACT",
    eyebrow: "ACTION / PROOF",
    state: "ACTIVE",
    priority: "P0/P1",
    accent: "nature",
    summary: "Action and proof layer that keeps contribution, delivery, outcome and impact explicitly separate.",
    why: "Make credible action easier without pretending payment or participation automatically equals ecological impact.",
    now: "The first operator/method/economics/proof/delivery pathway is being matured in parallel with the public system.",
    next: "Close one qualified operator and one financed/paid pilot path with auditable proof states.",
    aiPlan: "Build one complete delivery chain before multiplying units; preserve contribution ≠ delivery ≠ outcome ≠ impact everywhere.",
    evidence: "Goal v4 · D13 · IMPACT/business-model authority",
    owner: "AXE / IMPACT",
    authority: "IMPACT / BRAIN",
    freshness: "Manual projection 19 Aug 2026",
    externalUrl: "https://4planet.org/impact",
    assets: [{ label: "IMPACT", href: "https://4planet.org/impact", kind: "WEB" }],
  },
  {
    slug: "4planet/oce4n",
    universe: "4PLANET",
    kind: "DOMAIN",
    parent: "4planet",
    title: "OCE4N",
    eyebrow: "DOMAIN / LIVING OCEAN",
    state: "ACTIVE",
    priority: "DOMAIN",
    accent: "ocean",
    summary: "The living ocean — marine systems, species, pressures, places and solution pathways.",
    why: "Organise marine missions under one shared domain layer without pretending the planet has only four scientific ecosystem categories.",
    now: "WH4LES is an active proof route; marine plastic naming remains an explicit unresolved naming conflict in BRAIN.",
    next: "Deepen active proof and delivery routes while maintaining the rest of the Wave 01 mission portfolio honestly.",
    aiPlan: "Reuse ATLAS/SPECIES/Living Systems and shared actor/solution intelligence across every marine mission.",
    evidence: "Knowledge OS current Mission architecture",
    owner: "AXE / OCE4N",
    authority: "4PLANET MISSION ARCHITECTURE",
    freshness: "Fresh mission-name check 19 Aug 2026",
  },
  {
    slug: "4planet/e4rth",
    universe: "4PLANET",
    kind: "DOMAIN",
    parent: "4planet",
    title: "E4RTH",
    eyebrow: "DOMAIN / LAND + FRESHWATER",
    state: "ACTIVE",
    priority: "DOMAIN",
    accent: "earth",
    summary: "Land, freshwater and terrestrial living systems — including climate, Amazonia, species and restoration.",
    why: "Provide an operational mission layer over terrestrial/freshwater systems while the Planetary Map remains scientifically broader.",
    now: "SPECIES is an active Product Gold track; AM4ZONIA remains a flagship journey/project surface.",
    next: "Use Gold References and decision-grade truth to strengthen transfer across place, species and restoration missions.",
    aiPlan: "Keep one truth core; connect species, place, pressures, actors, solutions and capital without duplicating data.",
    evidence: "Knowledge OS current Mission architecture",
    owner: "AXE / E4RTH",
    authority: "4PLANET MISSION ARCHITECTURE",
    freshness: "Fresh mission-name check 19 Aug 2026",
  },
  {
    slug: "4planet/s4piens",
    universe: "4PLANET",
    kind: "DOMAIN",
    parent: "4planet",
    title: "S4PIENS",
    eyebrow: "DOMAIN / HUMAN SYSTEMS",
    state: "ACTIVE",
    priority: "DOMAIN",
    accent: "sapiens",
    summary: "Human systems that shape planetary outcomes — needs, consumption, value chains, pressure, response and agency.",
    why: "Make planetary systems human-relevant without collapsing dependency, pressure and response into one story.",
    now: "FOOD is an active organisational Gold Reference; HOMO SAPIENS / Human Systems Atlas is a new active project direction.",
    next: "Use FOOD as the first complete decision/action loop and connect SAPIENS Atlas/value-chain views to the same Planet Model.",
    aiPlan: "Model PLANET → HUMANS dependencies and HUMANS → PLANET pressure/value chains with separate relation classes and source-linked evidence.",
    evidence: "D12 FOOD Gold · SAP-SAPIENS-01 current project direction",
    owner: "AXE / S4PIENS",
    authority: "S4PIENS / BRAIN",
    freshness: "Fresh project context 19 Aug 2026",
  },
  {
    slug: "4planet/4culture",
    universe: "4PLANET",
    kind: "DOMAIN",
    parent: "4planet",
    title: "4CULTURE",
    eyebrow: "DOMAIN / CULTURE",
    state: "ACTIVE",
    priority: "DOMAIN",
    accent: "culture",
    summary: "Cultural systems that shape attention, meaning, imagination and behaviour.",
    why: "Turn truth and evidence into felt relevance, participation and culture without turning communication into propaganda.",
    now: "M4GAZINE, media, film, art and play/learning routes exist at different maturity levels under the same culture domain.",
    next: "Prioritise only cultural work that strengthens truth transmission, participation or active proof.",
    aiPlan: "Use Human Voice, editorial/source controls and reusable product intelligence; keep public cultural claims evidence-led.",
    evidence: "4CULTURE architecture · Human Voice / media / editorial controls",
    owner: "AXE / 4CULTURE",
    authority: "4PLANET MISSION ARCHITECTURE",
    freshness: "Fresh mission-name check 19 Aug 2026",
  },

  mission({
    slug: "4planet/oce4n/wh4les",
    parent: "4planet/oce4n",
    title: "WH4LES",
    accent: "ocean",
    state: "ACTIVE",
    priority: "P0 PROOF",
    summary: "Whale and cetacean intelligence, relationships, pressures and flagship proof journeys.",
    now: "Orca remains a Product Gold Reference and ORCA relationship route is an explicit early-founder-conversation exception.",
    next: "Close Orca Gold machinery and convert the strongest relationship/proof route without unsupported partnership claims.",
    authority: "WH4LES / SPECIES / BRAIN",
  }),
  mission({
    slug: "4planet/oce4n/cor4l",
    parent: "4planet/oce4n",
    title: "COR4L",
    accent: "ocean",
    summary: "Coral and reef intelligence within the living-ocean domain.",
    now: "Wave 01 mission retained; not currently allowed to displace higher-priority proof routes.",
    next: "Maintain source/actor context and activate deeper work when evidence, partner or capital trigger justifies it.",
    authority: "OCE4N / BRAIN",
  }),
  mission({
    slug: "4planet/oce4n/plastic-clean",
    parent: "4planet/oce4n",
    title: "PL4STIC / CLE4N",
    accent: "ocean",
    state: "CONFLICT",
    priority: "NAMING OPEN",
    summary: "Marine plastic / clean-ocean mission path. BRAIN currently preserves a PL4STIC/CLE4N naming conflict rather than silently choosing one.",
    now: "Delivery direction is important; canonical visible naming remains unresolved in current Knowledge OS.",
    next: "Resolve naming through Founder/canonical authority while continuing evidence-backed plastic delivery preparation underneath it.",
    authority: "OCE4N / KNOWLEDGE OS CONFLICT",
  }),
  mission({
    slug: "4planet/oce4n/rewild-marine",
    parent: "4planet/oce4n",
    title: "RE:WILD MARINE",
    accent: "ocean",
    summary: "Marine restoration mission pathway including locally grounded restoration possibilities.",
    now: "Wave 01 route retained; Oslofjord remains an important place/journey candidate rather than proof of delivery.",
    next: "Develop only evidence-backed operator/solution routes and preserve the difference between possibility and active delivery.",
    authority: "OCE4N / IMPACT / BRAIN",
  }),

  mission({
    slug: "4planet/e4rth/clim4te",
    parent: "4planet/e4rth",
    title: "CLIM4TE",
    accent: "earth",
    summary: "Climate as a living-systems pressure and enabling context across land, freshwater, ocean and human systems.",
    now: "Wave 01 mission retained; not the current lead proof path.",
    next: "Use shared authoritative climate layers/claims where they materially improve active journeys and decisions.",
    authority: "E4RTH / BRAIN",
  }),
  mission({
    slug: "4planet/e4rth/am4zonia",
    parent: "4planet/e4rth",
    title: "AM4ZONIA",
    accent: "nature",
    state: "BUILDING",
    priority: "FLAGSHIP",
    summary: "Amazonia place/system intelligence connecting forest, water, climate, species, people, pressures and solution pathways.",
    now: "A flagship journey direction exists; public claims must remain source/date/limitation aware and avoid invented partners or outcomes.",
    next: "Strengthen the focused journey on the same planetary data system and connect it to SPECIES, Living Systems and AM4ZONIA mission context.",
    authority: "E4RTH / AM4ZONIA / BRAIN",
  }),
  {
    ...mission({
      slug: "4planet/e4rth/species",
      parent: "4planet/e4rth",
      title: "SPECIES",
      accent: "nature",
      state: "ACTIVE",
      priority: "P0 GOLD",
      summary: "Discover, understand and care about life on Earth — a public product and Wave 01 mission route sharing the same canonical species truth.",
      now: "Jaguar and Orca are Product Gold References; transferability and shared machinery matter more than feature count.",
      next: "Close shared Gold contracts and prove an unlike/sparse-species transfer test.",
      authority: "SPECIES CANON / BRAIN",
      externalUrl: "https://4planet.org/species",
      founderDecisions: ["Judge premium SPECIES product quality before a new production release."],
    }),
    milestones: [
      { label: "SPECIES Canon", done: true },
      { label: "Jaguar Gold candidate", done: true },
      { label: "Orca shared Gold machinery", done: false },
      { label: "Unlike-species transfer test", done: false },
    ],
    tasks: [
      { text: "Close Orca/Jaguar shared Gold machinery", owner: "AI", state: "ACTIVE" },
      { text: "Prove sparse/unlike-species transfer", owner: "AI", state: "NEXT" },
    ],
  },
  mission({
    slug: "4planet/e4rth/rewild-land",
    parent: "4planet/e4rth",
    title: "RE:WILD LAND",
    accent: "earth",
    summary: "Terrestrial restoration mission pathway for evidence-backed place/operator/solution routes.",
    now: "Wave 01 mission retained; not currently a lead proof path.",
    next: "Activate deeper work only against a verified place, solution, operator and capital path.",
    authority: "E4RTH / IMPACT / BRAIN",
  }),

  {
    ...mission({
      slug: "4planet/s4piens/food",
      parent: "4planet/s4piens",
      title: "FOOD",
      accent: "sapiens",
      state: "ACTIVE",
      priority: "P0 GOLD",
      summary: "Human food systems and the first organisational Gold Reference: Everyday Protein Choice for an adult Norwegian household grocery shopper.",
      now: "FOOD — PERSON × FOOD × NORWAY v1 is the first full organisational intelligence → choice/action → proof loop.",
      next: "Complete evidence/hotspots → solutions/actors → no-score choice prototype → users/experts → correction → bounded action route → transfer adapter.",
      authority: "D12 FOOD GOLD / S4PIENS / BRAIN",
    }),
    milestones: [
      { label: "Gold Reference scope locked", done: true },
      { label: "Evidence / hotspot map", done: false },
      { label: "No-score choice prototype", done: false },
      { label: "6–10 user sessions + expert challenge", done: false },
      { label: "Bounded action/resource route", done: false },
    ],
    tasks: [
      { text: "Deepen evidence and hotspot model", owner: "AI", state: "ACTIVE" },
      { text: "Build no-score choice prototype when evidence supports it", owner: "AI", state: "NEXT" },
    ],
  },
  mission({
    slug: "4planet/s4piens/energy",
    parent: "4planet/s4piens",
    title: "EN3RGY / EN4RGY",
    accent: "sapiens",
    state: "CONFLICT",
    priority: "NAMING OPEN",
    summary: "Human energy systems mission. BRAIN preserves an EN3RGY/EN4RGY naming conflict rather than silently resolving it.",
    now: "Wave 01 mission retained; canonical spelling remains explicitly unresolved in current Knowledge OS.",
    next: "Resolve naming through canonical authority; deepen only when active project evidence or capital route justifies it.",
    authority: "S4PIENS / KNOWLEDGE OS CONFLICT",
  }),
  mission({
    slug: "4planet/s4piens/circular-city",
    parent: "4planet/s4piens",
    title: "CIRCULAR CITY",
    accent: "sapiens",
    summary: "Urban/circular human-systems mission connecting resources, infrastructure, waste, actors and solutions.",
    now: "Wave 01 mission retained; no separate public truth architecture authorised.",
    next: "Reuse shared Planet Model and Solutions Intelligence when an active proof route emerges.",
    authority: "S4PIENS / BRAIN",
  }),
  mission({
    slug: "4planet/s4piens/f4shion",
    parent: "4planet/s4piens",
    title: "F4SHION",
    accent: "sapiens",
    summary: "Fashion/value-chain human-systems mission connecting demand, production, materials, trade, pressures and response.",
    now: "Wave 01 mission retained; not current P0 execution.",
    next: "Maintain architecture and activate only when source maturity or project opportunity justifies it.",
    authority: "S4PIENS / BRAIN",
  }),

  mission({
    slug: "4planet/4culture/m4gazine",
    parent: "4planet/4culture",
    title: "M4GAZINE",
    accent: "culture",
    state: "ACTIVE",
    priority: "P1",
    summary: "Editorial nature/culture storytelling with source packs, Human Voice and premium publication grammar.",
    now: "Editorial voice, source/claim discipline and media relationship infrastructure exist; publication remains Founder-controlled.",
    next: "Develop fewer stronger source-grounded pieces around verified product/proof events.",
    authority: "4CULTURE / EDITORIAL BRAIN",
  }),
  mission({
    slug: "4planet/4culture/4film",
    parent: "4planet/4culture",
    title: "4FILM",
    accent: "culture",
    summary: "Film and documentary route for living-planet truth, field stories and cultural transmission.",
    now: "Ideas and funding routes exist; no broad production state should be inferred.",
    next: "Activate against a bounded story, rights path, budget and distribution/funding route.",
    authority: "4CULTURE / BRAIN",
  }),
  mission({
    slug: "4planet/4culture/4rt",
    parent: "4planet/4culture",
    title: "4RT",
    accent: "culture",
    summary: "Art/creative mission route that connects life, culture and public attention without weakening truth boundaries.",
    now: "Wave 01 mission retained; no separate operational system is required yet.",
    next: "Use surplus or project-specific capacity when a strong artist/cultural collaboration has evidence and fit.",
    authority: "4CULTURE / BRAIN",
  }),
  mission({
    slug: "4planet/4culture/4play",
    parent: "4planet/4culture",
    title: "4PLAY",
    accent: "culture",
    summary: "Play, interactive learning and game-like routes for understanding living systems and participation.",
    now: "Wave 01 mission retained; Nature Game remains a separate Sandbox experiment until promoted.",
    next: "Test playful interfaces only when they reuse verified intelligence and do not distort ecological truth.",
    authority: "4CULTURE / LABS / BRAIN",
  }),

  {
    slug: "odin",
    universe: "ODIN",
    kind: "ROOT",
    title: "ODIN",
    eyebrow: "FOUNDER SYSTEM / POSITIVE CONTROL",
    state: "ACTIVE",
    priority: "FOUNDER",
    accent: "odin",
    summary: "A calm founder operating system for memory, decisions, learning, processes and personal project continuity.",
    why: "Protect Founder cognition, creativity and continuity while removing avoidable administration and context loss.",
    now: "ODIN BRAIN, Founder OS and Process Library are being designed to accumulate knowledge without putting 4PLANET at risk.",
    next: "Keep the system useful, safe and inviting: better recovery, process reuse, idea capture and minimal Founder burden.",
    aiPlan: "Store durable knowledge once, preserve boundaries with 4PLANET, make processes reusable, and surface only what improves Founder judgement.",
    evidence: "ODIN BRAIN current programme direction / Founder operating decisions",
    owner: "ODIN / AXE",
    authority: "ODIN BRAIN",
    freshness: "Manual projection 19 Aug 2026",
    milestones: [
      { label: "ODIN BRAIN architecture direction established", done: true },
      { label: "Process Library direction established", done: true },
      { label: "Human Founder OS interface matured", done: false },
    ],
    tasks: [{ text: "Build safe shared Founder-grounding without merging private and 4PLANET truth domains", owner: "AI", state: "ACTIVE" }],
  },
  {
    slug: "odin/brain",
    universe: "ODIN",
    kind: "SYSTEM",
    parent: "odin",
    title: "BRAIN",
    eyebrow: "PERSONAL KNOWLEDGE OS",
    state: "ACTIVE",
    priority: "P0 PERSONAL",
    accent: "odin",
    summary: "Durable memory, learning and reconstruction system for Odin — separate from but safely interoperable with 4PLANET where appropriate.",
    why: "Protect what Odin knows, learns and decides so a fresh AI/project lead can recover it without depending on chat memory.",
    now: "Architecture and boundary direction exist; private and 4PLANET worlds must remain controlled rather than casually merged.",
    next: "Strengthen recovery, privacy boundaries and reusable Founder context while keeping project-specific authority separate.",
    aiPlan: "Capture durable facts/decisions/processes, preserve provenance and use explicit bridges instead of copying entire BRAINs together.",
    evidence: "ODIN BRAIN programme direction",
    owner: "AXE / ODIN BRAIN",
    authority: "ODIN BRAIN",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "odin/process-library",
    universe: "ODIN",
    kind: "SYSTEM",
    parent: "odin",
    title: "PROCESS LIBRARY",
    eyebrow: "REUSABLE WORKING METHODS",
    state: "BUILDING",
    priority: "P1",
    accent: "odin",
    summary: "A reusable library of proven ways Odin + AI analyse, build, decide, recover and run projects.",
    why: "Turn repeated good work into reusable processes so quality compounds instead of restarting in every chat.",
    now: "The direction is approved; useful 4PLANET process patterns are candidates for safe transfer where boundaries allow.",
    next: "Capture the highest-value repeatable AXE/Founder workflows and test whether they improve speed without adding bureaucracy.",
    aiPlan: "Extract only demonstrated processes, version them, link evidence/learning and retire processes that stop working.",
    evidence: "Founder ODIN BRAIN / Process Library decision",
    owner: "AXE / ODIN",
    authority: "ODIN BRAIN",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "odin/founder-os",
    universe: "ODIN",
    kind: "SYSTEM",
    parent: "odin",
    title: "FOUNDER OS",
    eyebrow: "DAILY CONTROL / CREATIVE SPACE",
    state: "BUILDING",
    priority: "P1",
    accent: "odin",
    summary: "A low-burden interface for what deserves Odin's attention, what AI is doing and where creative judgement creates leverage.",
    why: "Keep Odin out of task theatre while preserving the creative, strategic and relationship work only the Founder should do.",
    now: "Founder Daily Control rules exist; LABS is now a practical prototype surface for this style of control.",
    next: "Use LABS learnings to make a smaller, private, calmer daily Founder view when the authenticated projection boundary is ready.",
    aiPlan: "Surface top 1–3 Founder-only actions, actual movement, learning, blockers and next critical path — nothing else unless requested.",
    evidence: "D15 Founder Creative Control / BRAIN-12",
    owner: "AXE / ODIN",
    authority: "ODIN BRAIN / FOUNDER",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "odin/idea-vault",
    universe: "ODIN",
    kind: "SYSTEM",
    parent: "odin",
    title: "IDEA VAULT",
    eyebrow: "CREATIVE INTAKE",
    state: "BUILDING",
    priority: "P2",
    accent: "odin",
    summary: "A protected place for ideas that should be remembered, challenged and promoted only when they deserve execution capacity.",
    why: "Let Founder creativity stay abundant without silently reprioritising active critical paths.",
    now: "AXE IDEA + Critical-Path Firewall provide the control logic; a dedicated private UI is not yet connected.",
    next: "Project ideas into a simple incubate / test / promote / hold view once private BRAIN projection is available.",
    aiPlan: "Capture freely, classify honestly, attach hypotheses/evidence, and promote only when expected value beats current work.",
    evidence: "D15 Creative Firewall / D16 LABS doctrine",
    owner: "AXE / ODIN",
    authority: "ODIN BRAIN",
    freshness: "Manual projection 19 Aug 2026",
  },

  {
    slug: "p4nther",
    universe: "P4NTHER",
    kind: "ROOT",
    title: "P4NTHER",
    eyebrow: "STRATEGIC INTELLIGENCE / VENTURE",
    state: "BUILDING",
    priority: "SECONDARY",
    accent: "panther",
    summary: "Strategic intelligence and operating-system concept kept distinct from 4PLANET while reusing safe process infrastructure where appropriate.",
    why: "Preserve a separate strategic/venture world without contaminating 4PLANET mission truth or Founder-private knowledge.",
    now: "A prototype/OS direction exists; it remains subordinate to 4PLANET and Founder critical priorities.",
    next: "Maintain the project coherently and activate deeper build only when it has independent value/capacity.",
    aiPlan: "Share infrastructure/process patterns selectively; keep data, authority and product meaning separate.",
    evidence: "P4NTHER project context / existing prototype lineage",
    owner: "ODIN / AXE",
    authority: "P4NTHER PROJECT",
    freshness: "Manual projection 19 Aug 2026",
    milestones: [{ label: "Separate project identity preserved", done: true }],
  },
  {
    slug: "p4nther/brain",
    universe: "P4NTHER",
    kind: "SYSTEM",
    parent: "p4nther",
    title: "BRAIN",
    eyebrow: "PROJECT INTELLIGENCE",
    state: "BUILDING",
    priority: "P2",
    accent: "panther",
    summary: "P4NTHER-specific intelligence and project memory, separate from 4PLANET and ODIN private truth domains.",
    why: "Keep project context reconstructable without creating authority leakage between different project worlds.",
    now: "Conceptual/project context exists; no broad new architecture should be created without verified need.",
    next: "Use the common Project Factory and recovery controls rather than inventing another management system.",
    aiPlan: "Recover → execute bounded work → write evidence back to the correct P4NTHER authority.",
    evidence: "P4NTHER current context",
    owner: "AXE / P4NTHER",
    authority: "P4NTHER PROJECT",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "p4nther/ops",
    universe: "P4NTHER",
    kind: "CORE",
    parent: "p4nther",
    title: "OPS",
    eyebrow: "OPERATIONS",
    state: "QUEUED",
    priority: "P2",
    accent: "panther",
    summary: "Operational workflows for P4NTHER when the project earns active execution capacity.",
    why: "Keep execution legible without duplicating generic project-management infrastructure.",
    now: "Not current P0 work.",
    next: "Activate only against an independently valuable P4NTHER build objective.",
    aiPlan: "Reuse Project Factory/WBS controls when activated.",
    evidence: "P4NTHER project context",
    owner: "AXE",
    authority: "P4NTHER PROJECT",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "p4nther/intel",
    universe: "P4NTHER",
    kind: "CORE",
    parent: "p4nther",
    title: "INTEL",
    eyebrow: "SIGNALS / RESEARCH",
    state: "QUEUED",
    priority: "P2",
    accent: "panther",
    summary: "Signals, research and synthesis layer for P4NTHER-specific questions.",
    why: "Keep strategic research bounded to the project question rather than becoming general information accumulation.",
    now: "Not current P0 work.",
    next: "Activate only from a concrete P4NTHER decision or opportunity.",
    aiPlan: "Question → source → evidence → synthesis → decision impact.",
    evidence: "P4NTHER project context",
    owner: "AXE",
    authority: "P4NTHER PROJECT",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "p4nther/strategy",
    universe: "P4NTHER",
    kind: "CORE",
    parent: "p4nther",
    title: "STRATEGY",
    eyebrow: "DECISION / DIRECTION",
    state: "QUEUED",
    priority: "P2",
    accent: "panther",
    summary: "P4NTHER direction, decisions, hypotheses and route-to-value when the project is active.",
    why: "Keep strategic choices explicit and evidence-linked rather than buried in chats.",
    now: "Not current P0 work.",
    next: "Reopen only when independent value or Founder intent justifies it.",
    aiPlan: "Preserve decisions and hypotheses; do not compete with 4PLANET critical path.",
    evidence: "P4NTHER project context",
    owner: "ODIN / AXE",
    authority: "P4NTHER PROJECT",
    freshness: "Manual projection 19 Aug 2026",
  },

  {
    slug: "sandbox",
    universe: "SANDBOX",
    kind: "ROOT",
    title: "SANDBOX / LABS",
    eyebrow: "SURPLUS-CAPACITY EXPERIMENTS",
    state: "EXPERIMENT",
    priority: "AFTER ACTIVE WORK",
    accent: "sandbox",
    summary: "A controlled home for high-upside ideas that should survive without stealing execution capacity from active projects.",
    why: "Preserve creative optionality while keeping the main machine focused and recoverable.",
    now: "Ideas may be captured freely; only a small number should become active experiments at the same time.",
    next: "Promote only experiments that earn capacity through evidence, strategic fit or asymmetric upside.",
    aiPlan: "IDEA → HYPOTHESIS → PROTOTYPE → TEST → PROMOTE/HOLD/KILL. No automatic new truth system, product or SPV.",
    evidence: "D16 4PLANET LABS / Venture Factory doctrine",
    owner: "ODIN / AXE",
    authority: "LABS / PROJECT FACTORY",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "sandbox/nature-game",
    universe: "SANDBOX",
    kind: "LAB",
    parent: "sandbox",
    title: "NATURE GAME",
    eyebrow: "WILD LAB",
    state: "EXPERIMENT",
    priority: "SURPLUS",
    accent: "nature",
    summary: "A playful interface experiment for learning ecological relationships without confusing simulation with observed truth.",
    why: "Test whether verified nature intelligence can become compelling play, learning and participation.",
    now: "Idea retained; not active P0 execution.",
    next: "Prototype the smallest useful/playable relationship mechanic only when real surplus capacity exists.",
    aiPlan: "Reuse verified species/Living Systems truth; label simulation clearly; test engagement before scope expansion.",
    evidence: "D16 Nature Game hypothesis",
    owner: "AXE / 4CULTURE",
    authority: "LABS / BRAIN",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "sandbox/4planet-university",
    universe: "SANDBOX",
    kind: "LAB",
    parent: "sandbox",
    title: "4PLANET UNIVERSITY",
    eyebrow: "LEARNING LAB",
    state: "QUEUED",
    priority: "SURPLUS",
    accent: "culture",
    summary: "Source-linked learning journeys built from the same verified intelligence as the public products.",
    why: "Test whether validated intelligence can become reusable learning without a parallel knowledge system.",
    now: "Concept retained; no active build should displace Gold/product/capital work.",
    next: "Define one tiny learning journey against an already mature Gold Reference.",
    aiPlan: "Start with one verified journey, test comprehension, then decide whether the format deserves a larger product.",
    evidence: "D16 University hypothesis",
    owner: "AXE / PRODUCT",
    authority: "LABS / BRAIN",
    freshness: "Manual projection 19 Aug 2026",
  },
  {
    slug: "sandbox/okobrain",
    universe: "SANDBOX",
    kind: "LAB",
    parent: "sandbox",
    title: "ØKOBRAIN",
    eyebrow: "EXPLORATORY SYSTEM IDEA",
    state: "QUEUED",
    priority: "SURPLUS",
    accent: "sandbox",
    summary: "Exploratory ecology/intelligence concept retained as an idea until its distinct problem and value are proven.",
    why: "Keep the idea discoverable without prematurely creating a duplicate BRAIN or product architecture.",
    now: "Not active; definition remains intentionally bounded.",
    next: "Clarify the unique problem before any implementation. Kill or merge the idea if it duplicates NATUREBRAIN/BRAIN.",
    aiPlan: "Red-team uniqueness first; build only if a real non-duplicate use case survives.",
    evidence: "Founder LABS idea intake",
    owner: "AXE / LABS",
    authority: "LABS / PROJECT FACTORY",
    freshness: "Manual projection 19 Aug 2026",
  },
];

export const projectBySlug = (slug: string) => projects.find((project) => project.slug === slug);
export const childrenOf = (slug: string) => projects.filter((project) => project.parent === slug);
export const descendantsOf = (slug: string) => projects.filter((project) => project.slug.startsWith(`${slug}/`));

export const universeRoots = ["4planet", "odin", "p4nther", "sandbox"]
  .map((slug) => projectBySlug(slug))
  .filter((project): project is LabProject => Boolean(project));

export const founderQueue = projects.flatMap((project) =>
  (project.founderDecisions ?? []).map((decision) => ({ slug: project.slug, project: project.title, decision })),
);

export const portfolioStats = {
  active: projects.filter((project) => ["ACTIVE", "BUILDING", "PUBLIC"].includes(project.state)).length,
  founder: founderQueue.length,
  aiActive: projects.flatMap((project) => project.tasks ?? []).filter((task) => task.owner !== "FOUNDER" && ["ACTIVE", "NEXT"].includes(task.state)).length,
  queued: projects.filter((project) => ["QUEUED", "EXPERIMENT", "HOLD"].includes(project.state)).length,
  conflicts: projects.filter((project) => project.state === "CONFLICT").length,
};

export const recentSystemMoves = [
  ["D17", "LABS and 4PLANET Project Overview remain distinct but connected", "LOCKED"],
  ["BRAIN-13", "AXE fresh-context recovery guard", "ACTIVE"],
  ["LABS-5/6", "Human Project OS + reusable project grammar", "BUILDING"],
  ["LABS-7", "Safe BRAIN projection adapter", "NEXT"],
  ["MISSION NAMES", "PL4STIC/CLE4N and EN3RGY/EN4RGY conflicts kept explicit", "OPEN"],
] as const;
