export type ProjectState = "ACTIVE" | "BUILDING" | "GATED" | "CONTINUOUS" | "HOLD";
export type Project = {
  id: string;
  title: string;
  role: string;
  goal: string;
  why: string;
  deadline: string;
  priority: string;
  state: ProjectState;
  phase: string;
  next: string;
  evidence: string;
  economic: string;
  kpis: string[];
};

export const planVersion = "GIGA-PLAN-2026-09-02-v3";
export const verifiedAt = "02 SEP 2026";
export const authority = "CURRENT BRAIN / FOUNDER DECISIONS / GIGA GOALS — READ-ONLY PROJECTION";

export const scorecard = [
  ["PUBLIC PRODUCTS", "Usable public surfaces · release readiness · critical defects"],
  ["USERS / ADOPTION", "Activated meaningful users · repeat use · task completion · referrals"],
  ["HUMAN VALUE", "Money/time saved · decision quality · cognitive load · trust"],
  ["MONEY / ECONOMICS", "Contracted · revenue · cash · contribution · cost truth"],
  ["CAPITAL CONVERSION", "Stage movement · proposals/DD · wins · time-to-money · Founder minutes"],
  ["INTELLIGENCE / DATA", "Source/provenance coverage · freshness · entity/relationship coverage · UNKNOWN resolution"],
  ["TRUST / QUALITY", "Traceability · rights · corrections · accessibility · performance · security"],
  ["ACTION / IMPACT", "Action Contracts · funded/delivered · proof-of-done · outcomes · verified impact"],
  ["FACTORY THROUGHPUT", "Accepted outputs · lead/cycle time · productive autonomous cycles · WIP age"],
  ["FACTORY STABILITY", "First-pass acceptance · rework · escaped defects · recovery time · rollback success"],
  ["LEARNING / COMPOUNDING", "Learning closure · repeat-failure rate · insight→WBS latency · reuse · transfer speedup"],
  ["SUPERBRAIN / RECOVERY", "Fresh-session recovery · parity · drift/orphans · restore/replay · context efficiency"],
  ["PROJECT DELIVERY", "KR progress · milestone forecast · critical-path health · blocker age · schedule reliability"],
  ["DISTRIBUTION / NETWORK", "Organic entry · cross-product depth · creator/referral share · partner activation"],
  ["FOUNDER LEVERAGE", "Founder minutes · AI-complete-before-Founder · avoidable escalations"],
  ["COST / AUTONOMY", "Accepted value per AI-hour/NOK · infrastructure cost · autonomous share"],
] as const;

export const projects: Project[] = [
  {id:"SUPERBRAIN",title:"SUPERBRAIN / CNS BRAIN 2.0",role:"SCALABLE SYSTEM OF RECORD",goal:"Complete remote Supabase migration, portfolio hydration, legacy↔CNS parity, live sync, fresh-session recovery, dual-read, restore and security proof so Founder can make an explicit cutover decision.",why:"Knowledge OS cannot safely remain the long-run operating brain for 50→50,000+ project-scale ambition.",deadline:"09 SEP 2026 — CUTOVER PROOF PACK",priority:"P0 MULTIPLIER",state:"BUILDING",phase:"CUTOVER PROOF",next:"Run remote migration/readback + parity/fresh-session/restore/security gates; no authority cutover without zero-loss evidence.",evidence:"CNS Kernel 02 + Supabase/Postgres shadow architecture exists; legacy BRAIN remains authority until cutover.",economic:"Reduces coordination cost, context loss, duplicate work and Founder dependence at scale.",kpis:["Fresh-session recovery PASS","Legacy↔CNS parity","0 material orphans/drift","Restore/replay PASS"]},
  {id:"FACTORY",title:"4PLANET Autonomous Factory",role:"AUTONOMOUS PRODUCTION MULTIPLIER",goal:"Operate an hourly multi-role production workforce that observes, plans, researches, builds, tests, diagnoses, corrects, red-teams, independently judges, learns and selects the next highest-value work package.",why:"Make quality production compound hour after hour without Odin acting as production manager.",deadline:"03 SEP 2026 — GITHUB-BACKED FULL LOOP PROOF",priority:"P0 MULTIPLIER",state:"BUILDING",phase:"FULL LOOP ACTIVATION",next:"Prove token-backed dispatch/write path end-to-end, then run bounded WIP≤5 multi-role cycles.",evidence:"Factory runtime and CI exist; GitHub token is Founder-reported connected and must be runtime-proven.",economic:"Lower marginal production cost + faster iteration + higher quality across every product.",kpis:["Autonomous full-loop completion","Accepted outputs / AI-hour","First-pass acceptance","Repeat-failure rate","Founder interventions / accepted output"]},
  {id:"TEST",title:"TEST KING / ONE INTERFACE",role:"PUBLIC 4PLANET RECEIVER",goal:"Make all key public 4PLANET surfaces coherent, usable, truth-safe, mobile Gold and release-ready for Founder decision.",why:"Real-world publication creates users, proof, distribution and learning; internal perfection does not.",deadline:"07 SEP 2026 — RELEASE CANDIDATE",priority:"P0 PUBLIC",state:"BUILDING",phase:"CLOSURE",next:"Full route/UX/asset regression audit; close highest-severity defects; preserve Prototype SAFE.",evidence:"king/test is sole integration receiver and is far ahead of main.",economic:"Unlocks users, partners, capital proof and real-world feedback.",kpis:["Critical defects=0 at release gate","5s comprehension","Mobile Gold","No dead ends","Public key surfaces usable"]},
  {id:"ATLAS",title:"ATLAS",role:"PLANETARY SPATIAL INTELLIGENCE",goal:"Ship practical-use Gold with reliable search, a small set of excellent source-aware layers and useful species/place/observation handoffs.",why:"ATLAS is a key TEST KING surface and one of the clearest flagship routes into Living Planet Intelligence.",deadline:"07 SEP 2026 — PRACTICAL GOLD",priority:"P0 PUBLIC",state:"BUILDING",phase:"TEST KING CLOSURE",next:"Search usefulness + core layers + source states + mobile/performance + cross-product handoffs.",evidence:"Current TEST KING contains ATLAS runtime; quality/usefulness closure remains active.",economic:"Institutional intelligence, audience acquisition, partner proof and future paid intelligence.",kpis:["Search task success","Layer/source truth","Handoff completion","Performance","Repeat use baseline"]},
  {id:"ORCA",title:"ORCA / Bay of Biscay",role:"PLANET PROOF 01",goal:"Deliver a presentation-usable Orca/Bay ecosystem + species + survey journey that ORCA/4PLANET can actually use.",why:"First marine Gold Reference proves partner-led Planet Engine value and reusable ecosystem/journey architecture.",deadline:"09 SEP 2026 — USABLE GOLD",priority:"P0 PROOF",state:"BUILDING",phase:"GOLD CLOSURE",next:"Finish end-to-end Bay journey, mobile/desktop quality, map/species/data/source seams and presenter flow.",evidence:"ORCA/Bay work and deployed Factory QA evidence already exist.",economic:"Partner proof → pilots/funding → reusable marine product capability.",kpis:["Presenter-ready","Journey complete","Mobile Gold","Source-backed","Partner-useful"]},
  {id:"AMAZON",title:"Amazonia Ecosystem Gold",role:"TERRESTRIAL TRANSFER PROOF",goal:"Deliver a usable Amazon rainforest ecosystem case reusing Bay/Species/Journey learnings rather than bespoke architecture.",why:"Marine + terrestrial transfer is the fastest proof that ecosystem intelligence compounds.",deadline:"16 SEP 2026 — USABLE GOLD",priority:"P0/P1 PROOF",state:"BUILDING",phase:"TRANSFER",next:"Recover strongest existing Amazon/Jaguar donor value; connect ecosystem map, species, pressures, actors/solutions and journey.",evidence:"Amazon/Jaguar assets and donors exist in repository.",economic:"Proves transfer economics and creates major partner/capital/public proof.",kpis:["Usable case","Transfer reuse ratio","Build-time reduction vs Bay","Source quality","Journey completion"]},
  {id:"EMBLA",title:"Ask Embla + 4SAPIEN",role:"HUMAN ENGINE",goal:"Create real personal utility for at least one authorised user scenario, with measurable money/time/decision benefit and clear privacy boundaries.",why:"Mass-market entry should solve ordinary human problems, not require environmental motivation.",deadline:"30 SEP 2026 — REAL HUMAN UTILITY",priority:"P0 PROOF",state:"BUILDING",phase:"UTILITY PROOF",next:"Personal/household finance spine → one complete decision scenario → measured user benefit.",evidence:"4SAPIEN/finance surfaces exist; real utility proof remains required.",economic:"Consumer utility, subscription/commerce optionality and decision-layer distribution.",kpis:["Money/time saved","Task success","Decision quality","Repeat intent/use","Privacy gate PASS"]},
  {id:"S4PIENS",title:"S4PIENS / FOOD",role:"HUMAN-SYSTEM INTELLIGENCE",goal:"Traverse one FOOD chain end-to-end from human need through product/value chain/ecology/actors/pressures to solutions/capital/incentives with source-aware truth.",why:"Proves the architecture can model all materially relevant human systems over time.",deadline:"30 SEP 2026 — FOOD END-TO-END GOLD",priority:"P0 PROOF",state:"BUILDING",phase:"VERTICAL SLICE",next:"Close one real chain before widening taxonomy.",evidence:"FOOD/S4PIENS architecture and public/domain assets exist.",economic:"Enterprise supply/value-chain intelligence + consumer decision utility + capital/solution linkage.",kpis:["End-to-end traversal","Source coverage","Decision usefulness","Reuse into Embla/Company","Transfer readiness"]},
  {id:"IMPACT",title:"Universal IMPACT + Impact Unit 01",role:"ACTION MARKET",goal:"Close the first qualified field/operator partner and activate one real open Impact Unit/Action Contract with inspectable delivery and proof-of-done logic.",why:"Turns understanding into funded expert action; the 16 Missions are only first curated portfolios.",deadline:"14 OCT 2026 LATEST — 2–6 WEEK CLOSE WINDOW",priority:"P0 PROOF",state:"GATED",phase:"PARTNER + CONTRACT DILIGENCE",next:"Prepare Plastic Bank lead diligence/call pack; CleanHub reserve; Plastic Fischer direct-collection alternative. Founder release required before outreach.",evidence:"Prior IMP-PARTNER analysis ranks Plastic Bank preferred P1/Top-6 plastic candidate.",economic:"Transaction/funding/action rail; credible proof creates repeat funding and partner value.",kpis:["Qualified operator","Action Contract approved","Funding route","Delivery proof","Time-to-proof","Repeat funding"]},
  {id:"ACTORS",title:"Actor Graph",role:"SHARED PLANETARY-ACTION IDENTITY",goal:"Use one actor identity across Research, Solutions, Capital, S4PIENS, Company and IMPACT without duplicate directories.",why:"The same people/organisations are the connective tissue from knowledge to action.",deadline:"30 SEP 2026 — CROSS-WORLD PROOF",priority:"P1 CORE",state:"BUILDING",phase:"INTEGRATION",next:"Prove one actor object reused across ≥4 worlds with provenance.",evidence:"Actor Gold surfaces exist in TEST KING.",economic:"Network intelligence, lower duplicate-data cost, partner/enterprise value.",kpis:["Cross-world reuse","Duplicate rate","Provenance coverage","Actor→solution/project/capital links"]},
  {id:"SOLUTIONS",title:"Solutions + Innovation Intelligence",role:"WHAT WORKS / WHAT IS MISSING",goal:"For one real problem, show evidence-backed existing solutions, maturity, gaps, actors, pilots and capital needs.",why:"Moves 4PLANET from problem information toward allocation intelligence.",deadline:"30 SEP 2026 — TRAVERSAL PROOF",priority:"P1 CORE",state:"BUILDING",phase:"INTEGRATION",next:"Connect one problem→solution→innovation-gap→actor→capital chain.",evidence:"Solutions/Transition and innovation research programmes exist in BRAIN.",economic:"Decision support, R&I intelligence, procurement/capital matching.",kpis:["Evidence-backed solutions","Gap/maturity coverage","Actor links","Capital-need links","Decision usefulness"]},
  {id:"CAPITAL",title:"Capital Intelligence + Conversion Factory",role:"RESOURCE ALLOCATION",goal:"Convert qualified opportunities into real stage movement, proposals/DD, contracted value and cash while minimising Founder minutes.",why:"A planetary action system without capital conversion cannot move resources to solutions or sustain 4PLANET.",deadline:"CONTINUOUS — WEEKLY EVIDENCE",priority:"ALWAYS-ON",state:"CONTINUOUS",phase:"CONVERSION",next:"Deadline-safe expected-value production; distinguish pipeline→submitted→awarded→contracted→cash.",evidence:"Canonical x500 Capital Control Tower and hourly conversion automation exist.",economic:"Direct runway + funding for products/projects + future allocation intelligence.",kpis:["Contracted","Cash","Stage movement","Time-to-money","Founder minutes","Win/response rate"]},
  {id:"COMPANY",title:"4COMPANIES / Company Gold",role:"ENTERPRISE DECISION SURFACE",goal:"Prove one company truth spine and six-view decision journey, then transfer to 3 and 5 companies without bespoke architecture.",why:"Enterprise users need dependencies, pressures, solutions, capital and proof connected to one shared model.",deadline:"15 OCT 2026 — 3-CASE TRANSFER",priority:"P1",state:"BUILDING",phase:"GOLD 01",next:"Truth Spine 01 → six-view journey → case 02/03 transfer.",evidence:"Company Gold plan exists; separate autonomous project lead was removed to avoid duplicate control.",economic:"Enterprise intelligence/pilot/subscription opportunity.",kpis:["Truth completeness","Decision usefulness","Transfer speed","Reuse ratio","Paid-pilot signal"]},
  {id:"SPECIES",title:"SPECIES",role:"LIFE IDENTITY + DISCOVERY",goal:"Make species search/cards/journeys source-aware, compelling and reusable across rapidly expanding taxa without quality dilution.",why:"Species is a viral human entry point and a foundational shared entity for the Planet Engine.",deadline:"15 SEP 2026 — GOLD TRANSFER SET",priority:"P1 / TEST SUPPORT",state:"BUILDING",phase:"TRANSFER",next:"Use Orca/Jaguar Gold to harden reusable Species contract and search/discovery.",evidence:"Current TEST KING has Species engine/routes and multiple species datasets/assets.",economic:"Audience/search distribution + licensing/intelligence/education optionality.",kpis:["Search success","Transfer time/species","Source completeness","Journey depth","Repeat discovery"]},
  {id:"LIVING",title:"Living Systems",role:"RELATIONSHIP / DEPENDENCY INTELLIGENCE",goal:"Show why relationships and dependencies materially improve understanding or decisions beyond flat entity cards.",why:"4PLANET's differentiation depends on relationships, not just cataloguing objects.",deadline:"30 SEP 2026 — DECISION-VALUE PROOF",priority:"P1 CORE",state:"BUILDING",phase:"PROOF",next:"Attach evidence-bearing relationship edges to Orca/Bay, FOOD and Amazonia and test explanation value.",evidence:"Living Systems data/types/pages exist in TEST KING.",economic:"Core moat for institutional/enterprise/nature intelligence.",kpis:["Verified relationship edges","Explanation lift","Decision-use cases","Cross-product reuse"]},
  {id:"MARKET",title:"CRE4TORS × 4P MARKET × 4RT",role:"CULTURE + COMMERCE + DISTRIBUTION",goal:"Prove one creator product flow where customer value, creator value, 4PLANET economic value and funded action are separately inspectable.",why:"Align creator self-interest, culture, distribution and impact instead of relying on altruism.",deadline:"31 OCT 2026 — REAL-VALUE PROOF",priority:"P1",state:"BUILDING",phase:"GOLD / PROVIDER GATES",next:"Rights + curated product + transparent waterfall + payment/POD/impact contract diligence; no fake live commerce.",evidence:"Creator×Impact Commerce Gold contract already exists.",economic:"Commerce margin + creator economy + distribution + action funding.",kpis:["Creator earnings","Contribution margin","Creator-originated demand","Impact funding","Repeat purchase"]},
  {id:"MAG",title:"4PLANET MAGAZINE + Distribution",role:"TRUSTED ATTENTION",goal:"Turn source-backed stories/search/SEO into measurable deeper use of ATLAS, SPECIES, Journeys and Action surfaces.",why:"Strong products without discovery do not create users or proof.",deadline:"CONTINUOUS — WEEKLY DISTRIBUTION DELTA",priority:"CONTINUOUS",state:"CONTINUOUS",phase:"DISTRIBUTION",next:"Permanent article/search/SEO system + internal links + measurement; publish only under release authority.",evidence:"Magazine routes/runtime exist in TEST KING.",economic:"Organic acquisition, brand value, partner reach and commerce/capital support.",kpis:["Organic entries","Engaged reads","Cross-product depth","Return/share","Conversion to action/interest"]},
  {id:"LABS",title:"4PLANET LABS / OS",role:"FOUNDER OPERATING PROJECTION",goal:"Give Odin one owned read-only web surface showing roadmap, project goals/deadlines, evidence-based progress, scorecard, Factory state, economics/tasks and Founder gates directly projected from canonical truth.",why:"The autonomous organisation is otherwise invisible and Founder cannot steer or trust what cannot be inspected.",deadline:"05 SEP 2026 — LABS 1.0",priority:"P0 CONTROL",state:"BUILDING",phase:"DONOR RECOVERY",next:"Recover Founder-loved LABS donor into TEST KING, update to GIGA plan v3, then automate projection adapter.",evidence:"Founder-loved LABS v3 donor branch recovered with UI/data/tests; current TEST KING lacked route/files.",economic:"Founder leverage, lower coordination burden, faster detection of drift/waste.",kpis:["Project coverage","Freshness","Goal/deadline coverage","Founder action clarity","Automated projection coverage"]},
];

export const criticalPath = ["SUPERBRAIN","FACTORY","TEST","ATLAS","ORCA","AMAZON","EMBLA","IMPACT","S4PIENS"];
