-- RECOVERED FROM APPLIED 4PLANET-STAGING MIGRATION JOURNAL 2026-09-03
-- Missing tail of remotely applied cns_change_trials. Restores reproducible SUPERBRAIN V4 truth/provenance schema.
-- No authority cutover.

begin;

create table if not exists cns.entities(entity_id text primary key,entity_type text not null,canonical_name text not null,lifecycle text not null default 'ACTIVE' check(lifecycle in ('ACTIVE','SUPERSEDED','ARCHIVED')),source_id text references cns.source_registry(source_id) on delete restrict,source_revision text,metadata jsonb not null default '{}'::jsonb,last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists cns.entity_aliases(entity_alias_id bigint generated always as identity primary key,entity_id text not null references cns.entities(entity_id) on delete restrict,namespace text not null default 'GLOBAL',alias text not null,normalised_alias text generated always as (lower(regexp_replace(btrim(alias),'\s+',' ','g'))) stored,source_id text references cns.source_registry(source_id) on delete restrict,source_revision text,state text not null default 'ACTIVE' check(state in ('ACTIVE','SUPERSEDED','REJECTED')),created_at timestamptz not null default now(),unique(entity_id,namespace,normalised_alias));
create index if not exists cns_entity_alias_lookup_idx on cns.entity_aliases(namespace,normalised_alias) where state='ACTIVE';
create table if not exists cns.methodologies(methodology_id text primary key,name text not null,version text not null,description text,assumptions jsonb not null default '[]'::jsonb,validity_domain jsonb not null default '{}'::jsonb,limitations jsonb not null default '[]'::jsonb,source_id text references cns.source_registry(source_id) on delete restrict,source_revision text,content_hash text,state text not null default 'ACTIVE' check(state in ('ACTIVE','SUPERSEDED','REJECTED','ARCHIVED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(name,version));

alter table cns.evidence add column if not exists revision integer not null default 1 check(revision>0);
alter table cns.evidence add column if not exists supersedes_evidence_id text references cns.evidence(evidence_id) on delete restrict;
alter table cns.claims add column if not exists claim_kind text not null default 'SOURCE_CLAIM';
alter table cns.claims add column if not exists knowledge_state text not null default 'KNOWN';
alter table cns.claims add column if not exists source_id text references cns.source_registry(source_id) on delete restrict;
alter table cns.claims add column if not exists source_revision text;
alter table cns.claims add column if not exists methodology_id text references cns.methodologies(methodology_id) on delete restrict;
alter table cns.claims add column if not exists claimant_entity_id text references cns.entities(entity_id) on delete restrict;
alter table cns.claims add column if not exists valid_time_start timestamptz;
alter table cns.claims add column if not exists valid_time_end timestamptz;
alter table cns.claims add column if not exists observed_at timestamptz;
alter table cns.claims add column if not exists geography jsonb not null default '{}'::jsonb;
alter table cns.claims add column if not exists unit text;
alter table cns.claims add column if not exists scope jsonb not null default '{}'::jsonb;
alter table cns.claims add column if not exists revision integer not null default 1 check(revision>0);
alter table cns.claims add column if not exists supersedes_claim_id text references cns.claims(claim_id) on delete restrict;
do $$ begin
  if not exists(select 1 from pg_constraint where conrelid='cns.claims'::regclass and conname='cns_claim_kind_check') then alter table cns.claims add constraint cns_claim_kind_check check(claim_kind in ('SOURCE_FACT','SOURCE_CLAIM','INFERENCE','ESTIMATE','INTERPRETATION','RECOMMENDATION','UNKNOWN')); end if;
  if not exists(select 1 from pg_constraint where conrelid='cns.claims'::regclass and conname='cns_claim_knowledge_state_check') then alter table cns.claims add constraint cns_claim_knowledge_state_check check(knowledge_state in ('KNOWN','UNKNOWN','INSUFFICIENT_EVIDENCE','CONFLICTED')); end if;
  if not exists(select 1 from pg_constraint where conrelid='cns.claims'::regclass and conname='cns_claim_valid_time_check') then alter table cns.claims add constraint cns_claim_valid_time_check check(valid_time_end is null or valid_time_start is null or valid_time_end>=valid_time_start); end if;
end $$;
do $$ declare r record; begin for r in select conname from pg_constraint where conrelid='cns.claim_evidence'::regclass and contype='c' and pg_get_constraintdef(oid) ilike '%relation%' loop execute format('alter table cns.claim_evidence drop constraint %I',r.conname); end loop; end $$;
alter table cns.claim_evidence add constraint cns_claim_evidence_relation_check check(relation in ('SUPPORTS','CONTRADICTS','CONTEXT','DOES_NOT_ESTABLISH'));

create table if not exists cns.observations(observation_id text primary key,project_id text references cns.projects(project_id) on delete restrict,entity_id text references cns.entities(entity_id) on delete restrict,observation_type text not null,value jsonb not null,unit text,observed_at timestamptz not null,valid_time_start timestamptz,valid_time_end timestamptz,source_id text not null references cns.source_registry(source_id) on delete restrict,source_revision text not null,methodology_id text references cns.methodologies(methodology_id) on delete restrict,evidence_id text references cns.evidence(evidence_id) on delete restrict,uncertainty jsonb not null default '{}'::jsonb,quality jsonb not null default '{}'::jsonb,sampling_effort jsonb not null default '{}'::jsonb,geometry_private jsonb,public_geometry jsonb,spatial_precision_m numeric,public_precision_m numeric,sensitivity_state text not null default 'PUBLIC' check(sensitivity_state in ('PUBLIC','GENERALIZED','RESTRICTED')),sensitivity_reason text,state text not null default 'ACTIVE' check(state in ('ACTIVE','DISPUTED','SUPERSEDED','ARCHIVED')),revision integer not null default 1 check(revision>0),supersedes_observation_id text references cns.observations(observation_id) on delete restrict,last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now(),check(valid_time_end is null or valid_time_start is null or valid_time_end>=valid_time_start),check(sensitivity_state<>'RESTRICTED' or public_geometry is null),check(public_precision_m is null or spatial_precision_m is null or public_precision_m>=spatial_precision_m));
create index if not exists cns_observations_entity_time_idx on cns.observations(entity_id,observed_at desc);
create index if not exists cns_observations_project_time_idx on cns.observations(project_id,observed_at desc);
create table if not exists cns.signals(signal_id text primary key,project_id text references cns.projects(project_id) on delete restrict,entity_id text references cns.entities(entity_id) on delete restrict,signal_type text not null,value jsonb not null,methodology_id text not null references cns.methodologies(methodology_id) on delete restrict,evidence_refs jsonb not null default '[]'::jsonb,confidence numeric(5,4) check(confidence is null or (confidence>=0 and confidence<=1)),knowledge_state text not null default 'KNOWN' check(knowledge_state in ('KNOWN','UNKNOWN','INSUFFICIENT_EVIDENCE','CONFLICTED')),generated_at timestamptz not null default now(),state text not null default 'ACTIVE' check(state in ('ACTIVE','DISPUTED','SUPERSEDED','ARCHIVED')),revision integer not null default 1 check(revision>0),supersedes_signal_id text references cns.signals(signal_id) on delete restrict,last_event_id bigint references cns.events(event_id) on delete restrict);
create table if not exists cns.interpretations(interpretation_id text primary key,project_id text references cns.projects(project_id) on delete restrict,subject_type text not null,subject_id text not null,body jsonb not null,methodology_id text references cns.methodologies(methodology_id) on delete restrict,evidence_refs jsonb not null default '[]'::jsonb,limitations jsonb not null default '[]'::jsonb,confidence numeric(5,4) check(confidence is null or (confidence>=0 and confidence<=1)),knowledge_state text not null default 'KNOWN' check(knowledge_state in ('KNOWN','UNKNOWN','INSUFFICIENT_EVIDENCE','CONFLICTED')),state text not null default 'ACTIVE' check(state in ('ACTIVE','DISPUTED','SUPERSEDED','REJECTED','ARCHIVED')),revision integer not null default 1 check(revision>0),supersedes_interpretation_id text references cns.interpretations(interpretation_id) on delete restrict,last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists cns.conflicts(conflict_id text primary key,project_id text references cns.projects(project_id) on delete restrict,subject_type text not null,subject_id text not null,predicate text,severity text not null default 'P1' check(severity in ('INFO','P2','P1','P0')),summary text not null,state text not null default 'OPEN' check(state in ('OPEN','RESOLVED','SUPERSEDED','FALSE_POSITIVE')),evidence_refs jsonb not null default '[]'::jsonb,resolution_decision_id text references cns.decisions(decision_id) on delete restrict,resolution_notes text,opened_at timestamptz not null default now(),resolved_at timestamptz,last_event_id bigint references cns.events(event_id) on delete restrict,check(state<>'RESOLVED' or resolution_decision_id is not null or nullif(btrim(resolution_notes),'') is not null));
create table if not exists cns.conflict_claims(conflict_id text not null references cns.conflicts(conflict_id) on delete restrict,claim_id text not null references cns.claims(claim_id) on delete restrict,side text not null default 'OTHER' check(side in ('A','B','OTHER')),primary key(conflict_id,claim_id));

alter table cns.decisions add column if not exists rationale jsonb not null default '{}'::jsonb;
alter table cns.decisions add column if not exists assumptions jsonb not null default '[]'::jsonb;
alter table cns.decisions add column if not exists alternatives jsonb not null default '[]'::jsonb;
alter table cns.decisions add column if not exists unknowns jsonb not null default '[]'::jsonb;
alter table cns.decisions add column if not exists consequences jsonb not null default '[]'::jsonb;
alter table cns.decisions add column if not exists review_trigger jsonb not null default '{}'::jsonb;
alter table cns.decisions add column if not exists methodology_id text references cns.methodologies(methodology_id) on delete restrict;
create table if not exists cns.outcomes(outcome_id text primary key,project_id text references cns.projects(project_id) on delete restrict,decision_id text references cns.decisions(decision_id) on delete restrict,title text not null,observed_at timestamptz not null,value jsonb not null,evidence_refs jsonb not null default '[]'::jsonb,confidence numeric(5,4) check(confidence is null or (confidence>=0 and confidence<=1)),knowledge_state text not null default 'KNOWN' check(knowledge_state in ('KNOWN','UNKNOWN','INSUFFICIENT_EVIDENCE','CONFLICTED')),state text not null default 'ACTIVE' check(state in ('ACTIVE','DISPUTED','SUPERSEDED','ARCHIVED')),revision integer not null default 1 check(revision>0),supersedes_outcome_id text references cns.outcomes(outcome_id) on delete restrict,last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now());
create table if not exists cns.learnings(learning_id text primary key,project_id text references cns.projects(project_id) on delete restrict,outcome_id text references cns.outcomes(outcome_id) on delete restrict,title text not null,learning jsonb not null,evidence_refs jsonb not null default '[]'::jsonb,confidence numeric(5,4) check(confidence is null or (confidence>=0 and confidence<=1)),state text not null default 'CANDIDATE' check(state in ('CANDIDATE','ACCEPTED','REJECTED','SUPERSEDED','ARCHIVED')),revision integer not null default 1 check(revision>0),supersedes_learning_id text references cns.learnings(learning_id) on delete restrict,last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists cns.rule_changes(rule_change_id text primary key,project_id text references cns.projects(project_id) on delete restrict,learning_id text references cns.learnings(learning_id) on delete restrict,title text not null,proposal jsonb not null,baseline jsonb not null default '{}'::jsonb,candidate jsonb not null default '{}'::jsonb,test_plan jsonb not null default '{}'::jsonb,rollback_plan jsonb not null default '{}'::jsonb,evaluation_run_id uuid references cns.evaluation_runs(evaluation_run_id) on delete restrict,decision text not null default 'PENDING' check(decision in ('PENDING','KEEP','REJECT','ROLLED_BACK')),decision_reason text,applied_at timestamptz,rolled_back_at timestamptz,state text not null default 'PROPOSED' check(state in ('PROPOSED','TESTING','APPLIED','REJECTED','ROLLED_BACK','SUPERSEDED')),last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create or replace function cns.guard_rule_change() returns trigger language plpgsql security definer set search_path=cns,public as $$ declare v_eval text; begin if new.decision='KEEP' then if new.evaluation_run_id is null then raise exception 'CNS_RULE_KEEP_REQUIRES_EVALUATION'; end if; select state into v_eval from cns.evaluation_runs where evaluation_run_id=new.evaluation_run_id; if v_eval is distinct from 'PASS' then raise exception 'CNS_RULE_KEEP_REQUIRES_PASS'; end if; if new.state not in ('APPLIED','TESTING') then raise exception 'CNS_RULE_KEEP_STATE_INVALID'; end if; end if; if new.decision='ROLLED_BACK' and new.rolled_back_at is null then raise exception 'CNS_RULE_ROLLBACK_TIMESTAMP_REQUIRED'; end if; return new; end; $$;
drop trigger if exists cns_rule_change_guard on cns.rule_changes;
create trigger cns_rule_change_guard before insert or update on cns.rule_changes for each row execute function cns.guard_rule_change();

create table if not exists cns.provenance_edges(provenance_edge_id bigint generated always as identity primary key,subject_type text not null,subject_id text not null,relation text not null check(relation in ('DERIVED_FROM','GENERATED_BY','ATTRIBUTED_TO','INPUT_TO','OUTPUT_OF','SUPERSEDES','CORROBORATES')),object_type text not null,object_id text not null,activity_type text,activity_id text,agent_type text,agent_id text,source_id text references cns.source_registry(source_id) on delete restrict,source_revision text,event_id bigint references cns.events(event_id) on delete restrict,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(subject_type,subject_id,relation,object_type,object_id,activity_type,activity_id));
create index if not exists cns_provenance_subject_idx on cns.provenance_edges(subject_type,subject_id);
create index if not exists cns_provenance_object_idx on cns.provenance_edges(object_type,object_id);
create table if not exists cns.control_roles(role_id text primary key,description text not null,may_rewrite_source_truth boolean not null default false,created_at timestamptz not null default now());
insert into cns.control_roles(role_id,description,may_rewrite_source_truth) values
('LIBRARIAN','Canonical identity, deduplication, aliases, taxonomy, lineage and retrieval correctness',false),
('DOCTOR','Continuous health, stale/broken/orphan/conflict/drift/recovery detection',false),
('SCIENTIST','Methods, evidence extraction, uncertainty and validity-domain analysis',false),
('AUDITOR','Independent evidence-to-output and adversarial release verification',false),
('HISTORIAN','Immutable event, supersession and recovery lineage',false),
('GATEKEEPER','Rights, privacy, sensitive nature, regulated-output and release boundaries',false),
('TRAFFIC','Concurrency, leases and duplicate-work prevention',false),
('EVALUATOR','Test execution and regression assessment',false)
on conflict(role_id) do update set description=excluded.description,may_rewrite_source_truth=false;
create table if not exists cns.agent_control_roles(agent_id text not null references cns.agents(agent_id) on delete restrict,role_id text not null references cns.control_roles(role_id) on delete restrict,state text not null default 'ACTIVE' check(state in ('ACTIVE','SUSPENDED','REVOKED')),granted_at timestamptz not null default now(),primary key(agent_id,role_id));
create table if not exists cns.hypotheses(hypothesis_id text primary key,project_id text references cns.projects(project_id) on delete restrict,owner_identity text not null,title text not null,statement text not null,hypothesis_type text not null default 'FOUNDER_THESIS' check(hypothesis_type in ('FOUNDER_THESIS','WORKING_HYPOTHESIS','THEORY','DESIGN_PRINCIPLE','METAPHOR')),status text not null default 'DRAFT' check(status in ('DRAFT','TESTING','SUPPORTED','WEAKENED','REJECTED','SUPERSEDED')),falsifiers jsonb not null default '[]'::jsonb,supporting_evidence_refs jsonb not null default '[]'::jsonb,counter_evidence_refs jsonb not null default '[]'::jsonb,originality_note text,source_id text references cns.source_registry(source_id) on delete restrict,source_revision text,revision integer not null default 1 check(revision>0),supersedes_hypothesis_id text references cns.hypotheses(hypothesis_id) on delete restrict,publication_state text not null default 'PRIVATE' check(publication_state in ('PRIVATE','DRAFT','FOUNDER_REVIEW','APPROVED','PUBLISHED','RETRACTED')),published_uri text,last_event_id bigint references cns.events(event_id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(publication_state<>'PUBLISHED' or (published_uri is not null and jsonb_array_length(supporting_evidence_refs)>0)));

create or replace function cns.guard_strict_immutable() returns trigger language plpgsql as $$ begin raise exception 'CNS_IMMUTABLE_TRUTH_RECORD: append a new revision/superseding record'; end; $$;
drop trigger if exists cns_source_revision_immutable on cns.source_revisions;
create trigger cns_source_revision_immutable before update or delete on cns.source_revisions for each row execute function cns.guard_strict_immutable();
create or replace function cns.guard_truth_core_update() returns trigger language plpgsql as $$ declare old_core jsonb; new_core jsonb; begin if tg_op='DELETE' then raise exception 'CNS_TRUTH_DELETE_FORBIDDEN: supersede/archive instead'; end if; old_core:=to_jsonb(old)-array['state','status','last_event_id','updated_at','verified_at','resolved_at','resolution_decision_id','resolution_notes','publication_state','published_uri']; new_core:=to_jsonb(new)-array['state','status','last_event_id','updated_at','verified_at','resolved_at','resolution_decision_id','resolution_notes','publication_state','published_uri']; if old_core is distinct from new_core then raise exception 'CNS_TRUTH_CORE_MUTATION_FORBIDDEN: append a superseding revision'; end if; return new; end; $$;
do $$ declare t text; begin foreach t in array array['evidence','claims','methodologies','observations','signals','interpretations','decisions','outcomes','learnings','hypotheses','entity_aliases'] loop execute format('drop trigger if exists cns_truth_core_guard on cns.%I',t); execute format('create trigger cns_truth_core_guard before update or delete on cns.%I for each row execute function cns.guard_truth_core_update()',t); end loop; end $$;

create or replace view cns.v_entity_alias_collisions with (security_invoker=true) as select namespace,normalised_alias,array_agg(distinct entity_id order by entity_id) as entity_ids,count(distinct entity_id) as entity_count from cns.entity_aliases where state='ACTIVE' group by namespace,normalised_alias having count(distinct entity_id)>1;
create or replace view cns.v_claim_truth_trace with (security_invoker=true) as select c.claim_id,c.project_id,c.subject_type,c.subject_id,c.predicate,c.value,c.claim_kind,c.knowledge_state,c.authority,c.confidence,c.source_id,c.source_revision,c.methodology_id,c.valid_time_start,c.valid_time_end,c.observed_at,c.geography,c.unit,c.scope,c.state,c.revision,c.supersedes_claim_id,case when m.methodology_id is null then null else jsonb_build_object('id',m.methodology_id,'name',m.name,'version',m.version,'assumptions',m.assumptions,'validity_domain',m.validity_domain,'limitations',m.limitations) end as methodology,coalesce((select jsonb_agg(jsonb_build_object('relation',ce.relation,'evidence_id',e.evidence_id,'type',e.evidence_type,'source_id',e.source_id,'source_revision',e.source_revision,'uri',e.uri,'content_hash',e.content_hash,'observed_at',e.observed_at,'verified_at',e.verified_at,'state',e.state,'revision',e.revision,'supersedes_evidence_id',e.supersedes_evidence_id) order by e.evidence_id,ce.relation) from cns.claim_evidence ce join cns.evidence e using(evidence_id) where ce.claim_id=c.claim_id),'[]'::jsonb) as evidence_links,coalesce((select jsonb_agg(jsonb_build_object('conflict_id',cf.conflict_id,'severity',cf.severity,'state',cf.state,'summary',cf.summary) order by cf.severity,cf.conflict_id) from cns.conflict_claims cc join cns.conflicts cf using(conflict_id) where cc.claim_id=c.claim_id and cf.state='OPEN'),'[]'::jsonb) as open_conflicts from cns.claims c left join cns.methodologies m on m.methodology_id=c.methodology_id;
create or replace view cns.doctor_violations_v3 with (security_invoker=true) as select * from cns.doctor_violations_v2 union all select 'ENTITY_ALIAS_COLLISION','P0','ENTITY_ALIAS',namespace||':'||normalised_alias,null,'Active alias resolves to multiple canonical entities' from cns.v_entity_alias_collisions union all select 'OPEN_TRUTH_CONFLICT_P0','P0','CONFLICT',conflict_id,project_id,'Material truth conflict is unresolved' from cns.conflicts where state='OPEN' and severity='P0' union all select 'SOURCE_CLAIM_WITHOUT_SOURCE','P0','CLAIM',claim_id,project_id,'Source fact/claim lacks explicit source identity' from cns.claims where state in ('ACTIVE','DISPUTED') and claim_kind in ('SOURCE_FACT','SOURCE_CLAIM') and source_id is null union all select 'DERIVED_CLAIM_WITHOUT_METHOD','P0','CLAIM',claim_id,project_id,'Derived claim lacks versioned methodology' from cns.claims where state in ('ACTIVE','DISPUTED') and claim_kind in ('INFERENCE','ESTIMATE','INTERPRETATION','RECOMMENDATION') and methodology_id is null union all select 'CLAIM_SOURCE_REVISION_UNKNOWN','P1','CLAIM',claim_id,project_id,'Claim has source identity but no source revision' from cns.claims where state in ('ACTIVE','DISPUTED') and source_id is not null and nullif(btrim(source_revision),'') is null union all select 'RESTRICTED_OBSERVATION_WITH_PUBLIC_GEOMETRY','P0','OBSERVATION',observation_id,project_id,'Restricted observation exposes public geometry' from cns.observations where sensitivity_state='RESTRICTED' and public_geometry is not null union all select 'SOURCE_VERIFICATION_MISSING','P1','SOURCE',source_id,null,'Active source has freshness policy but has never been verified' from cns.source_registry where state='ACTIVE' and freshness_seconds is not null and last_verified_at is null union all select 'SOURCE_STALE','P1','SOURCE',source_id,null,'Active source verification is stale' from cns.source_registry where state='ACTIVE' and freshness_seconds is not null and last_verified_at is not null and last_verified_at+make_interval(secs=>freshness_seconds)<=now() union all select 'SOURCE_DEGRADED','P1','SOURCE',source_id,null,'Source is explicitly degraded; dependent outputs must not claim fresh certainty' from cns.source_registry where state='DEGRADED';
create or replace function cns.doctor_scan() returns integer language plpgsql security definer set search_path=cns,public as $$ declare v_count integer; begin perform cns.expire_dead_leases(); insert into cns.health_incidents(fingerprint,rule_id,severity,entity_type,entity_id,project_id,summary,evidence,state) select encode(digest(rule_id||'|'||entity_type||'|'||entity_id,'sha256'),'hex'),rule_id,severity,entity_type,entity_id,project_id,summary,'[]'::jsonb,'OPEN' from cns.doctor_violations_v3 on conflict(fingerprint) where state in ('OPEN','ACKNOWLEDGED') do update set last_seen_at=now(),summary=excluded.summary,severity=excluded.severity; get diagnostics v_count=row_count; update cns.health_incidents i set state='RESOLVED',resolved_at=now(),last_seen_at=now() where i.state in ('OPEN','ACKNOWLEDGED') and not exists(select 1 from cns.doctor_violations_v3 v where encode(digest(v.rule_id||'|'||v.entity_type||'|'||v.entity_id,'sha256'),'hex')=i.fingerprint); return v_count; end; $$;
insert into cns.system_meta(key,value) values('truth_model','{"version":4,"verified":false,"state":"PENDING_CERTIFICATION","principle":"UNKNOWN_IS_FIRST_CLASS","mutation_policy":"APPEND_OR_SUPERSEDE"}'::jsonb) on conflict(key) do update set value=excluded.value,updated_at=now();
drop view if exists cns.v_cutover_readiness;
create view cns.v_cutover_readiness with (security_invoker=true) as select (exists(select 1 from cns.parity_results) and not exists(select 1 from cns.parity_results where result<>'MATCH')) as parity_green,(exists(select 1 from cns.legacy_import_queue) and not exists(select 1 from cns.legacy_import_queue where state in ('STAGED','AMBIGUOUS'))) as hydration_green,(coalesce((select state='PASS' from cns.dual_read_runs order by finished_at desc nulls last,started_at desc limit 1),false)) as dual_read_green,not exists(select 1 from cns.health_incidents where state in ('OPEN','ACKNOWLEDGED') and severity='P0') as no_open_p0,not exists(select 1 from cns.doctor_violations_v3 where severity='P0') as invariants_green,coalesce((select (value->>'verified')::boolean from cns.system_meta where key='remote_readback'),false) as remote_readback_green,coalesce((select (value->>'verified')::boolean from cns.system_meta where key='backup_restore'),false) as backup_restore_green,coalesce((select (value->>'verified')::boolean from cns.system_meta where key='fresh_session'),false) as fresh_session_green,coalesce((select (value->>'verified')::boolean from cns.system_meta where key='security_review'),false) as security_green,coalesce((select (value->>'verified')::boolean from cns.system_meta where key='golden_eval'),false) as golden_eval_green,coalesce((select (value->>'verified')::boolean from cns.system_meta where key='truth_model'),false) as truth_model_green,coalesce((select value->>'mode' from cns.system_meta where key='authority_mode'),'UNKNOWN') as authority_mode,coalesce((select (value->>'cutover_authorized')::boolean from cns.system_meta where key='authority_mode'),false) as cutover_authorized;
alter default privileges in schema cns revoke execute on functions from public;
alter default privileges in schema cns revoke all on tables from public,anon,authenticated;
alter default privileges in schema cns revoke all on sequences from public,anon,authenticated;
revoke all on cns.change_trials,cns.entities,cns.entity_aliases,cns.methodologies,cns.observations,cns.signals,cns.interpretations,cns.conflicts,cns.conflict_claims,cns.outcomes,cns.learnings,cns.rule_changes,cns.provenance_edges,cns.control_roles,cns.agent_control_roles,cns.hypotheses from public,anon,authenticated;
revoke all on function cns.begin_change_trial(text,text,uuid,text,text,text,text[],jsonb,uuid) from public,anon,authenticated;
revoke all on function cns.activate_change_trial(uuid) from public,anon,authenticated;
revoke all on function cns.submit_change_trial(uuid,text,uuid) from public,anon,authenticated;
revoke all on function cns.finish_change_trial(uuid,text,text,jsonb) from public,anon,authenticated;
revoke all on function cns.block_change_trial(uuid,text,jsonb) from public,anon,authenticated;
revoke all on function cns.guard_rule_change() from public,anon,authenticated;
revoke all on function cns.guard_strict_immutable() from public,anon,authenticated;
revoke all on function cns.guard_truth_core_update() from public,anon,authenticated;
revoke all on function cns.doctor_scan() from public,anon,authenticated;
grant select,insert,update on cns.change_trials to service_role;
grant select,insert,update on cns.entities,cns.entity_aliases,cns.methodologies,cns.observations,cns.signals,cns.interpretations,cns.conflicts,cns.outcomes,cns.learnings,cns.rule_changes,cns.agent_control_roles,cns.hypotheses to service_role;
grant select,insert on cns.conflict_claims,cns.provenance_edges to service_role;
grant select on cns.control_roles,cns.v_wip_control,cns.v_entity_alias_collisions,cns.v_claim_truth_trace,cns.doctor_violations_v3,cns.v_cutover_readiness to service_role;
grant usage,select on all sequences in schema cns to service_role;
grant execute on function cns.begin_change_trial(text,text,uuid,text,text,text,text[],jsonb,uuid) to service_role;
grant execute on function cns.activate_change_trial(uuid) to service_role;
grant execute on function cns.submit_change_trial(uuid,text,uuid) to service_role;
grant execute on function cns.finish_change_trial(uuid,text,text,jsonb) to service_role;
grant execute on function cns.block_change_trial(uuid,text,jsonb) to service_role;
grant execute on function cns.doctor_scan() to service_role;
revoke update,delete on cns.source_revisions from service_role;
revoke delete on cns.evidence,cns.claims,cns.decisions from service_role;
revoke update,delete on cns.claim_evidence from service_role;
revoke delete on cns.entities,cns.entity_aliases,cns.methodologies,cns.observations,cns.signals,cns.interpretations,cns.conflicts,cns.outcomes,cns.learnings,cns.rule_changes,cns.hypotheses from service_role;
revoke update,delete on cns.provenance_edges,cns.conflict_claims from service_role;
update cns.system_meta set value='{"version":4,"migration":"20260824193000_cns_change_trials","truth_model":"SUPERBRAIN_V4_APPEND_SUPERSEDE"}'::jsonb,updated_at=now() where key='schema_version';
commit;
