import type {
  DecisionEvidence, DecisionField, DecisionGap, DecisionOption, DecisionPack,
  DimensionRating, OptionDimensionAssessment, OptionDimensionKey, ProvenancePointer,
  TruthClass, ConfidenceBand, EvidenceScope,
} from "./contracts.js";

const s = (sourceRef:string,title:string,url?:string): ProvenancePointer => ({sourceRef,title,url,provenanceStatus:"SOURCE_REGISTRY_ONLY"});
export const SOURCES = {
  IPM:s("SRC-POLL-IPM-PNAS-2021","Threshold IPM field experiment","https://pubmed.ncbi.nlm.nih.gov/34697238/"),
  FAP:s("SRC-POLL-FAP-MOROCCO-2021","Farming with Alternative Pollinators — Morocco","https://www.nature.com/articles/s41598-021-97695-5"),
  SYNTH:s("SRC-POLL-ALBRECHT-2020","Flower strips/hedgerows quantitative synthesis","https://pubmed.ncbi.nlm.nih.gov/32808477/"),
  PEST:s("SRC-POLL-BLUEBERRY-PESTICIDE-2024","Pesticide exposure in pollinator plantings","https://pubmed.ncbi.nlm.nih.gov/38402956/"),
  NORWAY:s("SRC-DI-NO-POLLINATOR-PLAN-2021","Norwegian wild-pollinator action plan 2021–2028","https://www.regjeringen.no/no/dokumenter/tiltaksplan-for-ville-pollinerande-insekt-2021-2028/id2867106/"),
  URBAN:s("SRC-DI-URBAN-NATCOM-2020","Urban bees and pollination across German cities","https://www.nature.com/articles/s41467-020-14496-6"),
  MOW:s("SRC-DI-MOWING-BURI-2014","Experimental mowing regimes and bees","https://pubmed.ncbi.nlm.nih.gov/24416434/"),
  SFI:s("SRC-POLL-UK-SFI26-CIPM2","England SFI26 flower-rich margins payment","https://www.gov.uk/find-funding-for-land-or-farms/cipm2-flower-rich-grass-margins-blocks-or-in-field-strips"),
  POMS:s("SRC-POLL-EU-POMS-2021","EU Pollinator Monitoring Scheme proposal","https://publications.jrc.ec.europa.eu/repository/handle/JRC122225"),
} as const;

const f=<T>(value:T,truthClass:TruthClass="4PLANET_ASSESSMENT",confidence:ConfidenceBand="MODERATE",sources:ProvenancePointer[]=[],limitations:string[]=[],evidenceScope?:EvidenceScope):DecisionField<T>=>({value,truthClass,confidence,sources,limitations,evidenceScope});
const D:OptionDimensionKey[]=["PROBLEM_RELEVANCE","EFFECTIVENESS_EVIDENCE","IMPLEMENTATION_MATURITY","TIME_TO_BENEFIT","COST_EVIDENCE","MAINTENANCE_BURDEN","ECOLOGICAL_CO_BENEFIT","HUMAN_CO_BENEFIT","TRADE_OFF_RISK","TRANSFERABILITY","MEASUREMENT_FEASIBILITY","UNCERTAINTY"];
const dims=(ratings:Partial<Record<OptionDimensionKey,DimensionRating>>,basis:string,sources:ProvenancePointer[]=[]):OptionDimensionAssessment[]=>D.map(d=>({dimension:d,rating:ratings[d]??"UNKNOWN",confidence:ratings[d]?"MODERATE":"UNKNOWN",basis,sources,unknowns:ratings[d]?[]:["Not sufficiently characterised for this Decision Pack."]}));
const opt=(id:string,label:string,relevance:string,ratings:Partial<Record<OptionDimensionKey,DimensionRating>>,sources:ProvenancePointer[]=[],interventionRefs:string[]=[],observed:DecisionField<string>[]=[],economics:DecisionField<string>[]=[],tradeoff="Context, maintenance and opportunity cost can change the result."):DecisionOption=>({optionId:id,label,pathwayRefs:[],interventionRefs,offeringRefs:[],implementationRefs:observed.length?[`impl:${id.toLowerCase()}`]:[],relevance:f(relevance,"4PLANET_ASSESSMENT","MODERATE",sources,["Relevance does not imply effectiveness."]),expectedOutcomes:[f("Potential improvement when the option is well matched to context.","4PLANET_ASSESSMENT","MODERATE",sources,["Expected, not observed at a new site."])],observedOutcomes:observed,economics,coBenefits:[f("Potential ecological or management co-benefits are context dependent.","4PLANET_ASSESSMENT","LOW",sources)],tradeOffs:[f(tradeoff,"4PLANET_ASSESSMENT","MODERATE",sources)],dimensions:dims(ratings,relevance,sources)});
const R={PROBLEM_RELEVANCE:"FAVOURABLE",EFFECTIVENESS_EVIDENCE:"MIXED",IMPLEMENTATION_MATURITY:"MIXED",TIME_TO_BENEFIT:"MIXED",COST_EVIDENCE:"UNKNOWN",MAINTENANCE_BURDEN:"MIXED",ECOLOGICAL_CO_BENEFIT:"FAVOURABLE",HUMAN_CO_BENEFIT:"MIXED",TRADE_OFF_RISK:"MIXED",TRANSFERABILITY:"MIXED",MEASUREMENT_FEASIBILITY:"FAVOURABLE",UNCERTAINTY:"MIXED"} as const;
const truth:DecisionPack["truthBoundary"]={decisionSupportIsAutomatedDecision:false,relevanceIsEffectiveness:false,implementationIsOutcome:false,expectedOutcomeIsObservedOutcome:false,policyIsResult:false,actorIsPartner:false,globalEvidenceIsLocalEvidence:false,databaseAbsenceIsRealWorldAbsence:false,universalBestOption:false};
const why=[f("Animal-mediated pollination supports reproduction of many wild plants and contributes to production of many crops; dependence and magnitude vary by crop and system.","SOURCE_REPORTED_CLAIM","HIGH",[SOURCES.SYNTH],["Do not convert this into a universal share of all food production."],"GLOBAL")];
const drivers=[f("Habitat simplification and pesticide exposure are material pressures in many crop landscapes, but local attribution is multi-causal and context dependent.","4PLANET_ASSESSMENT","MODERATE",[SOURCES.PEST,SOURCES.SYNTH],["Requires local evidence for local causal claims."],"TRANSFERRED")];
const gaps:DecisionGap[]=[{gapId:"POLL-GAP-LOCAL",type:"PLACE",statement:f("Local ecological and management conditions are not supplied by a generic pack.","UNKNOWN","HIGH"),decisionImpact:"HIGH"},{gapId:"POLL-GAP-ECON",type:"ECONOMICS",statement:f("Comparable intervention cost-effectiveness evidence remains sparse and contextual.","4PLANET_ASSESSMENT","HIGH",[SOURCES.SFI,SOURCES.FAP],["Payment rates are not intervention costs."]),decisionImpact:"HIGH"}];
const ev=(id:string,optionId:string,direction:DecisionEvidence["direction"],strength:DecisionEvidence["evidenceStrength"],claim:string,sources:ProvenancePointer[],geography?:string):DecisionEvidence=>({id,optionId,direction,evidenceStrength:strength,geography,claim:f(claim,"SOURCE_REPORTED_CLAIM",strength==="STRONG"?"HIGH":"MODERATE",sources)});

const farm=[
 opt("POLL-FARM-HABITAT","Flower-rich margins / habitat mosaics","Increase floral and habitat resources where habitat limitation is material.",{...R,COST_EVIDENCE:"MIXED",IMPLEMENTATION_MATURITY:"FAVOURABLE"},[SOURCES.SYNTH,SOURCES.FAP],["4P-SOL-000086"],[f("A 233-field Morocco study reported higher wild-pollinator diversity/abundance, lower pest abundance and an average net-income increase per surface of 121% versus controls.","SOURCE_REPORTED_CLAIM","HIGH",[SOURCES.FAP],["Do not transfer the 121% average to another region/crop."],"LOCAL")],[f("England SFI26 pays £798/ha/year for eligible flower-rich margins/blocks/strips.","SOURCE_REPORTED_CLAIM","HIGH",[SOURCES.SFI],["Payment rate, not measured intervention cost-effectiveness."],"LOCAL")]),
 opt("POLL-FARM-IPM","Threshold-based integrated pest management","Reduce avoidable insecticide use while managing pests through monitoring and thresholds.",{...R,EFFECTIVENESS_EVIDENCE:"FAVOURABLE",IMPLEMENTATION_MATURITY:"FAVOURABLE",TIME_TO_BENEFIT:"FAVOURABLE",HUMAN_CO_BENEFIT:"FAVOURABLE"},[SOURCES.IPM],["4P-SOL-000068"],[f("A four-year multi-site Midwestern US experiment reported 95% fewer insecticide treatments; corn yield was maintained and watermelon pollination/yield improved in that represented system.","SOURCE_REPORTED_CLAIM","HIGH",[SOURCES.IPM],["Crop, pest, climate and management context constrain transferability."],"LOCAL")]),
 opt("POLL-FARM-PESTICIDE","Pesticide-risk reduction integrated with habitat","Reduce pollinator exposure while avoiding habitat-only designs that leave exposure unchanged.",R,[SOURCES.PEST],["4P-SOL-000087"],[],[],"Feasible measures depend on crop-protection needs, compounds, timing and exposure pathways."),
];
export const POLLINATION_FARM_DECISION_PACK:DecisionPack={id:"DP-POLL-FARM-V1",version:"DECISION_PACK_V1",question:{id:"DQ-POLL-FARM-001",type:"ACTION",text:"How can pollination resilience be improved on an agricultural landscape without assuming yield gains?",actorType:"LAND_MANAGER",objective:"Compare interventions while preserving evidence, trade-offs and uncertainty.",constraints:["No universal best","No local-effect claim without local evidence"]},status:"DECISION_SUPPORT_READY",context:{problemFrameRefs:["4P-PX-0021"],livingSystemRefs:["taxon-group:wild-bees-bumblebees"],functionRefs:["function:animal-mediated-pollination"],ecosystemServiceRefs:["service:crop-pollination"],humanSystemRefs:["human-system:food-production"],pressureRefs:["pressure:habitat-simplification","pressure:pesticide-exposure"],place:{label:"Farm/place not specified",contextType:"QUERY_AREA",evidenceScope:"NO_LOCAL_EVIDENCE",transferBoundary:"External evidence must be transferred explicitly; no local outcome is inferred.",sources:[]}},whyItMatters:why,dependencies:[f("Western Honey Bee is one taxon and is not a proxy for all wild pollinators.","4PLANET_ASSESSMENT","HIGH",[SOURCES.SYNTH])],drivers,options:farm,evidence:[ev("POLL-E-IPM-S","POLL-FARM-IPM","SUPPORTS","STRONG","Threshold IPM reduced insecticide use while retaining/enhancing represented crop outcomes.",[SOURCES.IPM],"Midwestern US"),ev("POLL-E-HAB-Q","POLL-FARM-HABITAT","QUALIFIES","MODERATE","Flower-strip effects vary with crop, landscape and habitat design.",[SOURCES.SYNTH]),ev("POLL-E-HAB-C","POLL-FARM-HABITAT","CHALLENGES","MODERATE","A universal claim that flower-rich strips reliably increase crop yield is not supported.",[SOURCES.SYNTH]),ev("POLL-E-PEST-Q","POLL-FARM-PESTICIDE","QUALIFIES","MODERATE","Pollinator plantings can remain pesticide exposed next to conventionally managed fields.",[SOURCES.PEST])],gaps,nextInformationNeeded:[f("Specify crop, Place, management regime, pollinator baseline and decision objective before local comparison.","4PLANET_ASSESSMENT","HIGH")],possibleNextActions:[f("Consider a locally scoped comparison/pilot combining habitat, pesticide-risk and monitoring logic as appropriate, subject to agronomic/ecological review.","4PLANET_ASSESSMENT","MODERATE",[SOURCES.IPM,SOURCES.SYNTH],["Decision support, not agronomic prescription."])],truthBoundary:truth};

const muni=[opt("POLL-MUNI-HABITAT","Flower-rich public greenspace / roadside habitat","Increase floral resources and habitat heterogeneity on suitable public land.",R,[SOURCES.URBAN],["4P-SOL-000086"]),opt("POLL-MUNI-MOW","Delayed / phased mowing with refuges","Retain floral/nesting resources through modified mowing where suitable.",{...R,MAINTENANCE_BURDEN:"FAVOURABLE",TIME_TO_BENEFIT:"FAVOURABLE"},[SOURCES.MOW]),opt("POLL-MUNI-MONITOR","Baseline + repeat pollinator/habitat monitoring","Create evidence needed to distinguish policy/action from ecological outcome.",{...R,EFFECTIVENESS_EVIDENCE:"NOT_APPLICABLE",ECOLOGICAL_CO_BENEFIT:"NOT_APPLICABLE",TRANSFERABILITY:"FAVOURABLE",UNCERTAINTY:"FAVOURABLE"},[SOURCES.POMS],[],[],[],"Monitoring generates knowledge; it is not proof of ecological improvement.")];
export const POLLINATION_MUNICIPALITY_DECISION_PACK:DecisionPack={id:"DP-POLL-MUNICIPALITY-V1",version:"DECISION_PACK_V1",question:{id:"DQ-POLL-MUNI-001",type:"ACTION",text:"What actions could a municipality consider to support wild pollinators, and what evidence supports them?",actorType:"MUNICIPALITY",objective:"Identify options without turning policy or transferred studies into local outcomes.",constraints:["Municipality not specified","Policy existence is not ecological outcome"]},status:"DECISION_SUPPORT_READY",context:{problemFrameRefs:["4P-PX-0021"],livingSystemRefs:["taxon-group:wild-bees-bumblebees"],functionRefs:["function:animal-mediated-pollination"],ecosystemServiceRefs:["service:crop-pollination"],humanSystemRefs:["human-system:municipal-land-management"],pressureRefs:["pressure:habitat-simplification","pressure:pesticide-exposure"],place:{placeRef:"place:NO",label:"Norway / municipality to be specified",contextType:"ADMINISTRATIVE_CONTEXT",evidenceScope:"TRANSFERRED",transferBoundary:"The Norwegian action plan establishes policy relevance, not local ecological outcome; intervention evidence is transferred.",sources:[SOURCES.NORWAY]}},whyItMatters:why,dependencies:[f("Urban greenspace can support some pollinators, but effects vary among taxa and sites.","SOURCE_REPORTED_CLAIM","MODERATE",[SOURCES.URBAN],[],"TRANSFERRED")],drivers,options:muni,evidence:[ev("POLL-E-URBAN-S","POLL-MUNI-HABITAT","SUPPORTS","MODERATE","A multi-city German study found high bee richness/visitation and higher measured pollination in represented urban flower-rich sites.",[SOURCES.URBAN],"Nine German cities"),ev("POLL-E-MOW-Q","POLL-MUNI-MOW","QUALIFIES","MODERATE","Mowing changes can benefit wild bees, but cited evidence is transferred from meadow context.",[SOURCES.MOW],"Swiss meadow context")],gaps:[...gaps,{gapId:"POLL-GAP-MUNI",type:"PLACE",statement:f("Municipality-specific habitat, mowing, pesticide and pollinator baseline is absent.","UNKNOWN","HIGH"),decisionImpact:"BLOCKING"}],nextInformationNeeded:[f("Specify municipality and establish baseline land-management and pollinator evidence.","4PLANET_ASSESSMENT","HIGH",[SOURCES.POMS])],possibleNextActions:[f("Consider a locally reviewed portfolio of habitat, mowing/pesticide-risk and monitoring actions with baseline and follow-up measurement.","4PLANET_ASSESSMENT","MODERATE",[SOURCES.URBAN,SOURCES.POMS],["No local ecological outcome is predicted."])],truthBoundary:truth};

const research=(id:string,label:string,relevance:string,type:DecisionGap["type"],sources:ProvenancePointer[]=[])=>opt(id,label,relevance,{...R,EFFECTIVENESS_EVIDENCE:"NOT_APPLICABLE",ECOLOGICAL_CO_BENEFIT:"NOT_APPLICABLE",MEASUREMENT_FEASIBILITY:"FAVOURABLE",UNCERTAINTY:"FAVOURABLE"},sources,[],[],[],`Evidence-generation option targeting a ${type.toLowerCase()} gap; not an effectiveness or investment claim.`);
const fund=[research("POLL-FUND-LONG","Long-term population/outcome monitoring","Reduce the gap between short-term service measures and long-term population outcomes.","OUTCOME",[SOURCES.POMS]),research("POLL-FUND-TRANSFER","Multi-place transferability trials","Test how context changes intervention performance.","TRANSFERABILITY",[SOURCES.IPM,SOURCES.SYNTH]),research("POLL-FUND-ECON","Comparable intervention economics","Build comparable cost and outcome observations rather than mixing policy payments with costs.","ECONOMICS",[SOURCES.FAP,SOURCES.SFI])];
export const POLLINATION_FUNDER_DECISION_PACK:DecisionPack={id:"DP-POLL-FUNDER-V1",version:"DECISION_PACK_V1",question:{id:"DQ-POLL-FUND-001",type:"PRIORITISATION",text:"Where are the largest evidence or implementation gaps where funding could create useful proof?",actorType:"FUNDER",objective:"Identify evidence-generation hypotheses, not investment recommendations.",constraints:["No success probability","No return forecast","Gap priority is a 4PLANET assessment"]},status:"HUMAN_REVIEW_REQUIRED",context:{problemFrameRefs:["4P-PX-0021"],livingSystemRefs:["taxon-group:wild-bees-bumblebees"],functionRefs:["function:animal-mediated-pollination"],ecosystemServiceRefs:["service:crop-pollination"],humanSystemRefs:["human-system:food-production"],pressureRefs:["pressure:habitat-simplification","pressure:pesticide-exposure"],place:{label:"Multi-place / not specified",contextType:"QUERY_AREA",evidenceScope:"GLOBAL",transferBoundary:"Any funded project needs explicit Place and competent delivery/research actors before outcomes can be claimed.",sources:[]}},whyItMatters:why,dependencies:[],drivers,options:fund,evidence:[],gaps,nextInformationNeeded:[f("Define mandate, geography, eligibility and evidence horizon before prioritisation.","4PLANET_ASSESSMENT","HIGH")],possibleNextActions:[f("Consider scoping evidence-generation projects subject to expert study-design review and separate recipient diligence.","4PLANET_ASSESSMENT","MODERATE",[],["Not a funding recommendation."])],truthBoundary:truth};

const fp=[research("POLL-4P-PROV","Immutable Source Record recovery","Turn registry pointers into claim-specific immutable evidence records.","EVIDENCE"),research("POLL-4P-PLACE","Implementation + Place graph","Separate study, implementation, policy, observation and modelled geographies.","PLACE"),research("POLL-4P-MEASURE","Reusable measurement/outcome contract","Preserve expected outcome, measurement and observed outcome separately.","MEASUREMENT",[SOURCES.POMS]),research("POLL-4P-DI","Decision Pack runtime","Expose bounded options, evidence conflicts, uncertainty and gaps without automated decisions.","CAPABILITY")];
export const POLLINATION_4PLANET_DECISION_PACK:DecisionPack={id:"DP-POLL-4PLANET-V1",version:"DECISION_PACK_V1",question:{id:"DQ-POLL-4P-001",type:"ACTION",text:"What could 4PLANET legitimately accelerate without pretending to be the implementation partner?",actorType:"4PLANET_INTERNAL",objective:"Strengthen intelligence/evidence/Place/measurement infrastructure before separate field-action release.",constraints:["No partnership claim","No field outcome claim","Actor presence does not imply partnership"]},status:"DECISION_SUPPORT_READY",context:{problemFrameRefs:["4P-PX-0021"],livingSystemRefs:["taxon-group:wild-bees-bumblebees"],functionRefs:["function:animal-mediated-pollination"],ecosystemServiceRefs:["service:crop-pollination"],humanSystemRefs:["human-system:food-production"],pressureRefs:["pressure:habitat-simplification","pressure:pesticide-exposure"],place:{label:"4PLANET intelligence layer / multi-place",contextType:"QUERY_AREA",evidenceScope:"GLOBAL",transferBoundary:"Organising intelligence does not confer local action authority or implementation capability.",sources:[]}},whyItMatters:why,dependencies:[],drivers,options:fp,evidence:[],gaps,nextInformationNeeded:[f("Identify real research/data/field actors separately before partnership or implementation claims.","4PLANET_ASSESSMENT","HIGH")],possibleNextActions:[f("Build provenance recovery, Place mapping, Decision Packs and monitoring contracts as 4PLANET-owned intelligence infrastructure.","4PLANET_ASSESSMENT","HIGH"),f("Use separately verified field partners only after distinct founder release.","4PLANET_ASSESSMENT","HIGH")],truthBoundary:truth};

export const POLLINATION_DECISION_PACKS={FARM:POLLINATION_FARM_DECISION_PACK,MUNICIPALITY:POLLINATION_MUNICIPALITY_DECISION_PACK,FUNDER:POLLINATION_FUNDER_DECISION_PACK,"4PLANET":POLLINATION_4PLANET_DECISION_PACK} as const;
