const EDGE_URL=import.meta.env.VITE_COMPANY_BRAIN_URL||'https://ghvdzetmplqkdtfqiror.supabase.co/functions/v1/company-brain';
const SESSION_KEY='4planet.companyBrain.session.v1';
export type BrainSession={access_token:string;refresh_token:string;expires_at:number;token_type?:string};
export type CompanyWorkspace={company_id:string;display_name:string;legal_name?:string|null;claim_state?:string;role:string;updated_at?:string};
export type CompanyBrainSnapshot={company:Record<string,unknown>;member_role:string;memories:Array<Record<string,unknown>>;metrics:Array<Record<string,unknown>>;opportunities:Array<Record<string,unknown>>;decisions:Array<Record<string,unknown>>;interventions:Array<Record<string,unknown>>;results:Array<Record<string,unknown>>;learning:Array<Record<string,unknown>>;retrieved_at:string};

function readSession():BrainSession|null{try{const raw=window.localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as BrainSession;return value.access_token&&value.refresh_token&&value.expires_at?value:null}catch{return null}}
function storeSession(session:BrainSession|null){if(session)window.localStorage.setItem(SESSION_KEY,JSON.stringify(session));else window.localStorage.removeItem(SESSION_KEY)}
export function consumeCompanyBrainCallback(){const p=new URLSearchParams(window.location.hash.replace(/^#/,''));const access=p.get('access_token'),refresh=p.get('refresh_token');if(!access||!refresh)return readSession();const session:BrainSession={access_token:access,refresh_token:refresh,expires_at:Math.floor(Date.now()/1000)+Math.max(60,Number(p.get('expires_in')||3600)),token_type:p.get('token_type')||'bearer'};storeSession(session);window.history.replaceState({},document.title,`${window.location.pathname}${window.location.search}`);return session}
async function edge<T>(action:string,payload:Record<string,unknown>={},accessToken?:string):Promise<T>{const response=await fetch(EDGE_URL,{method:'POST',headers:{'content-type':'application/json',...(accessToken?{authorization:`Bearer ${accessToken}`}:{})},body:JSON.stringify({action,...payload})});const body=await response.json().catch(()=>null) as {ok?:boolean;state?:string;detail?:string;error_code?:string;data?:T;session?:T}|null;if(!response.ok||!body?.ok)throw new Error(body?.detail||body?.state||body?.error_code||`Company Brain ${action} failed`);return(body.data??body.session??body) as T}
async function refreshSession(session:BrainSession){try{const raw=await edge<Record<string,unknown>>('refresh_session',{refresh_token:session.refresh_token});const next:BrainSession={access_token:String(raw.access_token||''),refresh_token:String(raw.refresh_token||''),expires_at:Math.floor(Date.now()/1000)+Number(raw.expires_in||3600),token_type:String(raw.token_type||'bearer')};if(!next.access_token||!next.refresh_token)throw new Error('SESSION_REFRESH_FAILED');storeSession(next);return next}catch(error){storeSession(null);throw error}}
export async function currentCompanyBrainSession(){const session=consumeCompanyBrainCallback();if(!session)return null;return session.expires_at>Math.floor(Date.now()/1000)+60?session:refreshSession(session)}
async function authed<T>(action:string,payload:Record<string,unknown>={}){const session=await currentCompanyBrainSession();if(!session)throw new Error('AUTH_REQUIRED');return edge<T>(action,payload,session.access_token)}
export async function sendCompanyBrainMagicLink(email:string){const clean=email.trim().toLowerCase();if(!clean.includes('@'))throw new Error('Enter a valid email.');return edge('send_magic_link',{email:clean,redirect_to:`${window.location.origin}/4brand`})}
export async function signOutCompanyBrain(){const session=await currentCompanyBrainSession().catch(()=>null);if(session)await edge('sign_out',{},session.access_token).catch(()=>undefined);storeSession(null)}
export const listCompanyBrainWorkspaces=()=>authed<CompanyWorkspace[]>('list_workspaces');
export const createCompanyBrainWorkspace=(displayName:string,legalName?:string)=>authed<{company_id:string}>('create_workspace',{display_name:displayName,legal_name:legalName||null});
export const loadCompanyBrain=(companyId:string)=>authed<CompanyBrainSnapshot>('snapshot',{company_id:companyId});
export const saveCompanyTwin=(companyId:string,twin:Record<string,string>)=>authed<CompanyBrainSnapshot>('save_twin',{company_id:companyId,twin});
export const syncCompanyAnalysis=(companyId:string,analysis:unknown,ledger:Record<string,string>)=>authed<CompanyBrainSnapshot>('sync_analysis',{company_id:companyId,analysis,ledger});
export const companyValueReport=(companyId:string)=>authed<Record<string,unknown>>('value_report',{company_id:companyId});
export const companyCompoundingMetrics=(companyId:string)=>authed<Record<string,unknown>>('compounding_metrics',{company_id:companyId});
